import React,{useEffect,useMemo,useState} from 'react';
import {ExternalLink,FileUp,RefreshCw} from 'lucide-react';
import {api} from '../../lib/api.js';import {useAppData} from '../../core/AppDataContext.jsx';
import {Badge,Button,Card,ErrorBox,Field,Input,Loading,PageHeader,Select,Table} from '../../components/UI.jsx';
const types=[['identity','هوية/إقامة'],['passport','جواز سفر'],['visa','تأشيرة'],['other','أخرى']];
function asBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(new Error('تعذر قراءة الملف'));r.readAsDataURL(file)})}
export default function Documents(){
 const {data}=useAppData();const [cloud,setCloud]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[passenger,setPassenger]=useState(''),[type,setType]=useState('identity'),[number,setNumber]=useState(''),[file,setFile]=useState(null);
 const passengers=data.passengers||[];const pmap=useMemo(()=>Object.fromEntries(passengers.map(p=>[String(p.id),p.full_name||p.name||p.id])),[passengers]);
 async function load(){setError('');setCloud(null);try{setCloud(await api.module('documents'))}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 async function upload(e){e.preventDefault();if(!passenger||!file){setError('اختر المسافر والملف');return}if(file.size>6*1024*1024){setError('الحد الأقصى للملف 6MB');return}setBusy(true);setError('');try{await api.moduleWrite({action:'upload_passenger_document',passenger_id:passenger,document_type:type,document_number:number||null,file_name:file.name,mime_type:file.type||'application/octet-stream',base64:await asBase64(file)});setFile(null);setNumber('');e.currentTarget.reset();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function openDoc(r){try{const x=await api.moduleWrite({action:'document_signed_url',storage_path:r.storage_path,expires_in:600});if(x.signed_url)window.open(x.signed_url,'_blank','noopener,noreferrer')}catch(e){setError(e.message)}}
 const rows=cloud?.passenger_documents||[];const cols=[{key:'passenger',label:'المسافر',render:r=>pmap[String(r.passenger_id)]||r.passenger_id||'—'},{key:'document_type',label:'النوع'},{key:'document_number',label:'الرقم'},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='uploaded'?'green':'blue'}>{r.status||'—'}</Badge>},{key:'created_at',label:'تاريخ الرفع',render:r=>r.created_at?new Date(r.created_at).toLocaleString('ar-SA'):'—'},{key:'open',label:'',render:r=>r.storage_path?<Button onClick={()=>openDoc(r)}><ExternalLink size={15}/> فتح مؤقت</Button>:'—'}];
 return <><PageHeader title="المستندات" subtitle="رفع هويات وجوازات ومرفقات المسافرين إلى مساحة Supabase الخاصة بروابط مؤقتة" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث</Button>}/><ErrorBox error={error}/><Card><h3>رفع مستند جديد</h3><form className="form-grid" onSubmit={upload}><Field label="المسافر"><Select value={passenger} onChange={e=>setPassenger(e.target.value)} required><option value="">اختر المسافر</option>{passengers.map(p=><option value={p.id} key={p.id}>{p.full_name||p.name||p.id}</option>)}</Select></Field><Field label="نوع المستند"><Select value={type} onChange={e=>setType(e.target.value)}>{types.map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></Field><Field label="رقم المستند"><Input value={number} onChange={e=>setNumber(e.target.value)}/></Field><Field label="الملف" hint="حد أقصى 6MB"><Input type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)} required/></Field><div className="modal-actions"><Button variant="primary" type="submit" disabled={busy}><FileUp size={16}/>{busy?'جاري الرفع...':'رفع المستند'}</Button></div></form></Card>{!cloud&&!error?<Loading/>:<Card><div className="card-title"><h3>المستندات المحفوظة</h3><Badge>{rows.length}</Badge></div><Table rows={rows} columns={cols}/></Card>}</>
}
