const currentLanguage=()=>{try{return localStorage.getItem('almaher.language')||document.documentElement.lang||'ar'}catch{return 'ar'}};
const localeOf=lang=>({ar:'ar-SA',en:'en-GB',tr:'tr-TR',hi:'hi-IN',it:'it-IT',fr:'fr-FR',ur:'ur-PK'}[lang]||'ar-SA');
export const money=v=>new Intl.NumberFormat(localeOf(currentLanguage()),{style:'currency',currency:'SAR',maximumFractionDigits:2}).format(Number(v||0));
export const date=v=>{if(!v)return '—';try{return new Intl.DateTimeFormat(localeOf(currentLanguage()),{dateStyle:'medium'}).format(new Date(v))}catch{return String(v)}};
export const dateTime=v=>{if(!v)return '—';try{return new Intl.DateTimeFormat(localeOf(currentLanguage()),{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return String(v)}};
const STATUS={
 ar:{new:'جديد',confirmed:'مؤكد',paid:'مدفوع',cancelled:'ملغي',used:'مستخدم',completed:'مكتمل',active:'نشط',inactive:'موقوف',pending:'قيد المراجعة',approved:'معتمد',rejected:'مرفوض',available:'متاح',open:'مفتوح',closed:'مغلق',posted:'مرحّل',draft:'مسودة',in_progress:'قيد التنفيذ',done:'منتهٍ',resolved:'تم الحل',waiting:'بانتظار العميل',contacted:'تم التواصل',qualified:'مؤهل',follow_up:'متابعة',won:'تم التحويل',lost:'مغلق',urgent:'عاجل',high:'عالي',normal:'عادي',low:'منخفض'},
 en:{new:'New',confirmed:'Confirmed',paid:'Paid',cancelled:'Cancelled',used:'Used',completed:'Completed',active:'Active',inactive:'Inactive',pending:'Pending',approved:'Approved',rejected:'Rejected',available:'Available',open:'Open',closed:'Closed',posted:'Posted',draft:'Draft',in_progress:'In progress',done:'Done',resolved:'Resolved',waiting:'Waiting',contacted:'Contacted',qualified:'Qualified',follow_up:'Follow-up',won:'Won',lost:'Lost',urgent:'Urgent',high:'High',normal:'Normal',low:'Low'},
 tr:{new:'Yeni',confirmed:'Onaylandı',paid:'Ödendi',cancelled:'İptal',completed:'Tamamlandı',active:'Aktif',inactive:'Pasif',pending:'Bekliyor',approved:'Onaylı',rejected:'Reddedildi',available:'Müsait',open:'Açık',closed:'Kapalı',draft:'Taslak',in_progress:'Devam ediyor',done:'Tamamlandı',urgent:'Acil',high:'Yüksek',normal:'Normal',low:'Düşük'},
 hi:{new:'नया',confirmed:'पुष्ट',paid:'भुगतान',cancelled:'रद्द',completed:'पूर्ण',active:'सक्रिय',inactive:'निष्क्रिय',pending:'लंबित',approved:'स्वीकृत',rejected:'अस्वीकृत',available:'उपलब्ध',open:'खुला',closed:'बंद',draft:'मसौदा',in_progress:'प्रगति में',done:'पूर्ण',urgent:'तत्काल',high:'उच्च',normal:'सामान्य',low:'कम'},
 it:{new:'Nuovo',confirmed:'Confermato',paid:'Pagato',cancelled:'Annullato',completed:'Completato',active:'Attivo',inactive:'Inattivo',pending:'In attesa',approved:'Approvato',rejected:'Rifiutato',available:'Disponibile',open:'Aperto',closed:'Chiuso',draft:'Bozza',in_progress:'In corso',done:'Completato',urgent:'Urgente',high:'Alta',normal:'Normale',low:'Bassa'},
 fr:{new:'Nouveau',confirmed:'Confirmé',paid:'Payé',cancelled:'Annulé',completed:'Terminé',active:'Actif',inactive:'Inactif',pending:'En attente',approved:'Approuvé',rejected:'Rejeté',available:'Disponible',open:'Ouvert',closed:'Fermé',draft:'Brouillon',in_progress:'En cours',done:'Terminé',urgent:'Urgent',high:'Élevée',normal:'Normale',low:'Faible'},
 ur:{new:'نیا',confirmed:'تصدیق شدہ',paid:'ادا شدہ',cancelled:'منسوخ',completed:'مکمل',active:'فعال',inactive:'غیر فعال',pending:'زیر جائزہ',approved:'منظور',rejected:'مسترد',available:'دستیاب',open:'کھلا',closed:'بند',draft:'مسودہ',in_progress:'جاری',done:'مکمل',urgent:'فوری',high:'زیادہ',normal:'عام',low:'کم'}
};
export const statusLabel=v=>{const key=String(v||'').toLowerCase(),lang=currentLanguage();return STATUS[lang]?.[key]||STATUS.ar[key]||v||'—'};
export const phoneWa=v=>{let x=String(v||'').replace(/\D/g,'');if(x.startsWith('0'))x='966'+x.slice(1);return x};
export const pick=(o,...keys)=>keys.map(k=>o?.[k]).find(v=>v!==undefined&&v!==null&&v!=='')??'';
const JOURNEY={ar:{oneway:'ذهاب فقط',roundtrip:'ذهاب وعودة',separate:'ذهاب + عودة منفصلة',returnonly:'عودة فقط'},en:{oneway:'Outbound only',roundtrip:'Round trip',separate:'Outbound + separate return',returnonly:'Return only'},tr:{oneway:'Sadece gidiş',roundtrip:'Gidiş dönüş',separate:'Gidiş + ayrı dönüş',returnonly:'Sadece dönüş'},hi:{oneway:'केवल जाना',roundtrip:'आना-जाना',separate:'जाना + अलग वापसी',returnonly:'केवल वापसी'},it:{oneway:'Solo andata',roundtrip:'Andata e ritorno',separate:'Andata + ritorno separato',returnonly:'Solo ritorno'},fr:{oneway:'Aller simple',roundtrip:'Aller-retour',separate:'Aller + retour séparé',returnonly:'Retour seulement'},ur:{oneway:'صرف روانگی',roundtrip:'آنا جانا',separate:'روانگی + الگ واپسی',returnonly:'صرف واپسی'}};
export const journeyLabel=v=>JOURNEY[currentLanguage()]?.[String(v||'').toLowerCase()]||JOURNEY.ar[String(v||'').toLowerCase()]||v||'—';
export const tripWeekday=v=>{if(!v)return '—';try{return new Intl.DateTimeFormat(localeOf(currentLanguage()),{weekday:'long'}).format(new Date(`${String(v).slice(0,10)}T12:00:00`))}catch{return '—'}};
export const tripDate=v=>{if(!v)return '—';try{return new Intl.DateTimeFormat(localeOf(currentLanguage()),{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(`${String(v).slice(0,10)}T12:00:00`))}catch{return String(v)}};
export const tripDisplay=t=>{if(!t)return '—';const d=t.departure_date||t.departureDate||'',from=t.from_city||t.origin||'—',to=t.to_city||t.destination||'—',code=t.trip_code||t.code||'—',tripWord={ar:'رحلة',en:'Trip',tr:'Sefer',hi:'यात्रा',it:'Viaggio',fr:'Voyage',ur:'سفر'}[currentLanguage()]||'رحلة';return `${tripWord} ${tripWeekday(d)} — ${tripDate(d)} — ${from} ← ${to} — ${code}`};
