export const PRINT_LANGUAGES=[['ar','العربية','rtl'],['en','English','ltr'],['tr','Türkçe','ltr'],['hi','हिन्दी','ltr'],['it','Italiano','ltr'],['fr','Français','ltr'],['ur','اردو','rtl']];

const P={
 ar:{ticket:'التذكرة',bookingNo:'رقم الحجز',back:'رجوع',customer:'العميل',journeyType:'نوع الرحلة',housing:'السكن',paymentStatus:'حالة السداد',paidFull:'مسدد بالكامل',remaining:'المتبقي',outbound:'الذهاب',return:'العودة',passengers:'المسافرون',passenger:'مسافر',seatUnset:'المقعد غير محدد',hotel:'الفندق',room:'غرفة',total:'الإجمالي',paid:'المدفوع',bookingQr:'QR الحجز',boardingLocation:'موقع الصعود',terms:'الشروط والأحكام',defaultTerm1:'الحضور قبل موعد الانطلاق بوقت كافٍ.',defaultTerm2:'الاحتفاظ بالتذكرة والهوية/الإقامة أثناء الرحلة.',defaultTerm3:'التذكرة الملغاة أو المستبدلة غير صالحة للاستخدام.',termsSnapshot:'تخضع الرحلة للشروط والأحكام المسجلة بالنظام وقت إصدار التذكرة.',developer:'تطوير وإدارة النظام',tripUnavailable:'بيانات الرحلة غير متاحة',noHousing:'بدون سكن',day:'يوم'},
 en:{ticket:'Ticket',bookingNo:'Booking No.',back:'Back',customer:'Customer',journeyType:'Journey type',housing:'Accommodation',paymentStatus:'Payment status',paidFull:'Paid in full',remaining:'Remaining',outbound:'Outbound',return:'Return',passengers:'Passengers',passenger:'passenger',seatUnset:'Seat not assigned',hotel:'Hotel',room:'Room',total:'Total',paid:'Paid',bookingQr:'Booking QR',boardingLocation:'Boarding location',terms:'Terms & Conditions',defaultTerm1:'Please arrive sufficiently before departure time.',defaultTerm2:'Keep your ticket and ID/residence document during the trip.',defaultTerm3:'Cancelled or replaced tickets are not valid for use.',termsSnapshot:'The trip is subject to the terms stored in the system at ticket issue time.',developer:'System development & management',tripUnavailable:'Trip data unavailable',noHousing:'No accommodation',day:'day'},
 tr:{ticket:'Bilet',bookingNo:'Rezervasyon No.',back:'Geri',customer:'Müşteri',journeyType:'Yolculuk türü',housing:'Konaklama',paymentStatus:'Ödeme durumu',paidFull:'Tam ödendi',remaining:'Kalan',outbound:'Gidiş',return:'Dönüş',passengers:'Yolcular',passenger:'yolcu',seatUnset:'Koltuk atanmadı',hotel:'Otel',room:'Oda',total:'Toplam',paid:'Ödenen',bookingQr:'Rezervasyon QR',boardingLocation:'Biniş konumu',terms:'Şartlar ve Koşullar',defaultTerm1:'Lütfen kalkış saatinden yeterince önce hazır olun.',defaultTerm2:'Yolculuk boyunca biletinizi ve kimliğinizi yanınızda bulundurun.',defaultTerm3:'İptal edilen veya değiştirilen biletler geçersizdir.',termsSnapshot:'Yolculuk, bilet düzenlendiği anda sistemde kayıtlı şartlara tabidir.',developer:'Sistem geliştirme ve yönetim',tripUnavailable:'Sefer bilgisi mevcut değil',noHousing:'Konaklama yok',day:'gün'},
 hi:{ticket:'टिकट',bookingNo:'बुकिंग नंबर',back:'वापस',customer:'ग्राहक',journeyType:'यात्रा प्रकार',housing:'आवास',paymentStatus:'भुगतान स्थिति',paidFull:'पूरा भुगतान',remaining:'शेष',outbound:'जाना',return:'वापसी',passengers:'यात्री',passenger:'यात्री',seatUnset:'सीट निर्धारित नहीं',hotel:'होटल',room:'कमरा',total:'कुल',paid:'भुगतान',bookingQr:'बुकिंग QR',boardingLocation:'बोर्डिंग स्थान',terms:'नियम और शर्तें',defaultTerm1:'कृपया प्रस्थान समय से पर्याप्त पहले पहुँचें।',defaultTerm2:'यात्रा के दौरान टिकट और पहचान पत्र साथ रखें।',defaultTerm3:'रद्द या बदले गए टिकट उपयोग के लिए मान्य नहीं हैं।',termsSnapshot:'यात्रा टिकट जारी होने के समय सिस्टम में दर्ज शर्तों के अधीन है।',developer:'सिस्टम विकास और प्रबंधन',tripUnavailable:'यात्रा डेटा उपलब्ध नहीं',noHousing:'आवास नहीं',day:'दिन'},
 it:{ticket:'Biglietto',bookingNo:'N. prenotazione',back:'Indietro',customer:'Cliente',journeyType:'Tipo di viaggio',housing:'Alloggio',paymentStatus:'Stato pagamento',paidFull:'Pagato interamente',remaining:'Residuo',outbound:'Andata',return:'Ritorno',passengers:'Passeggeri',passenger:'passeggero',seatUnset:'Posto non assegnato',hotel:'Hotel',room:'Camera',total:'Totale',paid:'Pagato',bookingQr:'QR prenotazione',boardingLocation:'Punto di imbarco',terms:'Termini e condizioni',defaultTerm1:'Presentarsi con sufficiente anticipo rispetto alla partenza.',defaultTerm2:'Conservare biglietto e documento di identità durante il viaggio.',defaultTerm3:'I biglietti annullati o sostituiti non sono validi.',termsSnapshot:'Il viaggio è soggetto ai termini registrati nel sistema al momento dell’emissione.',developer:'Sviluppo e gestione del sistema',tripUnavailable:'Dati del viaggio non disponibili',noHousing:'Nessun alloggio',day:'giorno'},
 fr:{ticket:'Billet',bookingNo:'N° de réservation',back:'Retour',customer:'Client',journeyType:'Type de trajet',housing:'Hébergement',paymentStatus:'État du paiement',paidFull:'Payé intégralement',remaining:'Reste',outbound:'Aller',return:'Retour',passengers:'Passagers',passenger:'passager',seatUnset:'Siège non attribué',hotel:'Hôtel',room:'Chambre',total:'Total',paid:'Payé',bookingQr:'QR réservation',boardingLocation:'Lieu d’embarquement',terms:'Conditions générales',defaultTerm1:'Veuillez arriver suffisamment avant l’heure de départ.',defaultTerm2:'Gardez votre billet et votre pièce d’identité pendant le voyage.',defaultTerm3:'Les billets annulés ou remplacés ne sont pas valides.',termsSnapshot:'Le voyage est soumis aux conditions enregistrées dans le système au moment de l’émission.',developer:'Développement et gestion du système',tripUnavailable:'Données du trajet indisponibles',noHousing:'Sans hébergement',day:'jour'},
 ur:{ticket:'ٹکٹ',bookingNo:'بکنگ نمبر',back:'واپس',customer:'گاہک',journeyType:'سفر کی قسم',housing:'رہائش',paymentStatus:'ادائیگی کی حالت',paidFull:'مکمل ادائیگی',remaining:'باقی',outbound:'روانگی',return:'واپسی',passengers:'مسافر',passenger:'مسافر',seatUnset:'نشست مقرر نہیں',hotel:'ہوٹل',room:'کمرہ',total:'کل',paid:'ادا شدہ',bookingQr:'بکنگ QR',boardingLocation:'سوار ہونے کی جگہ',terms:'شرائط و ضوابط',defaultTerm1:'روانگی کے وقت سے کافی پہلے پہنچیں۔',defaultTerm2:'سفر کے دوران ٹکٹ اور شناختی دستاویز ساتھ رکھیں۔',defaultTerm3:'منسوخ یا تبدیل شدہ ٹکٹ قابل استعمال نہیں ہیں۔',termsSnapshot:'سفر ٹکٹ جاری ہونے کے وقت نظام میں درج شرائط کے تابع ہے۔',developer:'نظام کی ترقی اور انتظام',tripUnavailable:'سفر کی معلومات دستیاب نہیں',noHousing:'بغیر رہائش',day:'دن'}
};

export function printDirection(lang='ar'){return PRINT_LANGUAGES.find(x=>x[0]===lang)?.[2]||'rtl'}
export function pt(lang,key,fallback=''){return P[lang]?.[key]||P.ar[key]||fallback||key}
