import React,{useEffect,useMemo,useState} from 'react';
import {Building2,MapPin,Phone,Mail,Plus,Pencil,RefreshCw,Save,Landmark,Clock3,MessageCircle} from 'lucide-react';
import {useAppData} from '../../core/AppDataContext.jsx';
import {api} from '../../lib/api.js';
import {Badge,Button,Card,ErrorBox,Field,Input,Modal,PageHeader,Select,Textarea} from '../../components/UI.jsx';

const blank=()=>({name:'',status:'نشط',address:'',whatsapp:'',manager:'',commercialRegistration:'',taxNumber:'',email:'',workingHours:'',mapUrl:'',notes:'',showLegalOnTicket:true,contacts:[{label:'الحجوزات',phone:''}]});
const clean=v=>String(v??'').trim();
export default function Branches(){
 const {data,refresh}=useAppData(); const [open,setOpen]=useState(false),[form,setForm]=useState(blank()),[error,setError]=useState(''),[busy,setBusy]=useState(false),[company,setCompany]=useState(null),[companyBusy,setCompanyBusy]=useState(false);
 const contactsByBranch=useMemo(()=>{const m=new Map();for(const c of data.branchContacts||[]){const k=String(c.branch_id||'');const a=m.get(k)||[];a.push(c);m.set(k,a)}return m},[data.branchContacts]);
 async function loadCompany(){try{const x=await api.admin({action:'company_settings_get'});setCompany(x.settings||{})}catch(e){setError(e.message)}}
 useEffect(()=>{loadCompany()},[]);
 function edit(b){const contacts=(contactsByBranch.get(String(b.id))||[]).map(c=>({label:c.label||c.name||'رقم التواصل',phone:c.phone||c.number||c.whatsapp||''}));setForm({id:b.id,name:b.name||b.branch_name||'',status:b.status==='inactive'?'موقوف':'نشط',address:b.address||'',whatsapp:b.whatsapp||'',manager:b.manager_name||'',commercialRegistration:b.commercial_registration||'',taxNumber:b.tax_number||'',email:b.email||'',workingHours:b.working_hours||'',mapUrl:b.map_url||'',notes:b.notes||'',showLegalOnTicket:b.show_legal_on_ticket!==false,contacts:contacts.length?contacts:[{label:'الحجوزات',phone:''}]});setError('');setOpen(true)}
 function add(){setForm(blank());setError('');setOpen(true)}
 function set(k,v){setForm(x=>({...x,[k]:v}))}
 function contact(i,k,v){setForm(x=>({...x,contacts:x.contacts.map((c,j)=>j===i?{...c,[k]:v}:c)}))}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await api.admin({action:'save_branch',row:{...form,name:clean(form.name),contacts:form.contacts.filter(c=>clean(c.phone))}});setOpen(false);await refresh()}catch(e2){setError(e2.message)}finally{setBusy(false)}}
 async function saveCompany(e){e.preventDefault();setCompanyBusy(true);setError('');const f=Object.fromEntries(new FormData(e.currentTarget));try{const x=await api.admin({action:'company_settings_save',settings:f});setCompany(x.settings||f)}catch(e2){setError(e2.message)}finally{setCompanyBusy(false)}}
 return <><PageHeader title="الفروع وبيانات الشركة" subtitle="إدارة الفروع وأرقام التواصل والعناوين والبيانات القانونية التي تظهر في التذاكر والتقارير" actions={<><Button onClick={()=>refresh()}><RefreshCw size={16}/> تحديث</Button><Button variant="primary" onClick={add}><Plus size={16}/> إضافة فرع</Button></>}/><ErrorBox error={error}/>
 <div className="branch-admin-grid">{(data.branches||[]).map(b=>{const cs=contactsByBranch.get(String(b.id))||[];return <Card key={b.id} className="branch-card"><div className="branch-card-head"><div className="branch-icon"><Building2/></div><div><h3>{b.name||b.branch_name}</h3><Badge tone={b.status==='inactive'?'red':'green'}>{b.status==='inactive'?'موقوف':'نشط'}</Badge></div><Button onClick={()=>edit(b)}><Pencil size={15}/> تعديل</Button></div><div className="branch-meta">{b.address&&<span><MapPin size={14}/>{b.address}</span>}{b.manager_name&&<span><Landmark size={14}/>مدير الفرع: {b.manager_name}</span>}{b.email&&<span><Mail size={14}/>{b.email}</span>}{b.working_hours&&<span><Clock3 size={14}/>{b.working_hours}</span>}{(b.whatsapp||cs[0]?.phone)&&<span><MessageCircle size={14}/>{b.whatsapp||cs[0]?.phone}</span>}</div><div className="branch-phones">{cs.map((c,i)=><span key={c.id||i}><Phone size={13}/>{c.label||'تواصل'}: {c.phone||c.number}</span>)}</div></Card>})}</div>
 <Card className="company-settings-card"><div className="card-title"><div><h3>بيانات الشركة العامة</h3><p>تُستخدم كمرجع موحد في الهيدر والتذاكر والتقارير.</p></div></div>{company&&<form className="form-grid" onSubmit={saveCompany}><Field label="الاسم العربي"><Input name="company_name_ar" defaultValue={company.company_name_ar||'شركة الماهر الماسي'}/></Field><Field label="الاسم الإنجليزي"><Input name="company_name_en" defaultValue={company.company_name_en||'Al-Maher Al-Masi Company'}/></Field><Field label="السجل التجاري"><Input name="commercial_registration" defaultValue={company.commercial_registration||''}/></Field><Field label="الرقم الضريبي"><Input name="tax_number" defaultValue={company.tax_number||''}/></Field><Field label="البريد العام"><Input type="email" name="email" defaultValue={company.email||''}/></Field><Field label="الجوال العام"><Input name="phone" defaultValue={company.phone||''}/></Field><Field label="الموقع الإلكتروني"><Input name="website" defaultValue={company.website||''}/></Field><Field label="الشعار النصي"><Input name="slogan" defaultValue={company.slogan||'نُيسر دربك... لنطمئن قلبك'}/></Field><Field label="عنوان الشركة"><Input name="address" defaultValue={company.address||''}/></Field><div className="modal-actions"><Button variant="primary" type="submit" disabled={companyBusy}><Save size={16}/>{companyBusy?'جاري الحفظ...':'حفظ بيانات الشركة'}</Button></div></form>}</Card>
 <Modal open={open} onClose={()=>setOpen(false)} title={form.id?'تعديل الفرع':'إضافة فرع'}><form className="form-grid" onSubmit={save}><Field label="اسم الفرع"><Input value={form.name} onChange={e=>set('name',e.target.value)} required/></Field><Field label="الحالة"><Select value={form.status} onChange={e=>set('status',e.target.value)}><option>نشط</option><option>موقوف</option></Select></Field><Field label="العنوان"><Input value={form.address} onChange={e=>set('address',e.target.value)}/></Field><Field label="رابط الموقع"><Input value={form.mapUrl} onChange={e=>set('mapUrl',e.target.value)} placeholder="https://maps.google.com/..."/></Field><Field label="واتساب"><Input value={form.whatsapp} onChange={e=>set('whatsapp',e.target.value)}/></Field><Field label="مدير الفرع"><Input value={form.manager} onChange={e=>set('manager',e.target.value)}/></Field><Field label="البريد"><Input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="ساعات العمل"><Input value={form.workingHours} onChange={e=>set('workingHours',e.target.value)} placeholder="09:00 - 22:00"/></Field><Field label="السجل التجاري"><Input value={form.commercialRegistration} onChange={e=>set('commercialRegistration',e.target.value)}/></Field><Field label="الرقم الضريبي"><Input value={form.taxNumber} onChange={e=>set('taxNumber',e.target.value)}/></Field><Field label="ملاحظات"><Textarea value={form.notes} onChange={e=>set('notes',e.target.value)}/></Field><div className="shared-branches-box"><strong>أرقام التواصل</strong>{form.contacts.map((c,i)=><div className="branch-contact-row" key={i}><Input value={c.label} onChange={e=>contact(i,'label',e.target.value)} placeholder="المسمى"/><Input value={c.phone} onChange={e=>contact(i,'phone',e.target.value)} placeholder="05xxxxxxxx"/><Button type="button" onClick={()=>setForm(x=>({...x,contacts:x.contacts.filter((_,j)=>j!==i)}))}>حذف</Button></div>)}<Button type="button" onClick={()=>setForm(x=>({...x,contacts:[...x.contacts,{label:'رقم التواصل',phone:''}]}))}><Plus size={14}/> إضافة رقم</Button></div><label className="check-line"><input type="checkbox" checked={!!form.showLegalOnTicket} onChange={e=>set('showLegalOnTicket',e.target.checked)}/> إظهار البيانات القانونية في التذكرة عند توفرها</label><div className="modal-actions"><Button type="button" onClick={()=>setOpen(false)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>{busy?'جاري الحفظ...':'حفظ الفرع'}</Button></div></form></Modal></>;
}
