import React,{useEffect,useState} from 'react';
import {Printer,RefreshCw} from 'lucide-react';
import {api} from '../../lib/api.js';
import {Card,PageHeader,Button,Field,Input,Select,Textarea,ErrorBox,Table,Badge} from '../../components/UI.jsx';
import {money,dateTime,statusLabel} from '../../lib/format.js';

export default function Refunds({bookingParam=''}){
 const [booking,setBooking]=useState(bookingParam),[quote,setQuote]=useState(null),[list,setList]=useState([]),[caps,setCaps]=useState({}),[err,setErr]=useState(''),[busy,setBusy]=useState('');
 async function q(){setErr('');setQuote(null);try{setQuote(await api.admin({action:'refund_quote',booking_number:booking}))}catch(e){setErr(e.message)}}
 async function load(){setErr('');try{const x=await api.admin({action:'refund_list'});setList(x.rows||[]);setCaps({request:!!x.can_request,approve:!!x.can_approve,complete:!!x.can_complete,print:!!x.can_print})}catch(e){setErr(e.message)}}
 useEffect(()=>{load();if(bookingParam)q()},[]);
 async function requestRefund(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setBusy('request');try{await api.admin({action:'refund_request',booking_number:booking,amount:Number(f.amount),reason:f.reason,refund_method:f.refund_method,customer_ack_name:f.customer_ack_name,cancel_booking:!!f.cancel_booking,client_request_id:crypto.randomUUID?.()||String(Date.now()),direct_execute:!!f.direct_execute});await load();await q()}catch(e2){setErr(e2.message)}finally{setBusy('')}}
 async function decide(id,decision){setBusy(id);try{await api.admin({action:'refund_decide',id,decision});await load()}catch(e){setErr(e.message)}finally{setBusy('')}}
 async function complete(id){setBusy(id);try{await api.admin({action:'refund_complete',id});await load();if(booking)await q()}catch(e){setErr(e.message)}finally{setBusy('')}}
 return <><PageHeader title="الاسترداد" subtitle="طلب → اعتماد → تنفيذ، مع منع التكرار وعزل مالية الفروع" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث</Button>}/><ErrorBox error={err}/><div className="refund-grid"><Card><h3>استرداد حجز</h3><div className="inline-form"><Field label="رقم الحجز"><Input value={booking} onChange={e=>setBooking(e.target.value)}/></Field><Button onClick={q} disabled={!booking}>حساب المتاح</Button></div>{quote&&<><div className="quote-box"><div><span>المدفوع</span><strong>{money(quote.booking?.paid_amount)}</strong></div><div><span>سبق استرداده</span><strong>{money(quote.refunded_amount)}</strong></div><div><span>المتاح</span><strong>{money(quote.available_refund)}</strong></div></div>{quote.available_refund>0&&quote.capabilities?.request?<form className="form-grid" onSubmit={requestRefund}><Field label="المبلغ"><Input name="amount" type="number" step="0.01" min="0.01" max={quote.available_refund} required/></Field><Field label="طريقة الاسترداد"><Select name="refund_method"><option value="cash">نقدي</option><option value="bank_transfer">تحويل بنكي</option><option value="same_method">نفس وسيلة الدفع</option><option value="other">أخرى</option></Select></Field><Field label="اسم المستلم"><Input name="customer_ack_name" defaultValue={quote.booking?.customer_name||''}/></Field><Field label="السبب"><Textarea name="reason" required/></Field><label className="check"><input type="checkbox" name="cancel_booking"/> إلغاء الحجز بعد الاسترداد</label>{quote.capabilities?.approve&&quote.capabilities?.complete&&<label className="check"><input type="checkbox" name="direct_execute"/> تنفيذ مباشر إذا كانت صلاحياتي تسمح</label>}<Button variant="primary" type="submit" disabled={busy==='request'}>{busy==='request'?'جاري الإنشاء...':'إنشاء طلب الاسترداد'}</Button></form>:<div className="empty compact-empty">لا يوجد مبلغ متاح للاسترداد أو لا توجد صلاحية طلب.</div>}</>}</Card><Card><h3>طلبات الاسترداد</h3><Table rows={list} columns={[{key:'receipt_no',label:'السند'},{key:'booking_number',label:'الحجز'},{key:'amount',label:'المبلغ',render:r=>money(r.amount)},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='completed'?'green':r.status==='rejected'?'red':'orange'}>{statusLabel(r.status)}</Badge>},{key:'requested_at',label:'التاريخ',render:r=>dateTime(r.requested_at)},{key:'actions',label:'الإجراء',render:r=><div className="row-actions">{r.status==='pending'&&caps.approve&&<><button disabled={busy===r.id} onClick={e=>{e.stopPropagation();decide(r.id,'approved')}}>اعتماد</button><button disabled={busy===r.id} onClick={e=>{e.stopPropagation();decide(r.id,'rejected')}}>رفض</button></>}{r.status==='approved'&&caps.complete&&<button disabled={busy===r.id} onClick={e=>{e.stopPropagation();complete(r.id)}}>تنفيذ</button>}{r.status==='completed'&&caps.print&&<button onClick={e=>{e.stopPropagation();printRefund(r)}}><Printer size={14}/></button>}</div>}]}/></Card></div></>;
}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function printRefund(x){const w=open('','_blank');if(!w)return;w.document.write(`<html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${esc(x.receipt_no)}</title><style>@page{size:A4;margin:12mm}body{font-family:Tahoma;padding:20px}.doc{border:2px solid #c6a24c;border-radius:18px;padding:35px}h1{text-align:center;color:#123b72}.g{display:grid;grid-template-columns:1fr 1fr;gap:12px}.g div{border:1px solid #ddd;padding:12px;border-radius:8px}small{display:block;color:#777}</style></head><body><div class="doc"><h1>شركة الماهر الماسي<br><small>سند استرداد / صرف</small></h1><div class="g"><div><small>رقم السند</small><b>${esc(x.receipt_no)}</b></div><div><small>رقم الحجز</small><b>${esc(x.booking_number)}</b></div><div><small>العميل</small><b>${esc(x.customer_name)}</b></div><div><small>المبلغ</small><b>${Number(x.amount||0).toFixed(2)} ريال</b></div><div><small>السبب</small><b>${esc(x.reason)}</b></div><div><small>المنفذ</small><b>${esc(x.completed_by)}</b></div></div></div><script>onload=()=>setTimeout(()=>print(),150)<\/script></body></html>`);w.document.close()}
