import React,{useEffect,useState} from 'react';
import {Printer,RefreshCw} from 'lucide-react';
import {api} from '../../lib/api.js';
import {Card,PageHeader,Button,Field,Input,Select,Textarea,ErrorBox,Table,Badge} from '../../components/UI.jsx';
import {money,dateTime,statusLabel} from '../../lib/format.js';
import {useLanguage} from '../../core/LanguageContext.jsx';
import {useSystemBrand} from '../../core/SystemBrandContext.jsx';
import {basicPrintDocument,printHtmlDocument} from '../../lib/print.js';

const DOC={
 ar:{company:'شركة الماهر الماسي',title:'سند استرداد / صرف',receipt:'رقم السند',booking:'رقم الحجز',customer:'العميل',amount:'المبلغ',method:'طريقة الاسترداد',reason:'السبب',executed:'المنفذ',status:'الحالة',recipient:'توقيع المستلم',staff:'الموظف / الختم',sar:'ريال سعودي'},
 en:{company:'Al Maher Al Masi',title:'Refund / Disbursement Receipt',receipt:'Receipt No.',booking:'Booking No.',customer:'Customer',amount:'Amount',method:'Refund method',reason:'Reason',executed:'Processed by',status:'Status',recipient:'Recipient signature',staff:'Staff / Stamp',sar:'SAR'},
 tr:{company:'Al Maher Al Masi',title:'İade / Ödeme Makbuzu',receipt:'Makbuz No.',booking:'Rezervasyon No.',customer:'Müşteri',amount:'Tutar',method:'İade yöntemi',reason:'Neden',executed:'İşlemi yapan',status:'Durum',recipient:'Alıcı imzası',staff:'Personel / Kaşe',sar:'SAR'},
 hi:{company:'Al Maher Al Masi',title:'रिफंड / भुगतान रसीद',receipt:'रसीद नंबर',booking:'बुकिंग नंबर',customer:'ग्राहक',amount:'राशि',method:'रिफंड विधि',reason:'कारण',executed:'प्रक्रिया करने वाला',status:'स्थिति',recipient:'प्राप्तकर्ता हस्ताक्षर',staff:'कर्मचारी / मुहर',sar:'SAR'},
 it:{company:'Al Maher Al Masi',title:'Ricevuta Rimborso / Erogazione',receipt:'N. ricevuta',booking:'N. prenotazione',customer:'Cliente',amount:'Importo',method:'Metodo rimborso',reason:'Motivo',executed:'Eseguito da',status:'Stato',recipient:'Firma destinatario',staff:'Personale / Timbro',sar:'SAR'},
 fr:{company:'Al Maher Al Masi',title:'Reçu de remboursement / décaissement',receipt:'N° reçu',booking:'N° réservation',customer:'Client',amount:'Montant',method:'Mode de remboursement',reason:'Motif',executed:'Exécuté par',status:'Statut',recipient:'Signature bénéficiaire',staff:'Employé / Cachet',sar:'SAR'},
 ur:{company:'الماہر الماسی',title:'رقم واپسی / ادائیگی رسید',receipt:'رسید نمبر',booking:'بکنگ نمبر',customer:'گاہک',amount:'رقم',method:'رقم واپسی طریقہ',reason:'وجہ',executed:'عمل کرنے والا',status:'حالت',recipient:'وصول کنندہ دستخط',staff:'ملازم / مہر',sar:'سعودی ریال'}
};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export default function Refunds({bookingParam=''}){
 const {language,dir}=useLanguage();const {labels}=useSystemBrand();const T=DOC[language]||DOC.ar;
 const [booking,setBooking]=useState(bookingParam),[quote,setQuote]=useState(null),[list,setList]=useState([]),[caps,setCaps]=useState({}),[err,setErr]=useState(''),[busy,setBusy]=useState('');
 async function q(){setErr('');setQuote(null);try{setQuote(await api.admin({action:'refund_quote',booking_number:booking}))}catch(e){setErr(e.message)}}
 async function load(){setErr('');try{const x=await api.admin({action:'refund_list'});setList(x.rows||[]);setCaps({request:!!x.can_request,approve:!!x.can_approve,complete:!!x.can_complete,print:!!x.can_print})}catch(e){setErr(e.message)}}
 useEffect(()=>{load();if(bookingParam)q()},[]);
 async function requestRefund(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setBusy('request');try{await api.admin({action:'refund_request',booking_number:booking,amount:Number(f.amount),reason:f.reason,refund_method:f.refund_method,customer_ack_name:f.customer_ack_name,cancel_booking:!!f.cancel_booking,client_request_id:crypto.randomUUID?.()||String(Date.now()),direct_execute:!!f.direct_execute});await load();await q()}catch(e2){setErr(e2.message)}finally{setBusy('')}}
 async function decide(id,decision){setBusy(id);try{await api.admin({action:'refund_decide',id,decision});await load()}catch(e){setErr(e.message)}finally{setBusy('')}}
 async function complete(id){setBusy(id);try{await api.admin({action:'refund_complete',id});await load();if(booking)await q()}catch(e){setErr(e.message)}finally{setBusy('')}}
 function printRefund(x){
  const body=`<div class="doc"><div class="head"><img class="logo" src="/almaher-logo.jpeg"><div class="title"><h1>${esc(labels.system_name||T.company)}</h1><h2>${esc(T.title)}</h2></div></div><div class="grid"><div class="box"><small>${esc(T.receipt)}</small><b>${esc(x.receipt_no)}</b></div><div class="box"><small>${esc(T.booking)}</small><b>${esc(x.booking_number)}</b></div><div class="box"><small>${esc(T.customer)}</small><b>${esc(x.customer_name||x.customer_ack_name)}</b></div><div class="box amount"><small>${esc(T.amount)}</small><b>${Number(x.amount||0).toFixed(2)} ${esc(T.sar)}</b></div><div class="box"><small>${esc(T.method)}</small><b>${esc(x.refund_method||'—')}</b></div><div class="box"><small>${esc(T.reason)}</small><b>${esc(x.reason||'—')}</b></div><div class="box"><small>${esc(T.executed)}</small><b>${esc(x.completed_by||'—')}</b></div><div class="box"><small>${esc(T.status)}</small><b>${esc(statusLabel(x.status||'completed'))}</b></div></div><div class="sign"><div class="line">${esc(T.recipient)}</div><div class="line">${esc(T.staff)}</div></div></div>`;
  const html=basicPrintDocument({title:`${T.title} ${x.receipt_no||''}`,dir,lang:language,body,styles:'.doc{min-height:250mm;border:1.5px solid #c7a14a;border-radius:18px;padding:18mm;position:relative}.head{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #123b72;padding-bottom:14px}.logo{width:130px}.title h1{margin:0;color:#123b72}.title h2{color:#b28b31}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:22px}.box{border:1px solid #d9e0ea;border-radius:10px;padding:11px}.box small{display:block;color:#78869a;margin-bottom:5px}.amount{grid-column:1/-1;background:#f7f2e5;border-color:#c7a14a;font-size:20px}.sign{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:55px;text-align:center}.line{border-top:1px solid #777;padding-top:8px}'});printHtmlDocument(html)
 }
 return <><PageHeader title="الاسترداد" subtitle="طلب → اعتماد → تنفيذ، مع منع التكرار وعزل مالية الفروع" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث</Button>}/><ErrorBox error={err}/><div className="refund-grid"><Card><h3>استرداد حجز</h3><div className="inline-form"><Field label="رقم الحجز"><Input value={booking} onChange={e=>setBooking(e.target.value)}/></Field><Button onClick={q} disabled={!booking}>حساب المتاح</Button></div>{quote&&<><div className="quote-box"><div><span>المدفوع</span><strong>{money(quote.booking?.paid_amount)}</strong></div><div><span>سبق استرداده</span><strong>{money(quote.refunded_amount)}</strong></div><div><span>المتاح</span><strong>{money(quote.available_refund)}</strong></div></div>{quote.available_refund>0&&quote.capabilities?.request?<form className="form-grid" onSubmit={requestRefund}><Field label="المبلغ"><Input name="amount" type="number" step="0.01" min="0.01" max={quote.available_refund} required/></Field><Field label="طريقة الاسترداد"><Select name="refund_method"><option value="cash">نقدي</option><option value="bank_transfer">تحويل بنكي</option><option value="same_method">نفس وسيلة الدفع</option><option value="other">أخرى</option></Select></Field><Field label="اسم المستلم"><Input name="customer_ack_name" defaultValue={quote.booking?.customer_name||''}/></Field><Field label="السبب"><Textarea name="reason" required/></Field><label className="check"><input type="checkbox" name="cancel_booking"/> إلغاء الحجز بعد الاسترداد</label>{quote.capabilities?.approve&&quote.capabilities?.complete&&<label className="check"><input type="checkbox" name="direct_execute"/> تنفيذ مباشر إذا كانت صلاحياتي تسمح</label>}<Button variant="primary" type="submit" disabled={busy==='request'}>{busy==='request'?'جاري الإنشاء...':'إنشاء طلب الاسترداد'}</Button></form>:<div className="empty compact-empty">لا يوجد مبلغ متاح للاسترداد أو لا توجد صلاحية طلب.</div>}</>}</Card><Card><h3>طلبات الاسترداد</h3><Table rows={list} columns={[{key:'receipt_no',label:'السند'},{key:'booking_number',label:'الحجز'},{key:'amount',label:'المبلغ',render:r=>money(r.amount)},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='completed'?'green':r.status==='rejected'?'red':'orange'}>{statusLabel(r.status)}</Badge>},{key:'requested_at',label:'التاريخ',render:r=>dateTime(r.requested_at)},{key:'actions',label:'الإجراء',render:r=><div className="row-actions">{r.status==='pending'&&caps.approve&&<><button disabled={busy===r.id} onClick={e=>{e.stopPropagation();decide(r.id,'approved')}}>اعتماد</button><button disabled={busy===r.id} onClick={e=>{e.stopPropagation();decide(r.id,'rejected')}}>رفض</button></>}{r.status==='approved'&&caps.complete&&<button disabled={busy===r.id} onClick={e=>{e.stopPropagation();complete(r.id)}}>تنفيذ</button>}{r.status==='completed'&&caps.print&&<button title="طباعة سند الاسترداد" onClick={e=>{e.stopPropagation();printRefund(r)}}><Printer size={14}/></button>}</div>}]}/></Card></div></>;
}
