import React,{useEffect,useMemo,useState} from 'react';
import {RefreshCw,Plus,WalletCards,ReceiptText,Banknote,TrendingUp,LockKeyhole,Printer,Download,Eye,RotateCcw,LayoutDashboard,Scale,Building2,Clock3,Landmark,ArrowLeftRight} from 'lucide-react';
import {useAppData} from '../../core/AppDataContext.jsx';
import {useAuth} from '../../core/AuthContext.jsx';
import {useLanguage} from '../../core/LanguageContext.jsx';
import {api} from '../../lib/api.js';
import {Badge,Button,Card,ErrorBox,Field,Input,Loading,Modal,Select,Table,Textarea} from '../../components/UI.jsx';
import ModuleShell,{useModuleTab} from '../../components/ModuleShell.jsx';
import {money,dateTime,statusLabel} from '../../lib/format.js';
import {allFinance,has} from '../../lib/permissions.js';
import {basicPrintDocument,printHtmlDocument} from '../../lib/print.js';
import FinanceReconciliation from './FinanceReconciliation.jsx';
import SmartListFilters from '../../components/SmartListFilters.jsx';
import {matchesListQuery} from '../../lib/listFilters.js';
import {DATE_PRESET_OPTIONS,dateRangeForPreset,isWithinDateRange} from '../../lib/dateRangeFilters.js';
import RuleFilterBuilder from '../../components/RuleFilterBuilder.jsx';
import {matchesRuleSet} from '../../lib/ruleFilters.js';

const s=v=>String(v??'');
const REPORTS={summary:'الملخص المالي',expenses:'المصروفات',transactions:'الحركات المالية',cash_registers:'الخزن',cash_shifts:'الورديات',supplier_payables:'مستحقات الموردين'};
const esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
export default function Finance(){
 const {user}=useAuth(),{data:appData}=useAppData(),{language,dir,t}=useLanguage();
 const [data,setData]=useState(null),[brief,setBrief]=useState(null),[error,setError]=useState(''),[modal,setModal]=useState(null),[busy,setBusy]=useState(false);
 const [report,setReport]=useState({type:'summary',branch:'',from:'',to:''});
 const [listFilter,setListFilter]=useState({q:'',branch:'',status:'',type:'',category:'',register:'',datePreset:'',fromDate:'',toDate:''});
 const [listRules,setListRules]=useState([]),[listRuleMode,setListRuleMode]=useState('all');
 const p=user?.permissions||{},viewReceiptExplicit=Object.prototype.hasOwnProperty.call(p,'viewPaymentReceipts'),printReceiptExplicit=Object.prototype.hasOwnProperty.call(p,'printPaymentReceipts');
 const canViewReceipt=has(user,'viewPaymentReceipts')||(!viewReceiptExplicit&&(has(user,'finance')||has(user,'payments')));
 const canPrintReceipt=has(user,'printPaymentReceipts')||(!printReceiptExplicit&&(has(user,'finance')||has(user,'payments')));
 async function load(){setError('');try{const [d,b]=await Promise.all([api.module('finance_full'),api.mega('executive_brief',{},'GET').catch(()=>null)]);setData(d);setBrief(b)}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 const branchMap=useMemo(()=>new Map(appData.branches.map(b=>[s(b.id),b.name])),[appData.branches]);const registerMap=useMemo(()=>new Map((data?.cash_registers||[]).map(r=>[s(r.id),r])),[data]);
 async function addExpense(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await api.platform({action:'add_expense',row:{expense_date:f.expense_date,branch_id:f.branch_id||appData.scope?.branch_id,trip_id:f.trip_id||null,category:f.category,amount:Number(f.amount),notes:f.notes||''}});await load();setModal(null)}catch(e2){setError(e2.message)}finally{setBusy(false)}}
 async function addRegister(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await api.moduleWrite({action:'insert',table:'cash_registers',row:{name:f.name,branch_id:f.branch_id||appData.scope?.branch_id,active:true}});await load();setModal(null)}catch(e2){setError(e2.message)}finally{setBusy(false)}}
 async function openShift(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await api.moduleWrite({action:'insert',table:'cash_shifts',row:{register_id:f.register_id,staff_user_id:user?.id||null,opening_balance:Number(f.opening_balance||0),status:'open',opened_at:new Date().toISOString()}});await load();setModal(null)}catch(e2){setError(e2.message)}finally{setBusy(false)}}
 async function closeShift(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),row=modal?.row;if(!row)return;const actual=Number(f.actual_closing||0),expected=Number(row.expected_closing??row.opening_balance??0);setBusy(true);try{await api.moduleWrite({action:'update',table:'cash_shifts',id:row.id,row:{actual_closing:actual,variance:actual-expected,status:'closed',closed_at:new Date().toISOString(),closing_notes:f.closing_notes||''}});await load();setModal(null)}catch(e2){setError(e2.message)}finally{setBusy(false)}}
 function receiptRef(r){const ref=String(r.reference||r.reference_no||'').trim(),type=String(r.type||r.transaction_type||'').toLowerCase();return type==='payment'&&ref.startsWith('PAY-')?ref:''}
 function openReceipt(r,mode='view'){const ref=receiptRef(r);if(!ref)return;window.open(`/api/payments/receipt/${mode}?receipt_no=${encodeURIComponent(ref)}`,'_blank','noopener,noreferrer')}
 const moduleTabs=useMemo(()=>[
  {id:'overview',label:'نظرة عامة',icon:LayoutDashboard},
  {id:'reconciliation',label:'المطابقة المالية',icon:Scale},
  {id:'expenses',label:'المصروفات',icon:ReceiptText,badge:data?.expenses?.length??0},
  {id:'transactions',label:'الحركات',icon:ArrowLeftRight,badge:data?.transactions?.length??0},
  {id:'cash_registers',label:'الخزن',icon:Landmark,badge:data?.cash_registers?.length??0},
  {id:'cash_shifts',label:'الورديات',icon:Clock3,badge:data?.cash_shifts?.length??0},
  {id:'supplier_payables',label:'مستحقات الموردين',icon:Building2,badge:data?.supplier_payables?.length??0}
 ],[data]);
 const [tab,setTab]=useModuleTab('almaher:module:finance',moduleTabs,'overview');
 const cols={
  expenses:[{key:'expense_date',label:'التاريخ'},{key:'category',label:'البند'},{key:'amount',label:'المبلغ',render:r=>money(r.amount)},{key:'trip',label:'الرحلة',render:r=>appData.trips.find(t=>s(t.id)===s(r.trip_id))?.trip_code||'—'},{key:'branch',label:'الفرع',render:r=>branchMap.get(s(r.branch_id))||'—'},{key:'notes',label:'ملاحظات'}],
  transactions:[{key:'created_at',label:'التاريخ',render:r=>dateTime(r.created_at)},{key:'type',label:'النوع',render:r=>statusLabel(r.type||r.transaction_type)},{key:'amount',label:'المبلغ',render:r=>money(r.amount)},{key:'status',label:'الحالة',render:r=><Badge>{statusLabel(r.status||'posted')}</Badge>},{key:'reference',label:'المرجع',render:r=>r.reference||r.reference_no||r.booking_number||'—'},{key:'receipt',label:'سند القبض',render:r=>{const ref=receiptRef(r);if(!ref)return '—';return <div className="row-actions">{canViewReceipt&&<Button title="عرض سند القبض" onClick={()=>openReceipt(r,'view')}><Eye size={14}/> عرض</Button>}{canPrintReceipt&&<Button title="طباعة سند القبض" onClick={()=>openReceipt(r,'print')}><Printer size={14}/> طباعة</Button>}{!canViewReceipt&&!canPrintReceipt&&<Badge>سند محفوظ</Badge>}</div>}}],
  cash_registers:[{key:'name',label:'الخزنة'},{key:'branch',label:'الفرع',render:r=>branchMap.get(s(r.branch_id))||'—'},{key:'active',label:'الحالة',render:r=><Badge tone={r.active===false?'red':'green'}>{r.active===false?'موقوفة':'نشطة'}</Badge>}],
  cash_shifts:[{key:'register_id',label:'الخزنة',render:r=>registerMap.get(s(r.register_id))?.name||'—'},{key:'opened_at',label:'الفتح',render:r=>dateTime(r.opened_at)},{key:'opening_balance',label:'افتتاحي',render:r=>money(r.opening_balance)},{key:'actual_closing',label:'إغلاق فعلي',render:r=>r.actual_closing==null?'—':money(r.actual_closing)},{key:'variance',label:'الفرق',render:r=>r.variance==null?'—':money(r.variance)},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='closed'?'blue':'green'}>{statusLabel(r.status||'open')}</Badge>},{key:'action',label:'',render:r=>r.status==='open'?<Button onClick={()=>setModal({type:'closeShift',row:r})}>إغلاق الوردية</Button>:null}],
  supplier_payables:[{key:'due_date',label:'الاستحقاق'},{key:'supplier_id',label:'المورد'},{key:'amount',label:'المبلغ',render:r=>money(r.amount)},{key:'paid_amount',label:'المدفوع',render:r=>money(r.paid_amount)},{key:'status',label:'الحالة',render:r=><Badge>{statusLabel(r.status||'open')}</Badge>},{key:'notes',label:'ملاحظات'}]
 };
 const rows=['expenses','transactions','cash_registers','cash_shifts','supplier_payables'].includes(tab)?(data?.[tab]||[]):[];
 const branchOptions=useMemo(()=>appData.branches.map(b=>({value:s(b.id),label:b.name||b.branch_name||b.id})).sort((a,b)=>a.label.localeCompare(b.label,'ar')),[appData.branches]);
 const statusOptions=useMemo(()=>[...new Set(rows.map(r=>s(r.status||(tab==='cash_registers'?(r.active===false?'inactive':'active'):'')).trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar')).map(v=>({value:v,label:v==='active'?'نشطة':v==='inactive'?'موقوفة':statusLabel(v)})),[rows,tab]);
 const typeOptions=useMemo(()=>[...new Set(rows.map(r=>s(r.type||r.transaction_type).trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar')).map(v=>({value:v,label:statusLabel(v)})),[rows]);
 const categoryOptions=useMemo(()=>[...new Set(rows.map(r=>s(r.category).trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar')).map(v=>({value:v,label:v})),[rows]);
 const registerOptions=useMemo(()=>(data?.cash_registers||[]).map(r=>({value:s(r.id),label:r.name||r.id})).sort((a,b)=>a.label.localeCompare(b.label,'ar')),[data]);
 const financeRuleFields=useMemo(()=>[
  {key:'branch',label:'الفرع',options:branchOptions,get:r=>s(r.branch_id)},
  {key:'status',label:'الحالة',options:statusOptions,get:r=>s(r.status||(tab==='cash_registers'?(r.active===false?'inactive':'active'):'posted'))},
  {key:'type',label:'نوع الحركة',options:typeOptions,get:r=>s(r.type||r.transaction_type)},
  {key:'category',label:'البند',options:categoryOptions,get:r=>s(r.category)},
  {key:'register',label:'الخزنة',options:registerOptions,get:r=>s(r.register_id)},
  {key:'amount',label:'المبلغ',type:'number',get:r=>r.amount},
  {key:'paidAmount',label:'المبلغ المدفوع',type:'number',get:r=>r.paid_amount},
  {key:'variance',label:'فرق الوردية',type:'number',get:r=>r.variance},
  {key:'reference',label:'المرجع / رقم الحجز',get:r=>r.reference||r.reference_no||r.booking_number},
  {key:'date',label:'تاريخ السجل',type:'date',get:r=>rowDate(r)}
 ],[branchOptions,statusOptions,typeOptions,categoryOptions,registerOptions,tab]);
 const filteredRows=useMemo(()=>rows.filter(r=>{
  const currentStatus=s(r.status||(tab==='cash_registers'?(r.active===false?'inactive':'active'):''));
  if(listFilter.branch&&s(r.branch_id)!==listFilter.branch)return false;
  if(listFilter.status&&currentStatus!==listFilter.status)return false;
  if(listFilter.type&&s(r.type||r.transaction_type)!==listFilter.type)return false;
  if(listFilter.category&&s(r.category)!==listFilter.category)return false;
  if(listFilter.register&&s(r.register_id)!==listFilter.register)return false;
  if(!isWithinDateRange(rowDate(r),listFilter.fromDate,listFilter.toDate))return false;
  return matchesListQuery(listFilter.q,r.expense_date,r.category,r.notes,r.created_at,r.type,r.transaction_type,r.status,r.reference,r.reference_no,r.booking_number,r.name,r.opened_at,r.due_date,r.supplier_id,r.amount,r.paid_amount,branchMap.get(s(r.branch_id)),registerMap.get(s(r.register_id))?.name,appData.trips.find(t=>s(t.id)===s(r.trip_id))?.trip_code);
 }),[rows,listFilter,tab,branchMap,registerMap,appData.trips,listRules,financeRuleFields,listRuleMode]);
 function applyListDatePreset(v){setListFilter(x=>{if(!v)return {...x,datePreset:'',fromDate:'',toDate:''};if(v==='custom')return {...x,datePreset:v};const r=dateRangeForPreset(v);return {...x,datePreset:v,fromDate:r.from,toDate:r.to}})}
 function rawValue(r,key){if(key==='trip')return appData.trips.find(t=>s(t.id)===s(r.trip_id))?.trip_code||'—';if(key==='branch')return branchMap.get(s(r.branch_id))||'—';if(key==='register_id')return registerMap.get(s(r.register_id))?.name||'—';if(['amount','paid_amount','opening_balance','actual_closing','variance'].includes(key))return money(r[key]);if(['created_at','opened_at'].includes(key))return dateTime(r[key]);if(key==='status')return statusLabel(r.status);if(key==='active')return r.active===false?'موقوفة':'نشطة';if(key==='reference')return r.reference||r.reference_no||r.booking_number||'—';if(key==='type')return statusLabel(r.type||r.transaction_type);if(key==='receipt')return receiptRef(r)||'—';return r[key]??'—'}
 function rowDate(r){return String(r.expense_date||r.created_at||r.opened_at||r.due_date||'').slice(0,10)}
 function filtered(type=report.type){let out=[...(data?.[type]||[])];if(report.branch)out=out.filter(r=>s(r.branch_id)===s(report.branch));if(report.from)out=out.filter(r=>!rowDate(r)||rowDate(r)>=report.from);if(report.to)out=out.filter(r=>!rowDate(r)||rowDate(r)<=report.to);return out}
 function reportColumns(type=report.type){return (cols[type]||[]).filter(c=>c.key!=='action'&&c.key!=='receipt')}
 function reportBody(){
  const title=REPORTS[report.type]||'التقرير المالي',scope=report.branch?branchMap.get(s(report.branch))||'فرع محدد':allFinance(user)?'كل الفروع':'فرعك فقط';
  const meta=`<div class="meta">النطاق: ${esc(scope)}${report.from?` — من ${esc(report.from)}`:''}${report.to?` — إلى ${esc(report.to)}`:''} — ${esc(new Date().toLocaleString(language==='ar'?'ar-SA':language))}</div>`;
  const summary=`<div class="summary"><div class="box">${esc(t('totalBookings','إجمالي الحجوزات'))}<b>${esc(money(brief?.revenue))}</b></div><div class="box">${esc(t('grossCollected','إجمالي التحصيل التاريخي'))}<b>${esc(money(brief?.paid))}</b></div><div class="box">${esc(t('refunds','الاستردادات'))}<b>${esc(money(brief?.refunded))}</b></div><div class="box">${esc(t('netCollected','صافي المحصل'))}<b>${esc(money(brief?.net))}</b></div><div class="box">${esc(t('expenses','المصروفات'))}<b>${esc(money(brief?.expenses))}</b></div></div>`;
  if(report.type==='summary')return `<h1>${esc(title)}</h1>${meta}${summary}`;
  const cs=reportColumns(),rs=filtered();
  return `<h1>${esc(title)}</h1>${meta}${summary}<table><thead><tr>${cs.map(c=>`<th>${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${rs.length?rs.map(r=>`<tr>${cs.map(c=>`<td>${esc(rawValue(r,c.key))}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${Math.max(1,cs.length)}">لا توجد بيانات ضمن الاختيارات الحالية</td></tr>`}</tbody></table>`;
 }
 function doPrint(){try{const html=basicPrintDocument({title:REPORTS[report.type]||'التقرير المالي',dir,lang:language,body:reportBody(),styles:'h1{font-size:24px;margin:0 0 8px}.meta{color:#64748b;margin:0 0 16px}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:14px 0}.box{border:1px solid #dbe3ec;border-radius:10px;padding:9px}.box b{display:block;margin-top:4px}table{width:100%;border-collapse:collapse;margin-top:14px;font-size:11px}th,td{border:1px solid #dbe3ec;padding:7px;text-align:start}th{background:#f1f5f9}'});printHtmlDocument(html);setModal(null)}catch(e){setError(e.message)}}
 function exportCsv(type=report.type){if(type==='summary'){const lines=[['البند','القيمة'],['إجمالي الحجوزات',money(brief?.revenue)],['إجمالي التحصيل التاريخي',money(brief?.paid)],['الاستردادات',money(brief?.refunded)],['صافي المحصل',money(brief?.net)],['المصروفات',money(brief?.expenses)],['المتبقي المطلوب تحصيله',money(brief?.outstanding)]];downloadCsv(lines,'finance-summary');return}const cs=reportColumns(type),rs=filtered(type);downloadCsv([cs.map(c=>c.label),...rs.map(r=>cs.map(c=>String(rawValue(r,c.key))))],`finance-${type}`)}
 function downloadCsv(matrix,name){const lines=matrix.map(a=>a.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),blob=new Blob(['\ufeff'+lines],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${name}-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function openReports(){setReport({type:'summary',branch:allFinance(user)?'':(appData.scope?.branch_id||''),from:'',to:''});setModal('report')}
 const contextualActions=<><Button onClick={load}><RefreshCw size={16}/> {t('refresh','تحديث')}</Button>{tab==='expenses'&&has(user,'expenses')&&<Button variant="primary" onClick={()=>setModal('expense')}><Plus size={16}/> {t('expense','مصروف')}</Button>}{tab==='cash_registers'&&(has(user,'finance')||has(user,'payments'))&&<Button variant="primary" onClick={()=>setModal('register')}><Plus size={16}/> {t('cashRegister','خزنة')}</Button>}{tab==='cash_shifts'&&(has(user,'finance')||has(user,'shifts'))&&<Button variant="primary" onClick={()=>setModal('shift')}><Plus size={16}/> {t('openShift','فتح وردية')}</Button>}{has(user,'printReports')&&<Button onClick={openReports}><Printer size={16}/> مركز التقارير</Button>}{has(user,'reports')&&<Button onClick={()=>{setReport(r=>({...r,type:['expenses','transactions','cash_registers','cash_shifts','supplier_payables'].includes(tab)?tab:'summary'}));setModal('report')}}><Download size={16}/> CSV / PDF</Button>}</>;

 return <div className="finance-module" data-tab={tab}><ModuleShell title={t('finance','المالية')} subtitle={t('financeSubtitle','التحصيل والمصروفات والخزن والورديات بعزل مالي صارم للفروع')} icon={WalletCards} tabs={moduleTabs} activeTab={tab} onTabChange={v=>{setTab(v);setListFilter({q:'',branch:'',status:'',type:'',category:'',register:'',datePreset:'',fromDate:'',toDate:''});setListRules([]);setListRuleMode('all')}} actions={contextualActions} breadcrumbs={[{label:'المالية'},{label:moduleTabs.find(x=>x.id===tab)?.label||'نظرة عامة'}]}/><ErrorBox error={error}/>
 <div className="finance-overview-panel">
  <div className="stats-grid finance-stats"><Stat icon={<WalletCards/>} label={t('totalBookings','إجمالي الحجوزات')} value={money(brief?.revenue)}/><Stat icon={<Banknote/>} label={t('grossCollected','إجمالي التحصيل التاريخي')} value={money(brief?.paid)}/><Stat icon={<RotateCcw/>} label={t('refunds','الاستردادات')} value={money(brief?.refunded)}/><Stat icon={<TrendingUp/>} label={t('netCollected','صافي المحصل')} value={money(brief?.net)}/><Stat icon={<ReceiptText/>} label={t('expenses','المصروفات')} value={money(brief?.expenses)}/></div>
  <Card><div className="finance-scope"><LockKeyhole size={17}/><span>{t('financialScope','النطاق المالي الحالي')}: <b>{allFinance(user)?t('allBranches','كل الفروع'):t('yourBranchOnly','فرعك فقط')}</b></span>{brief?.outstanding>0&&<Badge tone="orange">متبقي تحصيل {money(brief.outstanding)}</Badge>}{brief?.financial_mismatches>0&&<Badge tone="red">عدم تطابق مالي {brief.financial_mismatches}</Badge>}</div><div className="finance-actions">{has(user,'expenses')&&<Button variant="primary" onClick={()=>setModal('expense')}><Plus size={16}/> {t('expense','مصروف')}</Button>}{(has(user,'finance')||has(user,'payments'))&&<Button onClick={()=>setModal('register')}><Plus size={16}/> {t('cashRegister','خزنة')}</Button>}{(has(user,'finance')||has(user,'shifts'))&&<Button onClick={()=>setModal('shift')}><Plus size={16}/> {t('openShift','فتح وردية')}</Button>}</div></Card>
 </div>
 {tab==='reconciliation'&&<FinanceReconciliation/>}
 {['expenses','transactions','cash_registers','cash_shifts','supplier_payables'].includes(tab)&&(!data&&!error?<Loading/>:<Card><div className="card-title"><h3>{moduleTabs.find(x=>x.id===tab)?.label}</h3><Badge>{rows.length}</Badge></div><SmartListFilters storageKey={`finance-${tab}-filters`} search={listFilter.q} onSearchChange={v=>setListFilter(x=>({...x,q:v}))} searchPlaceholder="ابحث في السجل المالي..." totalCount={rows.length} resultCount={filteredRows.length} onReset={()=>{setListFilter({q:'',branch:'',status:'',type:'',category:'',register:'',datePreset:'',fromDate:'',toDate:''});setListRules([]);setListRuleMode('all')}} advanced={{getValue:()=>({rules:listRules,mode:listRuleMode}),onApply:v=>{setListRules(Array.isArray(v?.rules)?v.rules:[]);setListRuleMode(v?.mode==='any'?'any':'all')},render:()=> <RuleFilterBuilder fields={financeRuleFields} rules={listRules} mode={listRuleMode} onRulesChange={setListRules} onModeChange={setListRuleMode}/>}} filters={[
 ...(rows.some(r=>r.branch_id!=null)?[{key:'branch',label:'الفرع',value:listFilter.branch,onChange:v=>setListFilter(x=>({...x,branch:v})),options:branchOptions}]:[]),
 ...((tab==='transactions'||tab==='cash_shifts'||tab==='cash_registers'||tab==='supplier_payables')?[{key:'status',label:'الحالة',value:listFilter.status,onChange:v=>setListFilter(x=>({...x,status:v})),options:statusOptions}]:[]),
 ...(tab==='transactions'?[{key:'type',label:'نوع الحركة',value:listFilter.type,onChange:v=>setListFilter(x=>({...x,type:v})),options:typeOptions}]:[]),
 ...(tab==='expenses'?[{key:'category',label:'البند',value:listFilter.category,onChange:v=>setListFilter(x=>({...x,category:v})),options:categoryOptions}]:[]),
 ...(tab==='cash_shifts'?[{key:'register',label:'الخزنة',value:listFilter.register,onChange:v=>setListFilter(x=>({...x,register:v})),options:registerOptions}]:[]),
 {key:'datePreset',label:'الفترة',value:listFilter.datePreset,onChange:applyListDatePreset,options:DATE_PRESET_OPTIONS},
 {key:'fromDate',label:'من تاريخ',value:listFilter.fromDate,onChange:v=>setListFilter(x=>({...x,fromDate:v,datePreset:v||x.toDate?'custom':''})),render:()=> <Input type="date" value={listFilter.fromDate} onChange={e=>setListFilter(x=>({...x,fromDate:e.target.value,datePreset:e.target.value||x.toDate?'custom':''}))}/>},
 {key:'toDate',label:'إلى تاريخ',value:listFilter.toDate,onChange:v=>setListFilter(x=>({...x,toDate:v,datePreset:x.fromDate||v?'custom':''})),render:()=> <Input type="date" value={listFilter.toDate} onChange={e=>setListFilter(x=>({...x,toDate:e.target.value,datePreset:x.fromDate||e.target.value?'custom':''}))}/>}
 ]}/><Table preferenceKey={'finance-'+tab} defaultPageSize={25} rows={filteredRows} columns={cols[tab]||[]}/></Card>)}
 <Modal open={modal==='report'} onClose={()=>setModal(null)} title="مركز التقارير والطباعة"><div className="form-grid"><Field label="نوع التقرير"><Select value={report.type} onChange={e=>setReport(r=>({...r,type:e.target.value}))}>{Object.entries(REPORTS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></Field><Field label="الفرع"><Select value={report.branch} onChange={e=>setReport(r=>({...r,branch:e.target.value}))} disabled={!allFinance(user)}><option value="">كل الفروع المصرح بها</option>{appData.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select></Field><Field label="من تاريخ"><Input type="date" value={report.from} onChange={e=>setReport(r=>({...r,from:e.target.value}))}/></Field><Field label="إلى تاريخ"><Input type="date" value={report.to} onChange={e=>setReport(r=>({...r,to:e.target.value}))}/></Field><Card><b>{REPORTS[report.type]}</b><p style={{margin:'6px 0 0',color:'#64748b'}}>سيتم طباعة المستند المختار فقط، وليس شاشة النظام أو التبويب الحالي.</p></Card><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button>{has(user,'reports')&&<Button type="button" onClick={()=>exportCsv()}><Download size={16}/> CSV</Button>}{has(user,'printReports')&&<Button variant="primary" type="button" onClick={doPrint}><Printer size={16}/> طباعة / PDF</Button>}</div></div></Modal>
 <Modal open={modal==='expense'} onClose={()=>setModal(null)} title="تسجيل مصروف"><form className="form-grid" onSubmit={addExpense}><Field label="التاريخ"><Input type="date" name="expense_date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field><Field label="الفرع"><Select name="branch_id" defaultValue={appData.scope?.branch_id||''} disabled={!allFinance(user)}><option value="">اختر</option>{appData.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select>{!allFinance(user)&&<input type="hidden" name="branch_id" value={appData.scope?.branch_id||''}/>}</Field><Field label="الرحلة"><Select name="trip_id"><option value="">بدون رحلة</option>{appData.trips.map(t=><option key={t.id} value={t.id}>{t.trip_code}</option>)}</Select></Field><Field label="البند"><Input name="category" required placeholder="وقود / فندق / تشغيل..."/></Field><Field label="المبلغ"><Input name="amount" type="number" min="0.01" step="0.01" required/></Field><Field label="ملاحظات"><Textarea name="notes"/></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>حفظ</Button></div></form></Modal>
 <Modal open={modal==='register'} onClose={()=>setModal(null)} title="إضافة خزنة"><form className="form-grid" onSubmit={addRegister}><Field label="اسم الخزنة"><Input name="name" required/></Field><Field label="الفرع"><Select name="branch_id" defaultValue={appData.scope?.branch_id||''} disabled={!allFinance(user)}>{appData.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select>{!allFinance(user)&&<input type="hidden" name="branch_id" value={appData.scope?.branch_id||''}/>}</Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>حفظ</Button></div></form></Modal>
 <Modal open={modal==='shift'} onClose={()=>setModal(null)} title="فتح وردية"><form className="form-grid" onSubmit={openShift}><Field label="الخزنة"><Select name="register_id" required><option value="">اختر</option>{(data?.cash_registers||[]).filter(r=>r.active!==false).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></Field><Field label="رصيد الافتتاح"><Input name="opening_balance" type="number" step="0.01" defaultValue="0"/></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>فتح</Button></div></form></Modal>
 <Modal open={modal?.type==='closeShift'} onClose={()=>setModal(null)} title="إغلاق الوردية"><form className="form-grid" onSubmit={closeShift}><Field label="الرصيد الفعلي"><Input name="actual_closing" type="number" step="0.01" required/></Field><Field label="ملاحظات الإغلاق"><Textarea name="closing_notes"/></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>إغلاق الوردية</Button></div></form></Modal></div>;
}
function Stat({icon,label,value}){return <Card className="stat-card"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></Card>}
