import React,{useEffect,useMemo,useState} from 'react';
import {RefreshCw,Plus,WalletCards,ReceiptText,Banknote,TrendingUp,LockKeyhole,Printer,Download} from 'lucide-react';
import {useAppData} from '../../core/AppDataContext.jsx';
import {useAuth} from '../../core/AuthContext.jsx';
import {api} from '../../lib/api.js';
import {Badge,Button,Card,ErrorBox,Field,Input,Loading,Modal,PageHeader,Select,Table,Textarea} from '../../components/UI.jsx';
import {money,dateTime,statusLabel} from '../../lib/format.js';
import {allFinance,has} from '../../lib/permissions.js';

const s=v=>String(v??'');
const TAB_TITLES={expenses:'المصروفات',transactions:'الحركات المالية',cash_registers:'الخزن',cash_shifts:'الورديات',supplier_payables:'مستحقات الموردين'};
const escapeHtml=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
export default function Finance(){
 const {user}=useAuth(),{data:appData}=useAppData();const [data,setData]=useState(null),[brief,setBrief]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState('expenses'),[modal,setModal]=useState(null),[busy,setBusy]=useState(false);
 async function load(){setError('');try{const [d,b]=await Promise.all([api.module('finance_full'),api.mega('executive_brief',{},'GET').catch(()=>null)]);setData(d);setBrief(b)}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 const branchMap=useMemo(()=>new Map(appData.branches.map(b=>[s(b.id),b.name])),[appData.branches]);const registerMap=useMemo(()=>new Map((data?.cash_registers||[]).map(r=>[s(r.id),r])),[data]);
 async function addExpense(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await api.platform({action:'add_expense',row:{expense_date:f.expense_date,branch_id:f.branch_id||appData.scope?.branch_id,trip_id:f.trip_id||null,category:f.category,amount:Number(f.amount),notes:f.notes||''}});await load();setModal(null)}catch(e2){setError(e2.message)}finally{setBusy(false)}}
 async function addRegister(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await api.moduleWrite({action:'insert',table:'cash_registers',row:{name:f.name,branch_id:f.branch_id||appData.scope?.branch_id,active:true}});await load();setModal(null)}catch(e2){setError(e2.message)}finally{setBusy(false)}}
 async function openShift(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await api.moduleWrite({action:'insert',table:'cash_shifts',row:{register_id:f.register_id,staff_user_id:user?.id||null,opening_balance:Number(f.opening_balance||0),status:'open',opened_at:new Date().toISOString()}});await load();setModal(null)}catch(e2){setError(e2.message)}finally{setBusy(false)}}
 async function closeShift(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),row=modal?.row;if(!row)return;const actual=Number(f.actual_closing||0),expected=Number(row.expected_closing??row.opening_balance??0);setBusy(true);try{await api.moduleWrite({action:'update',table:'cash_shifts',id:row.id,row:{actual_closing:actual,variance:actual-expected,status:'closed',closed_at:new Date().toISOString(),closing_notes:f.closing_notes||''}});await load();setModal(null)}catch(e2){setError(e2.message)}finally{setBusy(false)}}
 const tabs=[['expenses','المصروفات'],['transactions','الحركات'],['cash_registers','الخزن'],['cash_shifts','الورديات'],['supplier_payables','مستحقات الموردين']];
 const cols={
  expenses:[{key:'expense_date',label:'التاريخ'},{key:'category',label:'البند'},{key:'amount',label:'المبلغ',render:r=>money(r.amount)},{key:'trip',label:'الرحلة',render:r=>appData.trips.find(t=>s(t.id)===s(r.trip_id))?.trip_code||'—'},{key:'branch',label:'الفرع',render:r=>branchMap.get(s(r.branch_id))||'—'},{key:'notes',label:'ملاحظات'}],
  transactions:[{key:'created_at',label:'التاريخ',render:r=>dateTime(r.created_at)},{key:'type',label:'النوع',render:r=>statusLabel(r.type)},{key:'amount',label:'المبلغ',render:r=>money(r.amount)},{key:'status',label:'الحالة',render:r=><Badge>{statusLabel(r.status||'posted')}</Badge>},{key:'reference',label:'المرجع',render:r=>r.reference||r.reference_no||r.booking_number||'—'}],
  cash_registers:[{key:'name',label:'الخزنة'},{key:'branch',label:'الفرع',render:r=>branchMap.get(s(r.branch_id))||'—'},{key:'active',label:'الحالة',render:r=><Badge tone={r.active===false?'red':'green'}>{r.active===false?'موقوفة':'نشطة'}</Badge>}],
  cash_shifts:[{key:'register_id',label:'الخزنة',render:r=>registerMap.get(s(r.register_id))?.name||'—'},{key:'opened_at',label:'الفتح',render:r=>dateTime(r.opened_at)},{key:'opening_balance',label:'افتتاحي',render:r=>money(r.opening_balance)},{key:'actual_closing',label:'إغلاق فعلي',render:r=>r.actual_closing==null?'—':money(r.actual_closing)},{key:'variance',label:'الفرق',render:r=>r.variance==null?'—':money(r.variance)},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='closed'?'blue':'green'}>{statusLabel(r.status||'open')}</Badge>},{key:'action',label:'',render:r=>r.status==='open'?<Button onClick={()=>setModal({type:'closeShift',row:r})}>إغلاق الوردية</Button>:null}],
  supplier_payables:[{key:'due_date',label:'الاستحقاق'},{key:'supplier_id',label:'المورد'},{key:'amount',label:'المبلغ',render:r=>money(r.amount)},{key:'paid_amount',label:'المدفوع',render:r=>money(r.paid_amount)},{key:'status',label:'الحالة',render:r=><Badge>{statusLabel(r.status||'open')}</Badge>},{key:'notes',label:'ملاحظات'}]
 };
 const rows=data?.[tab]||[];
 function rawValue(r,key){
  if(key==='trip')return appData.trips.find(t=>s(t.id)===s(r.trip_id))?.trip_code||'—';
  if(key==='branch')return branchMap.get(s(r.branch_id))||'—';
  if(key==='register_id')return registerMap.get(s(r.register_id))?.name||'—';
  if(['amount','paid_amount','opening_balance','actual_closing','variance'].includes(key))return money(r[key]);
  if(['created_at','opened_at'].includes(key))return dateTime(r[key]);
  if(key==='status')return statusLabel(r.status);
  if(key==='active')return r.active===false?'موقوفة':'نشطة';
  if(key==='reference')return r.reference||r.reference_no||r.booking_number||'—';
  if(key==='type')return statusLabel(r.type);
  return r[key]??'—';
 }
 function reportColumns(){return (cols[tab]||[]).filter(c=>c.key!=='action')}
 function printReport(){
  const cs=reportColumns();const title=TAB_TITLES[tab]||'التقرير المالي';const scope=allFinance(user)?'كل الفروع':'فرعك فقط';
  const html=`<!doctype html><html dir="rtl" lang="ar"><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>body{font-family:Tahoma,Arial,sans-serif;color:#13233a;padding:24px}h1{margin:0 0 6px;font-size:24px}.meta{color:#64748b;margin-bottom:18px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:16px 0}.box{border:1px solid #dbe3ec;border-radius:10px;padding:10px}.box b{display:block;margin-top:4px}table{width:100%;border-collapse:collapse;margin-top:14px;font-size:12px}th,td{border:1px solid #dbe3ec;padding:8px;text-align:right}th{background:#f1f5f9}@media print{body{padding:0}.no-print{display:none}}</style></head><body><h1>${escapeHtml(title)}</h1><div class="meta">النطاق المالي: ${escapeHtml(scope)} — ${escapeHtml(new Date().toLocaleString('ar-SA'))}</div><div class="summary"><div class="box">إجمالي الحجوزات<b>${escapeHtml(money(brief?.revenue))}</b></div><div class="box">المحصل<b>${escapeHtml(money(brief?.paid))}</b></div><div class="box">المصروفات<b>${escapeHtml(money(brief?.expenses))}</b></div><div class="box">صافي المحصل<b>${escapeHtml(money(brief?.net))}</b></div></div><table><thead><tr>${cs.map(c=>`<th>${escapeHtml(c.label)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cs.map(c=>`<td>${escapeHtml(rawValue(r,c.key))}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cs.length}">لا توجد بيانات</td></tr>`}</tbody></table><script>window.onload=()=>{window.print()}</script></body></html>`;
  const w=window.open('','_blank','noopener,noreferrer');if(!w){setError('المتصفح منع نافذة الطباعة. اسمح بالنوافذ المنبثقة ثم حاول مرة أخرى.');return}w.document.open();w.document.write(html);w.document.close();
 }
 function exportCsv(){
  const cs=reportColumns();const lines=[[...cs.map(c=>c.label)],...rows.map(r=>cs.map(c=>String(rawValue(r,c.key)).replaceAll('"','""')))].map(a=>a.map(v=>`"${v}"`).join(',')).join('\n');
  const blob=new Blob(['\ufeff'+lines],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`finance-${tab}-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 return <><PageHeader title="المالية" subtitle="التحصيل والمصروفات والخزن والورديات بعزل مالي صارم للفروع" actions={<><Button onClick={load}><RefreshCw size={16}/> تحديث</Button>{has(user,'printReports')&&<Button onClick={printReport}><Printer size={16}/> طباعة التقرير</Button>}{has(user,'reports')&&<Button onClick={exportCsv}><Download size={16}/> تصدير CSV</Button>}</>}/><ErrorBox error={error}/><div className="stats-grid finance-stats"><Stat icon={<WalletCards/>} label="إجمالي الحجوزات" value={money(brief?.revenue)}/><Stat icon={<Banknote/>} label="المحصل" value={money(brief?.paid)}/><Stat icon={<ReceiptText/>} label="المصروفات" value={money(brief?.expenses)}/><Stat icon={<TrendingUp/>} label="صافي المحصل" value={money(brief?.net)}/></div><Card><div className="finance-scope"><LockKeyhole size={17}/><span>النطاق المالي الحالي: <b>{allFinance(user)?'كل الفروع':'فرعك فقط'}</b></span>{brief?.outstanding>0&&<Badge tone="orange">متبقي تحصيل {money(brief.outstanding)}</Badge>}</div><div className="finance-actions">{has(user,'expenses')&&<Button variant="primary" onClick={()=>setModal('expense')}><Plus size={16}/> مصروف</Button>}{(has(user,'finance')||has(user,'payments'))&&<Button onClick={()=>setModal('register')}><Plus size={16}/> خزنة</Button>}{(has(user,'finance')||has(user,'shifts'))&&<Button onClick={()=>setModal('shift')}><Plus size={16}/> فتح وردية</Button>}</div></Card><div className="tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}<span>{data?.[k]?.length??0}</span></button>)}</div>{!data&&!error?<Loading/>:<Card><Table rows={rows} columns={cols[tab]||[]}/></Card>}
 <Modal open={modal==='expense'} onClose={()=>setModal(null)} title="تسجيل مصروف"><form className="form-grid" onSubmit={addExpense}><Field label="التاريخ"><Input type="date" name="expense_date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field><Field label="الفرع"><Select name="branch_id" defaultValue={appData.scope?.branch_id||''} disabled={!allFinance(user)}><option value="">اختر</option>{appData.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select>{!allFinance(user)&&<input type="hidden" name="branch_id" value={appData.scope?.branch_id||''}/>}</Field><Field label="الرحلة"><Select name="trip_id"><option value="">بدون رحلة</option>{appData.trips.map(t=><option key={t.id} value={t.id}>{t.trip_code}</option>)}</Select></Field><Field label="البند"><Input name="category" required placeholder="وقود / فندق / تشغيل..."/></Field><Field label="المبلغ"><Input name="amount" type="number" min="0.01" step="0.01" required/></Field><Field label="ملاحظات"><Textarea name="notes"/></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>حفظ</Button></div></form></Modal>
 <Modal open={modal==='register'} onClose={()=>setModal(null)} title="إضافة خزنة"><form className="form-grid" onSubmit={addRegister}><Field label="اسم الخزنة"><Input name="name" required/></Field><Field label="الفرع"><Select name="branch_id" defaultValue={appData.scope?.branch_id||''} disabled={!allFinance(user)}>{appData.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select>{!allFinance(user)&&<input type="hidden" name="branch_id" value={appData.scope?.branch_id||''}/>}</Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>حفظ</Button></div></form></Modal>
 <Modal open={modal==='shift'} onClose={()=>setModal(null)} title="فتح وردية"><form className="form-grid" onSubmit={openShift}><Field label="الخزنة"><Select name="register_id" required><option value="">اختر</option>{(data?.cash_registers||[]).filter(r=>r.active!==false).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></Field><Field label="رصيد الافتتاح"><Input name="opening_balance" type="number" step="0.01" defaultValue="0"/></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>فتح</Button></div></form></Modal>
 <Modal open={modal?.type==='closeShift'} onClose={()=>setModal(null)} title="إغلاق الوردية"><form className="form-grid" onSubmit={closeShift}><Field label="الرصيد الفعلي"><Input name="actual_closing" type="number" step="0.01" required/></Field><Field label="ملاحظات الإغلاق"><Textarea name="closing_notes"/></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>إغلاق الوردية</Button></div></form></Modal></>;
}
function Stat({icon,label,value}){return <Card className="stat-card"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></Card>}
