import React,{useEffect,useMemo,useState} from 'react';
import {Download,FilePlus2,RefreshCw,Printer,FileDown,TrendingUp,WalletCards,ReceiptText,BusFront,AlertTriangle} from 'lucide-react';
import {api} from '../../lib/api.js';
import {useAppData} from '../../core/AppDataContext.jsx';
import {Badge,Button,Card,ErrorBox,Field,Loading,PageHeader,SearchSelect,Select,Table} from '../../components/UI.jsx';
import {money,statusLabel,tripDisplay} from '../../lib/format.js';
import {basicPrintDocument,printHtmlDocument} from '../../lib/print.js';
import {bookingFinanceNumbers,bookingFinancialState} from '../../lib/bookingFinance.js';
const TYPES=[['bookings_csv','الحجوزات CSV'],['passengers_csv','المسافرون CSV'],['operations_json','التشغيل JSON'],['finance_csv','المالية CSV']];
const esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const n=v=>Number(v||0);const s=v=>String(v??'');const lower=v=>s(v).toLowerCase();
export default function Reports(){
 const {data:app}=useAppData();
 const [data,setData]=useState(null),[brief,setBrief]=useState(null),[refundSummary,setRefundSummary]=useState({byId:{},byNo:{}}),[error,setError]=useState(''),[type,setType]=useState('bookings_csv'),[busy,setBusy]=useState(''),[orientation,setOrientation]=useState('portrait'),[tripId,setTripId]=useState(''),[upcomingOpen,setUpcomingOpen]=useState(()=>{try{return sessionStorage.getItem('almaher_reports_upcoming_open')==='1'}catch{return false}});
 async function load(){setError('');try{const [reports,kpi,refunds]=await Promise.all([api.module('reports'),api.mega('executive_brief',{},'GET'),api.bookingRefundSummaries().catch(()=>null)]);setData(reports);setBrief(kpi);setRefundSummary({byId:refunds?.by_booking_id||{},byNo:refunds?.by_booking_number||{}})}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function create(e){e.preventDefault();setBusy('new');setError('');try{await api.moduleWrite({action:'insert',table:'export_jobs',row:{export_type:type,status:'pending'}});await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 async function process(r){setBusy(r.id);setError('');try{const x=await api.moduleWrite({action:'process_export',id:r.id});if(x.signed_url)window.open(x.signed_url,'_blank','noopener,noreferrer');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 async function open(r){setError('');try{const x=await api.moduleWrite({action:'export_signed_url',storage_path:r.storage_path});if(x.signed_url)window.open(x.signed_url,'_blank','noopener,noreferrer')}catch(e){setError(e.message)}}
 const jobs=data?.export_jobs||[];
 const upcoming=brief?.upcoming||[];
 const tripPickerOptions=useMemo(()=>[...(app.trips||[])].sort((a,b)=>String(b.departure_date||'').localeCompare(String(a.departure_date||''))).map(t=>({value:t.id,label:tripDisplay(t),searchText:[t.trip_code,t.code,t.from_city,t.to_city,t.origin,t.destination,t.departure_date,t.return_date,t.branch_name].filter(Boolean).join(' ')})),[app.trips]);
 function toggleUpcoming(){setUpcomingOpen(v=>{const next=!v;try{sessionStorage.setItem('almaher_reports_upcoming_open',next?'1':'0')}catch{}return next})}
 const refundedFor=b=>n(refundSummary.byId?.[s(b?.id)])||n(refundSummary.byNo?.[s(b?.booking_number)]);
 const totalPassengers=useMemo(()=>app.passengers?.filter(p=>lower(p.status)!=='cancelled').length||0,[app.passengers]);
 const selectedTrip=useMemo(()=>(app.trips||[]).find(t=>s(t.id)===s(tripId))||null,[app.trips,tripId]);
 const tripBookings=useMemo(()=>(app.bookings||[]).filter(b=>(s(b.trip_id)===s(tripId)||s(b.return_trip_id)===s(tripId))&&lower(b.status)!=='cancelled'),[app.bookings,tripId]);
 const tripBookingIds=useMemo(()=>new Set(tripBookings.map(b=>s(b.id))),[tripBookings]);
 const tripPassengers=useMemo(()=>(app.passengers||[]).filter(p=>tripBookingIds.has(s(p.booking_id))&&lower(p.status)!=='cancelled'),[app.passengers,tripBookingIds]);
 const bookingMap=useMemo(()=>new Map((app.bookings||[]).map(b=>[s(b.id),b])),[app.bookings]);
 const netCollectionPct=n(brief?.revenue)>0?Math.round(n(brief?.net)/n(brief?.revenue)*1000)/10:0;
 const kpis=[
  ['الحجوزات',brief?.bookings||0,'حجز',TrendingUp],
  ['المسافرون',totalPassengers,'مسافر',BusFront],
  ['إجمالي المبيعات',money(brief?.revenue||0),`صافي تحصيل ${netCollectionPct}%`,ReceiptText],
  ['التحصيل التاريخي',money(brief?.paid||0),`مسترد ${money(brief?.refunded||0)}`,WalletCards],
  ['صافي المحصل',money(brief?.net||0),`متبقي ${money(brief?.outstanding||0)}`,TrendingUp]
 ];
 const reportCss=`@page{size:A4 ${orientation==='landscape'?'landscape':'portrait'};margin:9mm}body{font-size:11px}.head{display:flex;justify-content:space-between;gap:12px;border-bottom:2px solid #13233a;padding-bottom:8px;margin-bottom:12px}.head h1{font-size:20px;margin:0 0 4px}.meta{color:#64748b}.stats{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.chip{border:1px solid #dbe3ec;border-radius:8px;padding:5px 9px}.chip b{font-size:13px}table{width:100%;border-collapse:collapse;page-break-inside:auto}thead{display:table-header-group}tr{page-break-inside:avoid;page-break-after:auto}th,td{border:1px solid #dbe3ec;padding:6px;text-align:right;vertical-align:top}th{background:#f1f5f9;font-weight:700}.muted{color:#64748b}.money{white-space:nowrap}.footer{margin-top:10px;color:#64748b;font-size:9px}`;
 function tripHeader(title){return `<div class="head"><div><h1>${esc(title)}</h1><div class="meta">${esc(selectedTrip?tripDisplay(selectedTrip):'—')}</div></div><div class="meta">الكود: ${esc(selectedTrip?.code||selectedTrip?.trip_code||'—')}<br>التاريخ: ${esc(selectedTrip?.departure_date||'—')}<br>الوقت: ${esc(selectedTrip?.departure_time||selectedTrip?.time||'—')}</div></div>`}
 function requireTrip(){if(selectedTrip)return true;setError('اختر رحلة أولًا لطباعة الكشف.');return false}
 function printPassengerManifest(){if(!requireTrip())return;const rows=tripPassengers.map((p,i)=>{const b=bookingMap.get(s(p.booking_id))||{};return `<tr><td>${i+1}</td><td><b>${esc(p.name||p.full_name)}</b></td><td>${esc(p.identity||p.identity_no||p.national_id)}</td><td>${esc(p.nationality)}</td><td>${esc(p.gender)}</td><td>${esc(b.booking_number||b.booking_no||b.code||b.reference||p.booking_id)}</td><td>${esc(b.customer_phone||b.phone||b.mobile)}</td><td>${esc(p.seat_no||p.seat_number||'غير محدد')}</td></tr>`}).join('');const body=`${tripHeader('كشف ركاب الرحلة')}<div class="stats"><div class="chip">إجمالي الركاب <b>${tripPassengers.length}</b></div><div class="chip">الحجوزات <b>${tripBookings.length}</b></div><div class="chip">السعة التشغيلية <b>${esc(selectedTrip?.operational_capacity??selectedTrip?.capacity??'—')}</b></div><div class="chip">المتاح <b>${esc(selectedTrip?.available_seats??'—')}</b></div></div><table><thead><tr><th>#</th><th>المسافر</th><th>الهوية</th><th>الجنسية</th><th>الجنس</th><th>الحجز</th><th>الجوال</th><th>المقعد</th></tr></thead><tbody>${rows||'<tr><td colspan="8">لا يوجد ركاب في الرحلة.</td></tr>'}</tbody></table><div class="footer">تم إنشاء الكشف من نظام الماهر الماسي — ${esc(new Date().toLocaleString('ar-SA'))}</div>`;printHtmlDocument(basicPrintDocument({title:'كشف ركاب الرحلة',body,styles:reportCss}))}
 function printBookingManifest(){if(!requireTrip())return;const paxCount=new Map();for(const p of tripPassengers)paxCount.set(s(p.booking_id),(paxCount.get(s(p.booking_id))||0)+1);const rows=tripBookings.map((b,i)=>{const f=bookingFinanceNumbers(b,refundedFor(b)),state=bookingFinancialState(b,refundedFor(b));return `<tr><td>${i+1}</td><td><b>${esc(b.booking_number||b.booking_no||b.code||b.reference||b.id)}</b></td><td>${esc(b.customer_name||b.name)}</td><td>${esc(b.customer_phone||b.phone||b.mobile)}</td><td>${paxCount.get(s(b.id))||0}</td><td class="money">${esc(money(f.total))}</td><td class="money">${esc(money(f.gross))}</td><td class="money">${esc(money(f.refund))}</td><td class="money">${esc(money(f.paid))}</td><td class="money">${esc(money(f.remaining))}</td><td>${esc(state.label)}</td></tr>`}).join('');const totals=tripBookings.reduce((x,b)=>{const f=bookingFinanceNumbers(b,refundedFor(b));x.total+=f.total;x.gross+=f.gross;x.refund+=f.refund;x.net+=f.paid;x.remaining+=f.remaining;return x},{total:0,gross:0,refund:0,net:0,remaining:0});const body=`${tripHeader('كشف حجوزات الرحلة')}<div class="stats"><div class="chip">الحجوزات <b>${tripBookings.length}</b></div><div class="chip">الركاب <b>${tripPassengers.length}</b></div><div class="chip">الإجمالي <b>${esc(money(totals.total))}</b></div><div class="chip">التحصيل التاريخي <b>${esc(money(totals.gross))}</b></div><div class="chip">المسترد <b>${esc(money(totals.refund))}</b></div><div class="chip">صافي المحصل <b>${esc(money(totals.net))}</b></div><div class="chip">المتبقي <b>${esc(money(totals.remaining))}</b></div></div><table><thead><tr><th>#</th><th>الحجز</th><th>العميل</th><th>الجوال</th><th>الركاب</th><th>الإجمالي</th><th>التحصيل التاريخي</th><th>المسترد</th><th>الصافي</th><th>المتبقي</th><th>الحالة المالية</th></tr></thead><tbody>${rows||'<tr><td colspan="11">لا توجد حجوزات في الرحلة.</td></tr>'}</tbody></table><div class="footer">تم إنشاء الكشف من نظام الماهر الماسي — ${esc(new Date().toLocaleString('ar-SA'))}</div>`;printHtmlDocument(basicPrintDocument({title:'كشف حجوزات الرحلة',body,styles:reportCss}))}
 function printJobs(){const rows=jobs.map(r=>`<tr><td>${esc(TYPES.find(x=>x[0]===r.export_type)?.[1]||r.export_type)}</td><td>${esc(statusLabel(r.status||'pending'))}</td><td>${esc(r.created_at?new Date(r.created_at).toLocaleString('ar-SA'):'—')}</td><td>${esc(r.completed_at?new Date(r.completed_at).toLocaleString('ar-SA'):'—')}</td></tr>`).join('');const body=`<h1>سجل التقارير والتصدير</h1><p>تم إنشاء هذا المستند من مركز التقارير، ولا يتضمن واجهة النظام.</p><table><thead><tr><th>النوع</th><th>الحالة</th><th>الطلب</th><th>الاكتمال</th></tr></thead><tbody>${rows||'<tr><td colspan="4">لا توجد طلبات تصدير</td></tr>'}</tbody></table>`;const html=basicPrintDocument({title:'سجل التقارير والتصدير',body,styles:`@page{size:A4 ${orientation==='landscape'?'landscape':'portrait'}}h1{font-size:24px}p{color:#64748b}table{width:100%;border-collapse:collapse;margin-top:16px}th,td{border:1px solid #dbe3ec;padding:8px;text-align:right}th{background:#f1f5f9}`});printHtmlDocument(html)}
 function printKpi(){const cards=kpis.map(([label,value,sub])=>`<div class="k"><span>${esc(label)}</span><b>${esc(value)}</b><small>${esc(sub)}</small></div>`).join('');const trips=upcoming.map(t=>`<tr><td>${esc(t.code||t.trip_code||'—')}</td><td>${esc(t.name||`${t.from_city||''} ← ${t.to_city||''}`)}</td><td>${esc(t.departure_date||'—')}</td><td>${esc(statusLabel(t.status||''))}</td></tr>`).join('');const warnings=(brief?.warnings||[]).map(x=>`<li>${esc(x)}</li>`).join('');const body=`<h1>لوحة مؤشرات الأداء</h1><div class="grid">${cards}</div><h2>تنبيهات الإدارة</h2>${warnings?`<ul>${warnings}</ul>`:'<p>لا توجد تنبيهات حرجة.</p>'}<h2>الرحلات القادمة</h2><table><thead><tr><th>الكود</th><th>الرحلة</th><th>التاريخ</th><th>الحالة</th></tr></thead><tbody>${trips||'<tr><td colspan="4">لا توجد رحلات قادمة</td></tr>'}</tbody></table>`;printHtmlDocument(basicPrintDocument({title:'لوحة مؤشرات الأداء',body,styles:'@page{size:A4 landscape}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.k{border:1px solid #dbe3ec;padding:12px;border-radius:10px}.k span,.k small{display:block;color:#64748b}.k b{display:block;font-size:20px;margin:8px 0}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #dbe3ec;padding:8px;text-align:right}h2{margin-top:22px}'}))}
 const cols=[{key:'export_type',label:'النوع',render:r=>TYPES.find(x=>x[0]===r.export_type)?.[1]||r.export_type},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='completed'?'green':r.status==='failed'?'red':'orange'}>{statusLabel(r.status||'pending')}</Badge>},{key:'created_at',label:'الطلب',render:r=>r.created_at?new Date(r.created_at).toLocaleString('ar-SA'):'—'},{key:'completed_at',label:'الاكتمال',render:r=>r.completed_at?new Date(r.completed_at).toLocaleString('ar-SA'):'—'},{key:'action',label:'',render:r=>r.storage_path?<Button onClick={()=>open(r)}><Download size={15}/> تنزيل</Button>:<Button onClick={()=>process(r)} disabled={busy===r.id}>{busy===r.id?'جاري التجهيز...':'تجهيز الملف'}</Button>}];
 return <><PageHeader title="التقارير ومؤشرات الأداء" subtitle="لوحة إدارة تنفيذية + إنشاء ملفات تصدير من البيانات السحابية" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث</Button>}/><ErrorBox error={error}/>{brief&&<><div className="stats-grid">{kpis.map(([label,value,sub,Icon])=><Card key={label}><div className="stat-card"><Icon size={20}/><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div></Card>)}</div><Card><div className="card-title"><h3>ملخص الإدارة</h3><Button onClick={printKpi}><Printer size={16}/> طباعة مؤشرات الأداء</Button></div>{(brief.warnings||[]).length?<div className="warning-list">{brief.warnings.map((w,i)=><div key={i}><AlertTriangle size={16}/>{w}</div>)}</div>:<div className="success-note">لا توجد تنبيهات إدارية حرجة حاليًا.</div>}<button type="button" className="collapsible-heading" onClick={toggleUpcoming}><span><b>الرحلات القادمة</b> <small>({upcoming.length})</small></span><span className={`collapsible-arrow ${upcomingOpen?'open':''}`}>⌄</span></button>{upcomingOpen&&<div className="table-wrap collapsible-body"><table><thead><tr><th>الرحلة القادمة</th><th>التاريخ</th><th>الحالة</th></tr></thead><tbody>{upcoming.length?upcoming.map(t=><tr key={t.id}><td>{tripDisplay(t)}</td><td>{t.departure_date||'—'}</td><td><Badge>{statusLabel(t.status||'')}</Badge></td></tr>):<tr><td colSpan="3">لا توجد رحلات قادمة</td></tr>}</tbody></table></div>}</Card></>}
 <Card><div className="card-title"><h3>كشوف التشغيل المباشرة</h3><Badge>{tripPassengers.length} راكب</Badge></div><div className="inline-form"><Field label="الرحلة"><SearchSelect value={tripId} onChange={e=>setTripId(e.target.value)} options={tripPickerOptions} placeholder="اختر الرحلة"/></Field><Field label="اتجاه الطباعة"><Select value={orientation} onChange={e=>setOrientation(e.target.value)}><option value="portrait">A4 عمودي</option><option value="landscape">A4 أفقي</option></Select></Field><Button type="button" onClick={printPassengerManifest}><Printer size={16}/> كشف الركاب</Button><Button type="button" onClick={printBookingManifest}><Printer size={16}/> كشف الحجوزات</Button></div><div className="muted-note">الكشوف تُنشأ من البيانات المحمّلة والمسموح بها لحسابك، وتُفتح في نافذة طباعة مستقلة بدون واجهة النظام. من نافذة الطباعة يمكنك اختيار «حفظ كملف PDF».</div></Card>
 <Card><form className="inline-form" onSubmit={create}><Field label="تقرير جديد"><Select value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></Field><Field label="اتجاه الطباعة"><Select value={orientation} onChange={e=>setOrientation(e.target.value)}><option value="portrait">A4 عمودي</option><option value="landscape">A4 أفقي</option></Select></Field><Button variant="primary" type="submit" disabled={busy==='new'}><FilePlus2 size={16}/>{busy==='new'?'جاري الإنشاء...':'إنشاء طلب تصدير'}</Button><Button type="button" onClick={printJobs}><Printer size={16}/> طباعة السجل</Button><Button type="button" onClick={printJobs}><FileDown size={16}/> حفظ PDF</Button></form></Card>{!data&&!error?<Loading/>:<Card><div className="card-title"><h3>طلبات التصدير</h3><Badge>{jobs.length}</Badge></div><Table rows={jobs} columns={cols}/></Card>}</>}
