import React,{useEffect,useMemo,useState} from 'react';
import {RefreshCw,Plus,Pencil} from 'lucide-react';
import {api} from '../lib/api.js';
import {Card,PageHeader,Button,Loading,ErrorBox,Table,Modal,Field,Input,Textarea,Select} from '../components/UI.jsx';

export default function GenericModule({title,subtitle,resource,tabs,defaultTable}){
 const [data,setData]=useState(null),[table,setTable]=useState(defaultTable||tabs?.[0]?.table),[error,setError]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false);
 async function load(){setError('');setData(null);try{setData(await api.module(resource))}catch(e){setError(e.message)}}useEffect(()=>{load()},[resource]);
 const active=tabs?.find(x=>x.table===table)||tabs?.[0];const rows=data?.[table]||[];
 const columns=useMemo(()=>{const preferred=active?.columns||[];const cols=preferred.map(k=>({key:k,label:(active?.labels?.[k]||k).replaceAll('_',' '),render:r=>typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k]??'—')}));if(active?.writable)cols.push({key:'__edit',label:'',render:r=><Button onClick={e=>{e.stopPropagation();setEditing(r);setOpen(true)}}><Pencil size={14}/> تعديل</Button>});return cols},[active]);
 function add(){setEditing(null);setOpen(true);setError('')}
 async function save(e){e.preventDefault();setBusy(true);setError('');const f=Object.fromEntries(new FormData(e.currentTarget));let row={};for(const [k,v] of Object.entries(f)){if(k==='json')continue;const cfg=(active?.fields||[]).find(x=>x.name===k);if(cfg?.type==='number')row[k]=v===''?null:Number(v);else if(cfg?.type==='checkbox')row[k]=v==='on'||v==='true';else row[k]=v===''&&cfg?.nullable?null:v}if(f.json){try{row={...row,...JSON.parse(f.json)}}catch{setBusy(false);setError('JSON غير صالح');return}}try{if(editing?.id)await api.moduleWrite({action:'update',table,id:editing.id,row});else await api.moduleWrite({action:'insert',table,row});setOpen(false);setEditing(null);await load()}catch(e2){setError(e2.message)}finally{setBusy(false)}}
 return <><PageHeader title={title} subtitle={subtitle} actions={<><Button onClick={load}><RefreshCw size={16}/> تحديث</Button>{active?.writable&&<Button variant="primary" onClick={add}><Plus size={16}/> إضافة</Button>}</>}/><ErrorBox error={error}/>{tabs&&<div className="tabs">{tabs.map(t=><button key={t.table} onClick={()=>{setTable(t.table);setEditing(null)}} className={table===t.table?'active':''}>{t.label}<span>{data?.[t.table]?.length??0}</span></button>)}</div>}{!data&&!error?<Loading/>:<Card>{data?._missing_tables?.includes(table)?<div className="empty">الجدول <b>{table}</b> غير موجود في قاعدة البيانات الحالية.</div>:<Table rows={rows} columns={columns}/>}</Card>}
 <Modal open={open} onClose={()=>{setOpen(false);setEditing(null)}} title={`${editing?'تعديل':'إضافة'} — ${active?.label||active?.labelSingular||table}`}><form onSubmit={save} className="form-grid" key={`${table}-${editing?.id||'new'}`}>{(active?.fields||[]).map(f=><Field key={f.name} label={f.label||f.name} hint={f.hint}>{f.type==='select'?<Select name={f.name} defaultValue={editing?.[f.name]??f.defaultValue??''} required={f.required}>{!f.required&&<option value="">—</option>}{(f.options||[]).map(o=>Array.isArray(o)?<option key={o[0]} value={o[0]}>{o[1]}</option>:<option key={o} value={o}>{o}</option>)}</Select>:f.type==='checkbox'?<input name={f.name} type="checkbox" defaultChecked={Boolean(editing?.[f.name]??f.defaultValue)}/>:<Input name={f.name} type={f.type||'text'} defaultValue={editing?.[f.name]??f.defaultValue??''} required={f.required}/>}</Field>)}<Field label="حقول إضافية JSON" hint="اختياري — للحقول المتقدمة فقط"><Textarea name="json" placeholder='{"notes":"..."}'/></Field><div className="modal-actions"><Button type="button" onClick={()=>{setOpen(false);setEditing(null)}}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>{busy?'جاري الحفظ...':'حفظ'}</Button></div></form></Modal></>;
}
