import React,{useEffect,useMemo,useState} from 'react';
import QRCode from 'qrcode';
import './id-card-print.css';
import './id-card-orientation.css';
import './id-card-designer.css';

const statusAr={active:'فعالة',draft:'مسودة',pending_approval:'بانتظار الاعتماد',suspended:'موقوفة',expired:'منتهية',lost:'مفقودة',revoked:'ملغاة',reissued:'أعيد إصدارها'};
const CALIBRATION_KEY='almaher_idstudio_cr80_calibration_v1';
const normalizeOrientation=v=>v==='portrait'?'portrait':'landscape';
const DEFAULT_BRAND={companyNameAr:'الماهر الماسي',companyNameEn:'AL MAHER AL MASI',serviceLineAr:'لنقل الحجاج والمعتمرين',serviceLineEn:'For Hajj & Umrah Transport',sloganAr:'نُيسر دربك... لنطمئن قلبك',honorAr:'خدمة ضيوف الرحمن شرف لنا',honorEn:'SERVING THE GUESTS OF ALLAH IS AN HONOR FOR US'};
const DEFAULT_VIS={logo:true,companyName:true,serviceLine:true,slogan:true,holderPhoto:true,holderName:true,jobTitle:true,department:true,employeeId:true,licenseNumber:true,season:true,qr:true,approval:true,bus:true,makkah:true,footer:true};
const DEFAULT_FRONT_COPY={photoPlaceholder:'الصورة',holderNamePlaceholder:'اسم حامل البطاقة',jobTitlePlaceholder:'المسمى الوظيفي',idCardLabel:'ID CARD',departmentLabel:'القسم',licenseLabel:'الترخيص',seasonLabel:'الموسم',expiryLabel:'حتى',referenceCompanyLabel:'الشركة',referenceLicenseLabel:'الترخيص',referenceSeasonLabel:'الموسم',referenceEmployeeLabel:'رقم الموظف',qrLabel:'تحقق من البطاقة',approvalLabel:'اعتماد الإدارة',approvalAr:'معتمدة إلكترونيًا',approvalEn:'Electronic Verification',value1:'أمان',value2:'راحة',value3:'ثقة',inactiveWatermark:'غير معتمدة'};
const DEFAULT_BACK_VIS={logo:true,companyName:true,serviceLine:true,qr:true,employeeId:true,version:true,department:true,licenseNumber:true,season:true,expiry:true,note:true,footer:true};
const DEFAULT_BACK_COPY={companyNameAr:'',companyNameEn:'',serviceLineAr:'',qrLabel:'امسح للتحقق من حالة البطاقة',employeeIdLabel:'رقم البطاقة',versionLabel:'الإصدار',departmentLabel:'القسم',licenseLabel:'الترخيص',seasonLabel:'الموسم',expiryLabel:'الصلاحية',note:'الحالة الإلكترونية الحالية عبر رمز QR هي المرجع لصلاحية البطاقة.',footerAr:'',footerEn:''};
const DEFAULT_THEME={primary:'#0a4f93',secondary:'#073566',accent:'#d3a746',surface:'#ffffff',text:'#0b2f5d'};

export function getCR80Calibration(){try{const x=JSON.parse(localStorage.getItem(CALIBRATION_KEY)||'{}');return {offsetX:Number(x.offsetX)||0,offsetY:Number(x.offsetY)||0,scaleX:Number(x.scaleX)||1,scaleY:Number(x.scaleY)||1}}catch{return {offsetX:0,offsetY:0,scaleX:1,scaleY:1}}}
export function saveCR80Calibration(value={}){const x={offsetX:Number(value.offsetX)||0,offsetY:Number(value.offsetY)||0,scaleX:Number(value.scaleX)||1,scaleY:Number(value.scaleY)||1};try{localStorage.setItem(CALIBRATION_KEY,JSON.stringify(x))}catch{}return x}
function MetaPill({label,value,style}){return <span style={style}><b>{label}</b>{value||'—'}</span>}
function getDesigner(card={}){
 const snap=card.template_config_snapshot,hasSnap=snap&&typeof snap==='object'&&!Array.isArray(snap)&&Object.keys(snap).length>0;
 const cfg=hasSnap?snap:(card.template_config||card.published_config||{}),d=cfg?.designer||{};
 const visibility={...DEFAULT_VIS,...(d.visibility||{})};
 const theme={...DEFAULT_THEME,...(d.theme||{})};
 const inheritedBack={...DEFAULT_BACK_VIS,logo:visibility.logo,companyName:visibility.companyName,serviceLine:visibility.serviceLine,qr:visibility.qr,employeeId:visibility.employeeId,department:visibility.department,licenseNumber:visibility.licenseNumber,season:visibility.season,footer:visibility.footer};
 return {brand:{...DEFAULT_BRAND,...(d.brand||{})},frontCopy:{...DEFAULT_FRONT_COPY,...(d.frontCopy||{})},assets:{logoUrl:'',backgroundUrl:'',backBackgroundUrl:'',makkahUrl:'',busUrl:'',signatureUrl:'',...(d.assets||{})},visibility,backVisibility:{...inheritedBack,...(d.backVisibility||{})},backCopy:{...DEFAULT_BACK_COPY,...(d.backCopy||{})},theme,backTheme:{...theme,...(d.backTheme||{})},layout:{portrait:{...(d.layout?.portrait||{})},landscape:{...(d.layout?.landscape||{})}},backLayout:{portrait:{...(d.backLayout?.portrait||{})},landscape:{...(d.backLayout?.landscape||{})}},typography:{portrait:{...(d.typography?.portrait||{})},landscape:{...(d.typography?.landscape||{})}},backTypography:{portrait:{...(d.backTypography?.portrait||{})},landscape:{...(d.backTypography?.landscape||{})}}}
}
function cardStyle(designer,back=false){const t=back?designer.backTheme:designer.theme,a=designer.assets,bg=back?(a.backBackgroundUrl||a.backgroundUrl):a.backgroundUrl;return {'--id-primary':t.primary,'--id-secondary':t.secondary,'--id-accent':t.accent,'--id-surface':t.surface,'--id-text':t.text,'--id-bg-image':bg?`url("${String(bg).replace(/"/g,'')}")`:'none'}}
function styleFromLayout(map,orientation,key){const p=map?.[orientation]?.[key];if(!p||typeof p!=='object')return undefined;const s={};const num=v=>Number.isFinite(Number(v))?Number(v):null;const x=num(p.x),y=num(p.y),w=num(p.w),h=num(p.h),z=num(p.z),opacity=num(p.opacity);if(x!==null){s.left=`${x}mm`;s.right='auto';s.transform='none';s.position='absolute'}if(y!==null){s.top=`${y}mm`;s.bottom='auto';s.position='absolute'}if(w!==null&&w>0)s.width=`${w}mm`;if(h!==null&&h>0)s.height=`${h}mm`;if(z!==null)s.zIndex=Math.max(0,Math.min(50,z));if(opacity!==null)s.opacity=Math.max(0,Math.min(1,opacity));return Object.keys(s).length?s:undefined}
function typographyFromMap(map,orientation,key){const p=map?.[orientation]?.[key];if(!p||typeof p!=='object')return undefined;const s={};const size=Number(p.fontSizePt),weight=Number(p.fontWeight),spacing=Number(p.letterSpacingPt),line=Number(p.lineHeight);if(p.fontFamily)s.fontFamily=String(p.fontFamily);if(Number.isFinite(size)&&size>=4&&size<=40)s.fontSize=`${size}pt`;if(Number.isFinite(weight)&&weight>=300&&weight<=900)s.fontWeight=weight;if(/^#[0-9a-f]{3,8}$/i.test(String(p.color||'')))s.color=p.color;if(['left','center','right','start','end'].includes(p.align))s.textAlign=p.align;if(Number.isFinite(spacing)&&spacing>=-2&&spacing<=8)s.letterSpacing=`${spacing}pt`;if(Number.isFinite(line)&&line>=.8&&line<=3)s.lineHeight=line;return Object.keys(s).length?s:undefined}
const merge=(...styles)=>Object.assign({},...styles.filter(Boolean));

export function IDCardFace({card,side='front',verificationBase=''}){
 const [qr,setQr]=useState('');
 const verifyUrl=useMemo(()=>card?.qr_token?`${verificationBase||(typeof window!=='undefined'?window.location.origin:'')}/verify/id/${encodeURIComponent(card.qr_token)}`:'',[card?.qr_token,verificationBase]);
 useEffect(()=>{let alive=true;if(!verifyUrl){setQr('');return}QRCode.toDataURL(verifyUrl,{width:360,margin:1,errorCorrectionLevel:'M'}).then(x=>alive&&setQr(x)).catch(()=>alive&&setQr(''));return()=>{alive=false}},[verifyUrl]);
 if(!card)return null;
 const full=card.print_mode!=='front_back',issueVersion=Number(card.metadata?.issue_version||1),orientation=normalizeOrientation(card.orientation),designer=getDesigner(card),{brand,frontCopy,assets,visibility,backVisibility,backCopy}=designer;
 const cls=`idcard-cr80 idcard-${card.template_code||'makkah_luxury'} ${orientation}`;
 const ls=key=>styleFromLayout(designer.layout,orientation,key),bls=key=>styleFromLayout(designer.backLayout,orientation,key),ts=key=>typographyFromMap(designer.typography,orientation,key),bts=key=>typographyFromMap(designer.backTypography,orientation,key),backText=(key,fallback='')=>String(backCopy?.[key]??'').trim()||fallback;
 const Brand=({back=false}={})=>{const pos=back?bls:ls,text=back?bts:ts,vis=back?backVisibility:visibility,nameAr=back?backText('companyNameAr',brand.companyNameAr):brand.companyNameAr,nameEn=back?backText('companyNameEn',brand.companyNameEn):brand.companyNameEn,serviceLine=back?backText('serviceLineAr',brand.serviceLineAr):brand.serviceLineAr;return <>{vis.logo&&assets.logoUrl&&<img className={`idcard-template-logo ${back?'idcard-back-logo':''}`} style={pos('logo')} src={assets.logoUrl} alt=""/>}{vis.companyName&&<div className={`idcard-brand ${back?'idcard-back-brand':''}`} style={pos('brand')}><strong style={text('companyAr')||ts('companyAr')}>{nameAr}</strong><span style={text('companyEn')||ts('companyEn')}>{nameEn}</span></div>}{vis.serviceLine&&<div className={`idcard-company-line ${back?'idcard-back-service-line':''}`} style={merge(pos('serviceLine'),text('serviceLine')||ts('serviceLine'))}>{serviceLine}</div>}</>};
 const BackField=({show=true,label,value})=>show?<><b style={bts('metaLabel')||bts('meta')||ts('meta')}>{label}</b><span style={bts('metaValue')||bts('meta')||ts('meta')}>{value||'—'}</span></>:null;
 const backFooterAr=String(backCopy.footerAr||'').trim()||brand.honorAr,backFooterEn=String(backCopy.footerEn||'').trim()||brand.honorEn;
 if(side==='back'&&!full)return <div className={`${cls} back`} data-orientation={orientation} style={cardStyle(designer,true)}>
  <div className="idcard-custom-bg"></div><div className="idcard-decor idcard-decor-a"></div><div className="idcard-decor idcard-decor-b"></div><div className="idcard-lanyard-slot"></div><Brand back/>
  <div className="idcard-back-grid" style={bls('grid')}><div className="idcard-back-qr" style={bls('qr')}>{backVisibility.qr?(qr?<img className="idcard-qr large" src={qr} alt="QR verification"/>:<div className="idcard-qr-placeholder">QR</div>):null}{backVisibility.qr&&<small style={bts('qrLabel')}>{backCopy.qrLabel}</small>}</div><div className="idcard-info idcard-back-info" style={bls('info')}><BackField show={backVisibility.employeeId} label={backCopy.employeeIdLabel} value={card.card_number}/><BackField show={backVisibility.version} label={backCopy.versionLabel} value={`V${issueVersion}`}/><BackField show={backVisibility.department} label={backCopy.departmentLabel} value={card.department_ar}/><BackField show={backVisibility.licenseNumber} label={backCopy.licenseLabel} value={card.license_number}/><BackField show={backVisibility.season} label={backCopy.seasonLabel} value={card.season_label}/><BackField show={backVisibility.expiry} label={backCopy.expiryLabel} value={card.expiry_date}/></div></div>
  {backVisibility.note&&<div className="idcard-verify-note idcard-back-note" style={merge(bls('note'),bts('note'))}>{backCopy.note}</div>}
  {backVisibility.footer&&<div className="idcard-footer idcard-back-footer" style={merge(bls('footer'),bts('footer')||ts('footerAr'))}>{backFooterAr}{backFooterEn?` · ${backFooterEn}`:''}</div>}
 </div>;
 return <div className={`${cls} front`} data-orientation={orientation} style={cardStyle(designer,false)}>
  <div className="idcard-custom-bg"></div><div className="idcard-decor idcard-decor-a"></div><div className="idcard-decor idcard-decor-b"></div><div className="idcard-watermark-mark">M</div><div className="idcard-lanyard-slot"></div>
  {visibility.makkah&&assets.makkahUrl&&<img className="idcard-template-makkah" style={ls('makkah')} src={assets.makkahUrl} alt=""/>}{visibility.bus&&assets.busUrl&&<img className="idcard-template-bus" style={ls('bus')} src={assets.busUrl} alt=""/>}<Brand/>
  {visibility.holderPhoto&&<div className="idcard-photo" style={ls('photo')}>{card.photo_url?<img src={card.photo_url} alt=""/>:<span>{frontCopy.photoPlaceholder}</span>}</div>}
  <div className="idcard-person" style={ls('person')}>{visibility.holderName&&<><strong style={ts('nameAr')}>{card.name_ar||frontCopy.holderNamePlaceholder}</strong><span style={ts('nameEn')}>{card.name_en||''}</span></>}{visibility.jobTitle&&<><b style={ts('jobTitleAr')}>{card.job_title_ar||frontCopy.jobTitlePlaceholder}</b><small style={ts('jobTitleEn')}>{card.job_title_en||''}</small></>}</div>
  {visibility.employeeId&&<div className="idcard-number" style={ls('number')}><small style={ts('numberLabel')}>{frontCopy.idCardLabel}</small><span className="idcard-number-value" style={ts('cardNumber')}>{card.card_number||'MA-000'}</span><em>V{issueVersion}</em></div>}
  {full&&<div className="idcard-full-meta" style={ls('meta')}>{visibility.department&&<MetaPill label={frontCopy.departmentLabel} value={card.department_ar} style={ts('meta')}/>} {visibility.licenseNumber&&<MetaPill label={frontCopy.licenseLabel} value={card.license_number} style={ts('meta')}/>} {visibility.season&&<MetaPill label={frontCopy.seasonLabel} value={card.season_label} style={ts('meta')}/>}<MetaPill label={frontCopy.expiryLabel} value={card.expiry_date} style={ts('meta')}/></div>}
  {full&&<div className="idcard-reference-meta"><div><b>{frontCopy.referenceCompanyLabel}</b><span>{brand.companyNameAr}</span></div>{visibility.licenseNumber&&<div><b>{frontCopy.referenceLicenseLabel}</b><span>{card.license_number||'—'}</span></div>}{visibility.season&&<div><b>{frontCopy.referenceSeasonLabel}</b><span>{card.season_label||'—'}</span></div>}{visibility.employeeId&&<div><b>{frontCopy.referenceEmployeeLabel}</b><span>{card.card_number||'MA-000'}</span></div>}</div>}
  {visibility.qr&&qr&&<div className="idcard-qr-wrap" style={ls('qr')}><img className="idcard-qr" src={qr} alt="QR verification"/><small>{frontCopy.qrLabel}</small></div>}
  <div className={`idcard-status ${card.status||'draft'}`}>{statusAr[card.status]||card.status}</div>
  {visibility.slogan&&<div className="idcard-template-slogan" style={merge(ls('slogan'),ts('slogan'))}>{brand.sloganAr}</div>}
  {visibility.footer&&<div className="idcard-reference-footer" style={ls('footer')}><strong style={ts('footerAr')}>{brand.honorAr}</strong><span style={ts('footerEn')}>{brand.honorEn}</span></div>}
  <div className="idcard-reference-values"><span>{frontCopy.value1}</span><span>{frontCopy.value2}</span><span>{frontCopy.value3}</span></div>
  {card.status==='active'&&visibility.approval&&<div className="idcard-approval" style={ls('approval')}>{assets.signatureUrl&&<img className="idcard-template-signature" src={assets.signatureUrl} alt=""/>}<small className="idcard-approval-label">{frontCopy.approvalLabel}</small><b style={ts('approvalAr')}>{frontCopy.approvalAr}</b><span style={ts('approvalEn')}>{frontCopy.approvalEn}</span></div>}
  {card.status!=='active'&&<div className="idcard-watermark">{frontCopy.inactiveWatermark}</div>}
 </div>;
}

export function CR80CalibrationSheet({orientation='landscape'}){const o=normalizeOrientation(orientation);return <div className={`idcard-calibration-sheet ${o}`} data-orientation={o}><div className="calibration-border"></div><div className="calibration-center-x"></div><div className="calibration-center-y"></div><div className="calibration-label">CR80 · {o==='portrait'?'53.98 × 85.60':'85.60 × 53.98'} mm</div><div className="calibration-mm x">10 mm</div><div className="calibration-mm y">10 mm</div></div>}
export function BatchPrintSheet({cards=[],side='front'}){return <div id="idstudio-batch-print-root" className="idstudio-batch-print-sheet" data-side={side}>{cards.flatMap(card=>{const faces=side==='both'&&card.print_mode==='front_back'?['front','back']:[side==='back'?'back':'front'];const o=normalizeOrientation(card.orientation);return faces.map(face=><div className={`idstudio-batch-page ${o}`} data-orientation={o} key={`${card.id}-${face}`}><IDCardFace card={card} side={face}/></div>)})}</div>}
function applyCalibration(root,{offsetX,offsetY,scaleX,scaleY}={}){const saved=getCR80Calibration();root.style.setProperty('--print-x',`${offsetX??saved.offsetX}mm`);root.style.setProperty('--print-y',`${offsetY??saved.offsetY}mm`);root.style.setProperty('--print-scale-x',String(scaleX??saved.scaleX));root.style.setProperty('--print-scale-y',String(scaleY??saved.scaleY))}
function waitFrame(){return new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))}
function waitMs(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function waitImages(root){return Promise.all([...root.querySelectorAll('img')].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.addEventListener('load',resolve,{once:true});img.addEventListener('error',resolve,{once:true})})))}
async function waitPrintable(elements){const list=elements.filter(Boolean);await waitFrame();const started=Date.now();while(list.some(el=>el.querySelector('.idcard-qr-placeholder')||(el.querySelector('.idcard-status.active')&&!el.querySelector('.idcard-qr')))&&Date.now()-started<1400){await waitMs(50);await waitFrame()}await Promise.all(list.map(waitImages));await waitMs(80)}
function inheritedStyles(){return [...document.head.querySelectorAll('link[rel="stylesheet"],style')].map(node=>node.tagName==='LINK'?`<link rel="stylesheet" href="${node.href}">`:node.outerHTML).join('')}
async function printIsolated(elements,{orientation='landscape',copies=1,offsetX,offsetY,scaleX,scaleY}={}){
 const list=elements.filter(Boolean);if(!list.length)return false;await waitPrintable(list);const o=normalizeOrientation(orientation),size=o==='portrait'?{w:53.98,h:85.6}:{w:85.6,h:53.98},saved=getCR80Calibration(),cal={offsetX:offsetX??saved.offsetX,offsetY:offsetY??saved.offsetY,scaleX:scaleX??saved.scaleX,scaleY:scaleY??saved.scaleY},count=Math.min(50,Math.max(1,Math.trunc(Number(copies)||1)));
 const pages=[];for(let copy=0;copy<count;copy++)for(const el of list)pages.push(`<div class="idstudio-isolated-print-page">${el.outerHTML}</div>`);
 const iframe=document.createElement('iframe');iframe.setAttribute('aria-hidden','true');iframe.style.position='fixed';iframe.style.left='-10000px';iframe.style.top='0';iframe.style.width='1000px';iframe.style.height='1000px';iframe.style.border='0';document.body.appendChild(iframe);
 const doc=iframe.contentDocument,win=iframe.contentWindow;if(!doc||!win){iframe.remove();return false}const css=`<style>html,body{margin:0!important;padding:0!important;background:#fff!important;width:${size.w}mm!important;min-width:0!important}body *{visibility:visible!important}.idstudio-isolated-print-page{display:block!important;position:relative!important;width:${size.w}mm!important;height:${size.h}mm!important;margin:0!important;padding:0!important;overflow:hidden!important;break-after:page;page-break-after:always}.idstudio-isolated-print-page:last-child{break-after:auto;page-break-after:auto}.idstudio-isolated-print-page>.idcard-cr80,.idstudio-isolated-print-page>.idcard-calibration-sheet{display:block!important;visibility:visible!important;margin:0!important;border-radius:0!important;box-shadow:none!important;transform:translate(${cal.offsetX}mm,${cal.offsetY}mm) scale(${cal.scaleX},${cal.scaleY})!important;transform-origin:top left!important}@page{size:${size.w}mm ${size.h}mm;margin:0}@media print{html,body{margin:0!important;padding:0!important;width:${size.w}mm!important;height:auto!important;overflow:visible!important}body *{visibility:visible!important}.idstudio-isolated-print-page{display:block!important}.idstudio-isolated-print-page>.idcard-cr80,.idstudio-isolated-print-page>.idcard-calibration-sheet{display:block!important}}</style>`;
 doc.open();doc.write(`<!doctype html><html><head><meta charset="utf-8">${inheritedStyles()}${css}</head><body>${pages.join('')}</body></html>`);doc.close();
 try{if(doc.fonts?.ready)await doc.fonts.ready;await Promise.all([...doc.images].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=resolve;img.onerror=resolve})));await waitMs(120);let removed=false;const cleanup=()=>{if(removed)return;removed=true;iframe.remove()};win.addEventListener('afterprint',()=>setTimeout(cleanup,300),{once:true});win.focus();win.print();setTimeout(cleanup,60000);return true}catch(err){iframe.remove();throw err}
}
export function printCR80(card,{side='front',copies=1,offsetX,offsetY,scaleX,scaleY,calibration=false,orientation}={}){const root=document.getElementById('idstudio-print-root');if(!root)return false;const normalizedSide=side==='full'?'front':side,o=normalizeOrientation(orientation||card?.orientation),count=Math.min(50,Math.max(1,Math.trunc(Number(copies)||1)));let elements;if(calibration){elements=[root.querySelector('.idcard-calibration-sheet')]}else{const faces=normalizedSide==='both'?['front','back']:[normalizedSide];elements=faces.map(face=>root.querySelector(`.idcard-cr80.${face}`)).filter(Boolean)}if(!elements.filter(Boolean).length)return false;printIsolated(elements,{orientation:o,copies:count,offsetX,offsetY,scaleX,scaleY}).catch(err=>console.error('ID Studio isolated print failed',err));return true}
export function printCR80Batch({side='front',offsetX,offsetY,scaleX,scaleY}={}){const root=document.getElementById('idstudio-batch-print-root');if(!root||!root.children.length)return false;document.body.dataset.idstudioPrintMode='batch';root.dataset.side=side;applyCalibration(root,{offsetX,offsetY,scaleX,scaleY});window.print();return true}
