import React,{useEffect,useMemo,useState} from 'react';
import QRCode from 'qrcode';
import './id-card-print.css';
import './id-card-orientation.css';
import './id-card-designer.css';

const statusAr={active:'فعالة',draft:'مسودة',pending_approval:'بانتظار الاعتماد',suspended:'موقوفة',expired:'منتهية',lost:'مفقودة',revoked:'ملغاة',reissued:'أعيد إصدارها'};
const CALIBRATION_KEY='almaher_idstudio_cr80_calibration_v1';
const normalizeOrientation=v=>v==='portrait'?'portrait':'landscape';
const DEFAULT_BRAND={companyNameAr:'الماهر الماسي',companyNameEn:'AL MAHER AL MASI',serviceLineAr:'لنقل الحجاج والمعتمرين',serviceLineEn:'For Hajj & Umrah Transport',sloganAr:'نُيسر دربك... لنطمئن قلبك',honorAr:'خدمة ضيوف الرحمن شرف لنا',honorEn:'SERVING THE GUESTS OF ALLAH IS AN HONOR FOR US'};
const DEFAULT_VIS={logo:true,companyName:true,serviceLine:true,slogan:true,holderPhoto:true,holderName:true,jobTitle:true,department:true,employeeId:true,licenseNumber:true,season:true,qr:true,approval:true,bus:true,makkah:true,footer:true};
const DEFAULT_BACK_VIS={logo:true,companyName:true,serviceLine:true,qr:true,employeeId:true,version:true,department:true,licenseNumber:true,season:true,expiry:true,note:true,footer:true};
const DEFAULT_THEME={primary:'#0a4f93',secondary:'#073566',accent:'#d3a746',surface:'#ffffff',text:'#0b2f5d'};

export function getCR80Calibration(){try{const x=JSON.parse(localStorage.getItem(CALIBRATION_KEY)||'{}');return {offsetX:Number(x.offsetX)||0,offsetY:Number(x.offsetY)||0,scaleX:Number(x.scaleX)||1,scaleY:Number(x.scaleY)||1}}catch{return {offsetX:0,offsetY:0,scaleX:1,scaleY:1}}}
export function saveCR80Calibration(value={}){const x={offsetX:Number(value.offsetX)||0,offsetY:Number(value.offsetY)||0,scaleX:Number(value.scaleX)||1,scaleY:Number(value.scaleY)||1};try{localStorage.setItem(CALIBRATION_KEY,JSON.stringify(x))}catch{}return x}
function MetaPill({label,value,style}){return <span style={style}><b>{label}</b>{value||'—'}</span>}
function getDesigner(card={}){
 const snap=card.template_config_snapshot,hasSnap=snap&&typeof snap==='object'&&!Array.isArray(snap)&&Object.keys(snap).length>0;
 const cfg=hasSnap?snap:(card.template_config||card.published_config||{}),d=cfg?.designer||{};
 const visibility={...DEFAULT_VIS,...(d.visibility||{})};
 const inheritedBack={...DEFAULT_BACK_VIS,logo:visibility.logo,companyName:visibility.companyName,serviceLine:visibility.serviceLine,qr:visibility.qr,employeeId:visibility.employeeId,department:visibility.department,licenseNumber:visibility.licenseNumber,season:visibility.season,footer:visibility.footer};
 return {brand:{...DEFAULT_BRAND,...(d.brand||{})},assets:{logoUrl:'',backgroundUrl:'',makkahUrl:'',busUrl:'',signatureUrl:'',...(d.assets||{})},visibility,backVisibility:{...inheritedBack,...(d.backVisibility||{})},theme:{...DEFAULT_THEME,...(d.theme||{})},layout:{portrait:{...(d.layout?.portrait||{})},landscape:{...(d.layout?.landscape||{})}},backLayout:{portrait:{...(d.backLayout?.portrait||{})},landscape:{...(d.backLayout?.landscape||{})}},typography:{portrait:{...(d.typography?.portrait||{})},landscape:{...(d.typography?.landscape||{})}},backTypography:{portrait:{...(d.backTypography?.portrait||{})},landscape:{...(d.backTypography?.landscape||{})}}}
}
function cardStyle(designer){const t=designer.theme,a=designer.assets;return {'--id-primary':t.primary,'--id-secondary':t.secondary,'--id-accent':t.accent,'--id-surface':t.surface,'--id-text':t.text,'--id-bg-image':a.backgroundUrl?`url("${String(a.backgroundUrl).replace(/"/g,'')}")`:'none'}}
function styleFromLayout(map,orientation,key){const p=map?.[orientation]?.[key];if(!p||typeof p!=='object')return undefined;const s={};const num=v=>Number.isFinite(Number(v))?Number(v):null;const x=num(p.x),y=num(p.y),w=num(p.w),h=num(p.h),z=num(p.z),opacity=num(p.opacity);if(x!==null){s.left=`${x}mm`;s.right='auto';s.transform='none';s.position='absolute'}if(y!==null){s.top=`${y}mm`;s.bottom='auto';s.position='absolute'}if(w!==null&&w>0)s.width=`${w}mm`;if(h!==null&&h>0)s.height=`${h}mm`;if(z!==null)s.zIndex=Math.max(0,Math.min(50,z));if(opacity!==null)s.opacity=Math.max(0,Math.min(1,opacity));return Object.keys(s).length?s:undefined}
function typographyFromMap(map,orientation,key){const p=map?.[orientation]?.[key];if(!p||typeof p!=='object')return undefined;const s={};const size=Number(p.fontSizePt),weight=Number(p.fontWeight),spacing=Number(p.letterSpacingPt),line=Number(p.lineHeight);if(p.fontFamily)s.fontFamily=String(p.fontFamily);if(Number.isFinite(size)&&size>=4&&size<=40)s.fontSize=`${size}pt`;if(Number.isFinite(weight)&&weight>=300&&weight<=900)s.fontWeight=weight;if(/^#[0-9a-f]{3,8}$/i.test(String(p.color||'')))s.color=p.color;if(['left','center','right','start','end'].includes(p.align))s.textAlign=p.align;if(Number.isFinite(spacing)&&spacing>=-2&&spacing<=8)s.letterSpacing=`${spacing}pt`;if(Number.isFinite(line)&&line>=.8&&line<=3)s.lineHeight=line;return Object.keys(s).length?s:undefined}
const merge=(...styles)=>Object.assign({},...styles.filter(Boolean));

export function IDCardFace({card,side='front',verificationBase=''}){
 const [qr,setQr]=useState('');
 const verifyUrl=useMemo(()=>card?.qr_token?`${verificationBase||(typeof window!=='undefined'?window.location.origin:'')}/verify/id/${encodeURIComponent(card.qr_token)}`:'',[card?.qr_token,verificationBase]);
 useEffect(()=>{let alive=true;if(!verifyUrl){setQr('');return}QRCode.toDataURL(verifyUrl,{width:360,margin:1,errorCorrectionLevel:'M'}).then(x=>alive&&setQr(x)).catch(()=>alive&&setQr(''));return()=>{alive=false}},[verifyUrl]);
 if(!card)return null;
 const full=card.print_mode!=='front_back',issueVersion=Number(card.metadata?.issue_version||1),orientation=normalizeOrientation(card.orientation),designer=getDesigner(card),{brand,assets,visibility,backVisibility}=designer;
 const cls=`idcard-cr80 idcard-${card.template_code||'makkah_luxury'} ${orientation}`;
 const ls=key=>styleFromLayout(designer.layout,orientation,key),bls=key=>styleFromLayout(designer.backLayout,orientation,key),ts=key=>typographyFromMap(designer.typography,orientation,key),bts=key=>typographyFromMap(designer.backTypography,orientation,key);
 const Brand=({back=false}={})=>{const pos=back?bls:ls,text=back?bts:ts,vis=back?backVisibility:visibility;return <>{vis.logo&&assets.logoUrl&&<img className={`idcard-template-logo ${back?'idcard-back-logo':''}`} style={pos('logo')} src={assets.logoUrl} alt=""/>}{vis.companyName&&<div className={`idcard-brand ${back?'idcard-back-brand':''}`} style={pos('brand')}><strong style={text('companyAr')||ts('companyAr')}>{brand.companyNameAr}</strong><span style={text('companyEn')||ts('companyEn')}>{brand.companyNameEn}</span></div>}{vis.serviceLine&&<div className={`idcard-company-line ${back?'idcard-back-service-line':''}`} style={merge(pos('serviceLine'),text('serviceLine')||ts('serviceLine'))}>{brand.serviceLineAr}</div>}</>};
 const BackField=({show=true,label,value})=>show?<><b style={bts('metaLabel')||bts('meta')||ts('meta')}>{label}</b><span style={bts('metaValue')||bts('meta')||ts('meta')}>{value||'—'}</span></>:null;
 if(side==='back'&&!full)return <div className={`${cls} back`} data-orientation={orientation} style={cardStyle(designer)}>
  <div className="idcard-custom-bg"></div><div className="idcard-decor idcard-decor-a"></div><div className="idcard-decor idcard-decor-b"></div><div className="idcard-lanyard-slot"></div><Brand back/>
  <div className="idcard-back-grid" style={bls('grid')}><div className="idcard-back-qr" style={bls('qr')}>{backVisibility.qr?(qr?<img className="idcard-qr large" src={qr} alt="QR verification"/>:<div className="idcard-qr-placeholder">QR</div>):null}{backVisibility.qr&&<small style={bts('qrLabel')}>امسح للتحقق من حالة البطاقة</small>}</div><div className="idcard-info idcard-back-info" style={bls('info')}><BackField show={backVisibility.employeeId} label="رقم البطاقة" value={card.card_number}/><BackField show={backVisibility.version} label="الإصدار" value={`V${issueVersion}`}/><BackField show={backVisibility.department} label="القسم" value={card.department_ar}/><BackField show={backVisibility.licenseNumber} label="الترخيص" value={card.license_number}/><BackField show={backVisibility.season} label="الموسم" value={card.season_label}/><BackField show={backVisibility.expiry} label="الصلاحية" value={card.expiry_date}/></div></div>
  {backVisibility.note&&<div className="idcard-verify-note idcard-back-note" style={merge(bls('note'),bts('note'))}>الحالة الإلكترونية الحالية عبر رمز QR هي المرجع لصلاحية البطاقة.</div>}
  {backVisibility.footer&&<div className="idcard-footer idcard-back-footer" style={merge(bls('footer'),bts('footer')||ts('footerAr'))}>{brand.honorAr} · {brand.honorEn}</div>}
 </div>;
 return <div className={`${cls} front`} data-orientation={orientation} style={cardStyle(designer)}>
  <div className="idcard-custom-bg"></div><div className="idcard-decor idcard-decor-a"></div><div className="idcard-decor idcard-decor-b"></div><div className="idcard-watermark-mark">M</div><div className="idcard-lanyard-slot"></div>
  {visibility.makkah&&assets.makkahUrl&&<img className="idcard-template-makkah" style={ls('makkah')} src={assets.makkahUrl} alt=""/>}{visibility.bus&&assets.busUrl&&<img className="idcard-template-bus" style={ls('bus')} src={assets.busUrl} alt=""/>}<Brand/>
  {visibility.holderPhoto&&<div className="idcard-photo" style={ls('photo')}>{card.photo_url?<img src={card.photo_url} alt=""/>:<span>الصورة</span>}</div>}
  <div className="idcard-person" style={ls('person')}>{visibility.holderName&&<><strong style={ts('nameAr')}>{card.name_ar||'اسم حامل البطاقة'}</strong><span style={ts('nameEn')}>{card.name_en||''}</span></>}{visibility.jobTitle&&<><b style={ts('jobTitleAr')}>{card.job_title_ar||'المسمى الوظيفي'}</b><small style={ts('jobTitleEn')}>{card.job_title_en||''}</small></>}</div>
  {visibility.employeeId&&<div className="idcard-number" style={ls('number')}><small style={ts('numberLabel')}>ID CARD</small><span className="idcard-number-value" style={ts('cardNumber')}>{card.card_number||'MA-000'}</span><em>V{issueVersion}</em></div>}
  {full&&<div className="idcard-full-meta" style={ls('meta')}>{visibility.department&&<MetaPill label="القسم" value={card.department_ar} style={ts('meta')}/>} {visibility.licenseNumber&&<MetaPill label="الترخيص" value={card.license_number} style={ts('meta')}/>} {visibility.season&&<MetaPill label="الموسم" value={card.season_label} style={ts('meta')}/>}<MetaPill label="حتى" value={card.expiry_date} style={ts('meta')}/></div>}
  {full&&<div className="idcard-reference-meta"><div><b>الشركة</b><span>{brand.companyNameAr}</span></div>{visibility.licenseNumber&&<div><b>الترخيص</b><span>{card.license_number||'—'}</span></div>}{visibility.season&&<div><b>الموسم</b><span>{card.season_label||'—'}</span></div>}{visibility.employeeId&&<div><b>رقم الموظف</b><span>{card.card_number||'MA-000'}</span></div>}</div>}
  {visibility.qr&&qr&&<div className="idcard-qr-wrap" style={ls('qr')}><img className="idcard-qr" src={qr} alt="QR verification"/><small>تحقق من البطاقة</small></div>}
  <div className={`idcard-status ${card.status||'draft'}`}>{statusAr[card.status]||card.status}</div>
  {visibility.slogan&&<div className="idcard-template-slogan" style={merge(ls('slogan'),ts('slogan'))}>{brand.sloganAr}</div>}
  {visibility.footer&&<div className="idcard-reference-footer" style={ls('footer')}><strong style={ts('footerAr')}>{brand.honorAr}</strong><span style={ts('footerEn')}>{brand.honorEn}</span></div>}
  <div className="idcard-reference-values"><span>أمان</span><span>راحة</span><span>ثقة</span></div>
  {card.status==='active'&&visibility.approval&&<div className="idcard-approval" style={ls('approval')}>{assets.signatureUrl&&<img className="idcard-template-signature" src={assets.signatureUrl} alt=""/>}<small className="idcard-approval-label">اعتماد الإدارة</small><b style={ts('approvalAr')}>معتمدة إلكترونيًا</b><span style={ts('approvalEn')}>Electronic Verification</span></div>}
  {card.status!=='active'&&<div className="idcard-watermark">غير معتمدة</div>}
 </div>;
}

export function CR80CalibrationSheet({orientation='landscape'}){const o=normalizeOrientation(orientation);return <div className={`idcard-calibration-sheet ${o}`} data-orientation={o}><div className="calibration-border"></div><div className="calibration-center-x"></div><div className="calibration-center-y"></div><div className="calibration-label">CR80 · {o==='portrait'?'53.98 × 85.60':'85.60 × 53.98'} mm</div><div className="calibration-mm x">10 mm</div><div className="calibration-mm y">10 mm</div></div>}
export function BatchPrintSheet({cards=[],side='front'}){return <div id="idstudio-batch-print-root" className="idstudio-batch-print-sheet" data-side={side}>{cards.flatMap(card=>{const faces=side==='both'&&card.print_mode==='front_back'?['front','back']:[side==='back'?'back':'front'];const o=normalizeOrientation(card.orientation);return faces.map(face=><div className={`idstudio-batch-page ${o}`} data-orientation={o} key={`${card.id}-${face}`}><IDCardFace card={card} side={face}/></div>)})}</div>}
function applyCalibration(root,{offsetX,offsetY,scaleX,scaleY}={}){const saved=getCR80Calibration();root.style.setProperty('--print-x',`${offsetX??saved.offsetX}mm`);root.style.setProperty('--print-y',`${offsetY??saved.offsetY}mm`);root.style.setProperty('--print-scale-x',String(scaleX??saved.scaleX));root.style.setProperty('--print-scale-y',String(scaleY??saved.scaleY))}
function printRepeatedCopies(root,side,copies,calibration,orientation){const faces=side==='both'?['front','back']:[side];const o=normalizeOrientation(orientation);const temp=document.createElement('div');temp.className='idstudio-batch-print-sheet';temp.id='idstudio-single-copy-print-root';temp.dataset.side=side;temp.dataset.orientation=o;for(let copy=0;copy<copies;copy++)for(const face of faces){const source=root.querySelector(`.idcard-cr80.${face}`);if(!source)continue;const page=document.createElement('div');page.className=`idstudio-batch-page ${o}`;page.dataset.copy=String(copy+1);page.dataset.face=face;page.dataset.orientation=o;page.appendChild(source.cloneNode(true));temp.appendChild(page)}if(!temp.children.length)return false;document.body.appendChild(temp);applyCalibration(temp,calibration);document.body.dataset.idstudioPrintMode='batch';try{window.print()}finally{temp.remove();document.body.dataset.idstudioPrintMode='single'}return true}
export function printCR80(card,{side='front',copies=1,offsetX,offsetY,scaleX,scaleY,calibration=false,orientation}={}){const root=document.getElementById('idstudio-print-root');if(!root)return false;const normalizedSide=side==='full'?'front':side,o=normalizeOrientation(orientation||card?.orientation),count=Math.min(50,Math.max(1,Math.trunc(Number(copies)||1)));if(!calibration&&count>1)return printRepeatedCopies(root,normalizedSide,count,{offsetX,offsetY,scaleX,scaleY},o);document.body.dataset.idstudioPrintMode='single';root.dataset.side=calibration?'calibration':normalizedSide;root.dataset.orientation=o;applyCalibration(root,{offsetX,offsetY,scaleX,scaleY});root.dataset.copies=String(count);window.print();return true}
export function printCR80Batch({side='front',offsetX,offsetY,scaleX,scaleY}={}){const root=document.getElementById('idstudio-batch-print-root');if(!root||!root.children.length)return false;document.body.dataset.idstudioPrintMode='batch';root.dataset.side=side;applyCalibration(root,{offsetX,offsetY,scaleX,scaleY});window.print();return true}
