import React,{useEffect,useMemo,useState} from 'react';
import {Button,Card} from '../../components/UI.jsx';
import {idStudioApi} from './api.js';
import {IDCardFace} from './IDCardPrint.jsx';
import './id-studio-extras.css';

const ACTION_AR={create:'إنشاء البطاقة',update:'تعديل البيانات',photo_update:'تحديث الصورة',submit_for_approval:'إرسال للاعتماد',approve:'اعتماد البطاقة',suspend:'إيقاف البطاقة',resume:'إعادة تفعيل البطاقة',lost:'تسجيل مفقودة',reissue:'إعادة إصدار',revoke:'إلغاء البطاقة',print:'طباعة'};
function fmt(v){if(!v)return '—';try{return new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return String(v)}}

export function IDCardHistoryPanel({card,canAudit=false}){
 const [tab,setTab]=useState('versions'),[state,setState]=useState({loading:false,data:null,error:''});
 useEffect(()=>{let alive=true;if(!card?.id){setState({loading:false,data:null,error:''});return}setState({loading:true,data:null,error:''});idStudioApi.getCardHistory(card.id).then(data=>alive&&setState({loading:false,data,error:''})).catch(e=>alive&&setState({loading:false,data:null,error:e.message||'تعذر تحميل سجل البطاقة.'}));return()=>{alive=false}},[card?.id]);
 if(!card)return null;const d=state.data||{},versions=d.versions||[],prints=d.prints||[],audits=d.audits||[];
 return <Card className="idstudio-history-card"><div className="idstudio-history-head"><div><h3>سجل البطاقة</h3><small>{card.card_number} · الإصدار الحالي V{Number(card.metadata?.issue_version)||1}</small></div><Button onClick={()=>{setState({loading:true,data:null,error:''});idStudioApi.getCardHistory(card.id).then(data=>setState({loading:false,data,error:''})).catch(e=>setState({loading:false,data:null,error:e.message}))}}>تحديث السجل</Button></div>
  <div className="idstudio-history-tabs"><button className={tab==='versions'?'active':''} onClick={()=>setTab('versions')}>الإصدارات <b>{versions.length}</b></button>{canAudit&&<button className={tab==='audit'?'active':''} onClick={()=>setTab('audit')}>العمليات <b>{audits.length}</b></button>}{canAudit&&<button className={tab==='prints'?'active':''} onClick={()=>setTab('prints')}>الطباعة <b>{prints.length}</b></button>}</div>
  {state.loading&&<div className="idstudio-history-empty">جاري تحميل السجل...</div>}{state.error&&<div className="idstudio-history-error">{state.error}</div>}
  {!state.loading&&!state.error&&tab==='versions'&&<div className="idstudio-timeline">{versions.length?versions.map(v=><div className="idstudio-timeline-row" key={v.id}><span className="idstudio-timeline-dot">V{v.version}</span><div><strong>الإصدار {v.version}</strong><small>{v.reason||'إصدار البطاقة'} · {fmt(v.created_at)}</small><p>{v.snapshot?.name_ar||card.name_ar} — {v.snapshot?.job_title_ar||'بدون مسمى'}</p></div></div>):<div className="idstudio-history-empty">لا توجد إصدارات مسجلة.</div>}</div>}
  {!state.loading&&!state.error&&tab==='audit'&&canAudit&&<div className="idstudio-history-table"><table><thead><tr><th>العملية</th><th>المنفذ</th><th>السبب</th><th>الوقت</th></tr></thead><tbody>{audits.length?audits.map(a=><tr key={a.id}><td>{ACTION_AR[a.action]||a.action}</td><td dir="ltr">{a.actor_id||'—'}</td><td>{a.reason||'—'}</td><td>{fmt(a.created_at)}</td></tr>):<tr><td colSpan="4">لا توجد عمليات مسجلة.</td></tr>}</tbody></table></div>}
  {!state.loading&&!state.error&&tab==='prints'&&canAudit&&<div className="idstudio-history-table"><table><thead><tr><th>الوجه</th><th>النسخ</th><th>الطابعة</th><th>بواسطة</th><th>الوقت</th></tr></thead><tbody>{prints.length?prints.map(p=><tr key={p.id}><td>{p.print_side||'full'}</td><td>{p.copies||1}</td><td dir="ltr">{p.printer_profile_id||'—'}</td><td dir="ltr">{p.printed_by||'—'}</td><td>{fmt(p.printed_at)}</td></tr>):<tr><td colSpan="5">لا توجد عمليات طباعة مسجلة.</td></tr>}</tbody></table></div>}
 </Card>
}

export function IDBatchPrintPanel({cards=[],canPrint=false,calibration={},printerProfileId=null,onNotice,onError}){
 const activeCards=useMemo(()=>cards.filter(c=>c.status==='active'),[cards]);
 const [selected,setSelected]=useState([]),[mode,setMode]=useState('front'),[printing,setPrinting]=useState(false),[printCards,setPrintCards]=useState([]);
 useEffect(()=>{setSelected(prev=>prev.filter(id=>activeCards.some(c=>c.id===id)))},[activeCards]);
 function toggle(id){setSelected(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id])}
 async function run(){if(!canPrint||!selected.length)return;const chosen=activeCards.filter(c=>selected.includes(c.id));if(!chosen.length)return;setPrinting(true);try{const printable=mode==='back'?chosen.filter(c=>c.print_mode==='front_back'):chosen;if(!printable.length)throw new Error('البطاقات المحددة لا تحتوي على وجه خلفي للطباعة.');await Promise.all(printable.map(c=>idStudioApi.logPrint(c.id,mode,1,printerProfileId||null)));setPrintCards(printable);document.body.classList.add('idstudio-batch-mode');document.documentElement.style.setProperty('--batch-print-x',`${Number(calibration.offsetX)||0}mm`);document.documentElement.style.setProperty('--batch-print-y',`${Number(calibration.offsetY)||0}mm`);document.documentElement.style.setProperty('--batch-scale-x',String(Number(calibration.scaleX)||1));document.documentElement.style.setProperty('--batch-scale-y',String(Number(calibration.scaleY)||1));setTimeout(()=>{window.print();document.body.classList.remove('idstudio-batch-mode');onNotice?.(`تم تجهيز ${printable.length} بطاقة للطباعة الجماعية وتسجيلها في سجل الطباعة.`)},350)}catch(e){document.body.classList.remove('idstudio-batch-mode');onError?.(e.message||'تعذر تنفيذ الطباعة الجماعية.')}finally{setPrinting(false)}}
 return <Card className="idstudio-batch-card"><div className="idstudio-history-head"><div><h3>الطباعة الجماعية</h3><small>اختر البطاقات الفعالة ثم اطبع الأمام أو الخلف أو الوجهين دفعة واحدة.</small></div><span className="idstudio-batch-count">{selected.length} محددة</span></div>
  <div className="idstudio-batch-toolbar"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="front">الأمام فقط</option><option value="back">الخلف فقط</option><option value="both">الوجهين</option></select><Button onClick={()=>setSelected(activeCards.map(c=>c.id))} disabled={!activeCards.length}>تحديد الكل</Button><Button onClick={()=>setSelected([])} disabled={!selected.length}>إلغاء التحديد</Button><Button variant="primary" onClick={run} disabled={!canPrint||!selected.length||printing}>{printing?'جاري التجهيز...':`طباعة ${selected.length} بطاقة`}</Button></div>
  <div className="idstudio-batch-list">{activeCards.length?activeCards.map(c=><label key={c.id} className={selected.includes(c.id)?'selected':''}><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>toggle(c.id)}/><span><strong>{c.card_number}</strong>{c.name_ar}</span><small>{c.print_mode==='front_back'?'وجهين':'وجه واحد'}</small></label>):<div className="idstudio-history-empty">لا توجد بطاقات فعالة متاحة للطباعة.</div>}</div>
  <div id="idstudio-batch-print-root" data-mode={mode}>{printCards.map(c=><React.Fragment key={c.id}><IDCardFace card={c} side="front"/>{mode!=='front'&&c.print_mode==='front_back'&&<IDCardFace card={c} side="back"/>}</React.Fragment>)}</div>
 </Card>
}
