import React,{useEffect,useMemo,useState} from 'react';
import {Badge,Button,Card,PageHeader} from '../../components/UI.jsx';
import {useAuth} from '../../core/AuthContext.jsx';
import {useAppData} from '../../core/AppDataContext.jsx';
import {has} from '../../lib/permissions.js';
import {idStudioApi} from './api.js';
import {CR80CalibrationSheet,IDCardFace,getCR80Calibration,printCR80,saveCR80Calibration} from './IDCardPrint.jsx';
import {IDBatchPrintPanel,IDCardHistoryPanel} from './IDStudioExtras.jsx';
import './id-studio.css';

const FALLBACK_TEMPLATES=[
 {code:'makkah_luxury',name_ar:'مكة الفاخر',name_en:'Makkah Luxury',default_orientation:'portrait'},
 {code:'executive_side',name_ar:'التنفيذي الجانبي',name_en:'Executive Side',default_orientation:'portrait'},
 {code:'clean_formal',name_ar:'الرسمي النظيف',name_en:'Clean Formal',default_orientation:'landscape'},
 {code:'royal_dark',name_ar:'رويال دارك',name_en:'Royal Dark',default_orientation:'landscape'},
 {code:'minimal_corporate',name_ar:'المؤسسي البسيط',name_en:'Minimal Corporate',default_orientation:'landscape'},
];
const TEMPLATE_KIND={makkah_luxury:'luxury',executive_side:'side',clean_formal:'formal',royal_dark:'dark',minimal_corporate:'minimal'};
const JOBS={'مدير عام':'General Manager','مدير الحجوزات والتسكين':'Reservations & Housing Manager','مدير الحجوزات':'Reservations Manager','مدير التسكين':'Housing Manager','مدير فرع':'Branch Manager','مشرف تشغيل':'Operations Supervisor','مسؤول عمليات العمرة':'Umrah Operations Officer','مدير عمليات العمرة':'Umrah Operations Manager','موظف حجوزات':'Reservations Officer','محاسب':'Accountant','سائق':'Driver','مشرف':'Supervisor','موظف':'Employee'};
const DEPTS={'الحجوزات':'Reservations','التسكين':'Housing','التشغيل':'Operations','المالية':'Finance','الإدارة':'Administration','خدمة العملاء':'Customer Service','الأسطول':'Fleet'};
const AR_MAP={'ا':'a','أ':'a','إ':'i','آ':'a','ب':'b','ت':'t','ث':'th','ج':'j','ح':'h','خ':'kh','د':'d','ذ':'th','ر':'r','ز':'z','س':'s','ش':'sh','ص':'s','ض':'d','ط':'t','ظ':'z','ع':'a','غ':'gh','ف':'f','ق':'q','ك':'k','ل':'l','م':'m','ن':'n','ه':'h','ة':'a','و':'w','ؤ':'o','ي':'y','ى':'a','ئ':'e','ء':''};
const blankCalibration=()=>{const x=getCR80Calibration();return {id:'',name:'الطابعة الافتراضية',printer_name:'',offset_x_mm:x.offsetX,offset_y_mm:x.offsetY,scale_x:x.scaleX,scale_y:x.scaleY,is_default:true}};
function transliterateArabic(value=''){return String(value).split('').map(ch=>AR_MAP[ch]??ch).join('').replace(/\s+/g,' ').trim().split(' ').map(w=>w?`${w[0].toUpperCase()}${w.slice(1)}`:'').join(' ')}
function initialForm(){return {source_type:'standalone',linked_employee_id:'',holder_type:'employee',name_ar:'',name_en:'',job_title_ar:'',job_title_en:'',department_ar:'',department_en:'',phone:'',license_number:'2015',season_label:'1448هـ',issue_date:new Date().toISOString().slice(0,10),expiry_date:'',print_mode:'full',template_code:'makkah_luxury',orientation:'portrait',translation_auto:true}}
function cardToForm(card){const f=initialForm();for(const k of Object.keys(f))if(card?.[k]!==undefined&&card?.[k]!==null)f[k]=card[k];f.expiry_date=card?.expiry_date||'';f.linked_employee_id=card?.linked_employee_id||'';f.orientation=card?.orientation==='portrait'?'portrait':'landscape';return f}
function fmtDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(`${v}T00:00:00`))}catch{return v}}
function statusAr(v){return ({draft:'مسودة',pending_approval:'بانتظار الاعتماد',active:'فعالة',suspended:'موقوفة',expired:'منتهية',lost:'مفقودة',revoked:'ملغاة',reissued:'معاد إصدارها'})[v]||v}
function orientationAr(v){return v==='portrait'?'طولي':'عرضي'}
function orientationSize(v){return v==='portrait'?'53.98 × 85.60 مم':'85.60 × 53.98 مم'}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(new Error('تعذر قراءة الصورة.'));r.readAsDataURL(file)})}

export default function IDStudio(){
 const {user}=useAuth();const {data}=useAppData();
 const employees=data?.users||[];
 const [stats,setStats]=useState({active:0,draft:0,pending_approval:0,expiring_soon:0,total:0});
 const [cards,setCards]=useState([]),[templates,setTemplates]=useState(FALLBACK_TEMPLATES),[profiles,setProfiles]=useState([]);
 const [form,setForm]=useState(initialForm()),[editingId,setEditingId]=useState(''),[calibration,setCalibration]=useState(blankCalibration());
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [q,setQ]=useState(''),[status,setStatus]=useState(''),[selectedCard,setSelectedCard]=useState(null),[previewSide,setPreviewSide]=useState('front');
 const canCreate=has(user,'id_card_create'),canEdit=has(user,'id_card_edit'),canApprove=has(user,'id_card_approve'),canPrint=has(user,'id_card_print');
 const canLink=has(user,'id_card_link_employee'),canManageTemplates=has(user,'id_card_manage_templates'),canManageSettings=has(user,'id_card_manage_settings');
 const canReissue=has(user,'id_card_reissue'),canRevoke=has(user,'id_card_revoke'),canAudit=has(user,'id_card_audit_view');
 const selected=useMemo(()=>templates.find(x=>x.code===form.template_code)||FALLBACK_TEMPLATES[0],[templates,form.template_code]);
 const activeCalibration=useMemo(()=>({offsetX:Number(calibration.offset_x_mm)||0,offsetY:Number(calibration.offset_y_mm)||0,scaleX:Number(calibration.scale_x)||1,scaleY:Number(calibration.scale_y)||1}),[calibration]);

 async function load(filters={}){setLoading(true);setError('');try{const jobs=[idStudioApi.dashboard(),idStudioApi.listCards(filters),idStudioApi.listTemplates()];if(canManageSettings)jobs.push(idStudioApi.listPrinterProfiles());const [d,c,t,p]=await Promise.all(jobs);setStats(d?.stats||{});setCards(c?.rows||[]);if(t?.rows?.length)setTemplates(t.rows);if(p?.rows){setProfiles(p.rows);const def=p.rows.find(x=>x.is_default)||p.rows[0];if(def&&!calibration.id){setCalibration(def);saveCR80Calibration({offsetX:def.offset_x_mm,offsetY:def.offset_y_mm,scaleX:def.scale_x,scaleY:def.scale_y})}}}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const timer=setTimeout(()=>load({q,status}),300);return()=>clearTimeout(timer)},[q,status]);
 function setField(key,value){setForm(prev=>{const next={...prev,[key]:value};if(prev.translation_auto){if(key==='name_ar')next.name_en=transliterateArabic(value);if(key==='job_title_ar')next.job_title_en=JOBS[value]||prev.job_title_en;if(key==='department_ar')next.department_en=DEPTS[value]||prev.department_en}return next})}
 function chooseTemplate(code){const template=templates.find(x=>x.code===code)||FALLBACK_TEMPLATES.find(x=>x.code===code);setForm(prev=>({...prev,template_code:code,orientation:template?.default_orientation==='portrait'?'portrait':'landscape'}));if(!editingId)setSelectedCard(null);setPreviewSide('front')}
 function chooseEmployee(id){const emp=employees.find(x=>String(x.id)===String(id));setForm(prev=>({...prev,source_type:'linked_employee',linked_employee_id:id,name_ar:emp?.name||prev.name_ar,name_en:emp?.name_en||transliterateArabic(emp?.name||''),job_title_ar:emp?.job_title||emp?.role||prev.job_title_ar,job_title_en:JOBS[emp?.job_title||emp?.role]||prev.job_title_en,department_ar:emp?.department||prev.department_ar,department_en:DEPTS[emp?.department]||prev.department_en,phone:emp?.phone||prev.phone}))}
 function resetEditor(){setEditingId('');setForm(initialForm());setSelectedCard(null);setPreviewSide('front')}
 function editCard(card){if(!canEdit||!['draft','pending_approval'].includes(card.status)){setError('تعديل البيانات المباشر متاح للمسودة أو البطاقة بانتظار الاعتماد فقط. البطاقة الفعالة تُعدّل عبر إعادة الإصدار للحفاظ على السجل.');return}setEditingId(card.id);setForm(cardToForm(card));setSelectedCard(card);setPreviewSide('front');setError('');setNotice(`أنت تعدل الآن البطاقة ${card.card_number}.`);window.scrollTo({top:0,behavior:'smooth'})}
 async function saveCard(e,quick=false){e?.preventDefault?.();if(editingId&&!canEdit)return;if(!editingId&&!canCreate)return;setBusy(true);setError('');setNotice('');try{const payload={...form,orientation:form.orientation==='portrait'?'portrait':'landscape',linked_employee_id:form.source_type==='linked_employee'?form.linked_employee_id||null:null,expiry_date:form.expiry_date||null};let out;if(editingId){out=await idStudioApi.updateCard(editingId,payload);setNotice(`تم حفظ تعديلات البطاقة ${out?.card?.card_number||''}.`)}else{out=await idStudioApi.createCard(payload);if(quick){if(!canApprove)throw new Error('الإصدار السريع يحتاج صلاحية إنشاء + اعتماد البطاقة.');out=await idStudioApi.approveCard(out.card.id);setNotice(`تم الإصدار السريع للبطاقة ${out?.card?.card_number||''} واعتمادها مباشرة.`)}else setNotice(`تم إنشاء البطاقة ${out?.card?.card_number||''} كمسودة بنجاح.`)}setSelectedCard(out?.card||null);setEditingId('');setForm(initialForm());await load({q,status})}catch(e2){setError(e2.message)}finally{setBusy(false)}}
 async function action(fn,success){setBusy(true);setError('');setNotice('');try{const out=await fn();setNotice(success);if(out?.card)setSelectedCard(out.card);await load({q,status});return out}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function doPrint(card,side){if(!canPrint||card.status!=='active')return;setBusy(true);setError('');try{await idStudioApi.logPrint(card.id,side,1,calibration.id||null);setSelectedCard(card);setPreviewSide(side==='back'?'back':'front');setTimeout(()=>printCR80(card,{side,orientation:card.orientation,...activeCalibration}),60);setNotice(`تم تسجيل أمر الطباعة وفتح معاينة CR80 ${orientationAr(card.orientation)} بالمعايرة المحفوظة.`)}catch(e){setError(e.message)}finally{setBusy(false)}}
 function printCalibration(){const orientation=previewCard?.orientation||form.orientation||'landscape';saveCR80Calibration(activeCalibration);printCR80(null,{calibration:true,orientation,...activeCalibration});setNotice(`تم فتح ورقة اختبار CR80 ${orientationAr(orientation)}. اطبع بنسبة 100% بدون Fit to page.`)}
 async function saveCalibration(){if(!canManageSettings)return;setBusy(true);setError('');try{const out=await idStudioApi.savePrinterProfile(calibration);const p=out?.profile||calibration;setCalibration(p);saveCR80Calibration({offsetX:p.offset_x_mm,offsetY:p.offset_y_mm,scaleX:p.scale_x,scaleY:p.scale_y});setNotice('تم حفظ معايرة الطابعة وربطها بالطباعة القادمة.');await load({q,status})}catch(e){setError(e.message)}finally{setBusy(false)}}
 function chooseProfile(id){const p=profiles.find(x=>String(x.id)===String(id));if(!p)return;setCalibration(p);saveCR80Calibration({offsetX:p.offset_x_mm,offsetY:p.offset_y_mm,scaleX:p.scale_x,scaleY:p.scale_y})}
 async function uploadPhoto(e){const file=e.target.files?.[0];e.target.value='';if(!file||!selectedCard||!canEdit)return;if(file.size>4*1024*1024){setError('الصورة أكبر من 4MB.');return}setBusy(true);setError('');try{const dataUrl=await fileToDataUrl(file);const out=await idStudioApi.uploadPhoto(selectedCard.id,dataUrl);setSelectedCard(out.card);setNotice('تم رفع صورة حامل البطاقة وتحديث المعاينة.');await load({q,status})}catch(err){setError(err.message)}finally{setBusy(false)}}
 function askReason(title){const value=window.prompt(title,'');return value===null?null:String(value).trim()}
 function suspend(card){const reason=askReason('اكتب سبب إيقاف البطاقة');if(reason===null)return;action(()=>idStudioApi.suspendCard(card.id,reason||'إيقاف إداري'),'تم إيقاف البطاقة وتسجيل السبب.')}
 function resume(card){const reason=askReason('اكتب سبب إعادة تفعيل البطاقة');if(reason===null)return;action(()=>idStudioApi.resumeCard(card.id,reason||'إعادة تفعيل إداري'),'تمت إعادة تفعيل البطاقة وتسجيل العملية.')}
 function markLost(card){const reason=askReason('اكتب ملاحظة فقدان البطاقة');if(reason===null)return;action(()=>idStudioApi.markLost(card.id,reason||'فقدان البطاقة'),'تم تسجيل البطاقة كمفقودة وإيقاف صلاحيتها.')}
 function revoke(card){const reason=askReason('اكتب سبب إلغاء البطاقة نهائيًا');if(reason===null)return;if(!window.confirm('سيتم إلغاء البطاقة ولن تعتبر فعالة. هل تريد المتابعة؟'))return;action(()=>idStudioApi.revokeCard(card.id,reason||'إلغاء البطاقة'),'تم إلغاء البطاقة وتسجيل العملية.')}
 function reissue(card){const reason=askReason('سبب إعادة الإصدار: فقدان / تلف / تغيير بيانات');if(reason===null)return;if(!window.confirm('سيتم إغلاق الإصدار الحالي وإصدار QR جديد مع الحفاظ على رقم البطاقة. متابعة؟'))return;action(()=>idStudioApi.reissueCard(card.id,reason||'إعادة إصدار'),'تم إنشاء الإصدار البديل كمسودة وQR جديد.')}

 const previewCard=editingId?{...selectedCard,...form}:selectedCard||{...form,card_number:'MA-###',status:'draft',qr_token:null};
 return <div className="idstudio-page">
  <PageHeader title="ID Studio" subtitle="إصدار وإدارة بطاقات الشركة — مستقل بصلاحياته عن إدارة الموظفين"/>
  {error&&<div className="idstudio-error">{error}</div>}{notice&&<div className="idstudio-success">{notice}</div>}
  <div className="idstudio-stats"><Card className="idstudio-stat"><span>فعالة</span><strong>{stats.active||0}</strong><Badge>Active</Badge></Card><Card className="idstudio-stat"><span>مسودة</span><strong>{stats.draft||0}</strong><Badge>Draft</Badge></Card><Card className="idstudio-stat"><span>بانتظار الاعتماد</span><strong>{stats.pending_approval||0}</strong><Badge>Pending</Badge></Card><Card className="idstudio-stat"><span>قرب الانتهاء</span><strong>{stats.expiring_soon||0}</strong><Badge>30 يوم</Badge></Card></div>
  <div className="idstudio-grid">
   <Card className="idstudio-control"><div className="idstudio-section-title"><div><h3>{editingId?'تعديل البطاقة':'إصدار بطاقة جديدة'}</h3><small>{editingId?'يتم حفظ التعديل على نفس البطاقة مع تسجيله في Audit Log.':'رقم البطاقة وQR Token يُولدان من الخادم تلقائيًا.'}</small></div>{editingId&&<Badge>EDIT</Badge>}</div><form onSubmit={saveCard} className="idstudio-form">
    <label>مصدر حامل البطاقة<select value={form.source_type} onChange={e=>setField('source_type',e.target.value)}><option value="standalone">بطاقة مستقلة — بدون مستخدم بالنظام</option>{canLink&&<option value="linked_employee">ربط بموظف موجود</option>}</select></label>
    {form.source_type==='linked_employee'&&canLink&&<label>الموظف المرتبط<select value={form.linked_employee_id} onChange={e=>chooseEmployee(e.target.value)} required><option value="">اختر الموظف</option>{employees.map(emp=><option key={emp.id} value={emp.id}>{emp.name||emp.username} — {emp.role||'موظف'}</option>)}</select></label>}
    <div className="idstudio-form-2"><label>نوع حامل البطاقة<select value={form.holder_type} onChange={e=>setField('holder_type',e.target.value)}><option value="employee">موظف داخلي</option><option value="seasonal">موظف موسمي</option><option value="contractor">متعاون</option><option value="driver">سائق</option><option value="supervisor">مشرف</option><option value="visitor">زائر</option><option value="other">أخرى</option></select></label><label>القالب<select value={form.template_code} onChange={e=>chooseTemplate(e.target.value)}>{templates.map(t=><option key={t.code} value={t.code}>{t.name_ar}</option>)}</select></label></div>
    <div className="idstudio-orientation-picker"><span>اتجاه البطاقة</span><div className="idstudio-segment"><button type="button" className={form.orientation==='portrait'?'active':''} onClick={()=>setField('orientation','portrait')}>▯ طولي <small>53.98 × 85.60</small></button><button type="button" className={form.orientation==='landscape'?'active':''} onClick={()=>setField('orientation','landscape')}>▭ عرضي <small>85.60 × 53.98</small></button></div><small>القالب يختار اتجاهه الافتراضي تلقائيًا، وتقدر تغيّره لكل بطاقة على حدة.</small></div>
    <div className="idstudio-form-2"><label>الاسم بالعربية<input value={form.name_ar} onChange={e=>setField('name_ar',e.target.value)} required/></label><label>الاسم بالإنجليزية<input dir="ltr" value={form.name_en} onChange={e=>setField('name_en',e.target.value)}/></label></div>
    <div className="idstudio-form-2"><label>المسمى الوظيفي<input value={form.job_title_ar} onChange={e=>setField('job_title_ar',e.target.value)}/></label><label>Job Title<input dir="ltr" value={form.job_title_en} onChange={e=>setField('job_title_en',e.target.value)}/></label></div>
    <div className="idstudio-form-2"><label>القسم<input value={form.department_ar} onChange={e=>setField('department_ar',e.target.value)}/></label><label>Department<input dir="ltr" value={form.department_en} onChange={e=>setField('department_en',e.target.value)}/></label></div>
    <div className="idstudio-form-3"><label>الجوال<input dir="ltr" value={form.phone} onChange={e=>setField('phone',e.target.value)}/></label><label>الترخيص<input value={form.license_number} onChange={e=>setField('license_number',e.target.value)}/></label><label>الموسم<input value={form.season_label} onChange={e=>setField('season_label',e.target.value)}/></label></div>
    <div className="idstudio-form-3"><label>تاريخ الإصدار<input type="date" value={form.issue_date} onChange={e=>setField('issue_date',e.target.value)}/></label><label>تاريخ الانتهاء<input type="date" value={form.expiry_date} onChange={e=>setField('expiry_date',e.target.value)}/></label><label>الطباعة<select value={form.print_mode} onChange={e=>setField('print_mode',e.target.value)}><option value="full">وجه واحد كامل</option><option value="front_back">أمامي + خلفي</option></select></label></div>
    <label className="idstudio-check"><input type="checkbox" checked={form.translation_auto} onChange={e=>setField('translation_auto',e.target.checked)}/> ترجمة/تحويل تلقائي للإنجليزية</label><div className="idstudio-actions"><Button type="submit" variant="primary" disabled={busy||(!editingId&&!canCreate)}>{busy?'جاري الحفظ...':editingId?'حفظ التعديلات':'إنشاء كمسودة'}</Button>{!editingId&&canCreate&&canApprove&&<Button type="button" onClick={()=>saveCard(null,true)} disabled={busy}>⚡ إصدار سريع + اعتماد</Button>}<Button type="button" onClick={resetEditor}>إلغاء / جديد</Button></div>
   </form></Card>
   <Card className="idstudio-preview-card"><div className="idstudio-section-title"><div><h3>المعاينة الحقيقية</h3><small>{selectedCard?`${selectedCard.card_number} · ${statusAr(selectedCard.status)} · ${orientationAr(previewCard?.orientation)}`:`${selected?.name_ar||'القالب'} · ${orientationAr(previewCard?.orientation)} · معاينة قبل الحفظ`}</small></div><Badge>CR80</Badge></div>
    {previewCard?.print_mode==='front_back'&&<div className="idstudio-segment"><button className={previewSide==='front'?'active':''} onClick={()=>setPreviewSide('front')}>الوجه الأمامي</button><button className={previewSide==='back'?'active':''} onClick={()=>setPreviewSide('back')}>الوجه الخلفي</button></div>}
    <div className={`idstudio-real-preview ${previewCard?.orientation==='portrait'?'portrait-preview':'landscape-preview'}`}><IDCardFace card={previewCard} side={previewSide}/></div><div className="idstudio-safe">{orientationSize(previewCard?.orientation)} · {orientationAr(previewCard?.orientation)} · QR الحقيقي يظهر بعد حفظ البطاقة. البطاقات غير المعتمدة تحمل علامة «غير معتمدة».</div>
    {selectedCard&&<div className="idstudio-card-tools"><div className="idstudio-tool-title"><strong>إدارة البطاقة المحددة</strong><span>{selectedCard.card_number} · {statusAr(selectedCard.status)} · {orientationAr(selectedCard.orientation)}</span></div><div className="idstudio-actions">{canEdit&&['draft','pending_approval'].includes(selectedCard.status)&&<Button onClick={()=>editCard(selectedCard)} disabled={busy}>تعديل البيانات</Button>}{canEdit&&<label className="idstudio-upload"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadPhoto} disabled={busy}/><span>{selectedCard.photo_path?'تغيير الصورة':'رفع صورة'}</span></label>}{canEdit&&selectedCard.status==='active'&&<Button onClick={()=>suspend(selectedCard)} disabled={busy}>إيقاف</Button>}{canApprove&&selectedCard.status==='suspended'&&<Button onClick={()=>resume(selectedCard)} disabled={busy}>إعادة تفعيل</Button>}{canReissue&&['active','suspended'].includes(selectedCard.status)&&<Button onClick={()=>markLost(selectedCard)} disabled={busy}>مفقودة</Button>}{canReissue&&['active','suspended','lost'].includes(selectedCard.status)&&<Button onClick={()=>reissue(selectedCard)} disabled={busy}>إعادة إصدار</Button>}{canRevoke&&!['revoked','reissued'].includes(selectedCard.status)&&<Button onClick={()=>revoke(selectedCard)} disabled={busy}>إلغاء</Button>}</div></div>}
    {selectedCard?.status==='active'&&canPrint&&<div className="idstudio-actions"><Button onClick={()=>doPrint(selectedCard,selectedCard.print_mode==='front_back'?'front':'full')}>طباعة الأمام</Button>{selectedCard.print_mode==='front_back'&&<Button onClick={()=>doPrint(selectedCard,'back')}>طباعة الخلف</Button>}{selectedCard.print_mode==='front_back'&&<Button variant="primary" onClick={()=>doPrint(selectedCard,'both')}>طباعة الوجهين</Button>}</div>}
    <div className="idstudio-templates">{templates.map(t=><button type="button" key={t.code} className={`idstudio-template ${form.template_code===t.code?'selected':''}`} onClick={()=>chooseTemplate(t.code)}><div className={`template-thumb ${TEMPLATE_KIND[t.code]||'minimal'} ${t.default_orientation==='portrait'?'portrait':''}`}><i></i><b></b><em></em></div><strong>{t.name_ar}</strong><span>{t.name_en||''}</span><small>{orientationAr(t.default_orientation)}</small></button>)}</div>{canManageTemplates&&<div className="idstudio-note">لديك صلاحية إدارة القوالب. نشر إصدار قالب جديد سيتم فصله عن البطاقات التاريخية.</div>}
   </Card>
  </div>
  <IDCardHistoryPanel card={selectedCard} canAudit={canAudit}/>
  {canManageSettings&&<Card className="idstudio-printer-card"><div className="idstudio-section-title"><div><h3>معايرة طابعة CR80</h3><small>احفظ Profile مستقل لكل طابعة. ورقة الاختبار تتبع اتجاه البطاقة الحالية تلقائيًا.</small></div><Button onClick={printCalibration}>طباعة ورقة اختبار {orientationAr(previewCard?.orientation)}</Button></div><div className="idstudio-printer-grid"><label>Profile محفوظ<select value={calibration.id||''} onChange={e=>chooseProfile(e.target.value)}><option value="">Profile جديد</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}{p.printer_name?` — ${p.printer_name}`:''}</option>)}</select></label><label>اسم الـProfile<input value={calibration.name||''} onChange={e=>setCalibration(x=>({...x,name:e.target.value}))}/></label><label>اسم الطابعة<input value={calibration.printer_name||''} onChange={e=>setCalibration(x=>({...x,printer_name:e.target.value}))}/></label><label>إزاحة X بالملم<input type="number" step="0.1" value={calibration.offset_x_mm??0} onChange={e=>setCalibration(x=>({...x,offset_x_mm:e.target.value}))}/></label><label>إزاحة Y بالملم<input type="number" step="0.1" value={calibration.offset_y_mm??0} onChange={e=>setCalibration(x=>({...x,offset_y_mm:e.target.value}))}/></label><label>Scale X<input type="number" min="0.9" max="1.1" step="0.001" value={calibration.scale_x??1} onChange={e=>setCalibration(x=>({...x,scale_x:e.target.value}))}/></label><label>Scale Y<input type="number" min="0.9" max="1.1" step="0.001" value={calibration.scale_y??1} onChange={e=>setCalibration(x=>({...x,scale_y:e.target.value}))}/></label><label className="idstudio-check"><input type="checkbox" checked={!!calibration.is_default} onChange={e=>setCalibration(x=>({...x,is_default:e.target.checked}))}/> الطابعة/المعايرة الافتراضية</label></div><div className="idstudio-actions"><Button variant="primary" onClick={saveCalibration} disabled={busy}>حفظ المعايرة</Button><Button onClick={()=>setCalibration(blankCalibration())}>Profile جديد</Button></div></Card>}
  <IDBatchPrintPanel cards={cards} canPrint={canPrint} calibration={activeCalibration} printerProfileId={calibration.id||null} onNotice={setNotice} onError={setError}/>
  <Card><div className="idstudio-section-title"><div><h3>البطاقات</h3><small>{loading?'جاري التحميل...':`${cards.length} بطاقة ظاهرة ضمن نطاق صلاحيتك`}</small></div><Button onClick={()=>load({q,status})}>تحديث</Button></div><div className="idstudio-filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث بالاسم أو رقم البطاقة"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل الحالات</option><option value="draft">مسودة</option><option value="pending_approval">بانتظار الاعتماد</option><option value="active">فعالة</option><option value="suspended">موقوفة</option><option value="expired">منتهية</option><option value="lost">مفقودة</option><option value="revoked">ملغاة</option><option value="reissued">معاد إصدارها</option></select></div><div className="idstudio-table-wrap"><table className="idstudio-table"><thead><tr><th>رقم البطاقة</th><th>الاسم</th><th>المسمى</th><th>الحالة</th><th>القالب</th><th>الاتجاه</th><th>الانتهاء</th><th>إجراءات</th></tr></thead><tbody>{cards.length?cards.map(card=><tr key={card.id} className={selectedCard?.id===card.id?'selected-row':''}><td dir="ltr"><button className="idstudio-card-link" onClick={()=>{setSelectedCard(card);setPreviewSide('front')}}>{card.card_number}</button></td><td>{card.name_ar}<small>{card.name_en}</small></td><td>{card.job_title_ar||'—'}</td><td><span className={`idstudio-status ${card.status}`}>{statusAr(card.status)}</span></td><td>{card.template_code} · v{card.template_version||1}</td><td><Badge>{orientationAr(card.orientation)}</Badge></td><td>{fmtDate(card.expiry_date)}</td><td><div className="idstudio-row-actions"><button onClick={()=>{setSelectedCard(card);setPreviewSide('front')}}>معاينة</button>{canEdit&&['draft','pending_approval'].includes(card.status)&&<button disabled={busy} onClick={()=>editCard(card)}>تعديل</button>}{canEdit&&card.status==='draft'&&<button disabled={busy} onClick={()=>action(()=>idStudioApi.submitForApproval(card.id),'تم إرسال البطاقة للاعتماد.')}>إرسال للاعتماد</button>}{canApprove&&['draft','pending_approval'].includes(card.status)&&<button disabled={busy} onClick={()=>action(()=>idStudioApi.approveCard(card.id),'تم اعتماد البطاقة وتفعيل QR.')}>اعتماد</button>}{canApprove&&card.status==='suspended'&&<button disabled={busy} onClick={()=>resume(card)}>إعادة تفعيل</button>}{canPrint&&card.status==='active'&&<button disabled={busy} onClick={()=>doPrint(card,card.print_mode==='front_back'?'both':'full')}>طباعة</button>}{canReissue&&card.status==='lost'&&<button disabled={busy} onClick={()=>reissue(card)}>إعادة إصدار</button>}</div></td></tr>):<tr><td colSpan="8" className="idstudio-empty">لا توجد بطاقات مطابقة.</td></tr>}</tbody></table></div></Card>
  <div id="idstudio-print-root" className="idstudio-print-sheet" data-side="front" data-orientation={selectedCard?.orientation||form.orientation}><IDCardFace card={selectedCard} side="front"/>{selectedCard?.print_mode==='front_back'&&<IDCardFace card={selectedCard} side="back"/>}<CR80CalibrationSheet orientation={selectedCard?.orientation||form.orientation}/></div>
 </div>
}
