import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {IDCardFace} from './IDCardPrint.jsx';
import {idStudioApi} from './api.js';
import './id-template-visual-editor.css';

const frontSelectors={logo:'.idcard-template-logo',brand:'.idcard-brand',serviceLine:'.idcard-company-line',makkah:'.idcard-template-makkah',photo:'.idcard-photo',person:'.idcard-person',number:'.idcard-number',meta:'.idcard-full-meta, .idcard-reference-meta',qr:'.idcard-qr-wrap',approval:'.idcard-approval',bus:'.idcard-template-bus',slogan:'.idcard-template-slogan',footer:'.idcard-reference-footer'};
const backSelectors={logo:'.idcard-back-logo',brand:'.idcard-back-brand',serviceLine:'.idcard-back-service-line',grid:'.idcard-back-grid',qr:'.idcard-back-qr',info:'.idcard-back-info',note:'.idcard-back-note',footer:'.idcard-back-footer'};
const frontLabels={logo:'الشعار',brand:'اسم الشركة',serviceLine:'وصف النشاط',makkah:'مكة / برج الساعة',photo:'صورة الموظف',person:'الاسم والمسمى',number:'رقم البطاقة',meta:'بيانات البطاقة',qr:'QR',approval:'الاعتماد',bus:'الباص',slogan:'الشعار النصي',footer:'النص السفلي'};
const backLabels={logo:'شعار الخلف',brand:'اسم الشركة بالخلف',serviceLine:'وصف النشاط بالخلف',grid:'مجموعة بيانات الخلف',qr:'QR الخلف',info:'بيانات البطاقة بالخلف',note:'ملاحظة التحقق',footer:'النص السفلي بالخلف'};
const backVisibilityLabels={logo:'الشعار',companyName:'اسم الشركة',serviceLine:'وصف النشاط',qr:'QR',employeeId:'رقم البطاقة',version:'رقم الإصدار',department:'القسم',licenseNumber:'الترخيص',season:'الموسم',expiry:'تاريخ الصلاحية',note:'ملاحظة التحقق',footer:'النص السفلي'};
const backTypographyLabels={companyAr:'اسم الشركة العربي',companyEn:'اسم الشركة الإنجليزي',serviceLine:'وصف النشاط',qrLabel:'عبارة QR',metaLabel:'عناوين البيانات',metaValue:'قيم البيانات',note:'ملاحظة التحقق',footer:'النص السفلي'};
const fontFamilies=['Arial','Tahoma','Cairo','Noto Sans Arabic','Noto Kufi Arabic','Segoe UI'];
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const round=v=>Math.round(v*10)/10;
const grid=v=>Math.round(v*2)/2;
const clone=v=>JSON.parse(JSON.stringify(v||{}));
const SNAP_MM=.85;
function inheritedBackVisibility(config){const v=config?.designer?.visibility||{};return {logo:v.logo!==false,companyName:v.companyName!==false,serviceLine:v.serviceLine!==false,qr:v.qr!==false,employeeId:v.employeeId!==false,version:true,department:v.department!==false,licenseNumber:v.licenseNumber!==false,season:v.season!==false,expiry:true,note:true,footer:v.footer!==false,...(config?.designer?.backVisibility||{})}}
function numericOrBlank(value){if(value==='')return '';const n=Number(value);return Number.isFinite(n)?n:''}

export default function IDTemplateVisualEditor({templateCode='makkah_luxury',config,orientation='portrait',selectedElement='photo',onSelect,onLayoutChange}){
 const wrapRef=useRef(null),dragRef=useRef(null),moveRef=useRef(null),endRef=useRef(null);
 const [boxes,setBoxes]=useState({}),[guides,setGuides]=useState({x:null,y:null}),[snapEnabled,setSnapEnabled]=useState(true),[face,setFace]=useState('front');
 const [backLayout,setBackLayout]=useState(()=>clone(config?.designer?.backLayout||{portrait:{},landscape:{}})),[backVisibility,setBackVisibility]=useState(()=>inheritedBackVisibility(config)),[backTypography,setBackTypography]=useState(()=>clone(config?.designer?.backTypography||{portrait:{},landscape:{}}));
 const [backSelected,setBackSelected]=useState('qr'),[backText,setBackText]=useState('metaValue'),[backDirty,setBackDirty]=useState(false),[savingBack,setSavingBack]=useState(false),[backMessage,setBackMessage]=useState('');
 const size=orientation==='portrait'?{w:53.98,h:85.6}:{w:85.6,h:53.98};
 const frontLayout=config?.designer?.layout?.[orientation]||{};
 const currentLayout=face==='back'?(backLayout?.[orientation]||{}):frontLayout;
 const currentSelected=face==='back'?backSelected:selectedElement;
 const selectors=face==='back'?backSelectors:frontSelectors;
 const labels=face==='back'?backLabels:frontLabels;
 const selectedLayout=currentLayout?.[currentSelected]||{};
 const selectedLocked=selectedLayout.locked===true;
 const activeBackTypography=backTypography?.[orientation]?.[backText]||{};
 useEffect(()=>{if(backDirty)return;setBackLayout(clone(config?.designer?.backLayout||{portrait:{},landscape:{}}));setBackVisibility(inheritedBackVisibility(config));setBackTypography(clone(config?.designer?.backTypography||{portrait:{},landscape:{}}));setBackMessage('')},[templateCode,config,backDirty]);
 useEffect(()=>{setBoxes({});setGuides({x:null,y:null});setTimeout(()=>measure(),0)},[face,orientation]);
 function syncConfig(section,value){if(!config)return;config.designer=config.designer||{};config.designer[section]=clone(value)}
 const previewConfig=useMemo(()=>{const next=clone(config);next.designer=next.designer||{};next.designer.backLayout=clone(backLayout);next.designer.backVisibility=clone(backVisibility);next.designer.backTypography=clone(backTypography);return next},[config,backLayout,backVisibility,backTypography]);
 const sample=useMemo(()=>({id:'designer-preview',template_code:templateCode,template_config:previewConfig,orientation,print_mode:'front_back',status:'active',card_number:'MA-001',name_ar:'محمد عبدالرحمن حسن',name_en:'MOHAMED ABDELRAHMAN HASSAN',job_title_ar:'مدير الحجوزات والتسكين',job_title_en:'Reservations & Housing Manager',department_ar:'الحجوزات والتسكين',license_number:'MA-1448',season_label:'1448هـ',expiry_date:'2027-06-01',metadata:{issue_version:1},qr_token:'designer-preview-token'}),[templateCode,previewConfig,orientation]);
 const measure=useCallback(()=>{const root=wrapRef.current?.querySelector('.idcard-cr80');if(!root)return;const rr=root.getBoundingClientRect(),next={};Object.entries(selectors).forEach(([key,sel])=>{const el=root.querySelector(sel);if(!el)return;const r=el.getBoundingClientRect();if(r.width<1||r.height<1)return;const zi=parseInt(window.getComputedStyle(el).zIndex,10);next[key]={left:r.left-rr.left,top:r.top-rr.top,width:r.width,height:r.height,z:Number.isFinite(zi)?zi:1}});setBoxes(next)},[selectors]);
 const onWindowMove=useCallback(e=>moveRef.current?.(e),[]),onWindowEnd=useCallback(()=>endRef.current?.(),[]);
 useEffect(()=>{const onResize=()=>measure();window.addEventListener('resize',onResize);return()=>window.removeEventListener('resize',onResize)},[measure]);
 useEffect(()=>{const t1=requestAnimationFrame(()=>requestAnimationFrame(measure)),t2=setTimeout(measure,180);return()=>{cancelAnimationFrame(t1);clearTimeout(t2)}},[measure,previewConfig,orientation,templateCode,face]);
 useEffect(()=>()=>{window.removeEventListener('pointermove',onWindowMove);window.removeEventListener('pointerup',onWindowEnd);window.removeEventListener('pointercancel',onWindowEnd);dragRef.current=null},[onWindowMove,onWindowEnd]);
 function geometryFromBox(key){const root=wrapRef.current?.querySelector('.idcard-cr80'),b=boxes[key];if(!root||!b)return null;const rr=root.getBoundingClientRect(),sx=size.w/rr.width,sy=size.h/rr.height;return {x:round(b.left*sx),y:round(b.top*sy),w:round(b.width*sx),h:round(b.height*sy),sx,sy}}
 function isLocked(key){return currentLayout?.[key]?.locked===true}
 function selectKey(key){if(face==='back')setBackSelected(key);else onSelect?.(key)}
 function markBackDirty(){setBackDirty(true);setBackMessage('')}
 function applyLayout(key,patch){if(face==='front'){onLayoutChange?.(key,patch);return}setBackLayout(prev=>{const next=clone(prev);next[orientation]=next[orientation]||{};next[orientation][key]={...(next[orientation][key]||{}),...patch};syncConfig('backLayout',next);return next});markBackDirty()}
 function setBackVisibilityField(key,value){setBackVisibility(prev=>{const next={...prev,[key]:value};syncConfig('backVisibility',next);return next});markBackDirty()}
 function setBackTypographyField(key,value){setBackTypography(prev=>{const next=clone(prev);next[orientation]=next[orientation]||{};const current={...(next[orientation][backText]||{})};if(value===''||value===null||value===undefined)delete current[key];else current[key]=value;if(Object.keys(current).length)next[orientation][backText]=current;else delete next[orientation][backText];syncConfig('backTypography',next);return next});markBackDirty()}
 function resetBackTypography(){setBackTypography(prev=>{const next=clone(prev);if(next?.[orientation])delete next[orientation][backText];syncConfig('backTypography',next);return next});markBackDirty()}
 function axisTargets(axis,excludeKey){const max=axis==='x'?size.w:size.h,targets=[0,max/2,max];Object.entries(boxes).forEach(([key])=>{if(key===excludeKey)return;const g=geometryFromBox(key);if(!g)return;if(axis==='x')targets.push(g.x,g.x+g.w/2,g.x+g.w);else targets.push(g.y,g.y+g.h/2,g.y+g.h)});return [...new Set(targets.map(round))]}
 function snapAxis(start,length,targets,max){const anchors=[start,start+length/2,start+length];let best=null;for(const target of targets)for(const anchor of anchors){const delta=target-anchor,dist=Math.abs(delta);if(dist<=SNAP_MM&&(!best||dist<best.dist))best={value:start+delta,guide:target,dist}};if(best)return {value:clamp(round(best.value),0,Math.max(0,max-length)),guide:best.guide};return {value:clamp(round(grid(start)),0,Math.max(0,max-length)),guide:null}}
 function snapResize(start,length,targets,max){const edge=start+length;let best=null;for(const target of targets){const dist=Math.abs(target-edge);if(dist<=SNAP_MM&&target>start+2&&(!best||dist<best.dist))best={value:target-start,guide:target,dist}};if(best)return {value:round(clamp(best.value,2,max-start)),guide:best.guide};return {value:round(clamp(grid(length),2,max-start)),guide:null}}
 function begin(e,key,mode){e.preventDefault();e.stopPropagation();selectKey(key);if(isLocked(key))return;const g=geometryFromBox(key);if(!g)return;window.removeEventListener('pointermove',onWindowMove);window.removeEventListener('pointerup',onWindowEnd);window.removeEventListener('pointercancel',onWindowEnd);dragRef.current={key,mode,startX:e.clientX,startY:e.clientY,...g};setGuides({x:null,y:null});window.addEventListener('pointermove',onWindowMove);window.addEventListener('pointerup',onWindowEnd,{once:true});window.addEventListener('pointercancel',onWindowEnd,{once:true})}
 function move(e){const d=dragRef.current;if(!d)return;const dx=(e.clientX-d.startX)*d.sx,dy=(e.clientY-d.startY)*d.sy;if(d.mode==='move'){let x=clamp(d.x+dx,0,Math.max(0,size.w-d.w)),y=clamp(d.y+dy,0,Math.max(0,size.h-d.h)),gx=null,gy=null;if(snapEnabled){const sx=snapAxis(x,d.w,axisTargets('x',d.key),size.w),sy=snapAxis(y,d.h,axisTargets('y',d.key),size.h);x=sx.value;y=sy.value;gx=sx.guide;gy=sy.guide}else{x=round(x);y=round(y)}setGuides({x:gx,y:gy});applyLayout(d.key,{x,y})}else{let w=clamp(d.w+dx,2,size.w-d.x),h=clamp(d.h+dy,2,size.h-d.y),gx=null,gy=null;if(snapEnabled){const sw=snapResize(d.x,w,axisTargets('x',d.key),size.w),sh=snapResize(d.y,h,axisTargets('y',d.key),size.h);w=sw.value;h=sh.value;gx=sw.guide;gy=sh.guide}else{w=round(w);h=round(h)}setGuides({x:gx,y:gy});applyLayout(d.key,{x:d.x,y:d.y,w,h})}}
 function end(){dragRef.current=null;window.removeEventListener('pointermove',onWindowMove);window.removeEventListener('pointerup',onWindowEnd);window.removeEventListener('pointercancel',onWindowEnd);setGuides({x:null,y:null});setTimeout(measure,0)}
 moveRef.current=move;endRef.current=end;
 function currentZ(key){const configured=Number(currentLayout?.[key]?.z);if(Number.isFinite(configured))return configured;return Number(boxes?.[key]?.z)||1}
 function changeLayer(mode){if(!currentSelected)return;const values=Object.keys(selectors).map(currentZ),current=currentZ(currentSelected),max=Math.max(1,...values);let z=current;if(mode==='front')z=Math.min(50,max+1);if(mode==='forward')z=Math.min(50,current+1);if(mode==='backward')z=Math.max(0,current-1);if(mode==='back')z=0;applyLayout(currentSelected,{z})}
 function toggleLock(){if(!currentSelected)return;applyLayout(currentSelected,{locked:!selectedLocked})}
 function resetCurrent(){if(face==='front'){onLayoutChange?.(currentSelected,{x:undefined,y:undefined,w:undefined,h:undefined,z:undefined,opacity:undefined,locked:false});return}setBackLayout(prev=>{const next=clone(prev);if(next?.[orientation])delete next[orientation][currentSelected];syncConfig('backLayout',next);return next});markBackDirty()}
 function keyboardNudge(e){if(selectedLocked||!currentSelected||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const g=geometryFromBox(currentSelected);if(!g)return;const step=e.shiftKey?2:.5,dx=e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,dy=e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0;applyLayout(currentSelected,{x:round(clamp(g.x+dx,0,Math.max(0,size.w-g.w))),y:round(clamp(g.y+dy,0,Math.max(0,size.h-g.h)))})}
 async function saveBack(){if(!backDirty||savingBack)return;setSavingBack(true);setBackMessage('');try{const next=clone(config);next.designer=next.designer||{};next.designer.backLayout=clone(backLayout);next.designer.backVisibility=clone(backVisibility);next.designer.backTypography=clone(backTypography);const out=await idStudioApi.saveTemplate(templateCode,next,orientation,'back_face_designer_publish');setBackDirty(false);setBackMessage(`تم نشر الوجه الخلفي كإصدار v${out?.template?.published_version||''}. البطاقات القديمة لن تتغير.`)}catch(e){setBackMessage(e.message||'تعذر حفظ الوجه الخلفي')}finally{setSavingBack(false)}}
 const colorValue=/^#[0-9a-f]{6}$/i.test(String(activeBackTypography.color||''))?activeBackTypography.color:'#0b2f5d';
 return <div className="idvisual-editor">
  <div className="idvisual-toolbar"><div><b>محرر بصري مباشر</b><span>{face==='front'?'اسحب عناصر الوجه الأمامي، وكبّرها من المقبض الذهبي.':'الوجه الخلفي مستقل في المواضع والنصوص والعناصر الظاهرة عن الوجه الأمامي.'}</span></div><span className="idvisual-size">CR80 · {size.w} × {size.h} مم</span></div>
  <div className="idvisual-face-tabs"><button type="button" className={face==='front'?'active':''} onClick={()=>setFace('front')}>الوجه الأمامي</button><button type="button" className={face==='back'?'active':''} onClick={()=>{setFace('back');setBackSelected('qr')}}>الوجه الخلفي</button>{face==='back'&&<button type="button" className="save" disabled={!backDirty||savingBack} onClick={saveBack}>{savingBack?'جاري النشر...':'نشر الوجه الخلفي'}</button>}</div>
  {face==='back'&&backMessage&&<div className={`idvisual-message ${backMessage.startsWith('تم ')||backMessage.startsWith('تمت ')?'success':'error'}`}>{backMessage}</div>}
  <div className="idvisual-actions"><label className="idvisual-snap"><input type="checkbox" checked={snapEnabled} onChange={e=>setSnapEnabled(e.target.checked)}/><span>Snap ومحاذاة ذكية</span></label><span className="idvisual-selected">{labels[currentSelected]||currentSelected}</span><button type="button" className={selectedLocked?'active lock':''} onClick={toggleLock}>{selectedLocked?'🔒 فتح العنصر':'🔓 قفل العنصر'}</button><button type="button" onClick={()=>changeLayer('front')} title="إلى الواجهة">⇧ الواجهة</button><button type="button" onClick={()=>changeLayer('forward')} title="طبقة للأمام">↑ للأمام</button><button type="button" onClick={()=>changeLayer('backward')} title="طبقة للخلف">↓ للخلف</button><button type="button" onClick={()=>changeLayer('back')} title="إلى الخلفية">⇩ الخلفية</button><button type="button" onClick={resetCurrent}>إعادة موضع العنصر</button></div>
  {face==='back'&&<div className="idvisual-back-settings"><div className="idvisual-back-panel"><strong>إظهار وإخفاء عناصر الخلف</strong><div className="idvisual-back-toggles">{Object.entries(backVisibilityLabels).map(([key,label])=><label key={key}><input type="checkbox" checked={backVisibility[key]!==false} onChange={e=>setBackVisibilityField(key,e.target.checked)}/><span>{label}</span></label>)}</div></div><div className="idvisual-back-panel"><strong>خطوط وألوان نصوص الخلف — {orientation==='portrait'?'طولي':'عرضي'}</strong><div className="idvisual-back-text-tabs">{Object.entries(backTypographyLabels).map(([key,label])=><button type="button" key={key} className={backText===key?'active':''} onClick={()=>setBackText(key)}>{label}</button>)}</div><div className="idvisual-back-typo-grid"><label>نوع الخط<select value={activeBackTypography.fontFamily||''} onChange={e=>setBackTypographyField('fontFamily',e.target.value)}><option value="">خط القالب</option>{fontFamilies.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>الحجم pt<input type="number" step="0.25" min="4" max="40" value={activeBackTypography.fontSizePt??''} placeholder="افتراضي" onChange={e=>setBackTypographyField('fontSizePt',numericOrBlank(e.target.value))}/></label><label>الوزن<select value={activeBackTypography.fontWeight??''} onChange={e=>setBackTypographyField('fontWeight',e.target.value===''?'':Number(e.target.value))}><option value="">افتراضي</option>{[300,400,500,600,700,800,900].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>المحاذاة<select value={activeBackTypography.align||''} onChange={e=>setBackTypographyField('align',e.target.value)}><option value="">افتراضي</option><option value="right">يمين</option><option value="center">منتصف</option><option value="left">يسار</option></select></label><label>اللون<div className="idvisual-color"><input type="color" value={colorValue} onChange={e=>setBackTypographyField('color',e.target.value)}/><input dir="ltr" value={activeBackTypography.color||''} placeholder="لون القالب" onChange={e=>setBackTypographyField('color',e.target.value)}/></div></label><label>تباعد الحروف<input type="number" step="0.1" min="-2" max="8" value={activeBackTypography.letterSpacingPt??''} placeholder="افتراضي" onChange={e=>setBackTypographyField('letterSpacingPt',numericOrBlank(e.target.value))}/></label><label>ارتفاع السطر<input type="number" step="0.05" min="0.8" max="3" value={activeBackTypography.lineHeight??''} placeholder="افتراضي" onChange={e=>setBackTypographyField('lineHeight',numericOrBlank(e.target.value))}/></label></div><button type="button" className="idvisual-reset-typo" onClick={resetBackTypography}>إرجاع تنسيق النص للخلف إلى القالب</button></div></div>}
  <div className={`idvisual-canvas ${orientation}`}><div className="idvisual-card-wrap" ref={wrapRef} tabIndex="0" onKeyDown={keyboardNudge} aria-label="محرر مواضع عناصر بطاقة الهوية"><IDCardFace card={sample} side={face}/>{guides.x!==null&&<i className="idvisual-guide vertical" style={{left:`${guides.x/size.w*100}%`}}/>}{guides.y!==null&&<i className="idvisual-guide horizontal" style={{top:`${guides.y/size.h*100}%`}}/>}{Object.entries(boxes).map(([key,b])=>{const locked=isLocked(key);return <div key={key} className={`idvisual-box ${currentSelected===key?'selected':''} ${locked?'locked':''}`} style={{left:b.left,top:b.top,width:b.width,height:b.height}} onPointerDown={e=>begin(e,key,'move')} onClick={()=>selectKey(key)}><span>{locked?'🔒 ':''}{labels[key]||key}</span>{currentSelected===key&&!locked&&<i className="idvisual-resize" onPointerDown={e=>begin(e,key,'resize')}/>}</div>})}</div></div>
  <div className="idvisual-hint">Snap يلتقط الحواف والمراكز وعناصر التصميم الأخرى ضمن 0.85 مم، ومع عدم وجود محاذاة قريبة يستخدم شبكة 0.5 مم. الأسهم تحرك العنصر 0.5 مم وShift + سهم يحركه 2 مم.{face==='back'?' إعدادات الخلف محفوظة داخل نفس إصدار القالب ولا تؤثر على تصميم الوجه الأمامي.':''}</div>
 </div>
}
