import React,{useEffect,useMemo,useState} from 'react';
import {Button,Card} from '../../components/UI.jsx';
import {idStudioApi} from './api.js';
import './id-template-designer.css';

const clone=v=>JSON.parse(JSON.stringify(v||{}));
const baseDesigner={brand:{companyNameAr:'شركة الماهر الماسي للنقل',companyNameEn:'Al-Maher Al-Massy Transport Company',serviceLineAr:'لنقل الحجاج والمعتمرين',serviceLineEn:'For Hajj & Umrah Transport',sloganAr:'نُيسر دربك... لنطمئن قلبك',honorAr:'خدمة ضيوف الرحمن شرف لنا',honorEn:'SERVING THE GUESTS OF ALLAH IS AN HONOR FOR US'},assets:{logoUrl:'',backgroundUrl:'',makkahUrl:'',busUrl:'',signatureUrl:''},visibility:{logo:true,companyName:true,serviceLine:true,slogan:true,holderPhoto:true,holderName:true,jobTitle:true,department:true,employeeId:true,licenseNumber:true,season:true,qr:true,approval:true,bus:true,makkah:true,footer:true},theme:{primary:'#0a4f93',secondary:'#073566',accent:'#d3a746',surface:'#ffffff',text:'#0b2f5d'}};
function normalize(template){const cfg=clone(template?.published_config&&Object.keys(template.published_config).length?template.published_config:template?.config||{});cfg.designer=cfg.designer||{};cfg.designer.brand={...baseDesigner.brand,...(cfg.designer.brand||{})};cfg.designer.assets={...baseDesigner.assets,...(cfg.designer.assets||{})};cfg.designer.visibility={...baseDesigner.visibility,...(cfg.designer.visibility||{})};cfg.designer.theme={...baseDesigner.theme,...(cfg.designer.theme||{})};return cfg}
const visibilityLabels={logo:'الشعار',companyName:'اسم الشركة',serviceLine:'وصف النشاط',slogan:'الشعار النصي',holderPhoto:'صورة حامل البطاقة',holderName:'الاسم',jobTitle:'المسمى الوظيفي',department:'القسم',employeeId:'رقم البطاقة',licenseNumber:'الترخيص',season:'الموسم',qr:'QR',approval:'الاعتماد/التوقيع',bus:'صورة الباص',makkah:'صورة مكة/برج الساعة',footer:'النص السفلي'};

export default function IDTemplateDesigner({template,onDraftChange,onSaved,onNotice,onError}){
 const [config,setConfig]=useState(()=>normalize(template)),[orientation,setOrientation]=useState(template?.default_orientation==='portrait'?'portrait':'landscape'),[busy,setBusy]=useState(false);
 useEffect(()=>{setConfig(normalize(template));setOrientation(template?.default_orientation==='portrait'?'portrait':'landscape')},[template?.code,template?.published_version]);
 const d=config.designer;
 const set=(section,key,value)=>setConfig(prev=>{const next=clone(prev);next.designer=next.designer||{};next.designer[section]={...(next.designer[section]||{}),[key]:value};onDraftChange?.(next,orientation);return next});
 function setOrientationLive(value){setOrientation(value);onDraftChange?.(config,value)}
 async function save(){if(!template?.code)return;setBusy(true);onError?.('');try{const out=await idStudioApi.saveTemplate(template.code,config,orientation);onNotice?.(`تم نشر تصميم ${template.name_ar} كإصدار v${out?.template?.published_version||''}.`);onSaved?.(out?.template)}catch(e){onError?.(e.message)}finally{setBusy(false)}}
 async function restore(){if(!template?.code||!window.confirm('سيتم استعادة التصميم الأصلي لهذا القالب ونشره كإصدار جديد. متابعة؟'))return;setBusy(true);onError?.('');try{const out=await idStudioApi.restoreTemplate(template.code);onNotice?.(`تمت استعادة التصميم الأصلي لقالب ${template.name_ar}.`);onSaved?.(out?.template)}catch(e){onError?.(e.message)}finally{setBusy(false)}}
 const version=useMemo(()=>Number(template?.published_version||template?.version||1),[template]);
 return <Card className="idtemplate-designer"><div className="idtemplate-head"><div><h3>محرر تصميم البطاقة</h3><small>{template?.name_ar} · الإصدار المنشور v{version}</small></div><div className="idtemplate-head-actions"><Button onClick={restore} disabled={busy}>استعادة الأصل</Button><Button variant="primary" onClick={save} disabled={busy}>{busy?'جاري الحفظ...':'نشر التصميم'}</Button></div></div>
  <div className="idtemplate-orientation"><b>الاتجاه الافتراضي للقالب</b><button className={orientation==='portrait'?'active':''} onClick={()=>setOrientationLive('portrait')}>طولي</button><button className={orientation==='landscape'?'active':''} onClick={()=>setOrientationLive('landscape')}>عرضي</button></div>
  <details open><summary>الهوية والنصوص</summary><div className="idtemplate-grid"><label>اسم الشركة بالعربية<input value={d.brand.companyNameAr} onChange={e=>set('brand','companyNameAr',e.target.value)}/></label><label>Company Name<input dir="ltr" value={d.brand.companyNameEn} onChange={e=>set('brand','companyNameEn',e.target.value)}/></label><label>وصف النشاط<input value={d.brand.serviceLineAr} onChange={e=>set('brand','serviceLineAr',e.target.value)}/></label><label>Service Line<input dir="ltr" value={d.brand.serviceLineEn} onChange={e=>set('brand','serviceLineEn',e.target.value)}/></label><label>الشعار النصي<input value={d.brand.sloganAr} onChange={e=>set('brand','sloganAr',e.target.value)}/></label><label>العبارة السفلية<input value={d.brand.honorAr} onChange={e=>set('brand','honorAr',e.target.value)}/></label><label className="wide">Footer English<input dir="ltr" value={d.brand.honorEn} onChange={e=>set('brand','honorEn',e.target.value)}/></label></div></details>
  <details><summary>الشعار والصور</summary><div className="idtemplate-grid"><label className="wide">رابط الشعار<input dir="ltr" placeholder="https://..." value={d.assets.logoUrl} onChange={e=>set('assets','logoUrl',e.target.value)}/></label><label className="wide">رابط الخلفية<input dir="ltr" placeholder="https://..." value={d.assets.backgroundUrl} onChange={e=>set('assets','backgroundUrl',e.target.value)}/></label><label>صورة مكة / برج الساعة<input dir="ltr" placeholder="https://..." value={d.assets.makkahUrl} onChange={e=>set('assets','makkahUrl',e.target.value)}/></label><label>صورة الباص<input dir="ltr" placeholder="https://..." value={d.assets.busUrl} onChange={e=>set('assets','busUrl',e.target.value)}/></label><label className="wide">صورة التوقيع<input dir="ltr" placeholder="https://..." value={d.assets.signatureUrl} onChange={e=>set('assets','signatureUrl',e.target.value)}/></label></div><div className="idtemplate-help">رفع ملفات الصور مباشرة من داخل النظام سيتم توصيله في المرحلة التالية؛ حاليًا المحرر يقبل روابط الصور ويحفظها مع إصدار القالب.</div></details>
  <details><summary>الألوان</summary><div className="idtemplate-colors">{Object.entries({primary:'الأساسي',secondary:'الثانوي',accent:'الذهبي/Accent',surface:'الخلفية',text:'النص'}).map(([key,label])=><label key={key}><span>{label}</span><input type="color" value={d.theme[key]||baseDesigner.theme[key]} onChange={e=>set('theme',key,e.target.value)}/><input dir="ltr" value={d.theme[key]||''} onChange={e=>set('theme',key,e.target.value)}/></label>)}</div></details>
  <details><summary>إظهار وإخفاء العناصر</summary><div className="idtemplate-toggles">{Object.entries(visibilityLabels).map(([key,label])=><label key={key}><input type="checkbox" checked={d.visibility[key]!==false} onChange={e=>set('visibility',key,e.target.checked)}/><span>{label}</span></label>)}</div></details>
 </Card>
}
