import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {IDCardFace} from './IDCardPrint.jsx';
import './id-template-visual-editor.css';

const selectors={
 logo:'.idcard-template-logo',brand:'.idcard-brand',serviceLine:'.idcard-company-line',makkah:'.idcard-template-makkah',photo:'.idcard-photo',person:'.idcard-person',number:'.idcard-number',meta:'.idcard-full-meta',qr:'.idcard-qr-wrap',approval:'.idcard-approval',bus:'.idcard-template-bus',slogan:'.idcard-template-slogan',footer:'.idcard-reference-footer'
};
const labels={logo:'الشعار',brand:'اسم الشركة',serviceLine:'وصف النشاط',makkah:'مكة / برج الساعة',photo:'صورة الموظف',person:'الاسم والمسمى',number:'رقم البطاقة',meta:'بيانات البطاقة',qr:'QR',approval:'الاعتماد',bus:'الباص',slogan:'الشعار النصي',footer:'النص السفلي'};
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const round=v=>Math.round(v*10)/10;
const grid=v=>Math.round(v*2)/2;
const SNAP_MM=.85;

export default function IDTemplateVisualEditor({templateCode='makkah_luxury',config,orientation='portrait',selectedElement='photo',onSelect,onLayoutChange}){
 const wrapRef=useRef(null),dragRef=useRef(null),moveRef=useRef(null),endRef=useRef(null);
 const [boxes,setBoxes]=useState({}),[guides,setGuides]=useState({x:null,y:null}),[snapEnabled,setSnapEnabled]=useState(true);
 const size=orientation==='portrait'?{w:53.98,h:85.6}:{w:85.6,h:53.98};
 const layout=config?.designer?.layout?.[orientation]||{};
 const selectedLayout=layout?.[selectedElement]||{};
 const selectedLocked=selectedLayout.locked===true;
 const sample=useMemo(()=>({id:'designer-preview',template_code:templateCode,template_config:config,orientation,print_mode:'single',status:'active',card_number:'MA-001',name_ar:'محمد عبدالرحمن حسن',name_en:'MOHAMED ABDELRAHMAN HASSAN',job_title_ar:'مدير الحجوزات والتسكين',job_title_en:'Reservations & Housing Manager',department_ar:'الحجوزات والتسكين',license_number:'MA-1448',season_label:'1448هـ',expiry_date:'2027-06-01',metadata:{issue_version:1},qr_token:'designer-preview-token'}),[templateCode,config,orientation]);
 const measure=useCallback(()=>{const root=wrapRef.current?.querySelector('.idcard-cr80');if(!root)return;const rr=root.getBoundingClientRect(),next={};Object.entries(selectors).forEach(([key,sel])=>{const el=root.querySelector(sel);if(!el)return;const r=el.getBoundingClientRect();if(r.width<1||r.height<1)return;const zi=parseInt(window.getComputedStyle(el).zIndex,10);next[key]={left:r.left-rr.left,top:r.top-rr.top,width:r.width,height:r.height,z:Number.isFinite(zi)?zi:1}});setBoxes(next)},[]);
 const onWindowMove=useCallback(e=>moveRef.current?.(e),[]),onWindowEnd=useCallback(()=>endRef.current?.(),[]);
 useEffect(()=>{const onResize=()=>measure();window.addEventListener('resize',onResize);return()=>window.removeEventListener('resize',onResize)},[measure]);
 useEffect(()=>{const t1=requestAnimationFrame(()=>requestAnimationFrame(measure)),t2=setTimeout(measure,180);return()=>{cancelAnimationFrame(t1);clearTimeout(t2)}},[measure,config,orientation,templateCode]);
 useEffect(()=>()=>{window.removeEventListener('pointermove',onWindowMove);window.removeEventListener('pointerup',onWindowEnd);window.removeEventListener('pointercancel',onWindowEnd);dragRef.current=null},[onWindowMove,onWindowEnd]);
 function geometryFromBox(key){const root=wrapRef.current?.querySelector('.idcard-cr80'),b=boxes[key];if(!root||!b)return null;const rr=root.getBoundingClientRect(),sx=size.w/rr.width,sy=size.h/rr.height;return {x:round(b.left*sx),y:round(b.top*sy),w:round(b.width*sx),h:round(b.height*sy),sx,sy}}
 function isLocked(key){return layout?.[key]?.locked===true}
 function axisTargets(axis,excludeKey){const max=axis==='x'?size.w:size.h,targets=[0,max/2,max];Object.entries(boxes).forEach(([key])=>{if(key===excludeKey)return;const g=geometryFromBox(key);if(!g)return;if(axis==='x')targets.push(g.x,g.x+g.w/2,g.x+g.w);else targets.push(g.y,g.y+g.h/2,g.y+g.h)});return [...new Set(targets.map(round))]}
 function snapAxis(start,length,targets,max){const anchors=[start,start+length/2,start+length];let best=null;for(const target of targets)for(const anchor of anchors){const delta=target-anchor,dist=Math.abs(delta);if(dist<=SNAP_MM&&(!best||dist<best.dist))best={value:start+delta,guide:target,dist}};if(best)return {value:clamp(round(best.value),0,Math.max(0,max-length)),guide:best.guide};return {value:clamp(round(grid(start)),0,Math.max(0,max-length)),guide:null}}
 function snapResize(start,length,targets,max){const edge=start+length;let best=null;for(const target of targets){const dist=Math.abs(target-edge);if(dist<=SNAP_MM&&target>start+2&&(!best||dist<best.dist))best={value:target-start,guide:target,dist}};if(best)return {value:round(clamp(best.value,2,max-start)),guide:best.guide};return {value:round(clamp(grid(length),2,max-start)),guide:null}}
 function begin(e,key,mode){e.preventDefault();e.stopPropagation();onSelect?.(key);if(isLocked(key))return;const g=geometryFromBox(key);if(!g)return;window.removeEventListener('pointermove',onWindowMove);window.removeEventListener('pointerup',onWindowEnd);window.removeEventListener('pointercancel',onWindowEnd);dragRef.current={key,mode,startX:e.clientX,startY:e.clientY,...g};setGuides({x:null,y:null});window.addEventListener('pointermove',onWindowMove);window.addEventListener('pointerup',onWindowEnd,{once:true});window.addEventListener('pointercancel',onWindowEnd,{once:true})}
 function move(e){const d=dragRef.current;if(!d)return;const dx=(e.clientX-d.startX)*d.sx,dy=(e.clientY-d.startY)*d.sy;if(d.mode==='move'){let x=clamp(d.x+dx,0,Math.max(0,size.w-d.w)),y=clamp(d.y+dy,0,Math.max(0,size.h-d.h)),gx=null,gy=null;if(snapEnabled){const sx=snapAxis(x,d.w,axisTargets('x',d.key),size.w),sy=snapAxis(y,d.h,axisTargets('y',d.key),size.h);x=sx.value;y=sy.value;gx=sx.guide;gy=sy.guide}else{x=round(x);y=round(y)}setGuides({x:gx,y:gy});onLayoutChange?.(d.key,{x,y})}else{let w=clamp(d.w+dx,2,size.w-d.x),h=clamp(d.h+dy,2,size.h-d.y),gx=null,gy=null;if(snapEnabled){const sw=snapResize(d.x,w,axisTargets('x',d.key),size.w),sh=snapResize(d.y,h,axisTargets('y',d.key),size.h);w=sw.value;h=sh.value;gx=sw.guide;gy=sh.guide}else{w=round(w);h=round(h)}setGuides({x:gx,y:gy});onLayoutChange?.(d.key,{x:d.x,y:d.y,w,h})}}
 function end(){dragRef.current=null;window.removeEventListener('pointermove',onWindowMove);window.removeEventListener('pointerup',onWindowEnd);window.removeEventListener('pointercancel',onWindowEnd);setGuides({x:null,y:null});setTimeout(measure,0)}
 moveRef.current=move;endRef.current=end;
 function currentZ(key){const configured=Number(layout?.[key]?.z);if(Number.isFinite(configured))return configured;return Number(boxes?.[key]?.z)||1}
 function changeLayer(mode){if(!selectedElement)return;const values=Object.keys(selectors).map(currentZ),current=currentZ(selectedElement),max=Math.max(1,...values);let z=current;if(mode==='front')z=Math.min(50,max+1);if(mode==='forward')z=Math.min(50,current+1);if(mode==='backward')z=Math.max(0,current-1);if(mode==='back')z=0;onLayoutChange?.(selectedElement,{z})}
 function toggleLock(){if(!selectedElement)return;onLayoutChange?.(selectedElement,{locked:!selectedLocked})}
 function keyboardNudge(e){if(selectedLocked||!selectedElement||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const g=geometryFromBox(selectedElement);if(!g)return;const step=e.shiftKey?2:.5,dx=e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,dy=e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0;onLayoutChange?.(selectedElement,{x:round(clamp(g.x+dx,0,Math.max(0,size.w-g.w))),y:round(clamp(g.y+dy,0,Math.max(0,size.h-g.h)))})}
 return <div className="idvisual-editor">
  <div className="idvisual-toolbar"><div><b>محرر بصري مباشر</b><span>اسحب العناصر، كبّرها من المقبض الذهبي، والمحاذاة الذكية تضبط الحواف والمراكز تلقائيًا.</span></div><span className="idvisual-size">CR80 · {size.w} × {size.h} مم</span></div>
  <div className="idvisual-actions"><label className="idvisual-snap"><input type="checkbox" checked={snapEnabled} onChange={e=>setSnapEnabled(e.target.checked)}/><span>Snap ومحاذاة ذكية</span></label><span className="idvisual-selected">{labels[selectedElement]||selectedElement}</span><button type="button" className={selectedLocked?'active lock':''} onClick={toggleLock}>{selectedLocked?'🔒 فتح العنصر':'🔓 قفل العنصر'}</button><button type="button" onClick={()=>changeLayer('front')} title="إلى الواجهة">⇧ الواجهة</button><button type="button" onClick={()=>changeLayer('forward')} title="طبقة للأمام">↑ للأمام</button><button type="button" onClick={()=>changeLayer('backward')} title="طبقة للخلف">↓ للخلف</button><button type="button" onClick={()=>changeLayer('back')} title="إلى الخلفية">⇩ الخلفية</button></div>
  <div className={`idvisual-canvas ${orientation}`}><div className="idvisual-card-wrap" ref={wrapRef} tabIndex="0" onKeyDown={keyboardNudge} aria-label="محرر مواضع عناصر بطاقة الهوية"><IDCardFace card={sample}/>{guides.x!==null&&<i className="idvisual-guide vertical" style={{left:`${guides.x/size.w*100}%`}}/>}{guides.y!==null&&<i className="idvisual-guide horizontal" style={{top:`${guides.y/size.h*100}%`}}/>}{Object.entries(boxes).map(([key,b])=>{const locked=isLocked(key);return <div key={key} className={`idvisual-box ${selectedElement===key?'selected':''} ${locked?'locked':''}`} style={{left:b.left,top:b.top,width:b.width,height:b.height}} onPointerDown={e=>begin(e,key,'move')} onClick={()=>onSelect?.(key)}><span>{locked?'🔒 ':''}{labels[key]||key}</span>{selectedElement===key&&!locked&&<i className="idvisual-resize" onPointerDown={e=>begin(e,key,'resize')}/>}</div>})}</div></div>
  <div className="idvisual-hint">Snap يلتقط الحواف والمراكز وعناصر التصميم الأخرى ضمن 0.85 مم، ومع عدم وجود محاذاة قريبة يستخدم شبكة 0.5 مم. الأسهم تحرك العنصر 0.5 مم وShift + سهم يحركه 2 مم.</div>
 </div>
}
