import React,{useEffect,useMemo,useState} from 'react';
import {Button,Card} from '../../components/UI.jsx';
import {idStudioApi} from './api.js';
import IDTemplateVisualEditor from './IDTemplateVisualEditor.jsx';
import './id-template-designer.css';

const clone=v=>JSON.parse(JSON.stringify(v||{}));
const baseDesigner={brand:{companyNameAr:'شركة الماهر الماسي للنقل',companyNameEn:'Al-Maher Al-Massy Transport Company',serviceLineAr:'لنقل الحجاج والمعتمرين',serviceLineEn:'For Hajj & Umrah Transport',sloganAr:'نُيسر دربك... لنطمئن قلبك',honorAr:'خدمة ضيوف الرحمن شرف لنا',honorEn:'SERVING THE GUESTS OF ALLAH IS AN HONOR FOR US'},assets:{logoUrl:'',backgroundUrl:'',makkahUrl:'',busUrl:'',signatureUrl:''},visibility:{logo:true,companyName:true,serviceLine:true,slogan:true,holderPhoto:true,holderName:true,jobTitle:true,department:true,employeeId:true,licenseNumber:true,season:true,qr:true,approval:true,bus:true,makkah:true,footer:true},theme:{primary:'#0a4f93',secondary:'#073566',accent:'#d3a746',surface:'#ffffff',text:'#0b2f5d'},layout:{portrait:{},landscape:{}}};
function normalize(template){const cfg=clone(template?.published_config&&Object.keys(template.published_config).length?template.published_config:template?.config||{});cfg.designer=cfg.designer||{};cfg.designer.brand={...baseDesigner.brand,...(cfg.designer.brand||{})};cfg.designer.assets={...baseDesigner.assets,...(cfg.designer.assets||{})};cfg.designer.visibility={...baseDesigner.visibility,...(cfg.designer.visibility||{})};cfg.designer.theme={...baseDesigner.theme,...(cfg.designer.theme||{})};cfg.designer.layout={portrait:{...(cfg.designer.layout?.portrait||{})},landscape:{...(cfg.designer.layout?.landscape||{})}};return cfg}
const visibilityLabels={logo:'الشعار',companyName:'اسم الشركة',serviceLine:'وصف النشاط',slogan:'الشعار النصي',holderPhoto:'صورة حامل البطاقة',holderName:'الاسم',jobTitle:'المسمى الوظيفي',department:'القسم',employeeId:'رقم البطاقة',licenseNumber:'الترخيص',season:'الموسم',qr:'QR',approval:'الاعتماد/التوقيع',bus:'صورة الباص',makkah:'صورة مكة/برج الساعة',footer:'النص السفلي'};
const assetLabels={logoUrl:'الشعار',backgroundUrl:'الخلفية',makkahUrl:'مكة / برج الساعة',busUrl:'الباص',signatureUrl:'التوقيع'};
const layoutLabels={logo:'الشعار',brand:'اسم الشركة',serviceLine:'وصف النشاط',makkah:'مكة / برج الساعة',photo:'صورة الموظف',person:'الاسم والمسمى',number:'رقم البطاقة',meta:'بيانات البطاقة',qr:'QR',approval:'الاعتماد',bus:'الباص',slogan:'الشعار النصي',footer:'النص السفلي'};
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(new Error('تعذر قراءة الصورة.'));r.readAsDataURL(file)})}
function numericOrBlank(value){if(value==='')return '';const n=Number(value);return Number.isFinite(n)?n:''}
function AssetEditor({asset,label,value,onChange,onUpload,uploading}){return <div className="idtemplate-asset"><div className="idtemplate-asset-preview">{value?<img src={value} alt=""/>:<span>لا توجد صورة</span>}</div><div className="idtemplate-asset-fields"><strong>{label}</strong><div className="idtemplate-asset-actions"><label className="idtemplate-file"><input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>onUpload(asset,e)}/><span>{uploading?'جاري الرفع...':'رفع صورة'}</span></label>{value&&<button type="button" className="idtemplate-clear" onClick={()=>onChange('')}>إزالة</button>}</div><input dir="ltr" placeholder="أو الصق رابط صورة" value={value||''} onChange={e=>onChange(e.target.value)}/></div></div>}

export default function IDTemplateDesigner({template,onDraftChange,onSaved,onNotice,onError}){
 const [config,setConfig]=useState(()=>normalize(template)),[orientation,setOrientation]=useState(template?.default_orientation==='portrait'?'portrait':'landscape'),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(''),[selectedElement,setSelectedElement]=useState('photo');
 useEffect(()=>{setConfig(normalize(template));setOrientation(template?.default_orientation==='portrait'?'portrait':'landscape');setUploading('');setSelectedElement('photo')},[template?.code,template?.published_version]);
 const d=config.designer,activeLayout=d.layout?.[orientation]?.[selectedElement]||{};
 const notify=(next,ori=orientation)=>onDraftChange?.(next,ori);
 const set=(section,key,value)=>setConfig(prev=>{const next=clone(prev);next.designer=next.designer||{};next.designer[section]={...(next.designer[section]||{}),[key]:value};notify(next);return next});
 function setOrientationLive(value){setOrientation(value);onDraftChange?.(config,value)}
 function patchLayout(element,patch){setConfig(prev=>{const next=clone(prev);next.designer=next.designer||{};next.designer.layout=next.designer.layout||{portrait:{},landscape:{}};next.designer.layout[orientation]=next.designer.layout[orientation]||{};next.designer.layout[orientation][element]={...(next.designer.layout[orientation][element]||{}),...patch};notify(next);return next})}
 function setLayoutField(key,value){setConfig(prev=>{const next=clone(prev);next.designer=next.designer||{};next.designer.layout=next.designer.layout||{portrait:{},landscape:{}};next.designer.layout[orientation]=next.designer.layout[orientation]||{};const current={...(next.designer.layout[orientation][selectedElement]||{})};const parsed=numericOrBlank(value);if(parsed==='')delete current[key];else current[key]=parsed;if(Object.keys(current).length)next.designer.layout[orientation][selectedElement]=current;else delete next.designer.layout[orientation][selectedElement];notify(next);return next})}
 function nudge(dx,dy){patchLayout(selectedElement,{x:(Number(activeLayout.x)||0)+dx,y:(Number(activeLayout.y)||0)+dy})}
 function resetElement(){setConfig(prev=>{const next=clone(prev);if(next.designer?.layout?.[orientation])delete next.designer.layout[orientation][selectedElement];notify(next);return next})}
 async function uploadAsset(asset,e){const file=e.target.files?.[0];e.target.value='';if(!file||!template?.code)return;if(file.size>5*1024*1024){onError?.('حجم الصورة أكبر من 5MB.');return}setUploading(asset);onError?.('');try{const dataUrl=await fileToDataUrl(file);const out=await idStudioApi.uploadTemplateAsset(template.code,asset,dataUrl);const url=out?.asset?.url;if(!url)throw new Error('تم رفع الملف لكن لم يصل رابط الصورة من الخادم.');set('assets',asset,url);onNotice?.(`تم رفع ${assetLabels[asset]||'الصورة'} وإضافتها للمعاينة. اضغط «نشر التصميم» لاعتمادها.`)}catch(err){onError?.(err.message)}finally{setUploading('')}}
 async function save(){if(!template?.code)return;setBusy(true);onError?.('');try{const out=await idStudioApi.saveTemplate(template.code,config,orientation);onNotice?.(`تم نشر تصميم ${template.name_ar} كإصدار v${out?.template?.published_version||''}.`);onSaved?.(out?.template)}catch(e){onError?.(e.message)}finally{setBusy(false)}}
 async function restore(){if(!template?.code||!window.confirm('سيتم استعادة التصميم الأصلي لهذا القالب ونشره كإصدار جديد. متابعة؟'))return;setBusy(true);onError?.('');try{const out=await idStudioApi.restoreTemplate(template.code);onNotice?.(`تمت استعادة التصميم الأصلي لقالب ${template.name_ar}.`);onSaved?.(out?.template)}catch(e){onError?.(e.message)}finally{setBusy(false)}}
 const version=useMemo(()=>Number(template?.published_version||template?.version||1),[template]);
 const maxW=orientation==='portrait'?53.98:85.6,maxH=orientation==='portrait'?85.6:53.98;
 return <Card className="idtemplate-designer">
  <div className="idtemplate-head"><div><h3>محرر تصميم البطاقة</h3><small>{template?.name_ar} · الإصدار المنشور v{version}</small></div><div className="idtemplate-head-actions"><Button onClick={restore} disabled={busy||!!uploading}>استعادة الأصل</Button><Button variant="primary" onClick={save} disabled={busy||!!uploading}>{busy?'جاري الحفظ...':'نشر التصميم'}</Button></div></div>
  <div className="idtemplate-orientation"><b>الاتجاه الافتراضي للقالب</b><button className={orientation==='portrait'?'active':''} onClick={()=>setOrientationLive('portrait')}>طولي</button><button className={orientation==='landscape'?'active':''} onClick={()=>setOrientationLive('landscape')}>عرضي</button></div>
  <details open><summary>المحرر البصري — سحب وتكبير وتصغير</summary><IDTemplateVisualEditor templateCode={template?.code||'makkah_luxury'} config={config} orientation={orientation} selectedElement={selectedElement} onSelect={setSelectedElement} onLayoutChange={patchLayout}/></details>
  <details open><summary>الهوية والنصوص</summary><div className="idtemplate-grid"><label>اسم الشركة بالعربية<input value={d.brand.companyNameAr} onChange={e=>set('brand','companyNameAr',e.target.value)}/></label><label>Company Name<input dir="ltr" value={d.brand.companyNameEn} onChange={e=>set('brand','companyNameEn',e.target.value)}/></label><label>وصف النشاط<input value={d.brand.serviceLineAr} onChange={e=>set('brand','serviceLineAr',e.target.value)}/></label><label>Service Line<input dir="ltr" value={d.brand.serviceLineEn} onChange={e=>set('brand','serviceLineEn',e.target.value)}/></label><label>الشعار النصي<input value={d.brand.sloganAr} onChange={e=>set('brand','sloganAr',e.target.value)}/></label><label>العبارة السفلية<input value={d.brand.honorAr} onChange={e=>set('brand','honorAr',e.target.value)}/></label><label className="wide">Footer English<input dir="ltr" value={d.brand.honorEn} onChange={e=>set('brand','honorEn',e.target.value)}/></label></div></details>
  <details open><summary>الشعار والصور</summary><div className="idtemplate-assets">{Object.entries(assetLabels).map(([asset,label])=><AssetEditor key={asset} asset={asset} label={label} value={d.assets[asset]||''} uploading={uploading===asset} onChange={value=>set('assets',asset,value)} onUpload={uploadAsset}/>)}</div><div className="idtemplate-help">JPG / PNG / WebP بحد أقصى 5MB. الرفع يغيّر المعاينة فورًا، ولا يصبح التصميم رسميًا إلا بعد الضغط على «نشر التصميم».</div></details>
  <details open><summary>المواضع والمقاسات الدقيقة</summary><div className="idtemplate-layout"><div className="idtemplate-element-list">{Object.entries(layoutLabels).map(([key,label])=><button type="button" key={key} className={selectedElement===key?'active':''} onClick={()=>setSelectedElement(key)}>{label}</button>)}</div><div className="idtemplate-layout-editor"><div className="idtemplate-layout-title"><strong>{layoutLabels[selectedElement]}</strong><span>{orientation==='portrait'?'طولي':'عرضي'} · {maxW} × {maxH} مم</span></div><div className="idtemplate-layout-grid"><label>X من اليسار (مم)<input type="number" step="0.1" min="0" max={maxW} value={activeLayout.x??''} placeholder="افتراضي" onChange={e=>setLayoutField('x',e.target.value)}/></label><label>Y من الأعلى (مم)<input type="number" step="0.1" min="0" max={maxH} value={activeLayout.y??''} placeholder="افتراضي" onChange={e=>setLayoutField('y',e.target.value)}/></label><label>العرض W (مم)<input type="number" step="0.1" min="1" max={maxW} value={activeLayout.w??''} placeholder="افتراضي" onChange={e=>setLayoutField('w',e.target.value)}/></label><label>الارتفاع H (مم)<input type="number" step="0.1" min="1" max={maxH} value={activeLayout.h??''} placeholder="افتراضي" onChange={e=>setLayoutField('h',e.target.value)}/></label><label>طبقة Z<input type="number" step="1" min="0" max="50" value={activeLayout.z??''} placeholder="افتراضي" onChange={e=>setLayoutField('z',e.target.value)}/></label><label>الشفافية %<input type="number" step="1" min="0" max="100" value={activeLayout.opacity===undefined?'':Math.round(Number(activeLayout.opacity)*100)} placeholder="100" onChange={e=>setLayoutField('opacity',e.target.value===''?'':Math.max(0,Math.min(1,Number(e.target.value)/100)))}/></label></div><div className="idtemplate-nudge"><span>تحريك 0.5 مم:</span><button type="button" onClick={()=>nudge(0,-.5)}>↑</button><button type="button" onClick={()=>nudge(-.5,0)}>←</button><button type="button" onClick={()=>nudge(.5,0)}>→</button><button type="button" onClick={()=>nudge(0,.5)}>↓</button><button type="button" className="reset" onClick={resetElement}>إرجاع مكان العنصر للقالب</button></div><div className="idtemplate-help compact">تقدر تستخدم السحب من المعاينة أو تدخل الأرقام يدويًا بالملليمتر. اترك أي خانة فارغة لاستخدام موضع القالب الأصلي.</div></div></div></details>
  <details><summary>الألوان</summary><div className="idtemplate-colors">{Object.entries({primary:'الأساسي',secondary:'الثانوي',accent:'الذهبي/Accent',surface:'الخلفية',text:'النص'}).map(([key,label])=><label key={key}><span>{label}</span><input type="color" value={d.theme[key]||baseDesigner.theme[key]} onChange={e=>set('theme',key,e.target.value)}/><input dir="ltr" value={d.theme[key]||''} onChange={e=>set('theme',key,e.target.value)}/></label>)}</div></details>
  <details><summary>إظهار وإخفاء العناصر</summary><div className="idtemplate-toggles">{Object.entries(visibilityLabels).map(([key,label])=><label key={key}><input type="checkbox" checked={d.visibility[key]!==false} onChange={e=>set('visibility',key,e.target.checked)}/><span>{label}</span></label>)}</div></details>
 </Card>
}
