import React,{useMemo,useState,useEffect,useRef} from 'react';
import IDTemplateVisualEditorLegacy from './IDTemplateVisualEditorLegacy.jsx';
import {idStudioApi} from './api.js';

const fields={photoPlaceholder:'نص مكان الصورة',holderNamePlaceholder:'اسم حامل البطاقة الافتراضي',jobTitlePlaceholder:'المسمى الوظيفي الافتراضي',idCardLabel:'عنوان رقم البطاقة',departmentLabel:'عنوان القسم',licenseLabel:'عنوان الترخيص',seasonLabel:'عنوان الموسم',expiryLabel:'عنوان الصلاحية',referenceCompanyLabel:'عنوان الشركة في جدول البيانات',referenceLicenseLabel:'عنوان الترخيص في جدول البيانات',referenceSeasonLabel:'عنوان الموسم في جدول البيانات',referenceEmployeeLabel:'عنوان رقم الموظف',qrLabel:'عبارة QR',approvalLabel:'عنوان الاعتماد',approvalAr:'نص الاعتماد العربي',approvalEn:'نص الاعتماد الإنجليزي',value1:'القيمة الأولى',value2:'القيمة الثانية',value3:'القيمة الثالثة',inactiveWatermark:'علامة البطاقة غير المعتمدة'};
const defaults={photoPlaceholder:'الصورة',holderNamePlaceholder:'اسم حامل البطاقة',jobTitlePlaceholder:'المسمى الوظيفي',idCardLabel:'ID CARD',departmentLabel:'القسم',licenseLabel:'الترخيص',seasonLabel:'الموسم',expiryLabel:'حتى',referenceCompanyLabel:'الشركة',referenceLicenseLabel:'الترخيص',referenceSeasonLabel:'الموسم',referenceEmployeeLabel:'رقم الموظف',qrLabel:'تحقق من البطاقة',approvalLabel:'اعتماد الإدارة',approvalAr:'معتمدة إلكترونيًا',approvalEn:'Electronic Verification',value1:'أمان',value2:'راحة',value3:'ثقة',inactiveWatermark:'غير معتمدة'};
const visibilityDefaults={logo:true,companyName:true,serviceLine:true,slogan:true,holderPhoto:true,holderName:true,jobTitle:true,department:true,employeeId:true,licenseNumber:true,season:true,qr:true,approval:true,bus:true,makkah:true,footer:true};
const visibilityLabels={logo:'الشعار',companyName:'اسم الشركة',serviceLine:'وصف النشاط',slogan:'الشعار النصي',holderPhoto:'صورة حامل البطاقة',holderName:'الاسم',jobTitle:'المسمى الوظيفي',department:'القسم',employeeId:'رقم البطاقة',licenseNumber:'الترخيص',season:'الموسم',qr:'QR',approval:'الاعتماد/التوقيع',bus:'صورة الباص',makkah:'مكة / برج الساعة',footer:'النص السفلي'};
const groups={
 brand:{label:'هوية الشركة',elements:['logo','brand','serviceLine'],visibility:['logo','companyName','serviceLine']},
 holder:{label:'بيانات حامل البطاقة',elements:['photo','person'],visibility:['holderPhoto','holderName','jobTitle']},
 card:{label:'بيانات البطاقة',elements:['number','meta','qr'],visibility:['employeeId','department','licenseNumber','season','qr']},
 visual:{label:'العناصر البصرية',elements:['makkah','bus','slogan','footer'],visibility:['makkah','bus','slogan','footer']},
 approval:{label:'الاعتماد',elements:['approval'],visibility:['approval']}
};
const elementLabels={logo:'الشعار',brand:'اسم الشركة',serviceLine:'وصف النشاط',makkah:'مكة / برج الساعة',photo:'صورة الموظف',person:'الاسم والمسمى',number:'رقم البطاقة',meta:'بيانات البطاقة',qr:'QR',approval:'الاعتماد',bus:'الباص',slogan:'الشعار النصي',footer:'النص السفلي'};
const emptyGroups=()=>({portrait:[],landscape:[]});
const clone=v=>JSON.parse(JSON.stringify(v||{}));
const uniq=a=>[...new Set(a)];
const half=v=>Math.round(v*2)/2;
const tenth=v=>Math.round(v*10)/10;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));

export default function IDTemplateVisualEditor(props){
 const {templateCode='makkah_luxury',config,orientation='portrait'}=props;
 const editorRef=useRef(null),dragRef=useRef(null);
 const buildCopy=()=>({...defaults,...(config?.designer?.frontCopy||{})});
 const buildVisibility=()=>({...visibilityDefaults,...(config?.designer?.visibility||{})});
 const buildManualGroups=()=>{const g=config?.designer?.frontGroups||{};return {portrait:Array.isArray(g.portrait)?clone(g.portrait):[],landscape:Array.isArray(g.landscape)?clone(g.landscape):[]}};
 const [frontCopy,setFrontCopy]=useState(buildCopy),[frontVisibility,setFrontVisibility]=useState(buildVisibility),[manualGroups,setManualGroups]=useState(buildManualGroups),[selectedKeys,setSelectedKeys]=useState([]),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[groupMessage,setGroupMessage]=useState('');
 useEffect(()=>{setFrontCopy(buildCopy());setFrontVisibility(buildVisibility());setManualGroups(buildManualGroups());setSelectedKeys([]);setDirty(false);setMessage('');setGroupMessage('')},[templateCode]);
 useEffect(()=>{setSelectedKeys([]);setGroupMessage('')},[orientation]);
 useEffect(()=>{const root=editorRef.current;if(!root)return;const apply=()=>{root.querySelectorAll('.idvisual-box').forEach(box=>box.classList.remove('multi-selected'));for(const key of selectedKeys){const box=findBox(key);if(box)box.classList.add('multi-selected')}};apply();const t=setTimeout(apply,80);return()=>clearTimeout(t)},[selectedKeys,orientation,frontVisibility,config]);
 useEffect(()=>()=>endMultiDrag(),[]);
 function sync(section,value){if(!config)return;config.designer=config.designer||{};config.designer[section]=clone(value)}
 const previewConfig=useMemo(()=>{const next=clone(config);next.designer=next.designer||{};next.designer.frontCopy=clone(frontCopy);next.designer.visibility=clone(frontVisibility);next.designer.frontGroups=clone(manualGroups);return next},[config,frontCopy,frontVisibility,manualGroups]);
 function touch(){setDirty(true);setMessage('')}
 function setField(key,value){setFrontCopy(prev=>{const next={...prev,[key]:value};sync('frontCopy',next);return next});touch()}
 function reset(){const next={...defaults};setFrontCopy(next);sync('frontCopy',next);touch()}
 function setVisibility(key,value){setFrontVisibility(prev=>{const next={...prev,[key]:value};sync('visibility',next);return next});touch()}
 function setGroupVisibility(group,value){for(const key of groups[group].visibility)setVisibility(key,value)}
 function patchGroupElement(element,patch){config.designer=config.designer||{};config.designer.layout=config.designer.layout||{portrait:{},landscape:{}};config.designer.layout[orientation]=config.designer.layout[orientation]||{};config.designer.layout[orientation][element]={...(config.designer.layout[orientation][element]||{}),...patch};props.onLayoutChange?.(element,patch)}
 function setGroupLock(group,locked){groups[group].elements.forEach(element=>patchGroupElement(element,{locked}));touch()}
 function setGroupLayer(group,toFront){groups[group].elements.forEach((element,index)=>patchGroupElement(element,{z:toFront?40+index:index}));touch()}
 function persistManualGroups(next){setManualGroups(next);sync('frontGroups',next);touch();const anchor=selectedKeys[0]||props.selectedElement||'photo';props.onLayoutChange?.(anchor,{})}
 function currentManualGroups(){return manualGroups?.[orientation]||[]}
 function groupFor(key){return currentManualGroups().find(g=>Array.isArray(g.members)&&g.members.includes(key))||null}
 function groupSelectionFor(key){const g=groupFor(key);return g?g.members.filter(Boolean):[key]}
 function makeGroup(){const members=uniq(selectedKeys).filter(k=>elementLabels[k]);if(members.length<2){setGroupMessage('اختار عنصرين على الأقل باستخدام Shift + ضغط على العناصر داخل البطاقة.');return}const rows=currentManualGroups().filter(g=>!g.members?.some(m=>members.includes(m)));const merged=uniq([...members,...currentManualGroups().filter(g=>g.members?.some(m=>members.includes(m))).flatMap(g=>g.members||[])]);rows.push({id:`grp_${Date.now().toString(36)}`,members:merged});const next=clone(manualGroups||emptyGroups());next[orientation]=rows;setSelectedKeys(merged);persistManualGroups(next);setGroupMessage(`تم تجميع ${merged.length} عناصر. الضغط والسحب على أي عنصر منها يحرك المجموعة كلها.`)}
 function ungroup(){const rows=currentManualGroups(),hit=rows.filter(g=>g.members?.some(m=>selectedKeys.includes(m)));if(!hit.length){setGroupMessage('العناصر المحددة ليست داخل مجموعة يدوية.');return}const removed=uniq(hit.flatMap(g=>g.members||[]));const next=clone(manualGroups||emptyGroups());next[orientation]=rows.filter(g=>!hit.includes(g));setSelectedKeys(removed);persistManualGroups(next);setGroupMessage(`تم فك ${hit.length} مجموعة، والعناصر ما زالت محددة.`)}
 function clearSelection(){setSelectedKeys([]);setGroupMessage('')}
 function isFrontFace(){const active=editorRef.current?.querySelector('.idvisual-face-tabs button.active');return !active||String(active.textContent||'').includes('الأمامي')}
 function keyFromBox(box){const text=String(box?.querySelector(':scope > span')?.textContent||'').replace('🔒','').trim();return Object.entries(elementLabels).find(([,label])=>text.endsWith(label))?.[0]||null}
 function findBox(key){const root=editorRef.current;if(!root)return null;return [...root.querySelectorAll('.idvisual-box')].find(box=>keyFromBox(box)===key)||null}
 function toggleSelection(key,additive){const block=groupSelectionFor(key);setSelectedKeys(prev=>{if(!additive)return block;const allSelected=block.every(x=>prev.includes(x));return allSelected?prev.filter(x=>!block.includes(x)):uniq([...prev,...block])})}
 function geometry(key){const box=findBox(key),card=editorRef.current?.querySelector('.idvisual-card-wrap .idcard-cr80');if(!box||!card)return null;const br=box.getBoundingClientRect(),cr=card.getBoundingClientRect(),wmm=orientation==='portrait'?53.98:85.6,hmm=orientation==='portrait'?85.6:53.98;return {x:(br.left-cr.left)*wmm/cr.width,y:(br.top-cr.top)*hmm/cr.height,w:br.width*wmm/cr.width,h:br.height*hmm/cr.height,sx:wmm/cr.width,sy:hmm/cr.height,locked:box.classList.contains('locked')}}
 function selectedGeometry(){const rows=selectedKeys.map(k=>[k,geometry(k)]).filter(([,g])=>g);if(rows.length<2){setGroupMessage('اختار عنصرين على الأقل للمحاذاة.');return null}if(rows.some(([,g])=>g.locked)){setGroupMessage('في عنصر مقفول داخل التحديد. افتحه أولًا قبل المحاذاة أو التوزيع.');return null}return rows}
 function alignSelection(mode){const rows=selectedGeometry();if(!rows)return;const left=Math.min(...rows.map(([,g])=>g.x)),right=Math.max(...rows.map(([,g])=>g.x+g.w)),top=Math.min(...rows.map(([,g])=>g.y)),bottom=Math.max(...rows.map(([,g])=>g.y+g.h)),cx=(left+right)/2,cy=(top+bottom)/2;for(const [key,g] of rows){let x=g.x,y=g.y;if(mode==='left')x=left;if(mode==='right')x=right-g.w;if(mode==='hcenter')x=cx-g.w/2;if(mode==='top')y=top;if(mode==='bottom')y=bottom-g.h;if(mode==='vcenter')y=cy-g.h/2;props.onLayoutChange?.(key,{x:tenth(x),y:tenth(y)})}touch();setGroupMessage(`تمت محاذاة ${rows.length} عناصر ${mode==='left'?'يسارًا':mode==='right'?'يمينًا':mode==='hcenter'?'في المنتصف أفقيًا':mode==='top'?'للأعلى':mode==='bottom'?'للأسفل':'في المنتصف رأسيًا'}.`)}
 function distributeSelection(axis){const rows=selectedKeys.map(k=>[k,geometry(k)]).filter(([,g])=>g);if(rows.length<3){setGroupMessage('التوزيع المتساوي يحتاج 3 عناصر على الأقل.');return}if(rows.some(([,g])=>g.locked)){setGroupMessage('في عنصر مقفول داخل التحديد. افتحه أولًا قبل التوزيع.');return}const sorted=[...rows].sort((a,b)=>axis==='x'?a[1].x-b[1].x:a[1].y-b[1].y);if(axis==='x'){const start=sorted[0][1].x,end=sorted.at(-1)[1].x+sorted.at(-1)[1].w,total=sorted.reduce((s,[,g])=>s+g.w,0),gap=Math.max(0,(end-start-total)/(sorted.length-1));let cursor=start;for(const [key,g] of sorted){props.onLayoutChange?.(key,{x:tenth(cursor)});cursor+=g.w+gap}}else{const start=sorted[0][1].y,end=sorted.at(-1)[1].y+sorted.at(-1)[1].h,total=sorted.reduce((s,[,g])=>s+g.h,0),gap=Math.max(0,(end-start-total)/(sorted.length-1));let cursor=start;for(const [key,g] of sorted){props.onLayoutChange?.(key,{y:tenth(cursor)});cursor+=g.h+gap}}touch();setGroupMessage(`تم توزيع ${rows.length} عناصر بمسافات متساوية ${axis==='x'?'أفقيًا':'رأسيًا'}.`)}
 function startMultiDrag(e,key,members){const geoms={};for(const member of members){const g=geometry(member);if(g)geoms[member]=g}const keys=Object.keys(geoms);if(keys.length<2)return false;if(keys.some(k=>geoms[k].locked)){setGroupMessage('في عنصر مقفول داخل التحديد. افتحه أولًا قبل تحريك المجموعة.');return true}const primary=geoms[key]||geoms[keys[0]],minDx=Math.max(...keys.map(k=>-geoms[k].x)),maxDx=Math.min(...keys.map(k=>{const maxW=orientation==='portrait'?53.98:85.6;return maxW-geoms[k].x-geoms[k].w})),minDy=Math.max(...keys.map(k=>-geoms[k].y)),maxDy=Math.min(...keys.map(k=>{const maxH=orientation==='portrait'?85.6:53.98;return maxH-geoms[k].y-geoms[k].h}));dragRef.current={startX:e.clientX,startY:e.clientY,primary,geoms,keys,minDx,maxDx,minDy,maxDy};window.addEventListener('pointermove',onMultiMove);window.addEventListener('pointerup',endMultiDrag,{once:true});window.addEventListener('pointercancel',endMultiDrag,{once:true});setGroupMessage(`تحريك ${keys.length} عناصر معًا — شبكة 0.5 مم.`);return true}
 function onMultiMove(e){const d=dragRef.current;if(!d)return;let dx=(e.clientX-d.startX)*d.primary.sx,dy=(e.clientY-d.startY)*d.primary.sy;dx=clamp(half(dx),d.minDx,d.maxDx);dy=clamp(half(dy),d.minDy,d.maxDy);for(const key of d.keys){const g=d.geoms[key];props.onLayoutChange?.(key,{x:tenth(g.x+dx),y:tenth(g.y+dy)})}touch()}
 function endMultiDrag(){dragRef.current=null;window.removeEventListener('pointermove',onMultiMove);window.removeEventListener('pointerup',endMultiDrag);window.removeEventListener('pointercancel',endMultiDrag)}
 function handlePointerDownCapture(e){if(!isFrontFace())return;const box=e.target.closest?.('.idvisual-box');if(!box||!editorRef.current?.contains(box))return;const key=keyFromBox(box);if(!key)return;const block=groupSelectionFor(key);if(e.shiftKey){e.preventDefault();e.stopPropagation();toggleSelection(key,true);setGroupMessage('تحديد متعدد مفعل. اختار عناصر أخرى ثم استخدم التجميع أو المحاذاة أو التوزيع.');return}const selectedBlock=selectedKeys.includes(key)&&selectedKeys.length>1?selectedKeys:block;setSelectedKeys(selectedBlock);if(selectedBlock.length>1){e.preventDefault();e.stopPropagation();startMultiDrag(e,key,selectedBlock)}}
 function handleKeyDownCapture(e){if(!isFrontFace()||selectedKeys.length<2||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;const geoms=selectedKeys.map(k=>[k,geometry(k)]).filter(([,g])=>g);if(geoms.some(([,g])=>g.locked)){setGroupMessage('في عنصر مقفول داخل التحديد. افتحه أولًا قبل التحريك.');return}e.preventDefault();e.stopPropagation();let dx=0,dy=0,step=e.shiftKey?2:.5;if(e.key==='ArrowLeft')dx=-step;if(e.key==='ArrowRight')dx=step;if(e.key==='ArrowUp')dy=-step;if(e.key==='ArrowDown')dy=step;const maxW=orientation==='portrait'?53.98:85.6,maxH=orientation==='portrait'?85.6:53.98;dx=clamp(dx,Math.max(...geoms.map(([,g])=>-g.x)),Math.min(...geoms.map(([,g])=>maxW-g.x-g.w)));dy=clamp(dy,Math.max(...geoms.map(([,g])=>-g.y)),Math.min(...geoms.map(([,g])=>maxH-g.y-g.h)));for(const [key,g] of geoms)props.onLayoutChange?.(key,{x:tenth(g.x+dx),y:tenth(g.y+dy)});touch()}
 async function save(){if(!dirty||saving)return;setSaving(true);setMessage('');try{const next=clone(config);next.designer=next.designer||{};next.designer.frontCopy=clone(frontCopy);next.designer.visibility=clone(frontVisibility);next.designer.frontGroups=clone(manualGroups);const out=await idStudioApi.saveTemplate(templateCode,next,orientation,'front_face_align_distribute_publish');setDirty(false);setMessage(`تم نشر إعدادات الوجه الأمامي كإصدار v${out?.template?.published_version||''}. البطاقات القديمة لن تتغير.`)}catch(e){setMessage(e.message||'تعذر حفظ إعدادات الوجه الأمامي')}finally{setSaving(false)}}
 return <div ref={editorRef} style={{display:'grid',gap:10}} onPointerDownCapture={handlePointerDownCapture} onKeyDownCapture={handleKeyDownCapture}>
  <style>{`.idvisual-box.multi-selected{outline:2px solid #d3a746!important;outline-offset:2px;background:rgba(211,167,70,.09)!important}.idvisual-box.multi-selected>span{display:block!important;background:#8b6a1f!important}`}</style>
  <details open className="idvisual-back-panel"><summary style={{cursor:'pointer',fontSize:11,fontWeight:900,color:'#1f3550'}}>نصوص الوجه الأمامي القابلة للتعديل</summary><div className="idvisual-back-copy-grid">{Object.entries(fields).map(([key,label])=><label key={key}><span>{label}</span><input dir={key.endsWith('En')||key==='idCardLabel'?'ltr':undefined} value={frontCopy[key]??''} onChange={e=>setField(key,e.target.value)}/></label>)}</div><button type="button" className="idvisual-reset-typo" onClick={reset}>إرجاع نصوص الأمام الافتراضية</button></details>
  <details open className="idvisual-back-panel"><summary style={{cursor:'pointer',fontSize:11,fontWeight:900,color:'#1f3550'}}>إظهار وإخفاء عناصر الوجه الأمامي</summary><div className="idvisual-back-toggles">{Object.entries(visibilityLabels).map(([key,label])=><label key={key}><input type="checkbox" checked={frontVisibility[key]!==false} onChange={e=>setVisibility(key,e.target.checked)}/><span>{label}</span></label>)}</div></details>
  <details open className="idvisual-back-panel"><summary style={{cursor:'pointer',fontSize:11,fontWeight:900,color:'#1f3550'}}>تجميع وترتيب عناصر الوجه الأمامي</summary><div style={{display:'grid',gap:8}}>{Object.entries(groups).map(([key,g])=><div key={key} style={{display:'grid',gridTemplateColumns:'minmax(150px,1fr) repeat(6,auto)',gap:6,alignItems:'center',padding:7,border:'1px solid #edf0f4',borderRadius:8}}><strong style={{fontSize:10,color:'#31445d'}}>{g.label}</strong><button type="button" className="idvisual-reset-typo" onClick={()=>setGroupVisibility(key,true)}>إظهار</button><button type="button" className="idvisual-reset-typo" onClick={()=>setGroupVisibility(key,false)}>إخفاء</button><button type="button" className="idvisual-reset-typo" onClick={()=>setGroupLock(key,true)}>قفل</button><button type="button" className="idvisual-reset-typo" onClick={()=>setGroupLock(key,false)}>فتح</button><button type="button" className="idvisual-reset-typo" onClick={()=>setGroupLayer(key,true)}>للواجهة</button><button type="button" className="idvisual-reset-typo" onClick={()=>setGroupLayer(key,false)}>للخلفية</button></div>)}</div><div className="idvisual-hint">المجموعة الجاهزة تطبق الإظهار/الإخفاء والقفل وترتيب الطبقات دفعة واحدة.</div></details>
  <details open className="idvisual-back-panel"><summary style={{cursor:'pointer',fontSize:11,fontWeight:900,color:'#1f3550'}}>اختيار متعدد · Group / Align / Distribute</summary><div style={{display:'flex',gap:7,flexWrap:'wrap',alignItems:'center'}}><span className="idvisual-selected">{selectedKeys.length?`${selectedKeys.length} عنصر محدد`:'لا يوجد تحديد متعدد'}</span><button type="button" className="idvisual-reset-typo" disabled={selectedKeys.length<2} onClick={makeGroup}>تجميع المحدد</button><button type="button" className="idvisual-reset-typo" disabled={!selectedKeys.length} onClick={ungroup}>فك التجميع</button><button type="button" className="idvisual-reset-typo" disabled={!selectedKeys.length} onClick={clearSelection}>مسح التحديد</button></div>{selectedKeys.length>0&&<div style={{display:'flex',gap:5,flexWrap:'wrap'}}>{selectedKeys.map(key=><span key={key} style={{fontSize:9,fontWeight:900,padding:'4px 7px',borderRadius:999,background:'#fff7e2',border:'1px solid #ead29a',color:'#7b570b'}}>{elementLabels[key]||key}</span>)}</div>}<div style={{display:'grid',gap:7,paddingTop:4}}><strong style={{fontSize:10,color:'#31445d'}}>محاذاة العناصر المحددة</strong><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button type="button" className="idvisual-reset-typo" disabled={selectedKeys.length<2} onClick={()=>alignSelection('left')}>يسار</button><button type="button" className="idvisual-reset-typo" disabled={selectedKeys.length<2} onClick={()=>alignSelection('hcenter')}>منتصف أفقي</button><button type="button" className="idvisual-reset-typo" disabled={selectedKeys.length<2} onClick={()=>alignSelection('right')}>يمين</button><button type="button" className="idvisual-reset-typo" disabled={selectedKeys.length<2} onClick={()=>alignSelection('top')}>أعلى</button><button type="button" className="idvisual-reset-typo" disabled={selectedKeys.length<2} onClick={()=>alignSelection('vcenter')}>منتصف رأسي</button><button type="button" className="idvisual-reset-typo" disabled={selectedKeys.length<2} onClick={()=>alignSelection('bottom')}>أسفل</button></div><strong style={{fontSize:10,color:'#31445d'}}>توزيع المسافات بالتساوي</strong><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button type="button" className="idvisual-reset-typo" disabled={selectedKeys.length<3} onClick={()=>distributeSelection('x')}>توزيع أفقي</button><button type="button" className="idvisual-reset-typo" disabled={selectedKeys.length<3} onClick={()=>distributeSelection('y')}>توزيع رأسي</button></div></div><div className="idvisual-hint">اضغط Shift مع الضغط على عناصر البطاقة لاختيار أكثر من عنصر. تقدر تجمعها أو تحاذيها يمين/يسار/منتصف/أعلى/أسفل، ومع 3 عناصر أو أكثر توزع المسافات بينها بالتساوي. السحب والأسهم يفضلوا يحركوا التحديد كله معًا.</div>{groupMessage&&<div className="idvisual-message success">{groupMessage}</div>}</details>
  <div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}><button type="button" className="idvisual-reset-typo" disabled={!dirty||saving} onClick={save}>{saving?'جاري النشر...':'نشر إعدادات الأمام'}</button>{message&&<div className={`idvisual-message ${message.startsWith('تم ')?'success':'error'}`} style={{flex:'1 1 260px'}}>{message}</div>}</div>
  <IDTemplateVisualEditorLegacy {...props} config={previewConfig}/>
 </div>
}
