import React,{useEffect,useState} from 'react';
import './id-verify.css';

const STATUS={active:'فعالة',draft:'مسودة',pending_approval:'بانتظار الاعتماد',suspended:'موقوفة',expired:'منتهية',lost:'مفقودة',revoked:'ملغاة',reissued:'أعيد إصدارها'};
export default function IDVerify({token,go}){
  const [state,setState]=useState({loading:true,data:null,error:''});
  useEffect(()=>{let alive=true;async function run(){try{const r=await fetch(`/api/id-studio/verify?token=${encodeURIComponent(token||'')}`,{cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error||'تعذر التحقق من البطاقة.');if(alive)setState({loading:false,data,error:''})}catch(e){if(alive)setState({loading:false,data:null,error:e.message})}}run();return()=>{alive=false}},[token]);
  const c=state.data?.card;
  return <div className="idverify-page"><div className="idverify-card"><img src="/almaher-logo.jpeg" alt="الماهر الماسي" className="idverify-logo"/><h1>التحقق من بطاقة الشركة</h1><p className="idverify-sub">شركة الماهر الماسي لنقل الحجاج والمعتمرين</p>{state.loading&&<div className="idverify-loading">جاري التحقق من البطاقة...</div>}{state.error&&<div className="idverify-invalid"><strong>تعذر التحقق</strong><span>{state.error}</span></div>}{c&&<><div className={`idverify-result ${state.data.valid?'valid':'invalid'}`}><strong>{state.data.valid?'✓ بطاقة فعالة':'! البطاقة غير فعالة'}</strong><span>الحالة الحالية: {STATUS[c.status]||c.status}</span></div><div className="idverify-grid"><b>رقم البطاقة</b><span dir="ltr">{c.card_number}</span><b>الاسم</b><span>{c.name_ar}</span><b>المسمى الوظيفي</b><span>{c.job_title_ar||'—'}</span><b>القسم</b><span>{c.department_ar||'—'}</span><b>تاريخ الإصدار</b><span>{c.issue_date||'—'}</span><b>تاريخ الانتهاء</b><span>{c.expiry_date||'—'}</span></div><small className="idverify-time">آخر تحقق: {new Date(state.data.verified_at).toLocaleString('ar-SA')}</small></>}{go&&<button className="idverify-home" onClick={()=>go('/')}>العودة للرئيسية</button>}<div className="idverify-note">تعرض هذه الصفحة بيانات تحقق محدودة فقط. الحالة الإلكترونية الحالية هي المرجع لصلاحية البطاقة.</div></div></div>
}
