import React,{useEffect,useState} from 'react';
import {Badge,Card,Loading} from '../../components/UI.jsx';
import './id-studio.css';

const labels={active:'فعالة',suspended:'موقوفة',expired:'منتهية',lost:'مفقودة',revoked:'ملغاة',reissued:'تم استبدالها',draft:'مسودة',pending_approval:'بانتظار الاعتماد'};
export default function VerifyCard({token,go}){
 const [state,setState]=useState({loading:true,error:'',card:null});
 useEffect(()=>{let alive=true;(async()=>{try{const r=await fetch(`/api/id/verify?token=${encodeURIComponent(token||'')}`,{headers:{Accept:'application/json'},cache:'no-store'});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||'تعذر التحقق من البطاقة.');if(alive)setState({loading:false,error:'',card:b.card})}catch(e){if(alive)setState({loading:false,error:e.message,card:null})}})();return()=>{alive=false}},[token]);
 return <div className="idverify-page"><Card className="idverify-card"><img src="/almaher-logo.jpeg" alt="الماهر الماسي" className="idverify-logo"/><h1>التحقق من بطاقة الشركة</h1>{state.loading?<Loading text="جاري التحقق من البطاقة..."/>:state.error?<div className="idstudio-error">{state.error}</div>:<><div className={`idverify-status ${state.card?.status||''}`}><Badge>{labels[state.card?.status]||state.card?.status}</Badge></div>{state.card?.photo_url&&<img className="idverify-photo" src={state.card.photo_url} alt="صورة حامل البطاقة"/>}<h2>{state.card?.name_ar||'—'}</h2>{state.card?.name_en&&<div dir="ltr" className="idverify-en">{state.card.name_en}</div>}<p>{state.card?.job_title_ar||'—'}{state.card?.department_ar?` · ${state.card.department_ar}`:''}</p><div className="idverify-meta"><div><span>رقم البطاقة</span><b dir="ltr">{state.card?.card_number}</b></div><div><span>الشركة</span><b>شركة الماهر الماسي</b></div><div><span>تاريخ الإصدار</span><b>{state.card?.issue_date||'—'}</b></div><div><span>تاريخ الانتهاء</span><b>{state.card?.expiry_date||'غير محدد'}</b></div></div>{state.card?.status!=='active'&&<div className="idstudio-warning">هذه البطاقة ليست في حالة فعالة حاليًا. يرجى الرجوع إلى إدارة الشركة عند الحاجة.</div>}</>}</Card><button className="idverify-home" onClick={()=>go('/login')}>الدخول إلى نظام الماهر</button></div>
}
