import React,{useEffect,useMemo,useState} from 'react';
import {Armchair,Hotel,Printer,RefreshCw,ScanLine,Search,RotateCcw,Users} from 'lucide-react';
import {useAppData} from '../../core/AppDataContext.jsx';
import {api} from '../../lib/api.js';
import {Badge,Button,Card,PageHeader,Select,Field,Loading,ErrorBox,Table,Input} from '../../components/UI.jsx';
import {money,tripDisplay} from '../../lib/format.js';

const s=v=>String(v??'');
export default function Operations({initialTrip,go}){
 const {data}=useAppData();const [tripId,setTripId]=useState(initialTrip||''),[x,setX]=useState(null),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[branch,setBranch]=useState(''),[housing,setHousing]=useState('');
 const branchMap=useMemo(()=>new Map(data.branches.map(b=>[s(b.id),b.name||b.branch_name||b.id])),[data.branches]);
 async function load(id=tripId){if(!id)return;setBusy(true);setX(null);setErr('');try{setX(await api.admin({action:'trip_operational_data',trip_id:id}))}catch(e){setErr(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(initialTrip)load(initialTrip)},[initialTrip]);
 const bmap=useMemo(()=>new Map((x?.bookings||[]).map(b=>[s(b.id),b])),[x]);
 const rows=useMemo(()=>{let a=x?.passengers||[];if(q.trim()){const k=q.trim().toLowerCase();a=a.filter(p=>{const b=bmap.get(s(p.booking_id));return [p.full_name,p.identity_number,p.phone,p.nationality,b?.booking_number,b?.customer_name].some(v=>s(v).toLowerCase().includes(k))})}if(branch)a=a.filter(p=>s(bmap.get(s(p.booking_id))?.branch_id)===branch);if(housing)a=a.filter(p=>s(bmap.get(s(p.booking_id))?.accommodation_type)===housing);return a},[x,q,branch,housing,bmap]);
 const stats=useMemo(()=>{const bookings=x?.bookings||[],pax=x?.passengers||[];return {bookings:bookings.length,pax:pax.filter(p=>s(p.status)!=='cancelled').length,male:pax.filter(p=>['male','ذكر'].includes(s(p.gender).toLowerCase())).length,female:pax.filter(p=>['female','أنثى'].includes(s(p.gender).toLowerCase())).length,paid:bookings.reduce((n,b)=>n+(b.financial_visible?Number(b.paid_amount||0):0),0)}},[x]);
 const cols=[{key:'passenger_order',label:'#'},{key:'full_name',label:'الراكب',render:p=><div><b>{p.full_name||'—'}</b><div className="muted-small">{p.nationality||'—'}</div></div>},{key:'identity_number',label:'الهوية'},{key:'phone',label:'الجوال'},{key:'booking',label:'الحجز',render:p=>bmap.get(s(p.booking_id))?.booking_number||'—'},{key:'branch',label:'فرع الحجز',render:p=>branchMap.get(s(bmap.get(s(p.booking_id))?.branch_id))||'—'},{key:'housing',label:'السكن',render:p=>{const b=bmap.get(s(p.booking_id));return b?.accommodation_label||b?.accommodation_type||'—'}},{key:'boarding',label:'نقطة الصعود',render:p=>{const b=bmap.get(s(p.booking_id)),sn=b?.snapshot||{};return sn.boardingPoint||b?.boarding_point||'—'}},{key:'paid',label:'المدفوع',render:p=>{const b=bmap.get(s(p.booking_id));return b?.financial_visible?money(b.paid_amount):<Badge>محجوب</Badge>}}];
 return <><PageHeader title="التشغيل" subtitle="كشف الرحلة المشترك عبر الفروع مع حجب مالية الفروع غير المصرح بها" actions={x&&<Button onClick={()=>window.print()}><Printer size={16}/> طباعة الكشف</Button>}/><Card><div className="operations-selector"><Field label="الرحلة"><Select value={tripId} onChange={e=>{setTripId(e.target.value);setX(null)}}><option value="">اختر رحلة</option>{data.trips.map(t=><option key={t.id} value={t.id}>{tripDisplay(t)}</option>)}</Select></Field><Button variant="primary" disabled={!tripId||busy} onClick={()=>load()}>{busy?'جاري التحميل...':'فتح مركز التشغيل'}</Button>{tripId&&<Button onClick={()=>go('/trips/'+tripId)}>مركز الرحلة</Button>}</div></Card><ErrorBox error={err}/>{busy&&!x&&<Loading/>}{x&&<><div className="stats-grid operations-stats"><Mini icon={<Users/>} label="الحجوزات" value={stats.bookings}/><Mini icon={<Users/>} label="المسافرون" value={stats.pax}/><Mini label="رجال" value={stats.male}/><Mini label="نساء" value={stats.female}/></div><Card className="no-print"><div className="operation-links"><Button onClick={()=>go('/seats?trip='+tripId)}><Armchair size={16}/> المقاعد</Button><Button onClick={()=>go('/housing?trip='+tripId)}><Hotel size={16}/> التسكين</Button><Button onClick={()=>go('/scanner?trip='+tripId)}><ScanLine size={16}/> QR</Button><Button onClick={()=>go('/returns?trip='+tripId)}><RotateCcw size={16}/> العودة</Button><Button onClick={()=>load()}><RefreshCw size={16}/> تحديث</Button></div><div className="operation-filters"><div className="filterbar"><Search size={17}/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم، هوية، جوال أو حجز"/></div><Select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">كل فروع التشغيل</option>{[...new Set((x.bookings||[]).map(b=>s(b.branch_id)))].filter(Boolean).map(id=><option key={id} value={id}>{branchMap.get(id)||id}</option>)}</Select><Select value={housing} onChange={e=>setHousing(e.target.value)}><option value="">كل أنواع السكن</option><option value="none">بدون سكن</option><option value="shared">مشترك</option><option value="private">خاص</option></Select><Badge>{rows.length} راكب</Badge></div></Card><Card className="printable operations-sheet"><div className="print-only operation-print-head"><h2>كشف تشغيل الرحلة — {tripDisplay(x.trip)}</h2><p>{x.trip?.departure_time||''}</p></div><div className="card-title"><h3>كشف الركاب</h3><span>المالية: {x.finance_scope==='all'?'كاملة':'فرعك فقط'}</span></div><Table rows={rows} columns={cols}/></Card></>}</>;
}
function Mini({icon,label,value}){return <Card className="stat-card">{icon&&<div className="stat-icon">{icon}</div>}<div><span>{label}</span><strong>{value}</strong></div></Card>}
