import React,{useEffect,useMemo,useState} from 'react';
import {BellRing,Play,Plus,RefreshCw,Send,FileText,Workflow} from 'lucide-react';
import {useAppData} from '../../core/AppDataContext.jsx';
import {useAuth} from '../../core/AuthContext.jsx';
import {api} from '../../lib/api.js';
import {allOps,has} from '../../lib/permissions.js';
import {Badge,Button,Card,ErrorBox,Field,Input,Loading,Modal,PageHeader,Select,Table,Textarea} from '../../components/UI.jsx';
import {dateTime} from '../../lib/format.js';

const s=v=>String(v??'');
export default function Notifications(){
 const {user}=useAuth(),{data:app}=useAppData();const [data,setData]=useState(null),[tab,setTab]=useState('notifications'),[modal,setModal]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[runResult,setRunResult]=useState(null);
 async function load(){setError('');try{setData(await api.module('notifications'))}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 const branches=app.branches||[],trips=app.trips||[];const branchMap=useMemo(()=>new Map(branches.map(b=>[s(b.id),b.name||b.branch_name||b.id])),[branches]);
 async function saveNotification(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),old=modal?.row;const row={trip_id:f.trip_id||null,branch_id:f.branch_id||app.scope?.branch_id||null,channel:f.channel,recipient:f.recipient,language_code:f.language_code||'ar',template_key:f.template_key||null,payload:{manual:true,message:f.message||''},scheduled_at:f.scheduled_at?new Date(f.scheduled_at).toISOString():new Date().toISOString(),status:f.status||'scheduled'};setBusy(true);try{await api.moduleWrite(old?{action:'update',table:'notifications',id:old.id,row}:{action:'insert',table:'notifications',row});await load();setModal(null)}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function saveRule(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),old=modal?.row;const row={trip_id:f.trip_id||null,branch_id:f.branch_id||null,trigger_key:f.trigger_key,offset_minutes:f.offset_minutes===''?null:Number(f.offset_minutes),direction:f.direction||null,channel:f.channel||'whatsapp',template_key:f.template_key,mode:f.mode||'automatic',audience_rule:{scope:f.audience_scope||'trip'},active:f.active==='true'};setBusy(true);try{await api.moduleWrite(old?{action:'update',table:'notification_rules',id:old.id,row}:{action:'insert',table:'notification_rules',row});await load();setModal(null)}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function saveTemplate(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),old=modal?.row;const row={template_key:f.template_key,language_code:f.language_code||'ar',channel:f.channel||'whatsapp',subject:f.subject||null,body:f.body,active:f.active==='true',version_no:Number(f.version_no||1)};setBusy(true);try{await api.moduleWrite(old?{action:'update',table:'message_templates',id:old.id,row}:{action:'insert',table:'message_templates',row});await load();setModal(null)}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function runScheduler(){setBusy(true);setRunResult(null);try{const r=await api.mega('scheduler_run');setRunResult(r);await load()}catch(x){setError(x.message)}finally{setBusy(false)}}
 const ns=data?.notifications||[],rules=data?.notification_rules||[],templates=data?.message_templates||[];
 const notifCols=[{key:'created_at',label:'أنشئ',render:r=>dateTime(r.created_at)},{key:'channel',label:'القناة'},{key:'recipient',label:'المستلم'},{key:'template_key',label:'القالب',render:r=>r.template_key||'يدوي'},{key:'scheduled_at',label:'الموعد',render:r=>r.scheduled_at?dateTime(r.scheduled_at):'—'},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='failed'?'red':['sent','delivered'].includes(r.status)?'green':r.status==='scheduled'?'orange':'blue'}>{r.status||'—'}</Badge>},{key:'attempts',label:'المحاولات'},{key:'error_text',label:'الخطأ',render:r=>r.error_text?<span className="error-inline">{r.error_text}</span>:'—'}];
 const ruleCols=[{key:'trigger_key',label:'المشغل'},{key:'trip',label:'الرحلة',render:r=>trips.find(t=>s(t.id)===s(r.trip_id))?.trip_code||'كل الرحلات'},{key:'branch',label:'الفرع',render:r=>branchMap.get(s(r.branch_id))||'عام'},{key:'channel',label:'القناة'},{key:'template_key',label:'القالب'},{key:'offset_minutes',label:'الإزاحة',render:r=>r.offset_minutes==null?'—':`${r.offset_minutes} دقيقة`},{key:'mode',label:'النمط'},{key:'active',label:'الحالة',render:r=><Badge tone={r.active===false?'red':'green'}>{r.active===false?'موقوف':'نشط'}</Badge>},{key:'action',label:'',render:r=><Button onClick={()=>setModal({type:'rule',row:r})}>تعديل</Button>}];
 const templateCols=[{key:'template_key',label:'المفتاح'},{key:'channel',label:'القناة'},{key:'language_code',label:'اللغة'},{key:'version_no',label:'الإصدار'},{key:'body',label:'النص',render:r=><span className="template-preview">{r.body}</span>},{key:'active',label:'الحالة',render:r=><Badge tone={r.active===false?'red':'green'}>{r.active===false?'موقوف':'نشط'}</Badge>},{key:'action',label:'',render:r=><Button onClick={()=>setModal({type:'template',row:r})}>تعديل</Button>}];
 return <><PageHeader title="الإشعارات والأتمتة" subtitle="طابور الرسائل والقواعد والقوالب؛ فشل المزود لا يوقف الحجز" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث</Button>}/><ErrorBox error={error}/><Card><div className="notification-actions"><div><BellRing size={21}/><b>{ns.filter(n=>n.status==='scheduled').length} مجدول · {ns.filter(n=>n.status==='failed').length} فشل</b></div><div className="finance-actions"><Button variant="primary" onClick={()=>setModal({type:'notification'})}><Send size={16}/> رسالة/تنبيه</Button>{has(user,'automation')&&<Button onClick={()=>setModal({type:'rule'})}><Workflow size={16}/> قاعدة</Button>}<Button onClick={()=>setModal({type:'template'})}><FileText size={16}/> قالب</Button><Button onClick={runScheduler} disabled={busy}><Play size={16}/> تشغيل المجدول</Button></div></div>{runResult&&<div className="success-box">تم تشغيل المجدول بنجاح.</div>}</Card><div className="tabs"><button className={tab==='notifications'?'active':''} onClick={()=>setTab('notifications')}>الطابور<span>{ns.length}</span></button><button className={tab==='rules'?'active':''} onClick={()=>setTab('rules')}>القواعد<span>{rules.length}</span></button><button className={tab==='templates'?'active':''} onClick={()=>setTab('templates')}>القوالب<span>{templates.length}</span></button></div>{!data&&!error?<Loading/>:<Card><Table rows={tab==='notifications'?ns:tab==='rules'?rules:templates} columns={tab==='notifications'?notifCols:tab==='rules'?ruleCols:templateCols}/></Card>}
 <Modal open={modal?.type==='notification'} onClose={()=>setModal(null)} title="إضافة رسالة إلى الطابور"><form className="form-grid" onSubmit={saveNotification}><Field label="القناة"><Select name="channel" defaultValue="whatsapp"><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option><option value="email">Email</option><option value="push">Push</option></Select></Field><Field label="المستلم"><Input name="recipient" required placeholder="رقم الجوال أو البريد"/></Field><Field label="الفرع"><Select name="branch_id" defaultValue={app.scope?.branch_id||''} disabled={!allOps(user)}><option value="">عام</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name||b.branch_name}</option>)}</Select>{!allOps(user)&&<input type="hidden" name="branch_id" value={app.scope?.branch_id||''}/>}</Field><Field label="الرحلة"><Select name="trip_id"><option value="">بدون رحلة</option>{trips.map(t=><option key={t.id} value={t.id}>{t.trip_code}</option>)}</Select></Field><Field label="القالب"><Select name="template_key"><option value="">رسالة يدوية</option>{templates.filter(t=>t.active!==false).map(t=><option key={t.id} value={t.template_key}>{t.template_key} — {t.channel}</option>)}</Select></Field><Field label="اللغة"><Select name="language_code" defaultValue="ar"><option value="ar">العربية</option><option value="en">English</option></Select></Field><Field label="موعد الإرسال"><Input type="datetime-local" name="scheduled_at" defaultValue={toLocal(new Date())}/></Field><Field label="الحالة"><Select name="status" defaultValue="scheduled"><option value="scheduled">مجدولة</option><option value="manual">يدوية</option><option value="draft">مسودة</option></Select></Field><Field label="نص يدوي / ملاحظات"><Textarea name="message"/></Field><Actions busy={busy} close={()=>setModal(null)}/></form></Modal>
 <Modal open={modal?.type==='rule'} onClose={()=>setModal(null)} title={modal?.row?'تعديل قاعدة':'قاعدة إشعار جديدة'}><form className="form-grid" onSubmit={saveRule}><Field label="المشغل"><Select name="trigger_key" defaultValue={modal?.row?.trigger_key||'booking_created'}><option value="booking_created">إنشاء حجز</option><option value="trip_departure">موعد الانطلاق</option><option value="return_meeting">تجمع العودة</option><option value="return_departure">انطلاق العودة</option><option value="housing_checkin">التسكين</option><option value="payment_due">استحقاق دفع</option></Select></Field><Field label="القالب"><Input name="template_key" defaultValue={modal?.row?.template_key||''} required/></Field><Field label="القناة"><Select name="channel" defaultValue={modal?.row?.channel||'whatsapp'}><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option><option value="email">Email</option><option value="push">Push</option></Select></Field><Field label="إزاحة بالدقائق"><Input type="number" name="offset_minutes" defaultValue={modal?.row?.offset_minutes??''} placeholder="-60 = قبل بساعة"/></Field><Field label="الاتجاه"><Select name="direction" defaultValue={modal?.row?.direction||''}><option value="">عام</option><option value="outbound">ذهاب</option><option value="return">عودة</option></Select></Field><Field label="الفرع"><Select name="branch_id" defaultValue={modal?.row?.branch_id||''}><option value="">عام</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name||b.branch_name}</option>)}</Select></Field><Field label="الرحلة"><Select name="trip_id" defaultValue={modal?.row?.trip_id||''}><option value="">كل الرحلات</option>{trips.map(t=><option key={t.id} value={t.id}>{t.trip_code}</option>)}</Select></Field><Field label="النمط"><Select name="mode" defaultValue={modal?.row?.mode||'automatic'}><option value="automatic">تلقائي</option><option value="manual">يدوي</option><option value="disabled">معطل</option></Select></Field><Field label="الجمهور"><Select name="audience_scope" defaultValue={modal?.row?.audience_rule?.scope||'trip'}><option value="trip">ركاب الرحلة</option><option value="booking">الحجز</option><option value="branch">الفرع</option></Select></Field><Field label="الحالة"><Select name="active" defaultValue={modal?.row?.active===false?'false':'true'}><option value="true">نشطة</option><option value="false">موقوفة</option></Select></Field><Actions busy={busy} close={()=>setModal(null)}/></form></Modal>
 <Modal open={modal?.type==='template'} onClose={()=>setModal(null)} title={modal?.row?'تعديل قالب':'قالب جديد'} wide><form className="form-grid" onSubmit={saveTemplate}><Field label="مفتاح القالب"><Input name="template_key" defaultValue={modal?.row?.template_key||''} required placeholder="booking_confirmed"/></Field><Field label="القناة"><Select name="channel" defaultValue={modal?.row?.channel||'whatsapp'}><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option><option value="email">Email</option><option value="push">Push</option></Select></Field><Field label="اللغة"><Select name="language_code" defaultValue={modal?.row?.language_code||'ar'}><option value="ar">العربية</option><option value="en">English</option></Select></Field><Field label="الإصدار"><Input type="number" min="1" name="version_no" defaultValue={modal?.row?.version_no||1}/></Field><Field label="العنوان"><Input name="subject" defaultValue={modal?.row?.subject||''}/></Field><Field label="الحالة"><Select name="active" defaultValue={modal?.row?.active===false?'false':'true'}><option value="true">نشط</option><option value="false">موقوف</option></Select></Field><Field label="نص القالب"><Textarea name="body" defaultValue={modal?.row?.body||''} required rows={8} placeholder="مرحبًا {{customer_name}} ..."/></Field><Actions busy={busy} close={()=>setModal(null)}/></form></Modal></>;
}
function toLocal(v){const d=v instanceof Date?v:new Date(v);if(Number.isNaN(d.getTime()))return'';const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
function Actions({busy,close}){return <div className="modal-actions"><Button type="button" onClick={close}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>{busy?'جاري الحفظ...':'حفظ'}</Button></div>}
