import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,Printer,Hotel,Armchair,ScanLine,Users,RotateCcw,RefreshCw,BusFront} from 'lucide-react';
import {api} from '../../lib/api.js';
import {Badge,Card,PageHeader,Button,Loading,ErrorBox,Table} from '../../components/UI.jsx';
import {money} from '../../lib/format.js';

const s=v=>String(v??'');
export default function TripCenter({id,go}){
 const [x,setX]=useState(null),[extras,setExtras]=useState({seats:null,housing:null}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{const core=await api.admin({action:'trip_operational_data',trip_id:id});setX(core);const [seats,housing]=await Promise.all([api.module('seats').catch(()=>null),api.module('housing').catch(()=>null)]);setExtras({seats,housing})}catch(e){setError(e.message)}finally{setBusy(false)}}useEffect(()=>{load()},[id]);
 const passengerBooking=useMemo(()=>new Map((x?.bookings||[]).map(b=>[s(b.id),b])),[x]);const tripVehicleIds=useMemo(()=>new Set((extras.seats?.trip_vehicles||[]).filter(v=>s(v.trip_id)===s(id)).map(v=>s(v.id))),[extras,id]);const assignedSeats=(extras.seats?.seat_assignments||[]).filter(a=>tripVehicleIds.has(s(a.trip_vehicle_id))&&['assigned','hold'].includes(s(a.status)));const tripHotelIds=useMemo(()=>new Set((extras.housing?.trip_hotels||[]).filter(v=>s(v.trip_id)===s(id)).map(v=>s(v.id))),[extras,id]);const roomIds=useMemo(()=>new Set((extras.housing?.hotel_rooms||[]).filter(r=>tripHotelIds.has(s(r.trip_hotel_id))).map(r=>s(r.id))),[extras,tripHotelIds]);const housed=(extras.housing?.room_assignments||[]).filter(a=>roomIds.has(s(a.hotel_room_id))&&s(a.status)!=='released');
 if(!x&&!error)return <Loading text="تحميل مركز الرحلة..."/>;
 const pax=(x?.passengers||[]).filter(p=>s(p.status)!=='cancelled'),bookings=x?.bookings||[];const dues=bookings.reduce((n,b)=>n+(b.financial_visible?Math.max(0,Number(b.total_price||0)-Number(b.paid_amount||0)):0),0);
 return <><PageHeader title={x?.trip?.trip_code||'مركز الرحلة'} subtitle={`${x?.trip?.from_city||x?.trip?.origin||'—'} ← ${x?.trip?.to_city||x?.trip?.destination||'—'} · ${x?.trip?.departure_date||''} ${x?.trip?.departure_time||''}`} actions={<><Button onClick={()=>go('/trips')}><ArrowRight size={16}/> رجوع</Button><Button onClick={load} disabled={busy}><RefreshCw size={16}/> تحديث</Button><Button onClick={()=>window.print()}><Printer size={16}/> طباعة الكشف</Button></>}/><ErrorBox error={error}/>{x&&<><div className="stats-grid trip-center-stats"><Mini icon={<Users/>} label="الركاب" value={pax.length}/><Mini icon={<Armchair/>} label="مقاعد موزعة" value={extras.seats?assignedSeats.length:'—'}/><Mini icon={<Hotel/>} label="تم تسكينهم" value={extras.housing?housed.length:'—'}/><Mini label="متبقي ظاهر" value={money(dues)}/></div><div className="mini-actions"><button onClick={()=>go('/operations?trip='+id)}><Users/> الركاب والتشغيل</button><button onClick={()=>go('/seats?trip='+id)}><Armchair/> المقاعد</button><button onClick={()=>go('/housing?trip='+id)}><Hotel/> التسكين</button><button onClick={()=>go('/scanner?trip='+id)}><ScanLine/> QR</button><button onClick={()=>go('/returns?trip='+id)}><RotateCcw/> العودة</button><button onClick={()=>go('/fleet')}><BusFront/> الأسطول</button></div><Card className="printable"><div className="card-title"><h3>كشف ركاب الرحلة</h3><span>المالية: {x.finance_scope==='all'?'كل الفروع':'الفرع الخاص فقط'}</span></div><Table rows={pax} columns={[{key:'passenger_order',label:'#'},{key:'full_name',label:'المسافر'},{key:'identity_number',label:'الهوية'},{key:'phone',label:'الجوال'},{key:'booking',label:'الحجز',render:p=>passengerBooking.get(s(p.booking_id))?.booking_number||'—'},{key:'housing',label:'السكن',render:p=>passengerBooking.get(s(p.booking_id))?.accommodation_label||passengerBooking.get(s(p.booking_id))?.accommodation_type||'—'},{key:'paid',label:'المدفوع',render:p=>{const b=passengerBooking.get(s(p.booking_id));return b?.financial_visible?money(b.paid_amount):<Badge>محجوب</Badge>}}]}/></Card></>}</>;
}
function Mini({icon,label,value}){return <Card className="stat-card">{icon&&<div className="stat-icon">{icon}</div>}<div><span>{label}</span><strong>{value}</strong></div></Card>}
