import React,{useState} from 'react';
import {useLanguage} from '../core/LanguageContext.jsx';

const PUBLIC_TEXT={
 ar:{systemDesc:'نظام إدارة الرحلات والحجوزات والتسكين والتشغيل',trainingNotice:'وضع التدريب — جميع البيانات الحالية تجريبية وليست تشغيلًا فعليًا',identity:'اسم المستخدم / الجوال / البريد',password:'كلمة المرور',login:'دخول النظام',loggingIn:'جاري الدخول...',portal:'بوابة العميل / استعلام عن الحجز',trainingEnv:'بيئة التدريب',productionEnv:'تشغيل فعلي',version:'الإصدار',customerPortal:'بوابة العميل',staffLogin:'دخول الموظفين',lookupTitle:'استعلام عن حجزك',lookupHelp:'أدخل رقم الحجز ورقم الجوال أو الهوية لعرض بيانات رحلتك وتذكرتك بأمان.',bookingNo:'رقم الحجز',bookingExample:'مثال: 13466587',phoneOrId:'رقم الجوال أو الهوية',phoneOrIdExample:'05xxxxxxxx أو رقم الهوية',verifyHelp:'نستخدم هذه البيانات للتحقق من أن الحجز يخصك.',showBooking:'عرض الحجز',lookingUp:'جاري الاستعلام...',printPdf:'طباعة / PDF',customer:'العميل',journeyType:'نوع الرحلة',housing:'السكن',remaining:'المتبقي',passengers:'المسافرون',total:'الإجمالي',paid:'المدفوع',branchLocation:'موقع الفرع',tagline:'رحلتك معنا... بخدمة أوضح وراحة أكبر'},
 en:{systemDesc:'Trip, booking, housing and operations management system',trainingNotice:'Training mode — all current data is sample data and not live operations',identity:'Username / mobile / email',password:'Password',login:'Sign in',loggingIn:'Signing in...',portal:'Customer portal / Booking lookup',trainingEnv:'Training environment',productionEnv:'Production',version:'Version',customerPortal:'Customer Portal',staffLogin:'Staff login',lookupTitle:'Check your booking',lookupHelp:'Enter your booking number and mobile number or ID to securely view your trip and ticket.',bookingNo:'Booking number',bookingExample:'Example: 13466587',phoneOrId:'Mobile number or ID',phoneOrIdExample:'05xxxxxxxx or ID number',verifyHelp:'We use this information to verify that the booking belongs to you.',showBooking:'Show booking',lookingUp:'Checking...',printPdf:'Print / PDF',customer:'Customer',journeyType:'Trip type',housing:'Accommodation',remaining:'Remaining',passengers:'Passengers',total:'Total',paid:'Paid',branchLocation:'Branch location',tagline:'Travel with us with clearer service and greater comfort'},
 tr:{systemDesc:'Sefer, rezervasyon, konaklama ve operasyon yönetim sistemi',trainingNotice:'Eğitim modu — mevcut veriler deneme verisidir ve canlı operasyon değildir',identity:'Kullanıcı adı / telefon / e-posta',password:'Şifre',login:'Giriş yap',loggingIn:'Giriş yapılıyor...',portal:'Müşteri portalı / Rezervasyon sorgulama',trainingEnv:'Eğitim ortamı',productionEnv:'Canlı',version:'Sürüm',customerPortal:'Müşteri Portalı',staffLogin:'Personel girişi',lookupTitle:'Rezervasyonunu sorgula',lookupHelp:'Seyahat ve bilet bilgilerini güvenle görmek için rezervasyon numarası ve telefon veya kimlik numarasını gir.',bookingNo:'Rezervasyon numarası',bookingExample:'Örnek: 13466587',phoneOrId:'Telefon veya kimlik numarası',phoneOrIdExample:'05xxxxxxxx veya kimlik',verifyHelp:'Bu bilgileri rezervasyonun size ait olduğunu doğrulamak için kullanırız.',showBooking:'Rezervasyonu göster',lookingUp:'Sorgulanıyor...',printPdf:'Yazdır / PDF',customer:'Müşteri',journeyType:'Sefer türü',housing:'Konaklama',remaining:'Kalan',passengers:'Yolcular',total:'Toplam',paid:'Ödenen',branchLocation:'Şube konumu',tagline:'Daha açık hizmet ve daha fazla konforla yolculuk'},
 hi:{systemDesc:'यात्रा, बुकिंग, आवास और संचालन प्रबंधन प्रणाली',trainingNotice:'प्रशिक्षण मोड — वर्तमान डेटा नमूना है, वास्तविक संचालन नहीं',identity:'यूज़रनेम / मोबाइल / ईमेल',password:'पासवर्ड',login:'लॉग इन',loggingIn:'लॉग इन हो रहा है...',portal:'ग्राहक पोर्टल / बुकिंग खोज',trainingEnv:'प्रशिक्षण वातावरण',productionEnv:'लाइव संचालन',version:'संस्करण',customerPortal:'ग्राहक पोर्टल',staffLogin:'कर्मचारी लॉगिन',lookupTitle:'अपनी बुकिंग देखें',lookupHelp:'अपनी यात्रा और टिकट सुरक्षित रूप से देखने के लिए बुकिंग नंबर और मोबाइल या आईडी दर्ज करें।',bookingNo:'बुकिंग नंबर',bookingExample:'उदाहरण: 13466587',phoneOrId:'मोबाइल नंबर या आईडी',phoneOrIdExample:'05xxxxxxxx या आईडी नंबर',verifyHelp:'हम इस जानकारी से पुष्टि करते हैं कि बुकिंग आपकी है।',showBooking:'बुकिंग दिखाएँ',lookingUp:'जाँच हो रही है...',printPdf:'प्रिंट / PDF',customer:'ग्राहक',journeyType:'यात्रा प्रकार',housing:'आवास',remaining:'शेष',passengers:'यात्री',total:'कुल',paid:'भुगतान',branchLocation:'शाखा स्थान',tagline:'हमारे साथ अधिक स्पष्ट सेवा और आरामदायक यात्रा'},
 it:{systemDesc:'Sistema di gestione viaggi, prenotazioni, alloggi e operazioni',trainingNotice:'Modalità formazione — i dati attuali sono di prova e non operativi',identity:'Utente / cellulare / email',password:'Password',login:'Accedi',loggingIn:'Accesso...',portal:'Portale cliente / Ricerca prenotazione',trainingEnv:'Ambiente formazione',productionEnv:'Produzione',version:'Versione',customerPortal:'Portale Cliente',staffLogin:'Accesso personale',lookupTitle:'Consulta la tua prenotazione',lookupHelp:'Inserisci numero prenotazione e cellulare o documento per vedere viaggio e biglietto in sicurezza.',bookingNo:'Numero prenotazione',bookingExample:'Esempio: 13466587',phoneOrId:'Cellulare o documento',phoneOrIdExample:'05xxxxxxxx o documento',verifyHelp:'Usiamo questi dati per verificare che la prenotazione sia tua.',showBooking:'Mostra prenotazione',lookingUp:'Ricerca...',printPdf:'Stampa / PDF',customer:'Cliente',journeyType:'Tipo viaggio',housing:'Alloggio',remaining:'Residuo',passengers:'Passeggeri',total:'Totale',paid:'Pagato',branchLocation:'Posizione filiale',tagline:'Viaggia con noi con un servizio più chiaro e più comfort'},
 fr:{systemDesc:'Système de gestion des voyages, réservations, hébergement et opérations',trainingNotice:'Mode formation — les données actuelles sont des données de test, pas de production',identity:'Utilisateur / mobile / e-mail',password:'Mot de passe',login:'Connexion',loggingIn:'Connexion...',portal:'Portail client / Recherche de réservation',trainingEnv:'Environnement de formation',productionEnv:'Production',version:'Version',customerPortal:'Portail Client',staffLogin:'Connexion employés',lookupTitle:'Consulter votre réservation',lookupHelp:'Saisissez le numéro de réservation et le mobile ou la pièce d’identité pour afficher votre voyage et votre billet en toute sécurité.',bookingNo:'Numéro de réservation',bookingExample:'Exemple : 13466587',phoneOrId:'Mobile ou pièce d’identité',phoneOrIdExample:'05xxxxxxxx ou numéro d’identité',verifyHelp:'Ces informations servent à vérifier que la réservation vous appartient.',showBooking:'Afficher la réservation',lookingUp:'Recherche...',printPdf:'Imprimer / PDF',customer:'Client',journeyType:'Type de voyage',housing:'Hébergement',remaining:'Restant',passengers:'Passagers',total:'Total',paid:'Payé',branchLocation:'Localisation de l’agence',tagline:'Voyagez avec nous avec un service plus clair et plus de confort'},
 ur:{systemDesc:'سفر، بکنگ، رہائش اور آپریشنز مینجمنٹ سسٹم',trainingNotice:'تربیتی موڈ — موجودہ تمام ڈیٹا نمونہ ہے، حقیقی آپریشن نہیں',identity:'صارف نام / موبائل / ای میل',password:'پاس ورڈ',login:'لاگ اِن',loggingIn:'لاگ اِن ہو رہا ہے...',portal:'کسٹمر پورٹل / بکنگ تلاش',trainingEnv:'تربیتی ماحول',productionEnv:'عملی نظام',version:'ورژن',customerPortal:'کسٹمر پورٹل',staffLogin:'عملہ لاگ اِن',lookupTitle:'اپنی بکنگ دیکھیں',lookupHelp:'اپنے سفر اور ٹکٹ کی معلومات محفوظ طریقے سے دیکھنے کے لیے بکنگ نمبر اور موبائل یا شناخت درج کریں۔',bookingNo:'بکنگ نمبر',bookingExample:'مثال: 13466587',phoneOrId:'موبائل یا شناختی نمبر',phoneOrIdExample:'05xxxxxxxx یا شناختی نمبر',verifyHelp:'یہ معلومات بکنگ کی ملکیت کی تصدیق کے لیے استعمال ہوتی ہیں۔',showBooking:'بکنگ دکھائیں',lookingUp:'تلاش جاری ہے...',printPdf:'پرنٹ / PDF',customer:'کسٹمر',journeyType:'سفر کی قسم',housing:'رہائش',remaining:'باقی',passengers:'مسافر',total:'کل',paid:'ادا شدہ',branchLocation:'برانچ کا مقام',tagline:'ہمارے ساتھ زیادہ واضح خدمت اور زیادہ آرام کے ساتھ سفر کریں'}
};

export function usePublicText(){const {language}=useLanguage();const x=PUBLIC_TEXT[language]||PUBLIC_TEXT.ar;return k=>x[k]||PUBLIC_TEXT.ar[k]||k}

export default function PublicLanguageSwitcher({className=''}){
 const {language,setLanguage,languages}=useLanguage();const [open,setOpen]=useState(false);const current=languages.find(x=>x[0]===language)||languages[0];
 return <div className={`public-language-switcher ${className}`} style={{position:'relative',display:'inline-flex',zIndex:50}}><button type="button" onClick={()=>setOpen(v=>!v)} aria-label="Language" style={{display:'inline-flex',alignItems:'center',gap:8,border:'1px solid #d8dee8',borderRadius:999,padding:'8px 12px',background:'#fff',fontWeight:800,cursor:'pointer',minWidth:82,justifyContent:'center'}}><span>{current[3]||current[0].toUpperCase()}</span><span style={{fontSize:18}}>{current[4]||'🌐'}</span></button>{open&&<div style={{position:'absolute',top:'calc(100% + 6px)',insetInlineEnd:0,background:'#fff',border:'1px solid #d8dee8',borderRadius:14,boxShadow:'0 12px 30px rgba(15,23,42,.16)',padding:6,minWidth:165}}>{languages.map(x=><button key={x[0]} type="button" onClick={()=>{setLanguage(x[0]);setOpen(false)}} style={{width:'100%',display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,border:0,background:x[0]===language?'#f1f5f9':'transparent',padding:'9px 10px',borderRadius:9,cursor:'pointer'}}><span>{x[1]}</span><span>{x[3]} {x[4]}</span></button>)}</div>}</div>
}
