import React,{useMemo,useState} from 'react';
import {LayoutDashboard,BusFront,ClipboardList,Users,Hotel,Armchair,Truck,WalletCards,Receipt,ScanLine,HeartHandshake,FileText,BellRing,RotateCcw,ShieldCheck,BarChart3,Code2,LogOut,PanelRightClose,PanelRightOpen,Search,Globe2} from 'lucide-react';
import {useAuth} from '../core/AuthContext.jsx';
import {useAppData} from '../core/AppDataContext.jsx';
import {has} from '../lib/permissions.js';

const items=[
 ['/','الرئيسية',LayoutDashboard,[]],['/trips','الرحلات',BusFront,['trips','operations','viewBookings']],['/bookings','الحجوزات',ClipboardList,['viewBookings','editBookings','branchBooking']],['/passengers','الركاب',Users,['viewBookings','editPassenger']],['/housing','التسكين',Hotel,['housing']],['/seats','المقاعد',Armchair,['seats','operations']],['/fleet','الأسطول',Truck,['fleet','vehicles','trips']],['/finance','المالية',WalletCards,['finance','payments','expenses','refunds']],['/refunds','الاسترداد',Receipt,['refunds','refund_request','refund_approve','refund_complete']],['/operations','التشغيل',ShieldCheck,['operations','manifest','housingManifest','viewBookings']],['/scanner','QR والصعود',ScanLine,['scanner','qr','operations']],['/crm','CRM',HeartHandshake,['crm','customers']],['/documents','المستندات',FileText,['documents','editPassenger']],['/notifications','الإشعارات',BellRing,['notifications','automation']],['/returns','العودة',RotateCcw,['return','returns','operations']],['/staff','الموظفون',Users,['manageUsers']],['/reports','التقارير',BarChart3,['reports','printReports']],['/customer','بوابة العميل',Globe2,[]],['/developer','المطور والنظام',Code2,['developer']]
];
const text=v=>String(v??'').toLowerCase();
export default function Shell({children,route,go}){
 const {user,logout}=useAuth();const {data}=useAppData();const [collapsed,setCollapsed]=useState(false),[q,setQ]=useState(''),[focus,setFocus]=useState(false);
 const visible=useMemo(()=>items.filter(([, , ,perms])=>!perms.length||perms.some(k=>has(user,k))),[user]);
 const bookingMap=useMemo(()=>new Map((data.bookings||[]).map(b=>[String(b.id),b])),[data.bookings]);
 const searchResults=useMemo(()=>{const k=text(q).trim();if(k.length<2)return[];const out=[];for(const b of data.bookings||[]){if([b.booking_number,b.customer_name,b.customer_phone,b.customer_identity].some(v=>text(v).includes(k)))out.push({key:`b-${b.id}`,title:`حجز ${b.booking_number}`,sub:`${b.customer_name||''} · ${b.customer_phone||''}`,path:`/bookings/${encodeURIComponent(b.booking_number)}`})}for(const p of data.passengers||[]){if([p.full_name,p.identity_number,p.phone,p.nationality].some(v=>text(v).includes(k))){const b=bookingMap.get(String(p.booking_id));out.push({key:`p-${p.id}`,title:`مسافر — ${p.full_name||''}`,sub:`${p.identity_number||''}${b?.booking_number?` · حجز ${b.booking_number}`:''}`,path:b?`/bookings/${encodeURIComponent(b.booking_number)}`:'/passengers'})}}for(const t of data.trips||[]){if([t.trip_code,t.code,t.name,t.from_city,t.origin,t.to_city,t.destination,t.departure_date].some(v=>text(v).includes(k)))out.push({key:`t-${t.id}`,title:`رحلة ${t.trip_code||t.code||''}`,sub:`${t.from_city||t.origin||''} ← ${t.to_city||t.destination||''} · ${t.departure_date||''}`,path:`/trips/${encodeURIComponent(t.id)}`})}return out.slice(0,10)},[q,data,bookingMap]);
 async function signOut(){await logout();go('/login',{replace:true})}
 function choose(r){setQ('');setFocus(false);go(r.path)}
 return <div className={`app-shell ${collapsed?'collapsed':''}`}><aside className="sidebar"><div className="brand"><div className="brand-mark">م</div><div className="brand-copy"><strong>الماهر الماسي</strong><span>منصة التشغيل</span></div></div><nav>{visible.map(([p,label,Icon])=><button key={p} className={route===p||route.startsWith(p+'/')?'active':''} onClick={()=>go(p)} title={label}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="side-bottom"><button onClick={()=>setCollapsed(x=>!x)}>{collapsed?<PanelRightOpen size={19}/>:<PanelRightClose size={19}/>}<span>تصغير القائمة</span></button><button onClick={signOut}><LogOut size={19}/><span>تسجيل الخروج</span></button></div></aside><div className="content-shell"><header className="topbar"><div className="global-search-wrap"><div className="global-search"><Search size={18}/><input value={q} placeholder="ابحث عن حجز، راكب، رحلة..." onChange={e=>setQ(e.target.value)} onFocus={()=>setFocus(true)} onBlur={()=>setTimeout(()=>setFocus(false),160)} onKeyDown={e=>{if(e.key==='Enter'&&searchResults[0])choose(searchResults[0]);if(e.key==='Escape'){setQ('');setFocus(false)}}}/></div>{focus&&q.trim().length>=2&&<div className="global-results">{searchResults.length?searchResults.map(r=><button key={r.key} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(r)}><b>{r.title}</b><span>{r.sub}</span></button>):<div className="global-empty">لا توجد نتائج ضمن صلاحياتك الحالية.</div>}</div>}</div><div className="user-chip"><div><strong>{user?.name||user?.username||'المستخدم'}</strong><span>{user?.role||'—'}</span></div><div className="avatar">{String(user?.name||'م').trim().charAt(0)}</div><button className="top-logout" onClick={signOut} title="تسجيل الخروج"><LogOut size={18}/></button></div></header><main>{children}</main></div></div>;
}
