import React,{useEffect,useMemo,useState} from 'react';
import {LayoutDashboard,BusFront,ClipboardList,Users,Hotel,Armchair,Truck,WalletCards,Receipt,ScanLine,HeartHandshake,FileText,BellRing,RotateCcw,ShieldCheck,BarChart3,Code2,LogOut,PanelRightClose,PanelRightOpen,Search,Globe2,Building2,Handshake,CheckSquare2} from 'lucide-react';
import {useAuth} from '../core/AuthContext.jsx';
import {useAppData} from '../core/AppDataContext.jsx';
import {useLanguage} from '../core/LanguageContext.jsx';
import {has} from '../lib/permissions.js';
import {branchLogo} from '../lib/branding.js';
import {api} from '../lib/api.js';

const items=[
 ['/','home',LayoutDashboard,[]],['/trips','trips',BusFront,['trips','operations','viewBookings']],['/bookings','bookings',ClipboardList,['viewBookings','editBookings','branchBooking']],['/passengers','passengers',Users,['viewBookings','editPassenger']],['/housing','housing',Hotel,['housing']],['/seats','seats',Armchair,['seats','operations']],['/fleet','fleet',Truck,['fleet','vehicles','trips']],['/finance','finance',WalletCards,['finance','payments','expenses','refunds']],['/refunds','refunds',Receipt,['refunds','refund_request','refund_approve','refund_complete']],['/operations','operations',ShieldCheck,['operations','manifest','housingManifest','viewBookings']],['/scanner','scanner',ScanLine,['scanner','qr','operations']],['/crm','crm',HeartHandshake,['crm','customers']],['/documents','documents',FileText,['documents','editPassenger']],['/notifications','notifications',BellRing,['notifications','automation']],['/returns','returns',RotateCcw,['return','returns','operations']],['/branches','branches',Building2,['manageBranches']],['/partners','partners',Handshake,['finance','agents','suppliers']],['/workflow','workflow',CheckSquare2,['operations','approvals','tasks']],['/staff','staff',Users,['manageUsers']],['/reports','reports',BarChart3,['reports','printReports']],['/customer','customer',Globe2,[]],['/developer','developer',Code2,['developer_console_access']]
];
const text=v=>String(v??'').toLowerCase();
export default function Shell({children,route,go}){
 const {user,logout}=useAuth();const {data}=useAppData();const {language,setLanguage,languages,t}=useLanguage();const [collapsed,setCollapsed]=useState(false),[q,setQ]=useState(''),[focus,setFocus]=useState(false),[developer,setDeveloper]=useState({display_name:'Mohamed Abdelrahman Hassan',title:'مطور النظام',phone:'00966509444960'});
 useEffect(()=>{api.mega('public_brand_profile',{},'GET').then(x=>{if(x?.profile)setDeveloper(d=>({...d,...x.profile}))}).catch(()=>{})},[]);
 const visible=useMemo(()=>items.filter(([, , ,perms])=>!perms.length||perms.some(k=>has(user,k))),[user]);
 const activeBranch=useMemo(()=>{const bid=user?.branch_id||user?.home_branch_id||data.scope?.branch_id;return (data.branches||[]).find(b=>String(b.id)===String(bid))||null},[user,data.branches,data.scope]);
 const accountMode=user?.permissions?._accountMode==='production'?'production':'training';
 const bookingMap=useMemo(()=>new Map((data.bookings||[]).map(b=>[String(b.id),b])),[data.bookings]);
 const searchResults=useMemo(()=>{const k=text(q).trim();if(k.length<2)return[];const out=[];for(const b of data.bookings||[]){if([b.booking_number,b.customer_name,b.customer_phone,b.customer_identity].some(v=>text(v).includes(k)))out.push({key:`b-${b.id}`,title:`حجز ${b.booking_number}`,sub:`${b.customer_name||''} · ${b.customer_phone||''}`,path:`/bookings/${encodeURIComponent(b.booking_number)}`})}for(const p of data.passengers||[]){if([p.full_name,p.identity_number,p.phone,p.nationality].some(v=>text(v).includes(k))){const b=bookingMap.get(String(p.booking_id));out.push({key:`p-${p.id}`,title:`مسافر — ${p.full_name||''}`,sub:`${p.identity_number||''}${b?.booking_number?` · حجز ${b.booking_number}`:''}`,path:b?`/bookings/${encodeURIComponent(b.booking_number)}`:'/passengers'})}}for(const tr of data.trips||[]){if([tr.trip_code,tr.code,tr.name,tr.from_city,tr.origin,tr.to_city,tr.destination,tr.departure_date].some(v=>text(v).includes(k)))out.push({key:`t-${tr.id}`,title:`رحلة ${tr.trip_code||tr.code||''}`,sub:`${tr.from_city||tr.origin||''} ← ${tr.to_city||tr.destination||''} · ${tr.departure_date||''}`,path:`/trips/${encodeURIComponent(tr.id)}`})}return out.slice(0,10)},[q,data,bookingMap]);
 async function signOut(){await logout();go('/login',{replace:true})}
 function choose(r){setQ('');setFocus(false);go(r.path)}
 return <div className={`app-shell ${collapsed?'collapsed':''}`}><aside className="sidebar"><div className="brand"><img className="brand-logo" src={branchLogo(activeBranch)} alt={activeBranch?.name||'الماهر الماسي'}/><div className="brand-copy"><strong>{activeBranch?.name||'الماهر الماسي'}</strong><span>منصة التشغيل</span></div></div><nav>{visible.map(([p,key,Icon])=>{const label=t(key);return <button key={p} className={route===p||route.startsWith(p+'/')?'active':''} onClick={()=>go(p)} title={label}><Icon size={19}/><span>{label}</span></button>})}</nav><div className="side-bottom"><button onClick={()=>setCollapsed(x=>!x)}>{collapsed?<PanelRightOpen size={19}/>:<PanelRightClose size={19}/>}<span>تصغير القائمة</span></button><button onClick={signOut}><LogOut size={19}/><span>{t('logout')}</span></button></div></aside><div className="content-shell"><header className="topbar"><div className="global-search-wrap"><div className="global-search"><Search size={18}/><input value={q} placeholder={t('search')} onChange={e=>setQ(e.target.value)} onFocus={()=>setFocus(true)} onBlur={()=>setTimeout(()=>setFocus(false),160)} onKeyDown={e=>{if(e.key==='Enter'&&searchResults[0])choose(searchResults[0]);if(e.key==='Escape'){setQ('');setFocus(false)}}}/></div>{focus&&q.trim().length>=2&&<div className="global-results">{searchResults.length?searchResults.map(r=><button key={r.key} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(r)}><b>{r.title}</b><span>{r.sub}</span></button>):<div className="global-empty">لا توجد نتائج ضمن صلاحياتك الحالية.</div>}</div>}</div><div className="user-chip"><select aria-label="لغة النظام" value={language} onChange={e=>setLanguage(e.target.value)} style={{width:'auto',minWidth:105,padding:'7px 9px'}}>{languages.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select><div><strong>{user?.name||user?.username||'المستخدم'}</strong><span>{user?.role||'—'}{activeBranch?.name?` · ${activeBranch.name}`:''} · {accountMode==='production'?t('production'):t('training')}</span></div><div className="avatar">{String(user?.name||'م').trim().charAt(0)}</div><button className="top-logout" onClick={signOut} title={t('logout')}><LogOut size={18}/></button></div></header>{accountMode==='training'&&<div className="training-banner">وضع التدريب — هذا الحساب مخصص للتدريب والبيانات التجريبية</div>}<main>{children}</main><footer className="system-developer-footer"><span>تطوير وإدارة النظام</span><strong>{developer.display_name||'Mohamed Abdelrahman Hassan'}</strong>{developer.title&&<span>{developer.title}</span>}{developer.phone&&<span dir="ltr">{developer.phone}</span>}</footer></div></div>;
}
