import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
export const Card=({children,className=''})=><section className={`card ${className}`}>{children}</section>;
export const PageHeader=({title,subtitle,actions})=><div className="page-head"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</div>;
export const Button=({children,variant='secondary',className='',...p})=><button className={`btn ${variant} ${className}`} {...p}>{children}</button>;
export const Badge=({children,tone='blue'})=><span className={`badge ${tone}`}>{children}</span>;
export const Empty=({title='لا توجد بيانات',text='لم يتم العثور على سجلات لعرضها.'})=><div className="empty"><div className="empty-icon">◇</div><strong>{title}</strong><span>{text}</span></div>;
export const Loading=({text='جاري التحميل...'})=><div className="loading"><span className="spinner"/>{text}</div>;
const friendlyError=(error)=>{const s=String(error||'').trim();if(!s)return '';if(/Return date cannot be before departure date/i.test(s))return 'تاريخ العودة لا يمكن أن يكون قبل تاريخ الذهاب. راجع تاريخ العودة ثم حاول الحفظ مرة أخرى.';if(/duplicate key value.*staff_users_pkey/i.test(s))return 'يوجد تعارض في رقم حساب الموظف. حدّث الصفحة ثم حاول الحفظ مرة أخرى.';if(/violates check constraint.*trips_status_check/i.test(s))return 'حالة الرحلة غير مقبولة في قاعدة البيانات. اختر حالة صحيحة ثم حاول مرة أخرى.';if(/Could not find the 'branch_id' column of 'drivers'/i.test(s))return 'جدول السائقين يحتاج تحديث بنية الفرع. شغّل تحديث قاعدة البيانات الخاص بالسائقين ثم أعد المحاولة.';return s};
function feedbackHost(){if(typeof document==='undefined')return null;let host=document.getElementById('global-error-feedback-stack');if(!host){host=document.createElement('div');host.id='global-error-feedback-stack';host.className='global-error-feedback-stack';host.setAttribute('aria-live','assertive');document.body.appendChild(host)}return host}
export const ErrorBox=({error})=>{if(!error)return null;const node=<div className="error-box global-error-feedback" role="alert">{friendlyError(error)}</div>;const host=feedbackHost();return host?createPortal(node,host):node};
export function Modal({open,onClose,title,children,wide=false}){if(!open)return null;return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.()}}><div className={`modal ${wide?'wide':''}`}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose}>×</button></div><div className="modal-body">{children}</div></div></div>}
export const Field=({label,children,hint})=><label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;
export const Input=(p)=><input {...p}/>; export const Select=(p)=><select {...p}/>; export const Textarea=(p)=><textarea {...p}/>;
export function SearchSelect({value='',onChange,options=[],placeholder='اختر...',disabled=false,name='',className=''}){
 const ref=useRef(null),[open,setOpen]=useState(false),[query,setQuery]=useState('');
 useEffect(()=>{const close=e=>{if(ref.current&&!ref.current.contains(e.target))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 const selected=options.find(x=>String(x.value)===String(value));
 const filtered=useMemo(()=>{const q=String(query||'').trim().toLowerCase();if(!q)return options;return options.filter(x=>`${x.label||''} ${x.searchText||''}`.toLowerCase().includes(q))},[options,query]);
 const choose=opt=>{if(opt?.disabled)return;onChange?.({target:{value:String(opt?.value??''),name}});setQuery('');setOpen(false)};
 return <div className={`search-select ${className}`} ref={ref}>{name&&<input type="hidden" name={name} value={value||''}/>}<button type="button" className="search-select-trigger" disabled={disabled} onClick={()=>!disabled&&setOpen(x=>!x)} aria-expanded={open}><span className={!selected?'search-select-placeholder':''}>{selected?.label||placeholder}</span><span className={`search-select-arrow ${open?'open':''}`}>⌄</span></button>{open&&!disabled&&<div className="search-select-menu"><input className="search-select-input" value={query} onChange={e=>setQuery(e.target.value)} autoFocus placeholder={`ابحث — ${placeholder}`}/><div className="search-select-options">{filtered.length?filtered.map(opt=><button type="button" key={String(opt.value)} disabled={opt.disabled} className={`search-select-option ${String(opt.value)===String(value)?'selected':''}`} onClick={()=>choose(opt)}>{opt.label}</button>):<div className="search-select-empty">لا توجد نتائج مطابقة</div>}</div></div>}</div>
}
export function Table({columns,rows,onRow}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||r.booking_number||r.trip_code||i} onClick={()=>onRow?.(r)} className={onRow?'clickable':''}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):r[c.key]??'—'}</td>)}</tr>)}</tbody></table></div>}
