import React,{useEffect,useMemo,useState} from 'react';
import {Activity,RefreshCw,Search,ShieldCheck,WalletCards,Code2,Printer} from 'lucide-react';
import {Badge,Button,Card,ErrorBox,Field,Input,Select,Table} from '../../components/UI.jsx';
import {basicPrintDocument,printHtmlDocument} from '../../lib/print.js';

const esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const actionLabel=v=>({
 sync_users:'تعديل بيانات/صلاحيات الموظفين',security_permission_approval_decide:'قرار موافقة صلاحيات',security_permission_review:'مراجعة الصلاحيات',save_branch:'حفظ فرع',company_settings_save:'حفظ بيانات الشركة',create_operational_snapshot:'إنشاء لقطة تشغيلية',developer_studio_save:'حفظ إعدادات المطور',developer_studio_rollback:'استرجاع إعدادات المطور',insert:'إضافة سجل',update:'تعديل سجل'
}[String(v||'')]||String(v||'—'));

export default function AuditPanel(){
 const [rows,setRows]=useState([]),[summary,setSummary]=useState({total:0,security:0,finance:0,developer:0}),[scope,setScope]=useState(''),[q,setQ]=useState(''),[category,setCategory]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{const p=new URLSearchParams({limit:'300'});if(q.trim())p.set('q',q.trim());const r=await fetch(`/api/audit?${p.toString()}`,{credentials:'include',cache:'no-store'});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'تعذر قراءة سجل التدقيق');setRows(b.rows||[]);setSummary(b.summary||{});setScope(b.scope||'')}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>{if(category==='all')return true;const s=`${r.action||''} ${r.entity_type||''}`;if(category==='security')return /permission|security|login|auth|user|staff|approval/i.test(s);if(category==='finance')return /finance|payment|refund|expense|cash|shift/i.test(s);if(category==='developer')return /developer|backup|restore|purge|snapshot|setting|release/i.test(s);return true}),[rows,category]);
 function printAudit(){const body=`<h1>سجل التدقيق والأمان</h1><p>النطاق: ${esc(scope==='all'?'جميع الفروع':'الفرع الحالي')} — عدد السجلات: ${filtered.length}</p><table><thead><tr><th>الوقت</th><th>المستخدم</th><th>الدور</th><th>العملية</th><th>الكيان</th><th>المعرّف</th></tr></thead><tbody>${filtered.map(r=>`<tr><td>${esc(r.created_at?new Date(r.created_at).toLocaleString('ar-SA'):'—')}</td><td>${esc(r.actor_name||r.actor_id)}</td><td>${esc(r.actor_role)}</td><td>${esc(actionLabel(r.action))}</td><td>${esc(r.entity_type)}</td><td>${esc(r.entity_id)}</td></tr>`).join('')||'<tr><td colspan="6">لا توجد سجلات</td></tr>'}</tbody></table>`;printHtmlDocument(basicPrintDocument({title:'سجل التدقيق والأمان',body,styles:'@page{size:A4 landscape}table{width:100%;border-collapse:collapse}th,td{border:1px solid #dbe3ec;padding:7px;text-align:right}th{background:#f1f5f9}p{color:#64748b}'}))}
 const cols=[
  {key:'created_at',label:'الوقت',render:r=>r.created_at?new Date(r.created_at).toLocaleString('ar-SA'):'—'},
  {key:'actor_name',label:'المستخدم',render:r=><div><strong>{r.actor_name||r.actor_id||'—'}</strong><div className="muted-small">{r.actor_role||'—'}</div></div>},
  {key:'action',label:'العملية',render:r=><Badge>{actionLabel(r.action)}</Badge>},
  {key:'entity',label:'الكيان',render:r=><div>{r.entity_type||'—'}<div className="muted-small">{r.entity_id||'—'}</div></div>},
  {key:'branch_id',label:'الفرع',render:r=>r.branch_id||'عام'},
  {key:'metadata',label:'التفاصيل',render:r=><span className="muted-small">{r.metadata?.table||r.metadata?.path||r.metadata?.source||'—'}</span>}
 ];
 return <Card><div className="card-title"><div><h3><Activity size={18}/> سجل التدقيق والأمان</h3><small>قراءة فقط — يعرض العمليات الحساسة المسجلة من الخادم ويُراعي نطاق الفروع.</small></div><div className="developer-actions"><Button onClick={load} disabled={busy}><RefreshCw size={15}/> تحديث</Button><Button onClick={printAudit}><Printer size={15}/> طباعة السجل</Button></div></div><ErrorBox error={error}/><div className="stats-grid"><Card className="stat-card"><Activity/><div><span>إجمالي السجلات</span><strong>{summary.total||0}</strong></div></Card><Card className="stat-card"><ShieldCheck/><div><span>أمان وصلاحيات</span><strong>{summary.security||0}</strong></div></Card><Card className="stat-card"><WalletCards/><div><span>مالية</span><strong>{summary.finance||0}</strong></div></Card><Card className="stat-card"><Code2/><div><span>مطور ونظام</span><strong>{summary.developer||0}</strong></div></Card></div><div className="inline-form"><Field label="بحث"><div style={{position:'relative'}}><Search size={16} style={{position:'absolute',insetInlineStart:10,top:11}}/><Input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="المستخدم، العملية، الكيان..." style={{paddingInlineStart:34}}/></div></Field><Field label="التصنيف"><Select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">الكل</option><option value="security">أمان وصلاحيات</option><option value="finance">مالية</option><option value="developer">مطور ونظام</option></Select></Field><Button onClick={load} disabled={busy}>{busy?'جاري التحميل...':'تطبيق البحث'}</Button><Badge tone="green">{scope==='all'?'كل الفروع':'نطاق الفرع'}</Badge></div><Table rows={filtered} columns={cols}/></Card>;
}
