import React,{useEffect,useState} from 'react';
import {Activity,ShieldCheck,Database,HardDrive,Play,RefreshCw,FlaskConical,KeyRound,Archive,Save,Plus,Trash2,UserCog,FileText} from 'lucide-react';
import {api} from '../../lib/api.js';
import {Badge,Button,Card,ErrorBox,Field,Input,Loading,PageHeader,Textarea} from '../../components/UI.jsx';
import DeveloperDataCenter from './DeveloperDataCenter.jsx';

const DEFAULT_PROFILE={display_name:'Mohamed Abdelrahman Hassan',title:'مطور النظام',phone:'00966509444960',email:'',footer_note:'الدعم الفني وتطوير النظام'};
const DEFAULT_CONFIG={show_profile_all_pages:true,show_profile_tickets:true,show_profile_reports:true,show_profile_receipts:true};
const DEFAULT_LABELS={system_name:'الماهر الماسي',system_subtitle:'نظام إدارة الرحلات والحجوزات والتسكين والتشغيل',ticket_footer:'',report_footer:''};

export default function Developer(){
 const [status,setStatus]=useState(null),[health,setHealth]=useState(null),[predeploy,setPredeploy]=useState(null),[dataHealth,setDataHealth]=useState(null),[secrets,setSecrets]=useState(null),[snapshot,setSnapshot]=useState(null),[terms,setTerms]=useState([]),[profile,setProfile]=useState(DEFAULT_PROFILE),[config,setConfig]=useState(DEFAULT_CONFIG),[labels,setLabels]=useState(DEFAULT_LABELS),[error,setError]=useState(''),[busy,setBusy]=useState(''),[saved,setSaved]=useState('');
 async function load(){setError('');setSaved('');try{const [s,h,tx,studio]=await Promise.all([api.mega('status',{},'GET'),api.health(),api.mega('ticket_terms',{},'GET').catch(()=>({terms:[]})),api.mega('developer_studio_get',{},'GET').catch(()=>({profile:{},config:{},labels:{}}))]);setStatus({...s,publicHealth:h});if(Array.isArray(tx?.terms))setTerms(tx.terms);if(!studio?.restricted){setProfile({...DEFAULT_PROFILE,...(studio?.profile||{})});setConfig({...DEFAULT_CONFIG,...(studio?.config||{})});setLabels({...DEFAULT_LABELS,...(studio?.labels||{})})}}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 async function run(kind,fn,setter){setBusy(kind);setError('');try{setter(await fn())}catch(e){setError(e.message)}finally{setBusy('')}}
 async function saveTerms(){setBusy('terms');setError('');setSaved('');try{const cleaned=terms.map(x=>String(x||'').trim()).filter(Boolean);await api.mega('save_ticket_terms',{terms:cleaned});setTerms(cleaned);setSaved('تم حفظ شروط التذاكر بنجاح.') }catch(e){setError(e.message)}finally{setBusy('')}}
 async function saveStudio(){setBusy('studio');setError('');setSaved('');try{const cleanProfile={...profile,display_name:String(profile.display_name||'').trim(),title:String(profile.title||'').trim(),phone:String(profile.phone||'').trim(),email:String(profile.email||'').trim(),footer_note:String(profile.footer_note||'').trim()};const x=await api.mega('developer_studio_save',{profile:cleanProfile,config,labels});setProfile({...DEFAULT_PROFILE,...(x?.profile||cleanProfile)});setConfig({...DEFAULT_CONFIG,...(x?.config||config)});setLabels({...DEFAULT_LABELS,...(x?.labels||labels)});setSaved('تم نشر إعدادات المطور والهوية على النظام بنجاح.')}catch(e){setError(e.message)}finally{setBusy('')}}
 const provider=status?.providers||{},em=status?.emergency||{};
 return <><PageHeader title="المطور والنظام" subtitle="مركز تحكم المطور: الهوية، البيانات الظاهرة، الشروط، الجودة والسحابة" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث الحالة</Button>}/><ErrorBox error={error}/>{saved&&<div className="training-banner" style={{background:'#ecfdf3',color:'#166534',borderColor:'#bbf7d0'}}>{saved}</div>}{!status&&!error?<Loading/>:<><div className="stats-grid"><Card className="stat-card"><Activity/><div><span>الإصدار</span><strong>{status?.publicHealth?.version||'—'}</strong></div></Card><Card className="stat-card"><Database/><div><span>Supabase</span><strong>{provider?.supabase?.configured===false?'غير مضبوط':'مضبوط'}</strong></div></Card><Card className="stat-card"><ShieldCheck/><div><span>وضع النظام</span><strong>{em?.maintenance?.enabled?'صيانة':em?.read_only?.enabled?'قراءة فقط':'تشغيل'}</strong></div></Card><Card className="stat-card"><HardDrive/><div><span>البنية</span><strong>React + Worker</strong></div></Card></div>
<Card><div className="card-title"><div><h3><UserCog size={18}/> هوية المطور وبيانات الظهور</h3><small>تُستخدم كبيانات المطور الرسمية داخل النظام والتذاكر والمطبوعات.</small></div></div><div className="form-grid"><Field label="اسم المطور"><Input value={profile.display_name||''} onChange={e=>setProfile(x=>({...x,display_name:e.target.value}))} placeholder="Mohamed Abdelrahman Hassan"/></Field><Field label="المسمى"><Input value={profile.title||''} onChange={e=>setProfile(x=>({...x,title:e.target.value}))} placeholder="مطور النظام"/></Field><Field label="رقم التواصل"><Input value={profile.phone||''} onChange={e=>setProfile(x=>({...x,phone:e.target.value}))} inputMode="tel" placeholder="00966509444960"/></Field><Field label="البريد"><Input value={profile.email||''} onChange={e=>setProfile(x=>({...x,email:e.target.value}))} type="email"/></Field><Field label="عبارة أسفل بيانات المطور"><Input value={profile.footer_note||''} onChange={e=>setProfile(x=>({...x,footer_note:e.target.value}))}/></Field></div><div className="permissions-box"><div className="card-title"><h3><FileText size={17}/> أماكن إظهار بيانات المطور</h3></div><div className="permission-grid">{[['show_profile_all_pages','جميع صفحات النظام'],['show_profile_tickets','التذاكر'],['show_profile_reports','التقارير والكشوف'],['show_profile_receipts','السندات والمطبوعات']].map(([k,l])=><label className="permission-check" key={k}><input type="checkbox" checked={config[k]!==false} onChange={e=>setConfig(x=>({...x,[k]:e.target.checked}))}/> {l}</label>)}</div></div></Card>
<Card><div className="card-title"><div><h3>النصوص العامة للنظام</h3><small>تعديل المسميات الأساسية بدون الدخول للكود.</small></div></div><div className="form-grid"><Field label="اسم النظام"><Input value={labels.system_name||''} onChange={e=>setLabels(x=>({...x,system_name:e.target.value}))}/></Field><Field label="وصف النظام"><Input value={labels.system_subtitle||''} onChange={e=>setLabels(x=>({...x,system_subtitle:e.target.value}))}/></Field><Field label="تذييل التذكرة"><Input value={labels.ticket_footer||''} onChange={e=>setLabels(x=>({...x,ticket_footer:e.target.value}))}/></Field><Field label="تذييل التقارير"><Input value={labels.report_footer||''} onChange={e=>setLabels(x=>({...x,report_footer:e.target.value}))}/></Field></div><Button variant="primary" onClick={saveStudio} disabled={busy==='studio'}><Save size={16}/> {busy==='studio'?'جاري النشر...':'حفظ ونشر إعدادات المطور'}</Button></Card>
<DeveloperDataCenter/>
<Card><div className="developer-actions"><Button variant="primary" onClick={()=>run('health',()=>api.moduleWrite({action:'run_health_check'}),setHealth)} disabled={!!busy}><Play size={16}/> فحص المكونات</Button><Button onClick={()=>run('data',()=>api.mega('data_health'),setDataHealth)} disabled={!!busy}><FlaskConical size={16}/> سلامة البيانات</Button><Button onClick={()=>run('pre',()=>api.mega('predeploy_run',{release_version:'1.2.0'}),setPredeploy)} disabled={!!busy}><ShieldCheck size={16}/> فحص قبل النشر</Button><Button onClick={()=>run('secrets',()=>api.mega('secrets_status'),setSecrets)} disabled={!!busy}><KeyRound size={16}/> حالة المتغيرات</Button><Button onClick={()=>run('snapshot',()=>api.moduleWrite({action:'create_operational_snapshot'}),setSnapshot)} disabled={!!busy}><Archive size={16}/> لقطة تشغيلية</Button></div>{busy&&busy!=='studio'&&busy!=='terms'&&<div className="muted-small">جاري تنفيذ الفحص...</div>}</Card><Card><div className="card-title"><div><h3>شروط وأحكام التذاكر</h3><small>تظهر في A4 والحراري.</small></div><Button onClick={()=>setTerms(a=>[...a,''])}><Plus size={15}/> شرط</Button></div><div className="terms-editor">{terms.map((x,i)=><div className="term-row" key={i}><span>{i+1}</span><Textarea value={x} onChange={e=>setTerms(a=>a.map((v,j)=>j===i?e.target.value:v))}/><button onClick={()=>setTerms(a=>a.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div>)}</div><Button variant="primary" onClick={saveTerms} disabled={busy==='terms'}><Save size={16}/> حفظ الشروط</Button></Card><div className="developer-grid"><Result title="صحة المكونات" value={health}/><Result title="سلامة البيانات" value={dataHealth}/><Result title="فحص قبل النشر" value={predeploy}/><Result title="حالة المتغيرات" value={secrets}/></div>{snapshot&&<Card><div className="card-title"><h3>آخر لقطة تشغيلية</h3><Badge tone="green">تمت</Badge></div><p>تم إنشاء Snapshot تشغيلي وحفظه في مساحة النسخ الاحتياطية.</p>{snapshot.signed_url&&<a className="button-link" href={snapshot.signed_url} target="_blank" rel="noreferrer">فتح الرابط المؤقت</a>}</Card>}<Card><h3>حالة المزودين والطوارئ</h3><pre className="json-view">{JSON.stringify({providers:provider,emergency:em},null,2)}</pre></Card></>}</>;
}
function Result({title,value}){if(!value)return null;const ok=value.ok!==false&&value.status!=='warning'&&value.status!=='fail';return <Card><div className="card-title"><h3>{title}</h3><Badge tone={ok?'green':'orange'}>{ok?'سليم':'مراجعة'}</Badge></div><pre className="json-view compact-json">{JSON.stringify(value,null,2)}</pre></Card>}
