import React,{useEffect,useState} from 'react';
import {Activity,ShieldCheck,Database,HardDrive,Play,RefreshCw,FlaskConical,KeyRound,Archive} from 'lucide-react';
import {api} from '../../lib/api.js';
import {Badge,Button,Card,ErrorBox,Loading,PageHeader} from '../../components/UI.jsx';

export default function Developer(){
 const [status,setStatus]=useState(null),[health,setHealth]=useState(null),[predeploy,setPredeploy]=useState(null),[dataHealth,setDataHealth]=useState(null),[secrets,setSecrets]=useState(null),[snapshot,setSnapshot]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState('');
 async function load(){setError('');try{const [s,h]=await Promise.all([api.mega('status',{},'GET'),api.health()]);setStatus({...s,publicHealth:h})}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 async function run(kind,fn,setter){setBusy(kind);setError('');try{setter(await fn())}catch(e){setError(e.message)}finally{setBusy('')}}
 const provider=status?.providers||{},em=status?.emergency||{};
 return <><PageHeader title="المطور والنظام" subtitle="حالة السحابة، اختبارات الجودة، أسرار المزودين والنسخ التشغيلية" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث الحالة</Button>}/><ErrorBox error={error}/>{!status&&!error?<Loading/>:<><div className="stats-grid"><Card className="stat-card"><Activity/><div><span>الإصدار</span><strong>{status?.publicHealth?.version||'—'}</strong></div></Card><Card className="stat-card"><Database/><div><span>Supabase</span><strong>{provider?.supabase?.configured===false?'غير مضبوط':'مضبوط'}</strong></div></Card><Card className="stat-card"><ShieldCheck/><div><span>وضع النظام</span><strong>{em?.maintenance?.enabled?'صيانة':em?.read_only?.enabled?'قراءة فقط':'تشغيل'}</strong></div></Card><Card className="stat-card"><HardDrive/><div><span>البنية</span><strong>React + Worker</strong></div></Card></div><Card><div className="developer-actions"><Button variant="primary" onClick={()=>run('health',()=>api.moduleWrite({action:'run_health_check'}),setHealth)} disabled={!!busy}><Play size={16}/> فحص المكونات</Button><Button onClick={()=>run('data',()=>api.mega('data_health'),setDataHealth)} disabled={!!busy}><FlaskConical size={16}/> سلامة البيانات</Button><Button onClick={()=>run('pre',()=>api.mega('predeploy_run',{release_version:'1.2.0'}),setPredeploy)} disabled={!!busy}><ShieldCheck size={16}/> فحص قبل النشر</Button><Button onClick={()=>run('secrets',()=>api.mega('secrets_status'),setSecrets)} disabled={!!busy}><KeyRound size={16}/> حالة المتغيرات</Button><Button onClick={()=>run('snapshot',()=>api.moduleWrite({action:'create_operational_snapshot'}),setSnapshot)} disabled={!!busy}><Archive size={16}/> لقطة تشغيلية</Button></div>{busy&&<div className="muted-small">جاري تنفيذ الفحص...</div>}</Card><div className="developer-grid"><Result title="صحة المكونات" value={health}/><Result title="سلامة البيانات" value={dataHealth}/><Result title="فحص قبل النشر" value={predeploy}/><Result title="حالة المتغيرات" value={secrets}/></div>{snapshot&&<Card><div className="card-title"><h3>آخر لقطة تشغيلية</h3><Badge tone="green">تمت</Badge></div><p>تم إنشاء Snapshot تشغيلي وحفظه في مساحة النسخ الاحتياطية.</p>{snapshot.signed_url&&<a className="button-link" href={snapshot.signed_url} target="_blank" rel="noreferrer">فتح الرابط المؤقت</a>}</Card>}<Card><h3>حالة المزودين والطوارئ</h3><pre className="json-view">{JSON.stringify({providers:provider,emergency:em},null,2)}</pre></Card></>}</>;
}
function Result({title,value}){if(!value)return null;const ok=value.ok!==false&&value.status!=='warning'&&value.status!=='fail';return <Card><div className="card-title"><h3>{title}</h3><Badge tone={ok?'green':'orange'}>{ok?'سليم':'مراجعة'}</Badge></div><pre className="json-view compact-json">{JSON.stringify(value,null,2)}</pre></Card>}
