import React,{useEffect,useState} from 'react';
import {Archive,CheckCircle2,Eye,RefreshCw,ShieldAlert,XCircle} from 'lucide-react';
import {Badge,Button,Card,ErrorBox} from '../../components/UI.jsx';

async function req(path,{method='GET'}={}){
  const r=await fetch(path,{method,credentials:'include',headers:{Accept:'application/json','Content-Type':'application/json'},cache:'no-store'});
  const text=await r.text();let body={};try{body=text?JSON.parse(text):{}}catch{body={message:text}}
  if(!r.ok)throw new Error(body?.error||body?.message||`HTTP ${r.status}`);return body;
}

export default function ProductionControl(){
  const [state,setState]=useState(null),[snapshot,setSnapshot]=useState(null),[preview,setPreview]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function load(){setBusy('load');setError('');try{setState(await req('/api/production/readiness'))}catch(e){setError(e.message)}finally{setBusy('')}}
  useEffect(()=>{load()},[]);
  async function makeSnapshot(){setBusy('snapshot');setError('');setNotice('');try{const x=await req('/api/production/snapshot',{method:'POST'});setSnapshot(x);setNotice('تم إنشاء Snapshot محمية قبل التشغيل الفعلي. لم يتم حذف أو تغيير أي بيانات.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
  async function loadPreview(){setBusy('preview');setError('');setNotice('');try{const x=await req('/api/production/cleanup-preview');setPreview(x);setNotice('تم إنشاء معاينة تنظيف بيانات التدريب فقط. هذه العملية قراءة فقط ولم يتم حذف أي سجل.')}catch(e){setError(e.message)}finally{setBusy('')}}
  const checks=state?.checks||[],tables=state?.tables||[],previewTables=preview?.tables||[];
  return <Card><div className="card-title"><div><h3><ShieldAlert size={18}/> بوابة الانتقال من التدريب إلى التشغيل الفعلي</h3><small>التفعيل والحذف الفعليان ما زالا مقفولين. الأدوات الحالية للفحص، الـSnapshot، ومعاينة ما قد يُنظف فقط.</small></div><Badge tone={state?.ready?'green':'orange'}>{state?.ready?'جاهزية أولية مكتملة':'غير جاهز للتفعيل'}</Badge></div><ErrorBox error={error}/>{notice&&<div className="training-banner" style={{background:'#ecfdf3',color:'#166534',borderColor:'#bbf7d0'}}>{notice}</div>}
  <div className="developer-actions"><Button onClick={load} disabled={!!busy}><RefreshCw size={16}/> {busy==='load'?'جاري الفحص...':'إعادة فحص الجاهزية'}</Button><Button variant="primary" onClick={makeSnapshot} disabled={!!busy}><Archive size={16}/> {busy==='snapshot'?'جاري إنشاء Snapshot...':'إنشاء Snapshot قبل التشغيل'}</Button><Button onClick={loadPreview} disabled={!!busy}><Eye size={16}/> {busy==='preview'?'جاري إعداد المعاينة...':'معاينة تنظيف بيانات التدريب'}</Button></div>
  {state&&<><div className="stats-grid" style={{marginTop:14}}><Card className="stat-card"><div><span>الفروع</span><strong>{state.counts?.branches??0}</strong></div></Card><Card className="stat-card"><div><span>الموظفون النشطون</span><strong>{state.counts?.active_staff??0}</strong></div></Card><Card className="stat-card"><div><span>تشغيل فعلي</span><strong>{state.counts?.production_staff??0}</strong></div></Card><Card className="stat-card"><div><span>موافقات معلقة</span><strong>{state.counts?.pending_approvals??0}</strong></div></Card></div>
  <div className="permissions-box" style={{marginTop:14}}><div className="card-title"><h3>فحوصات ما قبل Production</h3></div>{checks.map(x=><div key={x.key} className="permission-check" style={{display:'flex',alignItems:'center',gap:10,marginBottom:8}}>{x.ok?<CheckCircle2 size={18} color="green"/>:<XCircle size={18} color="crimson"/>}<div><b>{x.label}</b><div className="muted-small">{x.details}{x.blocking?' · شرط إلزامي':''}</div></div></div>)}</div>
  <div className="permissions-box" style={{marginTop:14}}><div className="card-title"><h3>عزل بيانات التدريب / التشغيل</h3></div><div className="table-wrap"><table><thead><tr><th>الجدول</th><th>تدريب</th><th>تشغيل فعلي</th><th>الإجمالي</th><th>الحالة</th></tr></thead><tbody>{tables.map(x=><tr key={x.table}><td>{x.table}</td><td>{x.training}</td><td>{x.production}</td><td>{x.total}</td><td><Badge tone={x.ok?'green':'red'}>{x.ok?'سليم':'يحتاج Migration'}</Badge></td></tr>)}</tbody></table></div></div>
  <div className="error-box" style={{background:'#fff9ed',borderColor:'#f1d8a8',color:'#7a4b00',marginTop:14}}><ShieldAlert size={16}/> التفعيل الفعلي ما زال مقفولًا عمدًا. لن يُفتح إلا بعد Snapshot + مراجعة معاينة تنظيف بيانات التدريب + تأكيد مزدوج + Rollback صالح ومختبر.</div></>}
  {preview&&<div className="permissions-box" style={{marginTop:14}}><div className="card-title"><div><h3>معاينة تنظيف بيانات التدريب</h3><small>قراءة فقط — لا يوجد تنفيذ حذف من هذه الشاشة.</small></div><Badge tone={preview.ok?'green':'red'}>{preview.would_delete_rows??0} سجل تدريب</Badge></div><div className="table-wrap"><table><thead><tr><th>الجدول</th><th>سيُستهدف كتدريب</th><th>تشغيل فعلي محفوظ</th><th>الحالة</th></tr></thead><tbody>{previewTables.map(x=><tr key={x.table}><td>{x.table}</td><td>{x.would_delete}</td><td>{x.production}</td><td><Badge tone={x.ok?'green':'red'}>{x.ok?'قابل للمعاينة':'محظور'}</Badge></td></tr>)}</tbody></table></div>{(preview.protected_tables||[]).length>0&&<div className="muted-small" style={{marginTop:10}}>جداول محمية من التنظيف التلقائي: {(preview.protected_tables||[]).join('، ')}</div>}{(preview.warnings||[]).map((x,i)=><div key={i} className="muted-small" style={{marginTop:6}}>• {x}</div>)}</div>}
  {snapshot&&<div className="permissions-box" style={{marginTop:14}}><b>آخر Snapshot في هذه الجلسة</b><div className="muted-small">{snapshot?.row?.completed_at||snapshot?.row?.started_at||new Date().toLocaleString('ar-SA')}</div>{snapshot?.signed_url&&<a className="button-link" href={snapshot.signed_url} target="_blank" rel="noreferrer">فتح النسخة المؤقتة</a>}</div>}</Card>
}
