import React,{useEffect,useMemo,useState} from 'react';
import {BusFront,Plus,RefreshCw,Repeat2,Wrench,Link2,UserRound,Trash2,Pencil,Unlink} from 'lucide-react';
import {useAppData} from '../../core/AppDataContext.jsx';
import {useAuth} from '../../core/AuthContext.jsx';
import {api} from '../../lib/api.js';
import {allOps,has} from '../../lib/permissions.js';
import {Badge,Button,Card,ErrorBox,Field,Input,Loading,Modal,PageHeader,Select,Table,Textarea} from '../../components/UI.jsx';
import {dateTime,money} from '../../lib/format.js';

const s=v=>String(v??'');
const low=v=>s(v).toLowerCase();
const statusLabel=v=>({available:'متاحة',assigned:'مُعيّنة',maintenance:'صيانة',out_of_service:'خارج الخدمة',planned:'مخططة',in_progress:'جارية',completed:'مكتملة',cancelled:'ملغاة',active:'نشط',inactive:'موقوف'}[s(v)]||v||'—');
const activeLink=x=>!['cancelled','released','inactive'].includes(low(x?.status||'assigned'));
const activeSeat=x=>['assigned','hold','blocked'].includes(low(x?.status));
export default function Fleet(){
 const {user}=useAuth(),{data:app}=useAppData();
 const [data,setData]=useState(null),[drivers,setDrivers]=useState([]),[tab,setTab]=useState('vehicles'),[modal,setModal]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const canViewFleet=has(user,'viewFleet')||has(user,'fleet')||has(user,'vehicles');
 const canAddVehicle=has(user,'addVehicles')||has(user,'vehicles')||has(user,'fleet');
 const canEditVehicle=has(user,'editVehicles')||has(user,'vehicles')||has(user,'fleet');
 const canDeleteVehicle=has(user,'deleteVehicles')||has(user,'vehicles')||has(user,'fleet');
 const canViewDrivers=has(user,'viewDrivers')||has(user,'addDrivers')||has(user,'editDrivers')||has(user,'deleteDrivers')||has(user,'manageDrivers')||has(user,'fleet')||has(user,'vehicles');
 const canAddDriver=has(user,'addDrivers')||has(user,'manageDrivers')||has(user,'fleet')||has(user,'vehicles');
 const canEditDriver=has(user,'editDrivers')||has(user,'manageDrivers')||has(user,'fleet')||has(user,'vehicles');
 const canDeleteDriver=has(user,'deleteDrivers')||has(user,'manageDrivers')||has(user,'fleet')||has(user,'vehicles');
 const canAssignFleet=has(user,'assignFleet')||has(user,'fleet')||has(user,'vehicles');
 const canMaintenance=has(user,'manageMaintenance')||has(user,'fleet')||has(user,'vehicles');
 async function load(){setError('');try{const [fleet,driverData]=await Promise.all([canViewFleet||canAssignFleet||canMaintenance?api.module('fleet'):Promise.resolve({}),canViewDrivers?api.module('drivers'):Promise.resolve({drivers:[]})]);setData(fleet);setDrivers(driverData?.drivers||driverData?.rows||[])}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 const branches=app.branches||[],trips=app.trips||[],bookings=app.bookings||[],passengers=app.passengers||[],vehicles=data?.vehicles||[],assignments=data?.trip_vehicles||[],maintenance=data?.vehicle_maintenance||[],seatAssignments=data?.seat_assignments||[];
 const branchMap=useMemo(()=>new Map(branches.map(x=>[s(x.id),x.name||x.branch_name||x.id])),[branches]);
 const vehicleMap=useMemo(()=>new Map(vehicles.map(x=>[s(x.id),x])),[vehicles]);
 const tripMap=useMemo(()=>new Map(trips.map(x=>[s(x.id),x])),[trips]);
 const driverMap=useMemo(()=>new Map(drivers.map(x=>[s(x.id),x])),[drivers]);
 const bookingMap=useMemo(()=>new Map(bookings.map(x=>[s(x.id),x])),[bookings]);
 const bookedByTrip=useMemo(()=>{const m=new Map();for(const p of passengers){if(low(p.status)==='cancelled')continue;const b=bookingMap.get(s(p.booking_id));if(!b||low(b.status)==='cancelled')continue;for(const tid of [b.trip_id,b.return_trip_id])if(tid)m.set(s(tid),(m.get(s(tid))||0)+1)}return m},[passengers,bookingMap]);
 const activeAssignments=useMemo(()=>assignments.filter(activeLink),[assignments]);
 const activeSeatAssignments=useMemo(()=>seatAssignments.filter(activeSeat),[seatAssignments]);
 const capacityByTrip=useMemo(()=>{const m=new Map();for(const a of activeAssignments)m.set(s(a.trip_id),(m.get(s(a.trip_id))||0)+Number(a.booking_capacity||a.capacity||0));return m},[activeAssignments]);
 const duplicateKeys=useMemo(()=>{const count=new Map();for(const a of activeAssignments){const k=`${s(a.trip_id)}|${s(a.vehicle_id)}`;count.set(k,(count.get(k)||0)+1)}return new Set([...count].filter(([,n])=>n>1).map(([k])=>k))},[activeAssignments]);
 const driverConflictIds=useMemo(()=>{const bad=new Set(),perTrip=new Map();for(const a of activeAssignments){const tid=s(a.trip_id),main=s(a.driver_id),extra=s(a.extra_driver_id);if(main&&extra&&main===extra)bad.add(s(a.id));const bucket=perTrip.get(tid)||new Map();for(const did of [main,extra].filter(Boolean)){const prev=bucket.get(did);if(prev&&prev!==s(a.id)){bad.add(prev);bad.add(s(a.id))}else bucket.set(did,s(a.id))}perTrip.set(tid,bucket)}return bad},[activeAssignments]);
 const allocatedPassengersByTrip=useMemo(()=>{const m=new Map();const tvTrip=new Map(activeAssignments.map(a=>[s(a.id),s(a.trip_id)]));for(const a of activeSeatAssignments){if(low(a.status)!=='assigned'||!a.passenger_id)continue;const tid=tvTrip.get(s(a.trip_vehicle_id));if(!tid)continue;const set=m.get(tid)||new Set();set.add(s(a.passenger_id));m.set(tid,set)}return m},[activeAssignments,activeSeatAssignments]);
 function tripBooked(id){return bookedByTrip.get(s(id))||0}
 function tripCapacity(id){return capacityByTrip.get(s(id))||0}
 function tripAllocated(id){return allocatedPassengersByTrip.get(s(id))?.size||0}
 function tripUnallocated(id){return Math.max(0,tripBooked(id)-tripAllocated(id))}
 function tripAvailable(id){return Math.max(0,tripCapacity(id)-tripBooked(id))}
 function vehicleName(id){const v=vehicleMap.get(s(id));return v?`${v.code||v.name||'باص'}${v.plate_no?` — ${v.plate_no}:''}`:'—'}
 function driverName(id){const d=driverMap.get(s(id));return d?`${d.name||'سائق'}${d.phone?` — ${d.phone}:''}`:(id||'—')}
 function tripName(id){const t=tripMap.get(s(id));return t?`${t.trip_code||''} ${t.from_city||t.origin||''} ← ${t.to_city||t.destination||''}`:'—'}
 function tripSeatText(id){return `ركاب الرحلة ${tripBooked(id)} · موزع بمقاعد ${tripAllocated(id)} · بدون مقعد ${tripUnallocated(id)} · سعة الأسطول ${tripCapacity(id)} · متاح تشغيلي ${tripAvailable(id)}`}
 function busSeatStats(row){const cap=Number(row?.booking_capacity||row?.capacity||0);const rows=activeSeatAssignments.filter(x=>s(x.trip_vehicle_id)===s(row?.id));const assigned=rows.filter(x=>low(x.status)==='assigned').length;const reserved=rows.filter(x=>['hold','blocked'].includes(low(x.status))).length;const unavailable=rows.length;return {cap,assigned,reserved,unavailable,available:Math.max(0,cap-unavailable)}}
 function crewError(tripId,driverId,extraDriverId,currentId=''){const main=s(driverId),extra=s(extraDriverId);if(main&&extra&&main===extra)return 'لا يمكن اختيار نفس السائق كسائق أساسي وسائق إضافي لنفس الباص.';for(const did of [main,extra].filter(Boolean)){const conflict=activeAssignments.find(a=>s(a.id)!==s(currentId)&&s(a.trip_id)===s(tripId)&&(s(a.driver_id)===did||s(a.extra_driver_id)===did));if(conflict)return `السائق ${driverName(did)} معيّن بالفعل على باص آخر في نفس الرحلة.`}return ''}
 function done(msg){setNotice(msg);setTimeout(()=>setNotice(''),3500)}
 async function saveVehicle(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),old=modal?.row;if(old&&!canEditVehicle)return setError('لا توجد صلاحية تعديل المركبات.');if(!old&&!canAddVehicle)return setError('لا توجد صلاحية إضافة مركبات.');const row={branch_id:f.branch_id||app.scope?.branch_id||null,code:f.code||null,name:f.name||null,plate_no:f.plate_no,vehicle_type:f.vehicle_type||'bus',physical_capacity:Number(f.physical_capacity||49),booking_capacity:Number(f.booking_capacity||f.physical_capacity||49),status:f.status||'available',notes:f.notes||''};if(row.booking_capacity>row.physical_capacity)return setError('سعة الحجز لا يمكن أن تتجاوز السعة الفعلية');setBusy(true);try{await api.moduleWrite(old?{action:'update',table:'vehicles',id:old.id,row}:{action:'insert',table:'vehicles',row});await load();setModal(null);done(old?'تم تحديث المركبة بنجاح':'تمت إضافة المركبة بنجاح')}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function saveDriver(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),old=modal?.row;if(old&&!canEditDriver)return setError('لا توجد صلاحية تعديل السائقين.');if(!old&&!canAddDriver)return setError('لا توجد صلاحية إضافة سائقين.');const row={branch_id:f.branch_id||app.scope?.branch_id||null,name:String(f.name||'').trim(),phone:String(f.phone||'').trim(),national_id:String(f.national_id||'').trim()||null,license_no:String(f.license_no||'').trim()||null,license_expiry:f.license_expiry||null,status:f.status||'active',notes:f.notes||''};if(!row.name||!row.phone)return setError('اسم السائق ورقم الجوال مطلوبان');setBusy(true);try{await api.moduleWrite(old?{action:'update',table:'drivers',id:old.id,row}:{action:'insert',table:'drivers',row});await load();setModal(null);done(old?'تم تحديث بيانات السائق بنجاح':'تمت إضافة السائق بنجاح')}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function assignVehicle(e){e.preventDefault();if(!canAssignFleet)return setError('لا توجد صلاحية ربط المركبات والسائقين بالرحلات.');const f=Object.fromEntries(new FormData(e.currentTarget)),v=vehicleMap.get(s(f.vehicle_id));if(!v)return;const exists=activeAssignments.some(a=>s(a.trip_id)===s(f.trip_id)&&s(a.vehicle_id)===s(f.vehicle_id));if(exists)return setError('هذا الباص مرتبط بالفعل بنفس الرحلة. لا يمكن تكرار نفس الباص على نفس الرحلة.');const c=crewError(f.trip_id,f.driver_id,f.extra_driver_id);if(c)return setError(c);const row={trip_id:f.trip_id,vehicle_id:f.vehicle_id,bus_label:f.bus_label||v.code||v.name||'باص',capacity:Number(v.physical_capacity||49),booking_capacity:Number(v.booking_capacity||v.physical_capacity||49),driver_id:f.driver_id||null,extra_driver_id:f.extra_driver_id||null,supervisor_id:f.supervisor_id||null,status:'assigned'};setBusy(true);try{await api.moduleWrite({action:'insert',table:'trip_vehicles',row});await load();setModal(null);done('تم ربط المركبة والطاقم بالرحلة بنجاح')}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function saveCrew(e){e.preventDefault();if(!canAssignFleet)return setError('لا توجد صلاحية تعديل طاقم الرحلة.');const f=Object.fromEntries(new FormData(e.currentTarget)),row=modal?.row;if(!row)return;const c=crewError(row.trip_id,f.driver_id,f.extra_driver_id,row.id);if(c)return setError(c);setBusy(true);try{await api.moduleWrite({action:'update',table:'trip_vehicles',id:row.id,row:{driver_id:f.driver_id||null,extra_driver_id:f.extra_driver_id||null,supervisor_id:f.supervisor_id||null}});await load();setModal(null);done('تم تحديث سائق وطاقم الباص بنجاح')}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function swapVehicle(e){e.preventDefault();if(!canAssignFleet)return setError('لا توجد صلاحية تبديل مركبات الرحلات.');const f=Object.fromEntries(new FormData(e.currentTarget)),row=modal?.row;if(!row)return;const exists=activeAssignments.some(a=>s(a.id)!==s(row.id)&&s(a.trip_id)===s(row.trip_id)&&s(a.vehicle_id)===s(f.new_vehicle_id));if(exists)return setError('الباص البديل مرتبط بالفعل بهذه الرحلة.');setBusy(true);try{await api.mega('bus_swap',{trip_vehicle_id:row.id,new_vehicle_id:f.new_vehicle_id});await load();setModal(null);done('تم تبديل المركبة بأمان')}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function unlinkAssignment(row){if(!canAssignFleet)return setError('لا توجد صلاحية فك ربط الباص من الرحلة.');if(!confirm(`فك ربط ${vehicleName(row.vehicle_id)} من ${tripName(row.trip_id)}؟`))return;setBusy(true);try{await api.moduleWrite({action:'delete',table:'trip_vehicles',id:row.id});await load();done('تم فك ربط الباص من الرحلة')}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function deleteVehicle(row){if(!canDeleteVehicle)return setError('لا توجد صلاحية حذف المركبات.');if(!confirm(`حذف المركبة ${row.code||row.name||row.plate_no||''}؟`))return;setBusy(true);try{await api.moduleWrite({action:'delete',table:'vehicles',id:row.id});await load();done('تم حذف المركبة بنجاح')}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function deleteDriver(row){if(!canDeleteDriver)return setError('لا توجد صلاحية حذف السائقين.');if(!confirm(`حذف السائق ${row.name||''}؟`))return;setBusy(true);try{await api.moduleWrite({action:'delete',table:'drivers',id:row.id});await load();done('تم حذف السائق بنجاح')}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function saveMaintenance(e){e.preventDefault();if(!canMaintenance)return setError('لا توجد صلاحية إدارة الصيانة.');const f=Object.fromEntries(new FormData(e.currentTarget)),old=modal?.row;const row={vehicle_id:f.vehicle_id,maintenance_type:f.maintenance_type||null,due_date:f.due_date||null,status:f.status||'planned',cost:Number(f.cost||0),completed_at:f.status==='completed'?(old?.completed_at||new Date().toISOString()):null,notes:f.notes||''};setBusy(true);try{await api.moduleWrite(old?{action:'update',table:'vehicle_maintenance',id:old.id,row}:{action:'insert',table:'vehicle_maintenance',row});await load();setModal(null);done(old?'تم تحديث سجل الصيانة':'تم تسجيل الصيانة بنجاح')}catch(x){setError(x.message)}finally{setBusy(false)}}
 const vehicleCols=[{key:'vehicle',label:'المركبة',render:r=><div><strong>{r.code||r.name||'باص'}</strong><div className="muted-small">{r.plate_no||'بدون لوحة'}</div></div>},{key:'branch',label:'الفرع',render:r=>branchMap.get(s(r.branch_id))||'—'},{key:'capacity',label:'السعة',render:r=>`${r.booking_capacity||r.physical_capacity||0} / ${r.physical_capacity||0}`},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='available'?'green':r.status==='maintenance'?'orange':'blue'}>{statusLabel(r.status)}</Badge>},{key:'action',label:'',render:r=><div className="finance-actions">{canEditVehicle&&<Button onClick={()=>setModal({type:'vehicle',row:r})}>تعديل</Button>}{canDeleteVehicle&&<Button onClick={()=>deleteVehicle(r)}><Trash2 size={14}/> حذف</Button>}</div>}];
 const driverCols=[{key:'name',label:'السائق',render:r=><div><strong>{r.name||'—'}</strong><div className="muted-small">{r.phone||'—'}</div></div>},{key:'branch',label:'الفرع',render:r=>branchMap.get(s(r.branch_id))||'—'},{key:'license_no',label:'الرخصة',render:r=><div>{r.license_no||'—'}<div className="muted-small">{r.license_expiry||''}</div></div>},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='inactive'?'red':'green'}>{statusLabel(r.status)}</Badge>},{key:'action',label:'',render:r=><div className="finance-actions">{canEditDriver&&<Button onClick={()=>setModal({type:'driver',row:r})}>تعديل</Button>}{canDeleteDriver&&<Button onClick={()=>deleteDriver(r)}><Trash2 size={14}/> حذف</Button>}</div>}];
 const assignmentCols=[{key:'trip',label:'الرحلة',render:r=><div><strong>{tripName(r.trip_id)}</strong><div className="muted-small">{tripSeatText(r.trip_id)}</div></div>},{key:'vehicle',label:'الباص',render:r=><div><strong>{vehicleName(r.vehicle_id)}</strong>{duplicateKeys.has(`${s(r.trip_id)}|${s(r.vehicle_id)}`)&&<div><Badge tone="red">ربط مكرر</Badge></div>}</div>},{key:'driver_id',label:'السائق',render:r=><div><strong>{driverName(r.driver_id)}</strong>{r.extra_driver_id&&<div className="muted-small">إضافي: {driverName(r.extra_driver_id)}</div>}{driverConflictIds.has(s(r.id))&&<div><Badge tone="red">تعارض سائق</Badge></div>}</div>},{key:'capacity',label:'المقاعد',render:r=>{const x=busSeatStats(r);return <div><b>{x.available} متاح</b><div className="muted-small">معيّن {x.assigned} · احتياطي/محجوب {x.reserved} · سعة الباص {x.cap}</div></div>}},{key:'status',label:'الحالة',render:r=><Badge>{statusLabel(r.status)}</Badge>},{key:'action',label:'',render:r=>canAssignFleet?<div className="finance-actions"><Button onClick={()=>setModal({type:'crew',row:r})}><Pencil size={14}/> تعديل السائق</Button><Button onClick={()=>setModal({type:'swap',row:r})}><Repeat2 size={14}/> تبديل الباص</Button><Button onClick={()=>unlinkAssignment(r)}><Unlink size={14}/> فك الربط</Button></div>:'—'}];
 const maintenanceCols=[{key:'vehicle',label:'المركبة',render:r=>vehicleName(r.vehicle_id)},{key:'maintenance_type',label:'العملية'},{key:'due_date',label:'الاستحقاق'},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='completed'?'green':r.status==='planned'?'orange':'blue'}>{statusLabel(r.status)}</Badge>},{key:'cost',label:'التكلفة',render:r=>money(r.cost)},{key:'completed_at',label:'تمت',render:r=>r.completed_at?dateTime(r.completed_at):'—'},{key:'action',label:'',render:r=>canMaintenance?<Button onClick={()=>setModal({type:'maintenance',row:r})}>تعديل</Button>:'—'}];
 const tabs=[...(canViewFleet?[['vehicles','المركبات',vehicles.length]]:[]),...(canViewDrivers?[['drivers','السائقون',drivers.length]]:[]),...(canAssignFleet?[['assignments','ربط الرحلات',assignments.length]]:[]),...(canMaintenance?[['maintenance','الصيانة',maintenance.length]]:[])];
 useEffect(()=>{if(tabs.length&&!tabs.some(([k])=>k===tab))setTab(tabs[0][0])},[canViewFleet,canViewDrivers,canAssignFleet,canMaintenance]);
 const currentRows=tab==='vehicles'?vehicles:tab==='drivers'?drivers:tab==='assignments'?assignments:maintenance;const currentCols=tab==='vehicles'?vehicleCols:tab==='drivers'?driverCols:tab==='assignments'?assignmentCols:maintenanceCols;
 return <><PageHeader title="الأسطول والسائقون" subtitle="كل باص يحسب مقاعده وحده، والسائق لا يتكرر على أكثر من باص في نفس الرحلة" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث</Button>}/><ErrorBox error={error}/>{notice&&<div className="training-banner" style={{background:'#ecfdf3',color:'#166534',borderColor:'#bbf7d0'}}>{notice}</div>}{duplicateKeys.size>0&&<div className="error-box">يوجد ربط مكرر قديم لنفس الباص على نفس الرحلة. استخدم «فك الربط» لإزالة النسخة الزائدة؛ النظام يمنع أي تكرار جديد.</div>}{driverConflictIds.size>0&&<div className="error-box">يوجد تعارض قديم في السائقين: نفس السائق معيّن أكثر من مرة داخل نفس الرحلة أو معيّن كأساسي وإضافي. عدّل السائق في الصفوف المعلّمة «تعارض سائق».</div>}<Card><div className="fleet-head"><div><BusFront size={22}/><b>نطاق الأسطول: {allOps(user)?'كل التشغيل المسموح':'فرعك والرحلات المشتركة'}</b></div><div className="finance-actions">{canAddVehicle&&<Button variant="primary" onClick={()=>setModal({type:'vehicle'})}><Plus size={16}/> مركبة</Button>}{canAddDriver&&<Button onClick={()=>setModal({type:'driver'})}><UserRound size={16}/> سائق</Button>}{canAssignFleet&&<Button onClick={()=>setModal({type:'assign'})}><Link2 size={16}/> ربط برحلة</Button>}{canMaintenance&&<Button onClick={()=>setModal({type:'maintenance'})}><Wrench size={16}/> صيانة</Button>}</div></div></Card><div className="module-tabs">{tabs.map(([k,l,n])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l} <Badge>{n}</Badge></button>)}</div>{!data&&canViewFleet?<Loading/>:<Card><Table rows={currentRows} columns={currentCols}/></Card>}
 <Modal open={modal?.type==='vehicle'} onClose={()=>setModal(null)} title={modal?.row?'تعديل مركبة':'إضافة مركبة'}><form onSubmit={saveVehicle} className="form-grid"><Field label="الرمز"><Input name="code" defaultValue={modal?.row?.code||''}/></Field><Field label="الاسم"><Input name="name" defaultValue={modal?.row?.name||''}/></Field><Field label="رقم اللوحة"><Input name="plate_no" defaultValue={modal?.row?.plate_no||''} required/></Field><Field label="الفرع"><Select name="branch_id" defaultValue={modal?.row?.branch_id||app.scope?.branch_id||''}><option value="">غير محدد</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name||b.branch_name}</option>)}</Select></Field><Field label="السعة الفعلية"><Input name="physical_capacity" type="number" min="1" defaultValue={modal?.row?.physical_capacity||49}/></Field><Field label="سعة الحجز"><Input name="booking_capacity" type="number" min="1" defaultValue={modal?.row?.booking_capacity||modal?.row?.physical_capacity||49}/></Field><Field label="الحالة"><Select name="status" defaultValue={modal?.row?.status||'available'}><option value="available">متاحة</option><option value="maintenance">صيانة</option><option value="out_of_service">خارج الخدمة</option></Select></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>حفظ</Button></div></form></Modal>
 <Modal open={modal?.type==='driver'} onClose={()=>setModal(null)} title={modal?.row?'تعديل سائق':'إضافة سائق'}><form onSubmit={saveDriver} className="form-grid"><Field label="الاسم"><Input name="name" defaultValue={modal?.row?.name||''} required/></Field><Field label="الجوال"><Input name="phone" defaultValue={modal?.row?.phone||''} required/></Field><Field label="الهوية"><Input name="national_id" defaultValue={modal?.row?.national_id||''}/></Field><Field label="رقم الرخصة"><Input name="license_no" defaultValue={modal?.row?.license_no||''}/></Field><Field label="انتهاء الرخصة"><Input name="license_expiry" type="date" defaultValue={modal?.row?.license_expiry||''}/></Field><Field label="الفرع"><Select name="branch_id" defaultValue={modal?.row?.branch_id||app.scope?.branch_id||''}><option value="">غير محدد</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name||b.branch_name}</option>)}</Select></Field><Field label="الحالة"><Select name="status" defaultValue={modal?.row?.status||'active'}><option value="active">نشط</option><option value="inactive">موقوف</option></Select></Field><Field label="ملاحظات"><Textarea name="notes" defaultValue={modal?.row?.notes||''}/></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>حفظ</Button></div></form></Modal>
 <Modal open={modal?.type==='assign'} onClose={()=>setModal(null)} title="ربط مركبة برحلة"><form onSubmit={assignVehicle} className="form-grid"><Field label="الرحلة"><Select name="trip_id" required><option value="">اختر</option>{trips.map(t=><option key={t.id} value={t.id}>{tripName(t.id)} — {tripSeatText(t.id)}</option>)}</Select></Field><Field label="المركبة"><Select name="vehicle_id" required><option value="">اختر</option>{vehicles.filter(v=>v.status==='available'||!v.status).map(v=><option key={v.id} value={v.id}>{vehicleName(v.id)} — سعة {v.booking_capacity||v.physical_capacity||0}</option>)}</Select></Field><Field label="السائق"><Select name="driver_id"><option value="">بدون</option>{drivers.filter(d=>d.status!=='inactive').map(d=><option key={d.id} value={d.id}>{driverName(d.id)}</option>)}</Select></Field><Field label="سائق إضافي"><Select name="extra_driver_id"><option value="">بدون</option>{drivers.filter(d=>d.status!=='inactive').map(d=><option key={d.id} value={d.id}>{driverName(d.id)}</option>)}</Select></Field><Field label="رمز الباص"><Input name="bus_label"/></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>ربط</Button></div></form></Modal>
 <Modal open={modal?.type==='crew'} onClose={()=>setModal(null)} title={`تعديل سائق ${modal?.row?vehicleName(modal.row.vehicle_id):''}`}><form onSubmit={saveCrew} className="form-grid"><div className="success-note" style={{gridColumn:'1/-1'}}>{modal?.row?`${tripName(modal.row.trip_id)} — مقاعد هذا الباص: متاح ${busSeatStats(modal.row).available} من ${busSeatStats(modal.row).cap}`:''}</div><Field label="السائق"><Select name="driver_id" defaultValue={modal?.row?.driver_id||''}><option value="">بدون</option>{drivers.filter(d=>d.status!=='inactive').map(d=><option key={d.id} value={d.id}>{driverName(d.id)}</option>)}</Select></Field><Field label="السائق الإضافي"><Select name="extra_driver_id" defaultValue={modal?.row?.extra_driver_id||''}><option value="">بدون</option>{drivers.filter(d=>d.status!=='inactive').map(d=><option key={d.id} value={d.id}>{driverName(d.id)}</option>)}</Select></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>حفظ الطاقم</Button></div></form></Modal>
 <Modal open={modal?.type==='swap'} onClose={()=>setModal(null)} title="تبديل الباص"><form onSubmit={swapVehicle} className="form-grid"><div className="success-note" style={{gridColumn:'1/-1'}}>{modal?.row?`${tripName(modal.row.trip_id)} — الباص الحالي متاح ${busSeatStats(modal.row).available} من ${busSeatStats(modal.row).cap}`:''}</div><Field label="الباص البديل"><Select name="new_vehicle_id" required><option value="">اختر</option>{vehicles.filter(v=>s(v.id)!==s(modal?.row?.vehicle_id)&&(v.status==='available'||!v.status)).map(v=><option key={v.id} value={v.id}>{vehicleName(v.id)} — سعة {v.booking_capacity||v.physical_capacity||0}</option>)}</Select></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>تبديل آمن</Button></div></form></Modal>
 <Modal open={modal?.type==='maintenance'} onClose={()=>setModal(null)} title="صيانة مركبة"><form onSubmit={saveMaintenance} className="form-grid"><Field label="المركبة"><Select name="vehicle_id" defaultValue={modal?.row?.vehicle_id||''} required><option value="">اختر</option>{vehicles.map(v=><option key={v.id} value={v.id}>{vehicleName(v.id)}</option>)}</Select></Field><Field label="نوع الصيانة"><Input name="maintenance_type" defaultValue={modal?.row?.maintenance_type||''}/></Field><Field label="الاستحقاق"><Input name="due_date" type="date" defaultValue={modal?.row?.due_date||''}/></Field><Field label="الحالة"><Select name="status" defaultValue={modal?.row?.status||'planned'}><option value="planned">مخططة</option><option value="in_progress">جارية</option><option value="completed">مكتملة</option></Select></Field><Field label="التكلفة"><Input name="cost" type="number" min="0" defaultValue={modal?.row?.cost||0}/></Field><Field label="ملاحظات"><Textarea name="notes" defaultValue={modal?.row?.notes||''}/></Field><div className="modal-actions"><Button type="button" onClick={()=>setModal(null)}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>حفظ</Button></div></form></Modal></>;
}
