import React,{useEffect,useMemo,useState} from 'react';
import {BusFront,Plus,RefreshCw,Repeat2,Wrench,Link2} from 'lucide-react';
import {useAppData} from '../../core/AppDataContext.jsx';
import {useAuth} from '../../core/AuthContext.jsx';
import {api} from '../../lib/api.js';
import {allOps} from '../../lib/permissions.js';
import {Badge,Button,Card,ErrorBox,Field,Input,Loading,Modal,PageHeader,Select,Table,Textarea} from '../../components/UI.jsx';
import {dateTime,money} from '../../lib/format.js';

const s=v=>String(v??'');
const statusLabel=v=>({available:'متاحة',assigned:'مُعيّنة',maintenance:'صيانة',out_of_service:'خارج الخدمة',planned:'مخططة',completed:'مكتملة',cancelled:'ملغاة'}[s(v)]||v||'—');
export default function Fleet(){
 const {user}=useAuth(),{data:app}=useAppData();const [data,setData]=useState(null),[tab,setTab]=useState('vehicles'),[modal,setModal]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setError('');try{setData(await api.module('fleet'))}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 const branches=app.branches||[],trips=app.trips||[],vehicles=data?.vehicles||[],assignments=data?.trip_vehicles||[],maintenance=data?.vehicle_maintenance||[];
 const branchMap=useMemo(()=>new Map(branches.map(x=>[s(x.id),x.name||x.branch_name||x.id])),[branches]);const vehicleMap=useMemo(()=>new Map(vehicles.map(x=>[s(x.id),x])),[vehicles]);const tripMap=useMemo(()=>new Map(trips.map(x=>[s(x.id),x])),[trips]);
 function vehicleName(id){const v=vehicleMap.get(s(id));return v?`${v.code||v.name||'باص'}${v.plate_no?` — ${v.plate_no}`:''}`:'—'}
 async function saveVehicle(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),old=modal?.row;const row={branch_id:f.branch_id||app.scope?.branch_id||null,code:f.code||null,name:f.name||null,plate_no:f.plate_no,vehicle_type:f.vehicle_type||'bus',physical_capacity:Number(f.physical_capacity||49),booking_capacity:Number(f.booking_capacity||f.physical_capacity||49),status:f.status||'available',notes:f.notes||''};if(row.booking_capacity>row.physical_capacity){setError('سعة الحجز لا يمكن أن تتجاوز السعة الفعلية');return}setBusy(true);try{await api.moduleWrite(old?{action:'update',table:'vehicles',id:old.id,row}:{action:'insert',table:'vehicles',row});await load();setModal(null)}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function assignVehicle(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),v=vehicleMap.get(s(f.vehicle_id));if(!v)return;const row={trip_id:f.trip_id,vehicle_id:f.vehicle_id,bus_label:f.bus_label||v.code||v.name||'باص',capacity:Number(v.physical_capacity||49),booking_capacity:Number(v.booking_capacity||v.physical_capacity||49),driver_id:f.driver_id||null,extra_driver_id:f.extra_driver_id||null,supervisor_id:f.supervisor_id||null,status:'assigned'};setBusy(true);try{await api.moduleWrite({action:'insert',table:'trip_vehicles',row});await load();setModal(null)}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function swapVehicle(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),row=modal?.row;if(!row)return;setBusy(true);try{await api.mega('bus_swap',{trip_vehicle_id:row.id,new_vehicle_id:f.new_vehicle_id});await load();setModal(null)}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function saveMaintenance(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),old=modal?.row;const row={vehicle_id:f.vehicle_id,maintenance_type:f.maintenance_type||null,due_date:f.due_date||null,status:f.status||'planned',cost:Number(f.cost||0),completed_at:f.status==='completed'?(old?.completed_at||new Date().toISOString()):null,notes:f.notes||''};setBusy(true);try{await api.moduleWrite(old?{action:'update',table:'vehicle_maintenance',id:old.id,row}:{action:'insert',table:'vehicle_maintenance',row});await load();setModal(null)}catch(x){setError(x.message)}finally{setBusy(false)}}
 const vehicleCols=[{key:'vehicle',label:'المركبة',render:r=><div><strong>{r.code||r.name||'باص'}</strong><div className="muted-small">{r.plate_no||'بدون لوحة'}</div></div>},{key:'branch',label:'الفرع',render:r=>branchMap.get(s(r.branch_id))||'—'},{key:'capacity',label:'السعة',render:r=>`${r.booking_capacity||r.physical_capacity||0} / ${r.physical_capacity||0}`},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='available'?'green':r.status==='maintenance'?'orange':'blue'}>{statusLabel(r.status)}</Badge>},{key:'action',label:'',render:r=><Button onClick={()=>setModal({type:'vehicle',row:r})}>تعديل</Button>}];
 const assignmentCols=[{key:'trip',label:'الرحلة',render:r=>{const t=tripMap.get(s(r.trip_id));return t?`${t.trip_code||''} ${t.from_city||t.origin||''} ← ${t.to_city||t.destination||''}`:'—'}},{key:'vehicle',label:'الباص',render:r=>vehicleName(r.vehicle_id)},{key:'bus_label',label:'الرمز'},{key:'driver_id',label:'السائق',render:r=>r.driver_id||'—'},{key:'capacity',label:'السعة',render:r=>r.booking_capacity||r.capacity||'—'},{key:'status',label:'الحالة',render:r=><Badge>{statusLabel(r.status)}</Badge>},{key:'action',label:'',render:r=><Button onClick={()=>setModal({type:'swap',row:r})}><Repeat2 size={15}/> تبديل آمن</Button>}];
 const maintenanceCols=[{key:'vehicle',label:'المركبة',render:r=>vehicleName(r.vehicle_id)},{key:'maintenance_type',label:'العملية'},{key:'due_date',label:'الاستحقاق'},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='completed'?'green':r.status==='planned'?'orange':'blue'}>{statusLabel(r.status)}</Badge>},{key:'cost',label:'التكلفة',render:r=>money(r.cost)},{key:'completed_at',label:'تمت',render:r=>r.completed_at?dateTime(r.completed_at):'—'},{key:'action',label:'',render:r=><Button onClick={()=>setModal({type:'maintenance',row:r})}>تعديل</Button>}];
 const tabs=[['vehicles','المركبات',vehicles.length],['assignments','ربط الرحلات',assignments.length],['maintenance','الصيانة',maintenance.length]];
 return <><PageHeader title="الأسطول" subtitle="المركبات وربطها بالرحلات والصيانة وتبديل الباص بدون كسر توزيع المقاعد" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث</Button>}/><ErrorBox error={error}/><Card><div className="fleet-head"><div><BusFront size={22}/><b>نطاق الأسطول: {allOps(user)?'كل التشغيل المسموح':'فرعك والرحلات المشتركة'}</b></div><div className="finance-actions"><Button variant="primary" onClick={()=>setModal({type:'vehicle'})}><Plus size={16}/> مركبة</Button><Button onClick={()=>setModal({type:'assign'})}><Link2 size={16}/> ربط برحلة</Button><Button onClick={()=>setModal({type:'maintenance'})}><Wrench size={16}/> صيانة</Button></div></div></Card><div className="tabs">{tabs.map(([k,l,n])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}<span>{n}</span></button>)}</div>{!data&&!error?<Loading/>:<Card><Table rows={tab==='vehicles'?vehicles:tab==='assignments'?assignments:maintenance} columns={tab==='vehicles'?vehicleCols:tab==='assignments'?assignmentCols:maintenanceCols}/></Card>}
 <Modal open={modal?.type==='vehicle'} onClose={()=>setModal(null)} title={modal?.row?'تعديل المركبة':'مركبة جديدة'}><form className="form-grid" onSubmit={saveVehicle}><Field label="الفرع"><Select name="branch_id" defaultValue={modal?.row?.branch_id||app.scope?.branch_id||''} disabled={!allOps(user)}><option value="">اختر</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name||b.branch_name}</option>)}</Select>{!allOps(user)&&<input type="hidden" name="branch_id" value={app.scope?.branch_id||''}/>}</Field><Field label="كود المركبة"><Input name="code" defaultValue={modal?.row?.code||''}/></Field><Field label="الاسم"><Input name="name" defaultValue={modal?.row?.name||''}/></Field><Field label="رقم اللوحة"><Input name="plate_no" defaultValue={modal?.row?.plate_no||''} required/></Field><Field label="النوع"><Select name="vehicle_type" defaultValue={modal?.row?.vehicle_type||'bus'}><option value="bus">باص</option><option value="minibus">ميني باص</option><option value="car">سيارة</option></Select></Field><Field label="السعة الفعلية"><Input name="physical_capacity" type="number" min="1" defaultValue={modal?.row?.physical_capacity||49} required/></Field><Field label="سعة الحجز"><Input name="booking_capacity" type="number" min="1" defaultValue={modal?.row?.booking_capacity||49} required/></Field><Field label="الحالة"><Select name="status" defaultValue={modal?.row?.status||'available'}><option value="available">متاحة</option><option value="assigned">مُعيّنة</option><option value="maintenance">صيانة</option><option value="out_of_service">خارج الخدمة</option></Select></Field><Field label="ملاحظات"><Textarea name="notes" defaultValue={modal?.row?.notes||''}/></Field><Actions busy={busy} close={()=>setModal(null)}/></form></Modal>
 <Modal open={modal?.type==='assign'} onClose={()=>setModal(null)} title="ربط باص برحلة"><form className="form-grid" onSubmit={assignVehicle}><Field label="الرحلة"><Select name="trip_id" required><option value="">اختر</option>{trips.map(t=><option key={t.id} value={t.id}>{t.trip_code} — {t.from_city||t.origin} ← {t.to_city||t.destination}</option>)}</Select></Field><Field label="المركبة"><Select name="vehicle_id" required><option value="">اختر</option>{vehicles.filter(v=>v.status!=='out_of_service').map(v=><option key={v.id} value={v.id}>{v.code||v.name||'باص'} — {v.plate_no||'بدون لوحة'} ({v.booking_capacity||v.physical_capacity})</option>)}</Select></Field><Field label="اسم/رمز الباص"><Input name="bus_label" placeholder="باص 1"/></Field><Field label="السائق"><Input name="driver_id" placeholder="اسم أو معرف السائق"/></Field><Field label="السائق الإضافي"><Input name="extra_driver_id"/></Field><Field label="المشرف"><Input name="supervisor_id"/></Field><Actions busy={busy} close={()=>setModal(null)}/></form></Modal>
 <Modal open={modal?.type==='swap'} onClose={()=>setModal(null)} title="تبديل الباص بأمان"><form className="form-grid" onSubmit={swapVehicle}><Card><b>الحالي:</b> {vehicleName(modal?.row?.vehicle_id)}<div className="muted-small">لن يتم التبديل إذا كانت سعة الباص الجديد أقل من المقاعد المستخدمة.</div></Card><Field label="الباص البديل"><Select name="new_vehicle_id" required><option value="">اختر</option>{vehicles.filter(v=>s(v.id)!==s(modal?.row?.vehicle_id)&&v.status!=='out_of_service').map(v=><option key={v.id} value={v.id}>{v.code||v.name||'باص'} — {v.plate_no||'بدون لوحة'} ({v.booking_capacity||v.physical_capacity})</option>)}</Select></Field><Actions busy={busy} close={()=>setModal(null)} save="تنفيذ التبديل"/></form></Modal>
 <Modal open={modal?.type==='maintenance'} onClose={()=>setModal(null)} title={modal?.row?'تعديل الصيانة':'تسجيل صيانة'}><form className="form-grid" onSubmit={saveMaintenance}><Field label="المركبة"><Select name="vehicle_id" defaultValue={modal?.row?.vehicle_id||''} required><option value="">اختر</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.code||v.name||'باص'} — {v.plate_no}</option>)}</Select></Field><Field label="نوع الصيانة"><Input name="maintenance_type" defaultValue={modal?.row?.maintenance_type||''} placeholder="زيت / إطارات / دورية..." required/></Field><Field label="تاريخ الاستحقاق"><Input type="date" name="due_date" defaultValue={modal?.row?.due_date||''}/></Field><Field label="الحالة"><Select name="status" defaultValue={modal?.row?.status||'planned'}><option value="planned">مخططة</option><option value="in_progress">جارية</option><option value="completed">مكتملة</option><option value="cancelled">ملغاة</option></Select></Field><Field label="التكلفة"><Input type="number" name="cost" min="0" step="0.01" defaultValue={modal?.row?.cost||0}/></Field><Field label="ملاحظات"><Textarea name="notes" defaultValue={modal?.row?.notes||''}/></Field><Actions busy={busy} close={()=>setModal(null)}/></form></Modal></>;
}
function Actions({busy,close,save='حفظ'}){return <div className="modal-actions"><Button type="button" onClick={close}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>{busy?'جاري الحفظ...':save}</Button></div>}
