import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRightLeft,MapPin,Plus,RefreshCw,Clock3,CheckCircle2} from 'lucide-react';
import {useAppData} from '../../core/AppDataContext.jsx';
import {api} from '../../lib/api.js';
import {Badge,Button,Card,ErrorBox,Field,Input,Loading,Modal,PageHeader,Select,Table,Textarea} from '../../components/UI.jsx';
import {dateTime,tripDisplay} from '../../lib/format.js';

const s=v=>String(v??'');
const EVENT_LABELS={outbound_meeting:'تجمع الذهاب',outbound_departure:'انطلاق الذهاب',outbound_arrival:'وصول الذهاب',return_meeting:'تجمع العودة',return_departure:'انطلاق العودة',return_arrival:'وصول العودة',trip_completed:'اكتمال الرحلة'};
export default function Returns({initialTrip=''}){
 const {data:app}=useAppData();const [data,setData]=useState(null),[tripId,setTripId]=useState(initialTrip),[tab,setTab]=useState('timeline'),[modal,setModal]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setError('');try{const x=await api.module('return_ops');setData(x);if(!tripId){const preferred=(app.trips||[]).find(t=>t.return_date||t.return_trip_id)||(app.trips||[])[0];if(preferred)setTripId(s(preferred.id))}}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 const trip=useMemo(()=>(app.trips||[]).find(t=>s(t.id)===tripId),[app.trips,tripId]);
 const branchMap=useMemo(()=>new Map((app.branches||[]).map(b=>[s(b.id),b.name||b.branch_name||b.id])),[app.branches]);
 const events=(data?.trip_status_events||[]).filter(x=>s(x.trip_id)===tripId).sort((a,b)=>new Date(a.actual_at||a.planned_at||a.created_at)-new Date(b.actual_at||b.planned_at||b.created_at));
 const points=(data?.trip_meeting_points||[]).filter(x=>s(x.trip_id)===tripId).sort((a,b)=>new Date(a.meeting_at||0)-new Date(b.meeting_at||0));
 const notifications=(data?.notifications||[]).filter(x=>s(x.trip_id)===tripId);
 async function saveEvent(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),old=modal?.row;const row={trip_id:tripId,event_key:f.event_key,planned_at:f.planned_at?new Date(f.planned_at).toISOString():null,actual_at:f.actual_at?new Date(f.actual_at).toISOString():null,notes:f.notes||'',metadata:{source:'almaher-next'}};setBusy(true);try{await api.moduleWrite(old?{action:'update',table:'trip_status_events',id:old.id,row}:{action:'insert',table:'trip_status_events',row});await load();setModal(null)}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function markNow(key){if(!tripId)return;setBusy(true);try{await api.moduleWrite({action:'insert',table:'trip_status_events',row:{trip_id:tripId,event_key:key,actual_at:new Date().toISOString(),notes:'تسجيل مباشر من مركز العودة',metadata:{source:'quick_action'}}});await load()}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function savePoint(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),old=modal?.row;const row={trip_id:tripId,branch_id:f.branch_id||null,name:f.name,address:f.address||null,map_url:f.map_url||null,meeting_at:f.meeting_at?new Date(f.meeting_at).toISOString():null,departure_at:f.departure_at?new Date(f.departure_at).toISOString():null,direction:f.direction||'return',responsible_staff_id:f.responsible_staff_id||null,status:f.status||'open'};setBusy(true);try{await api.moduleWrite(old?{action:'update',table:'trip_meeting_points',id:old.id,row}:{action:'insert',table:'trip_meeting_points',row});await load();setModal(null)}catch(x){setError(x.message)}finally{setBusy(false)}}
 const eventCols=[{key:'event',label:'الحدث',render:r=><b>{EVENT_LABELS[r.event_key]||r.event_key}</b>},{key:'planned_at',label:'المخطط',render:r=>r.planned_at?dateTime(r.planned_at):'—'},{key:'actual_at',label:'الفعلي',render:r=>r.actual_at?<Badge tone="green">{dateTime(r.actual_at)}</Badge>:'—'},{key:'notes',label:'ملاحظات'},{key:'action',label:'',render:r=><Button onClick={()=>setModal({type:'event',row:r})}>تعديل</Button>}];
 const pointCols=[{key:'name',label:'نقطة التجمع',render:r=><div><b>{r.name}</b><div className="muted-small">{r.address||'—'}</div></div>},{key:'branch',label:'الفرع',render:r=>branchMap.get(s(r.branch_id))||'عام'},{key:'direction',label:'المسار',render:r=><Badge tone={r.direction==='return'?'orange':'blue'}>{r.direction==='return'?'عودة':'ذهاب'}</Badge>},{key:'meeting_at',label:'التجمع',render:r=>r.meeting_at?dateTime(r.meeting_at):'—'},{key:'departure_at',label:'الانطلاق',render:r=>r.departure_at?dateTime(r.departure_at):'—'},{key:'status',label:'الحالة',render:r=><Badge>{r.status||'open'}</Badge>},{key:'map',label:'',render:r=>r.map_url?<a className="button-link" href={r.map_url} target="_blank" rel="noreferrer">الخريطة</a>:null},{key:'action',label:'',render:r=><Button onClick={()=>setModal({type:'point',row:r})}>تعديل</Button>}];
 const notificationCols=[{key:'created_at',label:'أنشئ',render:r=>dateTime(r.created_at)},{key:'channel',label:'القناة'},{key:'recipient',label:'المستلم'},{key:'template_key',label:'القالب'},{key:'scheduled_at',label:'الموعد',render:r=>r.scheduled_at?dateTime(r.scheduled_at):'—'},{key:'status',label:'الحالة',render:r=><Badge tone={r.status==='failed'?'red':r.status==='sent'||r.status==='delivered'?'green':'blue'}>{r.status}</Badge>}];
 return <><PageHeader title="محرك العودة" subtitle="نقاط التجمع، توقيتات العودة، الحالة الفعلية وتنبيهات الرحلة" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث</Button>}/><ErrorBox error={error}/><Card><div className="return-toolbar"><Field label="الرحلة"><Select value={tripId} onChange={e=>setTripId(e.target.value)}><option value="">اختر رحلة</option>{(app.trips||[]).map(t=><option key={t.id} value={t.id}>{tripDisplay(t)}</option>)}</Select></Field>{trip&&<div className="return-trip-summary"><ArrowRightLeft size={18}/><div><b>{tripDisplay(trip)}</b><span>العودة: {trip.return_date||'—'}</span></div></div>}</div><div className="return-quick"><Button onClick={()=>markNow('return_meeting')} disabled={!tripId||busy}><Clock3 size={16}/> بدأ تجمع العودة</Button><Button variant="primary" onClick={()=>markNow('return_departure')} disabled={!tripId||busy}><ArrowRightLeft size={16}/> انطلقت العودة</Button><Button onClick={()=>markNow('return_arrival')} disabled={!tripId||busy}><CheckCircle2 size={16}/> وصلت العودة</Button></div></Card><div className="tabs"><button className={tab==='timeline'?'active':''} onClick={()=>setTab('timeline')}>الخط الزمني<span>{events.length}</span></button><button className={tab==='points'?'active':''} onClick={()=>setTab('points')}>نقاط التجمع<span>{points.length}</span></button><button className={tab==='notifications'?'active':''} onClick={()=>setTab('notifications')}>التنبيهات<span>{notifications.length}</span></button></div>{!data&&!error?<Loading/>:<Card>{tab==='timeline'&&<><div className="card-title"><h3>أحداث الرحلة</h3><Button variant="primary" disabled={!tripId} onClick={()=>setModal({type:'event'})}><Plus size={16}/> حدث</Button></div><Table rows={events} columns={eventCols}/></>}{tab==='points'&&<><div className="card-title"><h3>نقاط التجمع</h3><Button variant="primary" disabled={!tripId} onClick={()=>setModal({type:'point'})}><MapPin size={16}/> نقطة تجمع</Button></div><Table rows={points} columns={pointCols}/></>}{tab==='notifications'&&<Table rows={notifications} columns={notificationCols}/>}</Card>}
 <Modal open={modal?.type==='event'} onClose={()=>setModal(null)} title={modal?.row?'تعديل حدث':'إضافة حدث'}><form className="form-grid" onSubmit={saveEvent}><Field label="الحدث"><Select name="event_key" defaultValue={modal?.row?.event_key||'return_meeting'}>{Object.entries(EVENT_LABELS).map(([k,l])=><option key={k} value={k}>{l}</option>)}</Select></Field><Field label="الوقت المخطط"><Input type="datetime-local" name="planned_at" defaultValue={toLocal(modal?.row?.planned_at)}/></Field><Field label="الوقت الفعلي"><Input type="datetime-local" name="actual_at" defaultValue={toLocal(modal?.row?.actual_at)}/></Field><Field label="ملاحظات"><Textarea name="notes" defaultValue={modal?.row?.notes||''}/></Field><Actions busy={busy} close={()=>setModal(null)}/></form></Modal>
 <Modal open={modal?.type==='point'} onClose={()=>setModal(null)} title={modal?.row?'تعديل نقطة التجمع':'إضافة نقطة تجمع'}><form className="form-grid" onSubmit={savePoint}><Field label="الاسم"><Input name="name" defaultValue={modal?.row?.name||''} required/></Field><Field label="الفرع"><Select name="branch_id" defaultValue={modal?.row?.branch_id||''}><option value="">عام</option>{(app.branches||[]).map(b=><option key={b.id} value={b.id}>{b.name||b.branch_name}</option>)}</Select></Field><Field label="المسار"><Select name="direction" defaultValue={modal?.row?.direction||'return'}><option value="outbound">ذهاب</option><option value="return">عودة</option></Select></Field><Field label="العنوان"><Input name="address" defaultValue={modal?.row?.address||''}/></Field><Field label="رابط الخريطة"><Input name="map_url" defaultValue={modal?.row?.map_url||''} placeholder="https://..."/></Field><Field label="موعد التجمع"><Input type="datetime-local" name="meeting_at" defaultValue={toLocal(modal?.row?.meeting_at)}/></Field><Field label="موعد الانطلاق"><Input type="datetime-local" name="departure_at" defaultValue={toLocal(modal?.row?.departure_at)}/></Field><Field label="المسؤول"><Input name="responsible_staff_id" defaultValue={modal?.row?.responsible_staff_id||''}/></Field><Field label="الحالة"><Select name="status" defaultValue={modal?.row?.status||'open'}><option value="open">مفتوحة</option><option value="ready">جاهزة</option><option value="departed">غادرت</option><option value="closed">مغلقة</option></Select></Field><Actions busy={busy} close={()=>setModal(null)}/></form></Modal></>;
}
function toLocal(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
function Actions({busy,close}){return <div className="modal-actions"><Button type="button" onClick={close}>إلغاء</Button><Button variant="primary" type="submit" disabled={busy}>{busy?'جاري الحفظ...':'حفظ'}</Button></div>}
