import React,{useEffect,useMemo,useState} from 'react';
import {Armchair,RefreshCw,UserRoundCheck,XCircle,Lock} from 'lucide-react';
import {useAppData} from '../../core/AppDataContext.jsx';
import {api} from '../../lib/api.js';
import {Badge,Button,Card,ErrorBox,Field,Loading,Modal,PageHeader,Select} from '../../components/UI.jsx';
import {tripDisplay} from '../../lib/format.js';

const s=v=>String(v??'');
const active=a=>['assigned','hold','blocked'].includes(s(a?.status).toLowerCase());
export default function Seats({tripId:initialTrip=''}){
 const {data}=useAppData();const [payload,setPayload]=useState(null),[error,setError]=useState(''),[tripId,setTripId]=useState(initialTrip),[tripVehicleId,setTripVehicleId]=useState(''),[segment,setSegment]=useState('outbound'),[seat,setSeat]=useState(null),[busy,setBusy]=useState(false);
 async function load(){setError('');try{setPayload(await api.module('seats'))}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 const tvs=useMemo(()=>payload?.trip_vehicles?.filter(x=>s(x.trip_id)===s(tripId))||[],[payload,tripId]);
 useEffect(()=>{if(tvs.length&&!tvs.some(x=>s(x.id)===s(tripVehicleId)))setTripVehicleId(s(tvs[0].id));if(!tvs.length)setTripVehicleId('')},[tripId,payload]);
 const tv=tvs.find(x=>s(x.id)===s(tripVehicleId));const vehicle=payload?.vehicles?.find(x=>s(x.id)===s(tv?.vehicle_id));
 const seats=useMemo(()=>{const rows=(payload?.vehicle_seats||[]).filter(x=>s(x.vehicle_id)===s(tv?.vehicle_id)&&x.active!==false);if(rows.length)return [...rows].sort((a,b)=>Number(a.seat_index||a.seat_no||0)-Number(b.seat_index||b.seat_no||0));const cap=Number(tv?.booking_capacity||tv?.capacity||vehicle?.booking_capacity||vehicle?.physical_capacity||49);return Array.from({length:cap},(_,i)=>({id:`virtual-${i+1}`,seat_no:String(i+1),seat_index:i+1,seat_type:'passenger',active:true}))},[payload,tv,vehicle]);
 const assignments=useMemo(()=>(payload?.seat_assignments||[]).filter(x=>s(x.trip_vehicle_id)===s(tripVehicleId)&&s(x.segment_type||'outbound')===segment&&active(x)),[payload,tripVehicleId,segment]);
 const bySeat=useMemo(()=>new Map(assignments.map(x=>[s(x.seat_no),x])),[assignments]);
 const tripBookings=useMemo(()=>data.bookings.filter(b=>segment==='outbound'?s(b.trip_id)===s(tripId):(s(b.return_trip_id)===s(tripId)||(s(b.trip_id)===s(tripId)&&['roundtrip','returnonly'].includes(s(b.journey_mode).toLowerCase())))),[data.bookings,tripId,segment]);
 const bookingIds=useMemo(()=>new Set(tripBookings.map(b=>s(b.id))),[tripBookings]);
 const passengers=useMemo(()=>data.passengers.filter(p=>bookingIds.has(s(p.booking_id))&&s(p.status).toLowerCase()!=='cancelled'),[data.passengers,bookingIds]);
 const passengerMap=useMemo(()=>new Map(data.passengers.map(p=>[s(p.id),p])),[data.passengers]);const bookingMap=useMemo(()=>new Map(data.bookings.map(b=>[s(b.id),b])),[data.bookings]);
 async function assign(passengerId){if(!seat||!tv)return;setBusy(true);setError('');try{const current=bySeat.get(s(seat.seat_no));if(current&&current.passenger_id&&s(current.passenger_id)!==s(passengerId))await api.moduleWrite({action:'update',table:'seat_assignments',id:current.id,row:{status:'released'}});const old=assignments.find(a=>s(a.passenger_id)===s(passengerId)&&s(a.seat_no)!==s(seat.seat_no));if(old)await api.moduleWrite({action:'update',table:'seat_assignments',id:old.id,row:{status:'released'}});if(current&&s(current.passenger_id)===s(passengerId))return setSeat(null);const p=passengers.find(x=>s(x.id)===s(passengerId));await api.moduleWrite({action:'insert',table:'seat_assignments',row:{trip_vehicle_id:tripVehicleId,passenger_id:passengerId,booking_id:p?.booking_id||null,segment_type:segment,seat_no:s(seat.seat_no),status:'assigned'}});await load();setSeat(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function release(a){setBusy(true);try{await api.moduleWrite({action:'update',table:'seat_assignments',id:a.id,row:{status:'released'}});await load();setSeat(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function blockSeat(){if(!seat)return;setBusy(true);try{const current=bySeat.get(s(seat.seat_no));if(current)await api.moduleWrite({action:'update',table:'seat_assignments',id:current.id,row:{status:'released'}});await api.moduleWrite({action:'insert',table:'seat_assignments',row:{trip_vehicle_id:tripVehicleId,passenger_id:null,booking_id:null,segment_type:segment,seat_no:s(seat.seat_no),status:'blocked'}});await load();setSeat(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const used=assignments.filter(x=>s(x.status)==='assigned').length;
 return <><PageHeader title="المقاعد" subtitle="خريطة فعلية للباص — تعيين، نقل، تحرير وحجب المقعد" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث</Button>}/><ErrorBox error={error}/><Card><div className="seat-toolbar"><Field label="الرحلة"><Select value={tripId} onChange={e=>setTripId(e.target.value)}><option value="">اختر رحلة</option>{data.trips.map(t=><option key={t.id} value={t.id}>{tripDisplay(t)}</option>)}</Select></Field><Field label="الباص"><Select value={tripVehicleId} onChange={e=>setTripVehicleId(e.target.value)} disabled={!tripId}><option value="">{tvs.length?'اختر الباص':'لا يوجد باص معيّن'}</option>{tvs.map(x=><option key={x.id} value={x.id}>{x.bus_label||payload?.vehicles?.find(v=>s(v.id)===s(x.vehicle_id))?.name||payload?.vehicles?.find(v=>s(v.id)===s(x.vehicle_id))?.plate_no||'باص'}</option>)}</Select></Field><Field label="الاتجاه"><Select value={segment} onChange={e=>setSegment(e.target.value)}><option value="outbound">الذهاب</option><option value="return">العودة</option></Select></Field></div>{tripVehicleId&&<div className="seat-summary"><Badge tone="green">محجوز {used}</Badge><Badge>متاح {Math.max(0,seats.length-assignments.length)}</Badge><Badge tone="orange">إجمالي {seats.length}</Badge></div>}</Card>{!payload&&!error?<Loading/>:tripVehicleId?<Card><div className="bus-seat-map"><div className="bus-front">مقدمة الباص</div><div className="seat-grid">{seats.map(x=>{const a=bySeat.get(s(x.seat_no)),p=passengerMap.get(s(a?.passenger_id));const tone=a?.status==='blocked'?'blocked':a?'assigned':'free';return <button type="button" className={`seat-cell ${tone}`} key={x.id||x.seat_no} onClick={()=>setSeat(x)}><Armchair size={18}/><b>{x.seat_no}</b><small>{a?.status==='blocked'?'محجوب':p?.full_name||'متاح'}</small></button>})}</div></div></Card>:<Card><div className="empty">اختر الرحلة والباص لعرض خريطة المقاعد.</div></Card>}
 <Modal open={!!seat} onClose={()=>setSeat(null)} title={`المقعد ${seat?.seat_no||''}`}><SeatModal seat={seat} assignment={seat?bySeat.get(s(seat.seat_no)):null} passengerMap={passengerMap} bookingMap={bookingMap} passengers={passengers} assignments={assignments} onAssign={assign} onRelease={release} onBlock={blockSeat} busy={busy}/></Modal></>;
}
function SeatModal({seat,assignment,passengerMap,bookingMap,passengers,assignments,onAssign,onRelease,onBlock,busy}){const [pid,setPid]=useState(s(assignment?.passenger_id));const p=passengerMap.get(s(assignment?.passenger_id));return <div className="seat-modal"><div className="seat-current"><Armchair/><div><span>الحالة الحالية</span><strong>{assignment?.status==='blocked'?'محجوب':p?.full_name||'متاح'}</strong>{p&&<small>{bookingMap.get(s(p.booking_id))?.booking_number||''}</small>}</div></div><Field label="المسافر"><Select value={pid} onChange={e=>setPid(e.target.value)}><option value="">اختر مسافرًا</option>{passengers.map(x=>{const current=assignments.find(a=>s(a.passenger_id)===s(x.id));return <option key={x.id} value={x.id}>{x.full_name} — {bookingMap.get(s(x.booking_id))?.booking_number||''}{current?` — مقعد ${current.seat_no}`:''}</option>})}</Select></Field><div className="modal-actions"><Button variant="primary" disabled={!pid||busy} onClick={()=>onAssign(pid)}><UserRoundCheck size={16}/> تعيين للمقعد {seat?.seat_no}</Button>{assignment&&<Button disabled={busy} onClick={()=>onRelease(assignment)}><XCircle size={16}/> تحرير</Button>}<Button disabled={busy} onClick={onBlock}><Lock size={16}/> حجب المقعد</Button></div></div>}
