import React,{useEffect,useMemo,useState} from 'react';
import './seats-queue.css';
import {Armchair,RefreshCw,UserRoundCheck,XCircle,Lock,Clock3,PlayCircle} from 'lucide-react';
import {useAppData} from '../../core/AppDataContext.jsx';
import {api} from '../../lib/api.js';
import {Badge,Button,Card,ErrorBox,Field,Loading,Modal,PageHeader,SearchSelect,Select,Table} from '../../components/UI.jsx';
import {tripDisplay} from '../../lib/format.js';

const s=v=>String(v??'');
const low=v=>s(v).toLowerCase();
const active=a=>['assigned','hold','blocked'].includes(low(a?.status));
export default function Seats({tripId:initialTrip=''}){
 const {data}=useAppData();const [payload,setPayload]=useState(null),[error,setError]=useState(''),[tripId,setTripId]=useState(initialTrip),[tripVehicleId,setTripVehicleId]=useState(''),[segment,setSegment]=useState(''),[seat,setSeat]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){setError('');try{setPayload(await api.module('seats'))}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 const tripOptions=useMemo(()=>[...(data.trips||[])].sort((a,b)=>String(b.departure_date||'').localeCompare(String(a.departure_date||''))).map(t=>({value:t.id,label:tripDisplay(t),searchText:[t.trip_code,t.code,t.from_city,t.to_city,t.origin,t.destination,t.departure_date,t.return_date].filter(Boolean).join(' ')})),[data.trips]);
 const tvs=useMemo(()=>payload?.trip_vehicles?.filter(x=>s(x.trip_id)===s(tripId))||[],[payload,tripId]);
 useEffect(()=>{if(tvs.length&&!tvs.some(x=>s(x.id)===s(tripVehicleId)))setTripVehicleId(s(tvs[0].id));if(!tvs.length)setTripVehicleId('')},[tripId,payload]);
 const tv=tvs.find(x=>s(x.id)===s(tripVehicleId));const vehicle=payload?.vehicles?.find(x=>s(x.id)===s(tv?.vehicle_id));
 const seats=useMemo(()=>{const rows=(payload?.vehicle_seats||[]).filter(x=>s(x.vehicle_id)===s(tv?.vehicle_id)&&x.active!==false);if(rows.length)return [...rows].sort((a,b)=>Number(a.seat_index||a.seat_no||0)-Number(b.seat_index||b.seat_no||0));const cap=Number(tv?.booking_capacity||tv?.capacity||vehicle?.booking_capacity||vehicle?.physical_capacity||49);return Array.from({length:cap},(_,i)=>({id:`virtual-${i+1}`,seat_no:String(i+1),seat_index:i+1,seat_type:'passenger',active:true}))},[payload,tv,vehicle]);
 const assignments=useMemo(()=>(payload?.seat_assignments||[]).filter(x=>s(x.trip_vehicle_id)===s(tripVehicleId)&&s(x.segment_type||'outbound')===segment&&active(x)),[payload,tripVehicleId,segment]);
 const bySeat=useMemo(()=>new Map(assignments.map(x=>[s(x.seat_no),x])),[assignments]);
 const tripBookings=useMemo(()=>data.bookings.filter(b=>{const mode=low(b.journey_mode);if(segment==='outbound')return s(b.trip_id)===s(tripId)&&mode!=='returnonly';if(mode==='separate')return s(b.return_trip_id)===s(tripId);if(mode==='roundtrip'||mode==='returnonly')return s(b.trip_id)===s(tripId);return false}),[data.bookings,tripId,segment]);
 const bookingIds=useMemo(()=>new Set(tripBookings.map(b=>s(b.id))),[tripBookings]);
 const passengers=useMemo(()=>data.passengers.filter(p=>bookingIds.has(s(p.booking_id))&&low(p.status)!=='cancelled'),[data.passengers,bookingIds]);
 const passengerMap=useMemo(()=>new Map(data.passengers.map(p=>[s(p.id),p])),[data.passengers]);const bookingMap=useMemo(()=>new Map(data.bookings.map(b=>[s(b.id),b])),[data.bookings]);
 const assignedPassengerIds=useMemo(()=>new Set(assignments.filter(a=>low(a.status)==='assigned'&&a.passenger_id).map(a=>s(a.passenger_id))),[assignments]);
 const waiting=useMemo(()=>passengers.filter(p=>!assignedPassengerIds.has(s(p.id))).sort((a,b)=>{const ba=bookingMap.get(s(a.booking_id)),bb=bookingMap.get(s(b.booking_id));return String(ba?.created_at||a.created_at||'').localeCompare(String(bb?.created_at||b.created_at||''))||Number(a.passenger_order||0)-Number(b.passenger_order||0)}),[passengers,assignedPassengerIds,bookingMap]);
 const freeSeats=useMemo(()=>seats.filter(x=>!bySeat.has(s(x.seat_no))),[seats,bySeat]);
 async function assign(passengerId,targetSeat=seat){if(!targetSeat||!tv)return;setBusy(true);setError('');setNotice('');try{const current=bySeat.get(s(targetSeat.seat_no));if(current&&s(current.passenger_id)===s(passengerId))return setSeat(null);const p=passengers.find(x=>s(x.id)===s(passengerId));await api.seatAtomic({action:'assign',trip_vehicle_id:tripVehicleId,segment_type:segment,seat_no:s(targetSeat.seat_no),passenger_id:passengerId,booking_id:p?.booking_id||null});await load();setSeat(null);setNotice(`تم تعيين المقعد ${targetSeat.seat_no} بنجاح`)}catch(e){await load();setError(e.message)}finally{setBusy(false)}}
 async function release(a){setBusy(true);setNotice('');setError('');try{await api.seatAtomic({action:'released',trip_vehicle_id:tripVehicleId,segment_type:segment,seat_no:s(a.seat_no)});await load();setSeat(null);setNotice(`تم تحرير المقعد ${a.seat_no}`)}catch(e){await load();setError(e.message)}finally{setBusy(false)}}
 async function reserveSeat(){if(!seat)return;setBusy(true);setNotice('');setError('');try{await api.seatAtomic({action:'hold',trip_vehicle_id:tripVehicleId,segment_type:segment,seat_no:s(seat.seat_no)});await load();setSeat(null);setNotice(`تم حجز المقعد ${seat.seat_no} كاحتياطي`)}catch(e){await load();setError(e.message)}finally{setBusy(false)}}
 async function blockSeat(){if(!seat)return;setBusy(true);setNotice('');setError('');try{await api.seatAtomic({action:'blocked',trip_vehicle_id:tripVehicleId,segment_type:segment,seat_no:s(seat.seat_no)});await load();setSeat(null);setNotice(`تم حجب المقعد ${seat.seat_no}`)}catch(e){await load();setError(e.message)}finally{setBusy(false)}}
 async function promoteNext(targetSeat){const next=waiting[0];if(!next||!targetSeat)return;await assign(next.id,targetSeat)}
 const used=assignments.filter(x=>low(x.status)==='assigned').length,holds=assignments.filter(x=>low(x.status)==='hold').length,blocked=assignments.filter(x=>low(x.status)==='blocked').length;
 const waitingCols=[{key:'order',label:'#',render:(_,i)=>i+1},{key:'full_name',label:'المسافر'},{key:'booking',label:'الحجز',render:p=>bookingMap.get(s(p.booking_id))?.booking_number||'—'},{key:'nationality',label:'الجنسية'},{key:'action',label:'',render:p=>freeSeats.length?<Button disabled={busy} onClick={()=>assign(p.id,freeSeats[0])}><PlayCircle size={14}/> ترقية لأول مقعد متاح</Button>:<Badge tone="orange">بانتظار مقعد</Badge>}];
 return <><PageHeader title="المقاعد" subtitle="خريطة فعلية للباص — تعيين، نقل، تحرير، حجز احتياطي وقائمة انتظار" actions={<Button onClick={load}><RefreshCw size={16}/> تحديث</Button>}/><ErrorBox error={error}/>{notice&&<div className="success-note">{notice}</div>}<Card><div className="seat-toolbar"><Field label="الرحلة"><SearchSelect value={tripId} onChange={e=>setTripId(e.target.value)} options={tripOptions} placeholder="اختر الرحلة"/></Field><Field label="الباص"><Select value={tripVehicleId} onChange={e=>setTripVehicleId(e.target.value)} disabled={!tripId}><option value="">{tvs.length?'اختر الباص':'لا يوجد باص معيّن'}</option>{tvs.map(x=><option key={x.id} value={x.id}>{x.bus_label||payload?.vehicles?.find(v=>s(v.id)===s(x.vehicle_id))?.name||payload?.vehicles?.find(v=>s(v.id)===s(x.vehicle_id))?.plate_no||'باص'}</option>)}</Select></Field><Field label="الاتجاه"><Select value={segment} onChange={e=>setSegment(e.target.value)}><option value="">اختر الاتجاه</option><option value="outbound">الذهاب</option><option value="return">العودة</option></Select></Field></div>{tripVehicleId&&<div className="seat-summary"><Badge tone="green">معيّن {used}</Badge><Badge>متاح {freeSeats.length}</Badge><Badge tone="orange">احتياطي {holds}</Badge><Badge tone="red">محجوب {blocked}</Badge><Badge tone={waiting.length?'orange':'green'}>بدون مقعد {waiting.length}</Badge><Badge>إجمالي {seats.length}</Badge></div>}</Card>{!payload&&!error?<Loading/>:tripVehicleId?<><Card><div className="bus-seat-map"><div className="bus-front">مقدمة الباص</div><div className="seat-grid">{seats.map(x=>{const a=bySeat.get(s(x.seat_no)),p=passengerMap.get(s(a?.passenger_id));const tone=a?.status==='blocked'?'blocked':a?.status==='hold'?'hold':a?'assigned':'free';return <button type="button" className={`seat-cell ${tone}`} key={x.id||x.seat_no} onClick={()=>setSeat(x)}><Armchair size={18}/><b>{x.seat_no}</b><small>{a?.status==='blocked'?'محجوب':a?.status==='hold'?'احتياطي':p?.full_name||'متاح'}</small></button>})}</div></div></Card><Card><div className="card-title"><h3><Clock3 size={18}/> قائمة انتظار المقاعد</h3><Badge tone={waiting.length?'orange':'green'}>{waiting.length}</Badge></div>{waiting.length?<><p className="muted-small">تُرتب تلقائيًا حسب أقدم حجز ثم ترتيب المسافر. عند توفر مقعد يمكن ترقية أول منتظر مباشرة.</p>{freeSeats.length>0&&<Button variant="primary" disabled={busy} onClick={()=>promoteNext(freeSeats[0])}><PlayCircle size={16}/> ترقية أول منتظر إلى المقعد {freeSeats[0].seat_no}</Button>}<Table rows={waiting} columns={waitingCols}/></>:<div className="empty">كل المسافرين لديهم مقاعد محددة.</div>}</Card></>:<Card><div className="empty">اختر الرحلة والباص لعرض خريطة المقاعد.</div></Card>}
 <Modal open={!!seat} onClose={()=>setSeat(null)} title={`المقعد ${seat?.seat_no||''}`}><SeatModal seat={seat} assignment={seat?bySeat.get(s(seat.seat_no)):null} passengerMap={passengerMap} bookingMap={bookingMap} passengers={passengers} assignments={assignments} onAssign={assign} onRelease={release} onReserve={reserveSeat} onBlock={blockSeat} busy={busy}/></Modal></>;
}
function SeatModal({seat,assignment,passengerMap,bookingMap,passengers,assignments,onAssign,onRelease,onReserve,onBlock,busy}){const [pid,setPid]=useState(s(assignment?.passenger_id));const p=passengerMap.get(s(assignment?.passenger_id));return <div className="seat-modal"><div className="seat-current"><Armchair/><div><span>الحالة الحالية</span><strong>{assignment?.status==='blocked'?'محجوب':assignment?.status==='hold'?'محجوز احتياطيًا':p?.full_name||'متاح'}</strong>{p&&<small>{bookingMap.get(s(p.booking_id))?.booking_number||''}</small>}</div></div><Field label="المسافر"><Select value={pid} onChange={e=>setPid(e.target.value)}><option value="">اختر مسافرًا</option>{passengers.map(x=>{const current=assignments.find(a=>s(a.passenger_id)===s(x.id));return <option key={x.id} value={x.id}>{x.full_name} — {bookingMap.get(s(x.booking_id))?.booking_number||''}{current?` — مقعد ${current.seat_no}`:''}</option>})}</Select></Field><div className="modal-actions"><Button variant="primary" disabled={!pid||busy} onClick={()=>onAssign(pid)}><UserRoundCheck size={16}/> تعيين للمقعد {seat?.seat_no}</Button>{assignment&&<Button disabled={busy} onClick={()=>onRelease(assignment)}><XCircle size={16}/> تحرير</Button>}<Button disabled={busy} onClick={onReserve}><Clock3 size={16}/> حجز احتياطي</Button><Button disabled={busy} onClick={onBlock}><Lock size={16}/> حجب المقعد</Button></div></div>}
