import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';

export const LANGUAGES=[
 ['ar','العربية','rtl'],['en','English','ltr'],['tr','Türkçe','ltr'],['hi','हिन्दी','ltr'],['it','Italiano','ltr'],['fr','Français','ltr'],['ur','اردو','rtl']
];
const D={
 ar:{home:'الرئيسية',trips:'الرحلات',bookings:'الحجوزات',passengers:'الركاب',housing:'التسكين',seats:'المقاعد',fleet:'الأسطول والسائقون',finance:'المالية',refunds:'الاسترداد',operations:'التشغيل',scanner:'QR والصعود',crm:'CRM',documents:'المستندات',notifications:'الإشعارات',returns:'العودة',branches:'الفروع',partners:'الموردون والوكلاء',workflow:'المهام والموافقات',staff:'الموظفون',reports:'التقارير',customer:'بوابة العميل',developer:'المطور والنظام',search:'ابحث عن حجز، راكب، رحلة...',logout:'تسجيل الخروج',training:'تدريب',production:'تشغيل فعلي'},
 en:{home:'Home',trips:'Trips',bookings:'Bookings',passengers:'Passengers',housing:'Housing',seats:'Seats',fleet:'Fleet & Drivers',finance:'Finance',refunds:'Refunds',operations:'Operations',scanner:'QR & Boarding',crm:'CRM',documents:'Documents',notifications:'Notifications',returns:'Returns',branches:'Branches',partners:'Suppliers & Agents',workflow:'Tasks & Approvals',staff:'Staff',reports:'Reports',customer:'Customer Portal',developer:'Developer & System',search:'Search booking, passenger, trip...',logout:'Sign out',training:'Training',production:'Production'},
 tr:{home:'Ana Sayfa',trips:'Seferler',bookings:'Rezervasyonlar',passengers:'Yolcular',housing:'Konaklama',seats:'Koltuklar',fleet:'Filo ve Sürücüler',finance:'Finans',refunds:'İadeler',operations:'Operasyon',scanner:'QR ve Biniş',crm:'CRM',documents:'Belgeler',notifications:'Bildirimler',returns:'Dönüşler',branches:'Şubeler',partners:'Tedarikçiler ve Acenteler',workflow:'Görevler ve Onaylar',staff:'Personel',reports:'Raporlar',customer:'Müşteri Portalı',developer:'Geliştirici ve Sistem',search:'Rezervasyon, yolcu, sefer ara...',logout:'Çıkış',training:'Eğitim',production:'Canlı'},
 hi:{home:'मुख्य',trips:'यात्राएँ',bookings:'बुकिंग',passengers:'यात्री',housing:'आवास',seats:'सीटें',fleet:'बेड़ा और ड्राइवर',finance:'वित्त',refunds:'रिफंड',operations:'संचालन',scanner:'QR और बोर्डिंग',crm:'CRM',documents:'दस्तावेज़',notifications:'सूचनाएँ',returns:'वापसी',branches:'शाखाएँ',partners:'आपूर्तिकर्ता और एजेंट',workflow:'कार्य और अनुमोदन',staff:'कर्मचारी',reports:'रिपोर्ट',customer:'ग्राहक पोर्टल',developer:'डेवलपर और सिस्टम',search:'बुकिंग, यात्री, यात्रा खोजें...',logout:'लॉग आउट',training:'प्रशिक्षण',production:'लाइव'},
 it:{home:'Home',trips:'Viaggi',bookings:'Prenotazioni',passengers:'Passeggeri',housing:'Alloggi',seats:'Posti',fleet:'Flotta e Autisti',finance:'Finanza',refunds:'Rimborsi',operations:'Operazioni',scanner:'QR e Imbarco',crm:'CRM',documents:'Documenti',notifications:'Notifiche',returns:'Ritorni',branches:'Filiali',partners:'Fornitori e Agenti',workflow:'Attività e Approvazioni',staff:'Personale',reports:'Report',customer:'Portale Cliente',developer:'Sviluppatore e Sistema',search:'Cerca prenotazione, passeggero, viaggio...',logout:'Esci',training:'Formazione',production:'Produzione'},
 fr:{home:'Accueil',trips:'Voyages',bookings:'Réservations',passengers:'Passagers',housing:'Hébergement',seats:'Sièges',fleet:'Flotte et Chauffeurs',finance:'Finance',refunds:'Remboursements',operations:'Opérations',scanner:'QR et Embarquement',crm:'CRM',documents:'Documents',notifications:'Notifications',returns:'Retours',branches:'Agences',partners:'Fournisseurs et Agents',workflow:'Tâches et Approbations',staff:'Employés',reports:'Rapports',customer:'Portail Client',developer:'Développeur et Système',search:'Rechercher réservation, passager, voyage...',logout:'Déconnexion',training:'Formation',production:'Production'},
 ur:{home:'مرکزی صفحہ',trips:'سفر',bookings:'بکنگز',passengers:'مسافر',housing:'رہائش',seats:'نشستیں',fleet:'فلیٹ اور ڈرائیور',finance:'مالیات',refunds:'واپسی رقم',operations:'آپریشن',scanner:'QR اور بورڈنگ',crm:'CRM',documents:'دستاویزات',notifications:'اطلاعات',returns:'واپسی سفر',branches:'برانچز',partners:'سپلائرز اور ایجنٹس',workflow:'کام اور منظوری',staff:'عملہ',reports:'رپورٹس',customer:'کسٹمر پورٹل',developer:'ڈیولپر اور سسٹم',search:'بکنگ، مسافر، سفر تلاش کریں...',logout:'لاگ آؤٹ',training:'تربیت',production:'عملی'}
};
const C=createContext(null);
export function LanguageProvider({children}){const [language,setLanguageState]=useState(()=>localStorage.getItem('almaher.language')||'ar');const meta=LANGUAGES.find(x=>x[0]===language)||LANGUAGES[0];useEffect(()=>{document.documentElement.lang=language;document.documentElement.dir=meta[2];document.body.dir=meta[2]},[language,meta]);function setLanguage(v){setLanguageState(v);localStorage.setItem('almaher.language',v)}const value=useMemo(()=>({language,setLanguage,dir:meta[2],languages:LANGUAGES,t:(k,f)=>D[language]?.[k]||D.ar[k]||f||k}),[language,meta]);return <C.Provider value={value}>{children}</C.Provider>}
export function useLanguage(){return useContext(C)||{language:'ar',dir:'rtl',languages:LANGUAGES,setLanguage:()=>{},t:(k,f)=>D.ar[k]||f||k}}
export function suggestedLanguageForNationality(n=''){const s=String(n).trim().toLowerCase();if(/تركي|turk/.test(s))return'tr';if(/هند|india|indian/.test(s))return'hi';if(/باكستان|pakistan|urdu/.test(s))return'ur';if(/فرنسا|french|france/.test(s))return'fr';if(/ايطال|ital/.test(s))return'it';if(/سعود|مصر|اردن|الأردن|سوريا|سوري|لبنان|عراق|يمن|عمان|قطر|كويت|بحرين|امارات|الإمارات|مغرب|جزائر|تونس|ليبيا|سودان|فلسطين|موريتان|صومال|جيبوتي|جزر القمر|arab/.test(s))return'ar';return'en'}
