import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';

export const LANGUAGES=[
 ['ar','العربية','rtl','AR','🇸🇦'],
 ['en','English','ltr','EN','🇬🇧'],
 ['tr','Türkçe','ltr','TR','🇹🇷'],
 ['hi','हिन्दी','ltr','HI','🇮🇳'],
 ['it','Italiano','ltr','IT','🇮🇹'],
 ['fr','Français','ltr','FR','🇫🇷'],
 ['ur','اردو','rtl','UR','🇵🇰']
];

const D={
 ar:{
  home:'الرئيسية',trips:'الرحلات',bookings:'الحجوزات',passengers:'الركاب',housing:'التسكين',seats:'المقاعد',fleet:'الأسطول والسائقون',finance:'المالية',refunds:'الاسترداد',operations:'التشغيل',scanner:'QR والصعود',crm:'CRM',documents:'المستندات',notifications:'الإشعارات',returns:'العودة',branches:'الفروع',partners:'الموردون والوكلاء',workflow:'المهام والموافقات',staff:'الموظفون',reports:'التقارير',customer:'بوابة العميل',developer:'المطور والنظام',search:'ابحث عن حجز، راكب، رحلة...',logout:'تسجيل الخروج',training:'تدريب',production:'تشغيل فعلي',
  platform:'منصة التشغيل',collapseMenu:'تصغير القائمة',noSearchResults:'لا توجد نتائج ضمن صلاحياتك الحالية.',booking:'حجز',passenger:'مسافر',trip:'رحلة',user:'المستخدم',roleDeveloper:'مطور',systemDeveloper:'مطور النظام',systemDevelopment:'تطوير وإدارة النظام',trainingBanner:'وضع التدريب — هذا الحساب مخصص للتدريب والبيانات التجريبية',
  dashboardTitle:'مركز تشغيل الماهر',dashboardSubtitle:'نظرة لحظية على الرحلات والحجوزات والاستثناءات',activeTrips:'رحلات نشطة',remainingTotal:'إجمالي المتبقي',nearestTrips:'أقرب الرحلات',viewAll:'عرض الكل',needsAction:'يحتاج تدخل',withoutSeat:'مسافر بدون مقعد',needsHousing:'مسافر يحتاج تسكين',bookingDue:'حجز عليه متبقي',
  refresh:'تحديث',printReport:'طباعة التقرير',exportCsv:'تصدير CSV',financeSubtitle:'التحصيل والمصروفات والخزن والورديات بعزل مالي صارم للفروع',totalBookings:'إجمالي الحجوزات',collected:'المحصل',expenses:'المصروفات',netCollected:'صافي المحصل',financialScope:'النطاق المالي الحالي',allBranches:'كل الفروع',yourBranchOnly:'فرعك فقط',expense:'مصروف',cashRegister:'خزنة',openShift:'فتح وردية'
 },
 en:{
  home:'Home',trips:'Trips',bookings:'Bookings',passengers:'Passengers',housing:'Housing',seats:'Seats',fleet:'Fleet & Drivers',finance:'Finance',refunds:'Refunds',operations:'Operations',scanner:'QR & Boarding',crm:'CRM',documents:'Documents',notifications:'Notifications',returns:'Returns',branches:'Branches',partners:'Suppliers & Agents',workflow:'Tasks & Approvals',staff:'Staff',reports:'Reports',customer:'Customer Portal',developer:'Developer & System',search:'Search booking, passenger, trip...',logout:'Sign out',training:'Training',production:'Production',
  platform:'Operations Platform',collapseMenu:'Collapse menu',noSearchResults:'No results within your current permissions.',booking:'Booking',passenger:'Passenger',trip:'Trip',user:'User',roleDeveloper:'Developer',systemDeveloper:'System Developer',systemDevelopment:'System development & administration',trainingBanner:'Training mode — this account is for training and sample data',
  dashboardTitle:'Operations Center',dashboardSubtitle:'Live overview of trips, bookings and exceptions',activeTrips:'Active trips',remainingTotal:'Total outstanding',nearestTrips:'Upcoming trips',viewAll:'View all',needsAction:'Needs attention',withoutSeat:'passenger without seat',needsHousing:'passenger needs housing',bookingDue:'booking has outstanding balance',
  refresh:'Refresh',printReport:'Print report',exportCsv:'Export CSV',financeSubtitle:'Collections, expenses, registers and shifts with strict branch isolation',totalBookings:'Total bookings',collected:'Collected',expenses:'Expenses',netCollected:'Net collected',financialScope:'Current financial scope',allBranches:'All branches',yourBranchOnly:'Your branch only',expense:'Expense',cashRegister:'Cash register',openShift:'Open shift'
 },
 tr:{
  home:'Ana Sayfa',trips:'Seferler',bookings:'Rezervasyonlar',passengers:'Yolcular',housing:'Konaklama',seats:'Koltuklar',fleet:'Filo ve Sürücüler',finance:'Finans',refunds:'İadeler',operations:'Operasyon',scanner:'QR ve Biniş',crm:'CRM',documents:'Belgeler',notifications:'Bildirimler',returns:'Dönüşler',branches:'Şubeler',partners:'Tedarikçiler ve Acenteler',workflow:'Görevler ve Onaylar',staff:'Personel',reports:'Raporlar',customer:'Müşteri Portalı',developer:'Geliştirici ve Sistem',search:'Rezervasyon, yolcu, sefer ara...',logout:'Çıkış',training:'Eğitim',production:'Canlı',platform:'Operasyon Platformu',collapseMenu:'Menüyü daralt',noSearchResults:'Mevcut yetkileriniz kapsamında sonuç yok.',booking:'Rezervasyon',passenger:'Yolcu',trip:'Sefer',user:'Kullanıcı',roleDeveloper:'Geliştirici',systemDeveloper:'Sistem Geliştiricisi',systemDevelopment:'Sistem geliştirme ve yönetimi',trainingBanner:'Eğitim modu — bu hesap eğitim ve örnek veriler içindir',dashboardTitle:'Operasyon Merkezi',dashboardSubtitle:'Seferler, rezervasyonlar ve istisnalara anlık bakış',activeTrips:'Aktif seferler',remainingTotal:'Toplam bakiye',nearestTrips:'Yaklaşan seferler',viewAll:'Tümünü gör',needsAction:'Müdahale gerekli',withoutSeat:'koltuksuz yolcu',needsHousing:'konaklama gereken yolcu',bookingDue:'bakiyesi kalan rezervasyon',refresh:'Yenile',printReport:'Raporu yazdır',exportCsv:'CSV dışa aktar',financeSubtitle:'Şube bazlı sıkı ayrımla tahsilat, gider, kasa ve vardiyalar',totalBookings:'Toplam rezervasyon',collected:'Tahsil edilen',expenses:'Giderler',netCollected:'Net tahsilat',financialScope:'Mevcut mali kapsam',allBranches:'Tüm şubeler',yourBranchOnly:'Yalnız şubeniz',expense:'Gider',cashRegister:'Kasa',openShift:'Vardiya aç'
 },
 hi:{
  home:'मुख्य',trips:'यात्राएँ',bookings:'बुकिंग',passengers:'यात्री',housing:'आवास',seats:'सीटें',fleet:'बेड़ा और ड्राइवर',finance:'वित्त',refunds:'रिफंड',operations:'संचालन',scanner:'QR और बोर्डिंग',crm:'CRM',documents:'दस्तावेज़',notifications:'सूचनाएँ',returns:'वापसी',branches:'शाखाएँ',partners:'आपूर्तिकर्ता और एजेंट',workflow:'कार्य और अनुमोदन',staff:'कर्मचारी',reports:'रिपोर्ट',customer:'ग्राहक पोर्टल',developer:'डेवलपर और सिस्टम',search:'बुकिंग, यात्री, यात्रा खोजें...',logout:'लॉग आउट',training:'प्रशिक्षण',production:'लाइव',platform:'संचालन प्लेटफ़ॉर्म',collapseMenu:'मेनू छोटा करें',noSearchResults:'आपकी वर्तमान अनुमतियों में कोई परिणाम नहीं।',booking:'बुकिंग',passenger:'यात्री',trip:'यात्रा',user:'उपयोगकर्ता',roleDeveloper:'डेवलपर',systemDeveloper:'सिस्टम डेवलपर',systemDevelopment:'सिस्टम विकास और प्रशासन',trainingBanner:'प्रशिक्षण मोड — यह खाता प्रशिक्षण और नमूना डेटा के लिए है',dashboardTitle:'संचालन केंद्र',dashboardSubtitle:'यात्राओं, बुकिंग और अपवादों का त्वरित दृश्य',activeTrips:'सक्रिय यात्राएँ',remainingTotal:'कुल बकाया',nearestTrips:'आगामी यात्राएँ',viewAll:'सभी देखें',needsAction:'ध्यान आवश्यक',withoutSeat:'यात्री बिना सीट',needsHousing:'यात्री को आवास चाहिए',bookingDue:'बुकिंग पर बकाया',refresh:'रीफ़्रेश',printReport:'रिपोर्ट प्रिंट करें',exportCsv:'CSV निर्यात',financeSubtitle:'शाखा अलगाव के साथ संग्रह, खर्च, नकद रजिस्टर और शिफ्ट',totalBookings:'कुल बुकिंग',collected:'संग्रहित',expenses:'खर्च',netCollected:'शुद्ध संग्रह',financialScope:'वर्तमान वित्तीय दायरा',allBranches:'सभी शाखाएँ',yourBranchOnly:'केवल आपकी शाखा',expense:'खर्च',cashRegister:'कैश रजिस्टर',openShift:'शिफ्ट खोलें'
 },
 it:{home:'Home',trips:'Viaggi',bookings:'Prenotazioni',passengers:'Passeggeri',housing:'Alloggi',seats:'Posti',fleet:'Flotta e Autisti',finance:'Finanza',refunds:'Rimborsi',operations:'Operazioni',scanner:'QR e Imbarco',crm:'CRM',documents:'Documenti',notifications:'Notifiche',returns:'Ritorni',branches:'Filiali',partners:'Fornitori e Agenti',workflow:'Attività e Approvazioni',staff:'Personale',reports:'Report',customer:'Portale Cliente',developer:'Sviluppatore e Sistema',search:'Cerca prenotazione, passeggero, viaggio...',logout:'Esci',training:'Formazione',production:'Produzione',platform:'Piattaforma Operativa',collapseMenu:'Riduci menu',noSearchResults:'Nessun risultato con i permessi attuali.',booking:'Prenotazione',passenger:'Passeggero',trip:'Viaggio',user:'Utente',roleDeveloper:'Sviluppatore',systemDeveloper:'Sviluppatore di sistema',systemDevelopment:'Sviluppo e amministrazione sistema',trainingBanner:'Modalità formazione — account per formazione e dati di prova',dashboardTitle:'Centro Operativo',dashboardSubtitle:'Panoramica di viaggi, prenotazioni ed eccezioni',activeTrips:'Viaggi attivi',remainingTotal:'Totale residuo',nearestTrips:'Viaggi imminenti',viewAll:'Vedi tutto',needsAction:'Richiede intervento',withoutSeat:'passeggero senza posto',needsHousing:'passeggero da alloggiare',bookingDue:'prenotazione con saldo',refresh:'Aggiorna',printReport:'Stampa report',exportCsv:'Esporta CSV',financeSubtitle:'Incassi, spese, casse e turni con isolamento rigoroso per filiale',totalBookings:'Totale prenotazioni',collected:'Incassato',expenses:'Spese',netCollected:'Netto incassato',financialScope:'Ambito finanziario attuale',allBranches:'Tutte le filiali',yourBranchOnly:'Solo la tua filiale',expense:'Spesa',cashRegister:'Cassa',openShift:'Apri turno'},
 fr:{home:'Accueil',trips:'Voyages',bookings:'Réservations',passengers:'Passagers',housing:'Hébergement',seats:'Sièges',fleet:'Flotte et Chauffeurs',finance:'Finance',refunds:'Remboursements',operations:'Opérations',scanner:'QR et Embarquement',crm:'CRM',documents:'Documents',notifications:'Notifications',returns:'Retours',branches:'Agences',partners:'Fournisseurs et Agents',workflow:'Tâches et Approbations',staff:'Employés',reports:'Rapports',customer:'Portail Client',developer:'Développeur et Système',search:'Rechercher réservation, passager, voyage...',logout:'Déconnexion',training:'Formation',production:'Production',platform:'Plateforme Opérationnelle',collapseMenu:'Réduire le menu',noSearchResults:'Aucun résultat dans vos autorisations actuelles.',booking:'Réservation',passenger:'Passager',trip:'Voyage',user:'Utilisateur',roleDeveloper:'Développeur',systemDeveloper:'Développeur système',systemDevelopment:'Développement et administration du système',trainingBanner:'Mode formation — compte réservé à la formation et aux données de test',dashboardTitle:'Centre des Opérations',dashboardSubtitle:'Vue instantanée des voyages, réservations et exceptions',activeTrips:'Voyages actifs',remainingTotal:'Total restant',nearestTrips:'Prochains voyages',viewAll:'Voir tout',needsAction:'Intervention requise',withoutSeat:'passager sans siège',needsHousing:'passager à héberger',bookingDue:'réservation avec solde',refresh:'Actualiser',printReport:'Imprimer le rapport',exportCsv:'Exporter CSV',financeSubtitle:'Encaissements, dépenses, caisses et équipes avec séparation stricte par agence',totalBookings:'Total réservations',collected:'Encaissé',expenses:'Dépenses',netCollected:'Net encaissé',financialScope:'Périmètre financier actuel',allBranches:'Toutes les agences',yourBranchOnly:'Votre agence uniquement',expense:'Dépense',cashRegister:'Caisse',openShift:'Ouvrir équipe'},
 ur:{home:'مرکزی صفحہ',trips:'سفر',bookings:'بکنگز',passengers:'مسافر',housing:'رہائش',seats:'نشستیں',fleet:'فلیٹ اور ڈرائیور',finance:'مالیات',refunds:'واپسی رقم',operations:'آپریشن',scanner:'QR اور بورڈنگ',crm:'CRM',documents:'دستاویزات',notifications:'اطلاعات',returns:'واپسی سفر',branches:'برانچز',partners:'سپلائرز اور ایجنٹس',workflow:'کام اور منظوری',staff:'عملہ',reports:'رپورٹس',customer:'کسٹمر پورٹل',developer:'ڈیولپر اور سسٹم',search:'بکنگ، مسافر، سفر تلاش کریں...',logout:'لاگ آؤٹ',training:'تربیت',production:'عملی',platform:'آپریشن پلیٹ فارم',collapseMenu:'مینو چھوٹا کریں',noSearchResults:'موجودہ اختیارات میں کوئی نتیجہ نہیں۔',booking:'بکنگ',passenger:'مسافر',trip:'سفر',user:'صارف',roleDeveloper:'ڈیولپر',systemDeveloper:'سسٹم ڈیولپر',systemDevelopment:'سسٹم کی تیاری اور انتظام',trainingBanner:'تربیتی موڈ — یہ اکاؤنٹ تربیت اور نمونہ ڈیٹا کے لیے ہے',dashboardTitle:'آپریشن سینٹر',dashboardSubtitle:'سفروں، بکنگز اور استثنائی حالات کا فوری جائزہ',activeTrips:'فعال سفر',remainingTotal:'کل بقایا',nearestTrips:'قریب ترین سفر',viewAll:'سب دیکھیں',needsAction:'توجہ درکار',withoutSeat:'مسافر بغیر نشست',needsHousing:'مسافر کو رہائش درکار',bookingDue:'بکنگ پر بقایا',refresh:'تازہ کریں',printReport:'رپورٹ پرنٹ کریں',exportCsv:'CSV برآمد',financeSubtitle:'برانچ کی سخت علیحدگی کے ساتھ وصولیاں، اخراجات، کیش اور شفٹس',totalBookings:'کل بکنگز',collected:'وصول شدہ',expenses:'اخراجات',netCollected:'خالص وصولی',financialScope:'موجودہ مالی دائرہ',allBranches:'تمام برانچز',yourBranchOnly:'صرف آپ کی برانچ',expense:'خرچ',cashRegister:'کیش',openShift:'شفٹ کھولیں'}
};

const C=createContext(null);
export function LanguageProvider({children}){
 const [language,setLanguageState]=useState(()=>localStorage.getItem('almaher.language')||'ar');
 const meta=LANGUAGES.find(x=>x[0]===language)||LANGUAGES[0];
 useEffect(()=>{document.documentElement.lang=language;document.documentElement.dir=meta[2];document.body.dir=meta[2]},[language,meta]);
 function setLanguage(v){setLanguageState(v);localStorage.setItem('almaher.language',v)}
 const value=useMemo(()=>({language,setLanguage,dir:meta[2],languages:LANGUAGES,meta,t:(k,f)=>D[language]?.[k]||D.ar[k]||f||k}),[language,meta]);
 return <C.Provider value={value}>{children}</C.Provider>
}
export function useLanguage(){return useContext(C)||{language:'ar',dir:'rtl',languages:LANGUAGES,meta:LANGUAGES[0],setLanguage:()=>{},t:(k,f)=>D.ar[k]||f||k}}
export function suggestedLanguageForNationality(n=''){const s=String(n).trim().toLowerCase();if(/تركي|turk/.test(s))return'tr';if(/هند|india|indian/.test(s))return'hi';if(/باكستان|pakistan|urdu/.test(s))return'ur';if(/فرنسا|french|france/.test(s))return'fr';if(/ايطال|ital/.test(s))return'it';if(/سعود|مصر|اردن|الأردن|سوريا|سوري|لبنان|عراق|يمن|عمان|قطر|كويت|بحرين|امارات|الإمارات|مغرب|جزائر|تونس|ليبيا|سودان|فلسطين|موريتان|صومال|جيبوتي|جزر القمر|arab/.test(s))return'ar';return'en'}
