import {useEffect} from 'react';
import {useLanguage} from './LanguageContext.jsx';

// Safe bridge for legacy modules that still contain Arabic literals.
// Only known UI vocabulary is translated. Customer/staff-entered data remains untouched.
const R=[
 ['تحديث','Refresh','Yenile','रीफ़्रेश','Aggiorna','Actualiser','تازہ کریں'],['حفظ','Save','Kaydet','सहेजें','Salva','Enregistrer','محفوظ کریں'],['إلغاء','Cancel','İptal','रद्द करें','Annulla','Annuler','منسوخ کریں'],['إضافة','Add','Ekle','जोड़ें','Aggiungi','Ajouter','شامل کریں'],['تعديل','Edit','Düzenle','संपादित करें','Modifica','Modifier','ترمیم'],['حذف','Delete','Sil','हटाएँ','Elimina','Supprimer','حذف کریں'],['بحث','Search','Ara','खोज','Cerca','Rechercher','تلاش'],['طباعة','Print','Yazdır','प्रिंट','Stampa','Imprimer','پرنٹ'],['تنزيل','Download','İndir','डाउनलोड','Scarica','Télécharger','ڈاؤن لوڈ'],['رفع','Upload','Yükle','अपलोड','Carica','Téléverser','اپ لوڈ'],['اعتماد','Approve','Onayla','स्वीकृत करें','Approva','Approuver','منظور'],['رفض','Reject','Reddet','अस्वीकार','Rifiuta','Rejeter','مسترد'],['تنفيذ','Execute','Uygula','निष्पादित करें','Esegui','Exécuter','عمل کریں'],
 ['الرحلة','Trip','Sefer','यात्रा','Viaggio','Voyage','سفر'],['الرحلات','Trips','Seferler','यात्राएँ','Viaggi','Voyages','سفر'],['الحجز','Booking','Rezervasyon','बुकिंग','Prenotazione','Réservation','بکنگ'],['الحجوزات','Bookings','Rezervasyonlar','बुकिंग','Prenotazioni','Réservations','بکنگز'],['المسافر','Passenger','Yolcu','यात्री','Passeggero','Passager','مسافر'],['المسافرون','Passengers','Yolcular','यात्री','Passeggeri','Passagers','مسافر'],['الراكب','Passenger','Yolcu','यात्री','Passeggero','Passager','مسافر'],['الركاب','Passengers','Yolcular','यात्री','Passeggeri','Passagers','مسافر'],['الفرع','Branch','Şube','शाखा','Filiale','Agence','شاخ'],['الفروع','Branches','Şubeler','शाखाएँ','Filiali','Agences','شاخیں'],['الموظفون','Staff','Personel','कर्मचारी','Personale','Employés','ملازمین'],['التشغيل','Operations','Operasyon','संचालन','Operazioni','Opérations','آپریشنز'],['التسكين','Housing','Konaklama','आवास','Alloggi','Hébergement','رہائش'],['المقاعد','Seats','Koltuklar','सीटें','Posti','Sièges','نشستیں'],['المالية','Finance','Finans','वित्त','Finanza','Finance','مالیات'],['الاسترداد','Refunds','İadeler','रिफंड','Rimborsi','Remboursements','رقم واپسی'],['التقارير','Reports','Raporlar','रिपोर्ट','Report','Rapports','رپورٹس'],['المستندات','Documents','Belgeler','दस्तावेज़','Documenti','Documents','دستاویزات'],['الإشعارات','Notifications','Bildirimler','सूचनाएँ','Notifiche','Notifications','اطلاعات'],['المطور والنظام','Developer & System','Geliştirici ve Sistem','डेवलपर और सिस्टम','Sviluppatore e Sistema','Développeur et Système','ڈیولپر اور سسٹم'],
 ['الاسم','Name','Ad','नाम','Nome','Nom','نام'],['الهوية','ID','Kimlik','पहचान','Documento','Identité','شناخت'],['الجنسية','Nationality','Uyruk','राष्ट्रीयता','Nazionalità','Nationalité','قومیت'],['الجوال','Mobile','Cep telefonu','मोबाइल','Cellulare','Mobile','موبائل'],['التاريخ','Date','Tarih','तारीख','Data','Date','تاریخ'],['الوقت','Time','Saat','समय','Ora','Heure','وقت'],['الحالة','Status','Durum','स्थिति','Stato','Statut','حالت'],['النوع','Type','Tür','प्रकार','Tipo','Type','قسم'],['المبلغ','Amount','Tutar','राशि','Importo','Montant','رقم'],['المدفوع','Paid','Ödenen','भुगतान','Pagato','Payé','ادا شدہ'],['المتبقي','Outstanding','Kalan','बकाया','Residuo','Restant','باقی'],['الإجمالي','Total','Toplam','कुल','Totale','Total','کل'],['المصروفات','Expenses','Giderler','खर्च','Spese','Dépenses','اخراجات'],['الحركات المالية','Transactions','Mali hareketler','वित्तीय लेनदेन','Movimenti finanziari','Transactions financières','مالی لین دین'],['الخزن','Cash registers','Kasalar','कैश रजिस्टर','Casse','Caisses','کیش رجسٹر'],['الخزنة','Cash register','Kasa','कैश रजिस्टर','Cassa','Caisse','کیش رجسٹر'],['الورديات','Shifts','Vardiyalar','शिफ्ट','Turni','Équipes','شفٹس'],['مستحقات الموردين','Supplier payables','Tedarikçi borçları','आपूर्तिकर्ता देय','Debiti fornitori','Dettes fournisseurs','سپلائر واجبات'],['المورد','Supplier','Tedarikçi','आपूर्तिकर्ता','Fornitore','Fournisseur','سپلائر'],['ملاحظات','Notes','Notlar','टिप्पणियाँ','Note','Notes','نوٹس'],['نقطة الصعود','Boarding point','Biniş noktası','बोर्डिंग पॉइंट','Punto di salita','Point d’embarquement','سوار ہونے کا مقام'],
 ['اختر','Select','Seç','चुनें','Seleziona','Sélectionner','منتخب کریں'],['اختر رحلة','Select trip','Sefer seç','यात्रा चुनें','Seleziona viaggio','Sélectionner le voyage','سفر منتخب کریں'],['اختر الفندق','Select hotel','Otel seç','होटल चुनें','Seleziona hotel','Sélectionner l’hôtel','ہوٹل منتخب کریں'],['كل الفروع','All branches','Tüm şubeler','सभी शाखाएँ','Tutte le filiali','Toutes les agences','تمام شاخیں'],['فرعك فقط','Your branch only','Yalnız şubeniz','केवल आपकी शाखा','Solo la tua filiale','Votre agence uniquement','صرف آپ کی شاخ'],['بدون سكن','No housing','Konaklama yok','बिना आवास','Senza alloggio','Sans hébergement','بغیر رہائش'],['مشترك','Shared','Paylaşımlı','साझा','Condiviso','Partagé','مشترکہ'],['خاص','Private','Özel','निजी','Privato','Privé','نجی'],['غرفة','Room','Oda','कमरा','Camera','Chambre','کمرہ'],['الفندق','Hotel','Otel','होटल','Hotel','Hôtel','ہوٹل'],['كشف السكن','Housing manifest','Konaklama listesi','आवास सूची','Elenco alloggi','Liste hébergement','رہائش فہرست'],['كشف الركاب','Passenger manifest','Yolcu listesi','यात्री सूची','Elenco passeggeri','Liste passagers','مسافر فہرست'],['مركز الرحلة','Trip center','Sefer merkezi','यात्रा केंद्र','Centro viaggio','Centre du voyage','سفر مرکز'],['مركز التشغيل','Operations center','Operasyon merkezi','संचालन केंद्र','Centro operativo','Centre des opérations','آپریشن مرکز'],
 ['جاري التحميل...','Loading...','Yükleniyor...','लोड हो रहा है...','Caricamento...','Chargement...','لوڈ ہو رہا ہے...'],['جاري الحفظ...','Saving...','Kaydediliyor...','सहेजा जा रहा है...','Salvataggio...','Enregistrement...','محفوظ ہو رہا ہے...'],['جاري التجهيز...','Preparing...','Hazırlanıyor...','तैयार हो रहा है...','Preparazione...','Préparation...','تیاری جاری ہے...'],['لا توجد بيانات','No data','Veri yok','कोई डेटा नहीं','Nessun dato','Aucune donnée','کوئی ڈیٹا نہیں'],['غير مصرح','Access denied','Yetkisiz','अनधिकृत','Non autorizzato','Non autorisé','رسائی نہیں'],['الصفحة غير موجودة','Page not found','Sayfa bulunamadı','पृष्ठ नहीं मिला','Pagina non trovata','Page introuvable','صفحہ نہیں ملا'],['العودة للرئيسية','Back to home','Ana sayfaya dön','मुख्य पर वापस','Torna alla home','Retour à l’accueil','مرکزی صفحے پر واپس'],
 ['جديد','New','Yeni','नया','Nuovo','Nouveau','نیا'],['مؤكد','Confirmed','Onaylandı','पुष्ट','Confermato','Confirmé','تصدیق شدہ'],['مدفوع','Paid','Ödendi','भुगतान','Pagato','Payé','ادا شدہ'],['ملغي','Cancelled','İptal','रद्द','Annullato','Annulé','منسوخ'],['مكتمل','Completed','Tamamlandı','पूर्ण','Completato','Terminé','مکمل'],['نشط','Active','Aktif','सक्रिय','Attivo','Actif','فعال'],['موقوف','Inactive','Pasif','निष्क्रिय','Inattivo','Inactif','غیر فعال'],['قيد المراجعة','Pending','Beklemede','लंबित','In attesa','En attente','زیر جائزہ'],['معتمد','Approved','Onaylı','स्वीकृत','Approvato','Approuvé','منظور'],['مرفوض','Rejected','Reddedildi','अस्वीकृत','Rifiutato','Rejeté','مسترد'],['متاح','Available','Mevcut','उपलब्ध','Disponibile','Disponible','دستیاب'],['مفتوح','Open','Açık','खुला','Aperto','Ouvert','کھلا'],['مغلق','Closed','Kapalı','बंद','Chiuso','Fermé','بند'],['قيد التنفيذ','In progress','Devam ediyor','प्रगति पर','In corso','En cours','جاری'],['عاجل','Urgent','Acil','तत्काल','Urgente','Urgent','فوری'],['عالي','High','Yüksek','उच्च','Alto','Élevé','اعلی'],['عادي','Normal','Normal','सामान्य','Normale','Normal','عام'],['منخفض','Low','Düşük','निम्न','Basso','Faible','کم'],
 ['طباعة التقرير','Print report','Raporu yazdır','रिपोर्ट प्रिंट करें','Stampa report','Imprimer le rapport','رپورٹ پرنٹ کریں'],['طباعة الكشف','Print manifest','Listeyi yazdır','सूची प्रिंट करें','Stampa elenco','Imprimer la liste','فہرست پرنٹ کریں'],['حفظ PDF','Save PDF','PDF kaydet','PDF सहेजें','Salva PDF','Enregistrer PDF','PDF محفوظ کریں'],['تصدير CSV','Export CSV','CSV dışa aktar','CSV निर्यात','Esporta CSV','Exporter CSV','CSV ایکسپورٹ'],['طلبات الاسترداد','Refund requests','İade talepleri','रिफंड अनुरोध','Richieste rimborso','Demandes de remboursement','رقم واپسی درخواستیں'],['إنشاء طلب الاسترداد','Create refund request','İade talebi oluştur','रिफंड अनुरोध बनाएँ','Crea richiesta rimborso','Créer une demande de remboursement','رقم واپسی درخواست بنائیں'],['طريقة الاسترداد','Refund method','İade yöntemi','रिफंड विधि','Metodo rimborso','Mode de remboursement','رقم واپسی طریقہ'],['نقدي','Cash','Nakit','नकद','Contanti','Espèces','نقد'],['تحويل بنكي','Bank transfer','Banka havalesi','बैंक ट्रांसफर','Bonifico bancario','Virement bancaire','بینک ٹرانسفر'],['أخرى','Other','Diğer','अन्य','Altro','Autre','دیگر'],['السبب','Reason','Neden','कारण','Motivo','Motif','وجہ'],['السند','Receipt','Makbuz','रसीद','Ricevuta','Reçu','رسید']
];
const codes=['ar','en','tr','hi','it','fr','ur'];
const phrases=[...R].sort((a,b)=>b[0].length-a[0].length);
const textOriginal=new WeakMap(),attrOriginal=new WeakMap();
const rx=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
function convert(source,language){if(!source||language==='ar')return source;const idx=Math.max(1,codes.indexOf(language));let out=source;for(const row of phrases)if(out.includes(row[0]))out=out.replace(new RegExp(rx(row[0]),'g'),row[idx]||row[1]);return out}
function skip(el){return !el||['SCRIPT','STYLE','CODE','PRE','TEXTAREA'].includes(el.tagName)||el.closest?.('[data-no-translate],.json-view,[contenteditable="true"]')}
function textNode(node,language,refresh=false){const el=node.parentElement;if(skip(el))return;if(refresh||!textOriginal.has(node))textOriginal.set(node,node.nodeValue||'');const src=textOriginal.get(node)||'';const next=language==='ar'?src:convert(src,language);if(node.nodeValue!==next)node.nodeValue=next}
function attrs(el,language,refresh=false){if(!(el instanceof Element)||skip(el))return;let saved=attrOriginal.get(el);if(!saved){saved={};attrOriginal.set(el,saved)}for(const name of ['placeholder','title','aria-label']){if(refresh&&el.hasAttribute(name))saved[name]=el.getAttribute(name)||'';else if(saved[name]===undefined&&el.hasAttribute(name))saved[name]=el.getAttribute(name)||'';if(saved[name]===undefined)continue;const next=language==='ar'?saved[name]:convert(saved[name],language);if(el.getAttribute(name)!==next)el.setAttribute(name,next)}}
function walk(root,language){if(!root)return;if(root.nodeType===Node.TEXT_NODE){textNode(root,language);return}if(root.nodeType!==Node.ELEMENT_NODE&&root.nodeType!==Node.DOCUMENT_FRAGMENT_NODE)return;if(root.nodeType===Node.ELEMENT_NODE)attrs(root,language);const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT|NodeFilter.SHOW_ELEMENT);let n;while((n=w.nextNode()))n.nodeType===Node.TEXT_NODE?textNode(n,language):attrs(n,language)}
export default function RuntimeTranslationSafe(){const {language}=useLanguage();useEffect(()=>{let observer;const observe=()=>observer?.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label']});const apply=fn=>{observer?.disconnect();try{fn()}finally{observe()}};observer=new MutationObserver(records=>apply(()=>{for(const rec of records){if(rec.type==='characterData')textNode(rec.target,language,true);else if(rec.type==='attributes')attrs(rec.target,language,true);for(const n of rec.addedNodes||[])walk(n,language)}}));apply(()=>walk(document.body,language));document.documentElement.lang=language;document.documentElement.dir=['ar','ur'].includes(language)?'rtl':'ltr';return()=>observer.disconnect()},[language]);return null}
