from pathlib import Path


def replace(path, old, new, count=1):
    p=Path(path); s=p.read_text()
    if old not in s:
        raise SystemExit(f'pattern not found in {path}: {old[:120]!r}')
    p.write_text(s.replace(old,new,count))

# UI: reusable searchable selector.
replace('src/components/UI.jsx',"import React from 'react';","import React,{useEffect,useMemo,useRef,useState} from 'react';")
replace('src/components/UI.jsx',"export const Input=(p)=><input {...p}/>; export const Select=(p)=><select {...p}/>; export const Textarea=(p)=><textarea {...p}/>;",'''export const Input=(p)=><input {...p}/>; export const Select=(p)=><select {...p}/>; export const Textarea=(p)=><textarea {...p}/>;
export function SearchSelect({value='',onChange,options=[],placeholder='اختر...',disabled=false,name='',className=''}){
 const ref=useRef(null),[open,setOpen]=useState(false),[query,setQuery]=useState('');
 useEffect(()=>{const close=e=>{if(ref.current&&!ref.current.contains(e.target))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 const selected=options.find(x=>String(x.value)===String(value));
 const filtered=useMemo(()=>{const q=String(query||'').trim().toLowerCase();if(!q)return options;return options.filter(x=>`${x.label||''} ${x.searchText||''}`.toLowerCase().includes(q))},[options,query]);
 const choose=opt=>{if(opt?.disabled)return;onChange?.({target:{value:String(opt?.value??''),name}});setQuery('');setOpen(false)};
 return <div className={`search-select ${className}`} ref={ref}>{name&&<input type="hidden" name={name} value={value||''}/>}<button type="button" className="search-select-trigger" disabled={disabled} onClick={()=>!disabled&&setOpen(x=>!x)} aria-expanded={open}><span className={!selected?'search-select-placeholder':''}>{selected?.label||placeholder}</span><span className={`search-select-arrow ${open?'open':''}`}>⌄</span></button>{open&&!disabled&&<div className="search-select-menu"><input className="search-select-input" value={query} onChange={e=>setQuery(e.target.value)} autoFocus placeholder={`ابحث — ${placeholder}`}/><div className="search-select-options">{filtered.length?filtered.map(opt=><button type="button" key={String(opt.value)} disabled={opt.disabled} className={`search-select-option ${String(opt.value)===String(value)?'selected':''}`} onClick={()=>choose(opt)}>{opt.label}</button>):<div className="search-select-empty">لا توجد نتائج مطابقة</div>}</div></div>}</div>
}''')

# Reports: no automatic first-trip selection; searchable trip picker; collapsible upcoming list.
replace('src/modules/reports/Reports.jsx',"import {Badge,Button,Card,ErrorBox,Field,Loading,PageHeader,Select,Table} from '../../components/UI.jsx';","import {Badge,Button,Card,ErrorBox,Field,Loading,PageHeader,SearchSelect,Select,Table} from '../../components/UI.jsx';")
replace('src/modules/reports/Reports.jsx',"const [data,setData]=useState(null),[brief,setBrief]=useState(null),[refundSummary,setRefundSummary]=useState({byId:{},byNo:{}}),[error,setError]=useState(''),[type,setType]=useState('bookings_csv'),[busy,setBusy]=useState(''),[orientation,setOrientation]=useState('portrait'),[tripId,setTripId]=useState('');","const [data,setData]=useState(null),[brief,setBrief]=useState(null),[refundSummary,setRefundSummary]=useState({byId:{},byNo:{}}),[error,setError]=useState(''),[type,setType]=useState('bookings_csv'),[busy,setBusy]=useState(''),[orientation,setOrientation]=useState('portrait'),[tripId,setTripId]=useState(''),[upcomingOpen,setUpcomingOpen]=useState(()=>{try{return sessionStorage.getItem('almaher_reports_upcoming_open')==='1'}catch{return false}});")
replace('src/modules/reports/Reports.jsx'," useEffect(()=>{if(!tripId&&app.trips?.length)setTripId(s(app.trips[0].id))},[app.trips,tripId]);\n","")
replace('src/modules/reports/Reports.jsx'," const upcoming=brief?.upcoming||[];"," const upcoming=brief?.upcoming||[];\n const tripPickerOptions=useMemo(()=>[...(app.trips||[])].sort((a,b)=>String(b.departure_date||'').localeCompare(String(a.departure_date||''))).map(t=>({value:t.id,label:tripDisplay(t),searchText:[t.trip_code,t.code,t.from_city,t.to_city,t.origin,t.destination,t.departure_date,t.return_date,t.branch_name].filter(Boolean).join(' ')})),[app.trips]);\n function toggleUpcoming(){setUpcomingOpen(v=>{const next=!v;try{sessionStorage.setItem('almaher_reports_upcoming_open',next?'1':'0')}catch{}return next})}")
old='''<Card><div className="card-title"><h3>ملخص الإدارة</h3><Button onClick={printKpi}><Printer size={16}/> طباعة مؤشرات الأداء</Button></div>{(brief.warnings||[]).length?<div className="warning-list">{brief.warnings.map((w,i)=><div key={i}><AlertTriangle size={16}/>{w}</div>)}</div>:<div className="success-note">لا توجد تنبيهات إدارية حرجة حاليًا.</div>}<div className="table-wrap"><table><thead><tr><th>الرحلة القادمة</th><th>التاريخ</th><th>الحالة</th></tr></thead><tbody>{upcoming.length?upcoming.map(t=><tr key={t.id}><td>{tripDisplay(t)}</td><td>{t.departure_date||'—'}</td><td><Badge>{statusLabel(t.status||'')}</Badge></td></tr>):<tr><td colSpan="3">لا توجد رحلات قادمة</td></tr>}</tbody></table></div></Card>'''
new='''<Card><div className="card-title"><h3>ملخص الإدارة</h3><Button onClick={printKpi}><Printer size={16}/> طباعة مؤشرات الأداء</Button></div>{(brief.warnings||[]).length?<div className="warning-list">{brief.warnings.map((w,i)=><div key={i}><AlertTriangle size={16}/>{w}</div>)}</div>:<div className="success-note">لا توجد تنبيهات إدارية حرجة حاليًا.</div>}<button type="button" className="collapsible-heading" onClick={toggleUpcoming}><span><b>الرحلات القادمة</b> <small>({upcoming.length})</small></span><span className={`collapsible-arrow ${upcomingOpen?'open':''}`}>⌄</span></button>{upcomingOpen&&<div className="table-wrap collapsible-body"><table><thead><tr><th>الرحلة القادمة</th><th>التاريخ</th><th>الحالة</th></tr></thead><tbody>{upcoming.length?upcoming.map(t=><tr key={t.id}><td>{tripDisplay(t)}</td><td>{t.departure_date||'—'}</td><td><Badge>{statusLabel(t.status||'')}</Badge></td></tr>):<tr><td colSpan="3">لا توجد رحلات قادمة</td></tr>}</tbody></table></div>}</Card>'''
replace('src/modules/reports/Reports.jsx',old,new)
replace('src/modules/reports/Reports.jsx','''<Field label="الرحلة"><Select value={tripId} onChange={e=>setTripId(e.target.value)}><option value="">اختر رحلة</option>{(app.trips||[]).map(t=><option key={t.id} value={t.id}>{tripDisplay(t)}</option>)}</Select></Field>''','''<Field label="الرحلة"><SearchSelect value={tripId} onChange={e=>setTripId(e.target.value)} options={tripPickerOptions} placeholder="اختر الرحلة"/></Field>''')

# Housing: searchable trip selector and explicit hotel choice (no first hotel auto-selection).
replace('src/modules/housing/HousingBase.jsx',"import {Badge,Button,Card,ErrorBox,Field,Input,Loading,Modal,PageHeader,Select,Table} from '../../components/UI.jsx';","import {Badge,Button,Card,ErrorBox,Field,Input,Loading,Modal,PageHeader,SearchSelect,Select,Table} from '../../components/UI.jsx';")
replace('src/modules/housing/HousingBase.jsx'," useEffect(()=>{if(tripHotels.length&&!tripHotels.some(x=>s(x.id)===s(tripHotelId)))setTripHotelId(s(tripHotels[0].id));if(!tripHotels.length)setTripHotelId('')},[tripId,payload]);"," useEffect(()=>{if(tripHotelId&&!tripHotels.some(x=>s(x.id)===s(tripHotelId)))setTripHotelId('');if(!tripHotels.length)setTripHotelId('')},[tripId,payload,tripHotels,tripHotelId]);")
replace('src/modules/housing/HousingBase.jsx'," const selectedTrip=data.trips.find(t=>s(t.id)===s(tripId));"," const selectedTrip=data.trips.find(t=>s(t.id)===s(tripId));\n const housingTripOptions=useMemo(()=>[...(data.trips||[])].sort((a,b)=>String(b.departure_date||'').localeCompare(String(a.departure_date||''))).map(t=>({value:t.id,label:tripDisplay(t),searchText:[t.trip_code,t.from_city,t.to_city,t.departure_date,t.return_date].filter(Boolean).join(' ')})),[data.trips]);")
replace('src/modules/housing/HousingBase.jsx','''<Field label="الرحلة"><Select value={tripId} onChange={e=>setTripId(e.target.value)}><option value="">اختر رحلة</option>{data.trips.map(t=><option key={t.id} value={t.id}>{tripDisplay(t)}</option>)}</Select></Field>''','''<Field label="الرحلة"><SearchSelect value={tripId} onChange={e=>setTripId(e.target.value)} options={housingTripOptions} placeholder="اختر الرحلة"/></Field>''')
replace('src/modules/housing/HousingBase.jsx','''<option value="">اختر</option>{hotels.filter(h=>h.active!==false).map(h=><option key={h.id} value={h.id}>{h.name} — {h.city||''}</option>)}</Select>''','''<option value="">اختر الفندق</option>{hotels.filter(h=>h.active!==false).map(h=><option key={h.id} value={h.id}>{h.name} — {h.city||''}</option>)}</Select>''')

# Booking: explicit primary choices and searchable trip lists; preserve existing-booking values.
replace('src/modules/bookings/BookingEditor.jsx',"import {Card,PageHeader,Button,Field,Input,Select,Textarea,ErrorBox,Badge} from '../../components/UI.jsx';","import {Card,PageHeader,Button,Field,Input,SearchSelect,Select,Textarea,ErrorBox,Badge} from '../../components/UI.jsx';")
replace('src/modules/bookings/BookingEditor.jsx',"const emptyP=()=>({name:'',gender:'male',nationality:'السعودية',identity:'',phone:'',preferredLanguage:'ar'});","const emptyP=()=>({name:'',gender:'',nationality:'',identity:'',phone:'',preferredLanguage:'ar'});")
replace('src/modules/bookings/BookingEditor.jsx'," const initialJourneyMode=existing?.journey_mode||snap.journeyMode||'oneway';"," const initialJourneyMode=existing?.journey_mode||snap.journeyMode||'';")
replace('src/modules/bookings/BookingEditor.jsx'," const [accommodation,setAccommodation]=useState(existing?.accommodation_type||snap.accommodationType||'none');"," const [accommodation,setAccommodation]=useState(existing?.accommodation_type||snap.accommodationType||'');")
replace('src/modules/bookings/BookingEditor.jsx'," const [customerDraft,setCustomerDraft]=useState({name:existing?.customer_name||'',phone:existing?.customer_phone||'',identity:existing?.customer_identity||'',nationality:existing?.customer_nationality||'السعودية',gender:existing?.customer_gender||'male'});"," const [customerDraft,setCustomerDraft]=useState({name:existing?.customer_name||'',phone:existing?.customer_phone||'',identity:existing?.customer_identity||'',nationality:existing?.customer_nationality||'',gender:existing?.customer_gender||''});")
replace('src/modules/bookings/BookingEditor.jsx'," const selectedBranchId=existing?.branch_id||data.scope?.branch_id||user?.branch_id||'';"," const selectedBranchId=existing?.branch_id||'';")
replace('src/modules/bookings/BookingEditor.jsx'," const trip=data.trips.find(t=>String(t.id)===String(tripId));"," const bookingTripOptions=useMemo(()=>tripOptions.map(t=>({value:t.id,label:tripDisplay(t),searchText:[t.trip_code,t.from_city,t.to_city,t.departure_date,t.return_date].filter(Boolean).join(' ')})),[tripOptions]);\n const separateReturnSearchOptions=useMemo(()=>separateReturnOptions.map(t=>({value:t.id,label:`${t.branch_name?`${t.branch_name} — `:''}${tripDisplay(t)} — العودة ${t.return_date||''} ${t.return_time||''}`,searchText:[t.branch_name,t.trip_code,t.from_city,t.to_city,t.return_date,t.return_time].filter(Boolean).join(' ')})),[separateReturnOptions]);\n const trip=data.trips.find(t=>String(t.id)===String(tripId));")
replace('src/modules/bookings/BookingEditor.jsx'," function validate(paid){if(!tripId)return 'اختر الرحلة.';"," function validate(paid){if(!journeyMode)return 'اختر نوع الرحلة.';if(!accommodation)return 'اختر نوع السكن.';if(!customerDraft.nationality)return 'اختر الجنسية.';if(!customerDraft.gender)return 'اختر الجنس.';if(!tripId)return 'اختر الرحلة.';")
replace('src/modules/bookings/BookingEditor.jsx','''<Field label="الفرع"><Select name="branch_id" defaultValue={selectedBranchId} required>{availableBranches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select></Field>''','''<Field label="الفرع"><Select name="branch_id" defaultValue={selectedBranchId} required><option value="">اختر الفرع</option>{availableBranches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select></Field>''')
replace('src/modules/bookings/BookingEditor.jsx','''<Field label="نوع الرحلة"><Select value={journeyMode} onChange={e=>{const v=e.target.value;setJourneyMode(v);if(v!=='separate')setReturnTripId('')}}><option value="oneway">ذهاب فقط</option>''','''<Field label="نوع الرحلة"><Select value={journeyMode} required onChange={e=>{const v=e.target.value;setJourneyMode(v);if(v!=='separate')setReturnTripId('')}}><option value="">اختر نوع الرحلة</option><option value="oneway">ذهاب فقط</option>''')
replace('src/modules/bookings/BookingEditor.jsx','''<Field label={tripLabel}><Select value={tripId} onChange={e=>setTripId(e.target.value)} required><option value="">اختر الرحلة</option>{tripOptions.map(t=><option key={t.id} value={t.id}>{tripDisplay(t)}</option>)}</Select></Field>''','''<Field label={tripLabel}><SearchSelect value={tripId} onChange={e=>setTripId(e.target.value)} options={bookingTripOptions} placeholder="اختر الرحلة"/></Field>''')
replace('src/modules/bookings/BookingEditor.jsx','''<Select value={returnTripId} onChange={e=>setReturnTripId(e.target.value)} required><option value="">اختر رحلة العودة</option>{separateReturnOptions.map(t=><option key={t.id} value={t.id}>{t.branch_name?`${t.branch_name} — `:''}{tripDisplay(t)} — العودة {t.return_date} {t.return_time||''}</option>)}</Select>''','''<SearchSelect value={returnTripId} onChange={e=>setReturnTripId(e.target.value)} options={separateReturnSearchOptions} placeholder="اختر رحلة العودة"/>''')
replace('src/modules/bookings/BookingEditor.jsx','''<Field label="الجنسية"><Select value={customerDraft.nationality} onChange={e=>setCustomer('nationality',e.target.value)}>{nationalityOptions(customerDraft.nationality).map(x=><option key={x} value={x}>{x}</option>)}</Select></Field>''','''<Field label="الجنسية"><Select value={customerDraft.nationality} required onChange={e=>setCustomer('nationality',e.target.value)}><option value="">اختر الجنسية</option>{nationalityOptions(customerDraft.nationality).map(x=><option key={x} value={x}>{x}</option>)}</Select></Field>''')
replace('src/modules/bookings/BookingEditor.jsx','''<Field label="الجنس"><Select value={customerDraft.gender} onChange={e=>{const v=e.target.value;setCustomer('gender',v);if(isFemale(v)&&accommodation==='shared')setAccommodation('private')}}><option value="male">ذكر</option>''','''<Field label="الجنس"><Select value={customerDraft.gender} required onChange={e=>{const v=e.target.value;setCustomer('gender',v);if(isFemale(v)&&accommodation==='shared')setAccommodation('private')}}><option value="">اختر الجنس</option><option value="male">ذكر</option>''')
replace('src/modules/bookings/BookingEditor.jsx','''<Select value={accommodation} onChange={e=>setAccommodation(e.target.value)}><option value="none">بدون سكن</option>''','''<Select value={accommodation} required onChange={e=>setAccommodation(e.target.value)}><option value="">اختر نوع السكن</option><option value="none">بدون سكن</option>''')
replace('src/modules/bookings/BookingEditor.jsx','''<Field label="الجنسية"><Select value={p.nationality||'السعودية'} onChange={e=>updatePassenger(i,'nationality',e.target.value)} disabled={!existing&&i===0}>{nationalityOptions(p.nationality).map(x=><option key={x} value={x}>{x}</option>)}</Select></Field>''','''<Field label="الجنسية"><Select value={p.nationality||''} required onChange={e=>updatePassenger(i,'nationality',e.target.value)} disabled={!existing&&i===0}><option value="">اختر الجنسية</option>{nationalityOptions(p.nationality).map(x=><option key={x} value={x}>{x}</option>)}</Select></Field>''')
replace('src/modules/bookings/BookingEditor.jsx','''<Field label="الجنس"><Select value={p.gender||'male'} onChange={e=>updatePassenger(i,'gender',e.target.value)} disabled={!existing&&i===0}><option value="male">ذكر</option>''','''<Field label="الجنس"><Select value={p.gender||''} required onChange={e=>updatePassenger(i,'gender',e.target.value)} disabled={!existing&&i===0}><option value="">اختر الجنس</option><option value="male">ذكر</option>''')

# CSS for reusable searchable select + collapsible section.
p=Path('src/styles.css'); css=p.read_text(); extra='''\n/* Searchable operational selectors and collapsible report sections */\n.search-select{position:relative;width:100%}.search-select-trigger{width:100%;min-height:46px;border:1px solid #cfd8e3;border-radius:12px;background:#fff;color:#13233a;padding:10px 13px;display:flex;align-items:center;justify-content:space-between;gap:10px;font:inherit;text-align:start}.search-select-trigger:disabled{background:#f6f7f9;color:#98a2b3}.search-select-placeholder{color:#7d8795}.search-select-arrow,.collapsible-arrow{transition:transform .18s ease}.search-select-arrow.open,.collapsible-arrow.open{transform:rotate(180deg)}.search-select-menu{position:absolute;inset-inline:0;top:calc(100% + 6px);z-index:1200;background:#fff;border:1px solid #d8e0e8;border-radius:14px;box-shadow:0 14px 36px rgba(20,35,58,.16);padding:9px}.search-select-input{width:100%;margin:0 0 8px}.search-select-options{max-height:280px;overflow:auto;display:grid;gap:4px}.search-select-option{border:0;background:transparent;border-radius:9px;padding:9px 10px;text-align:start;color:#172b45;font:inherit;cursor:pointer}.search-select-option:hover,.search-select-option.selected{background:#eef5fb}.search-select-empty{padding:12px;color:#7d8795;text-align:center}.collapsible-heading{width:100%;border:0;border-top:1px solid #e6ebf0;background:transparent;margin-top:12px;padding:12px 2px 4px;display:flex;align-items:center;justify-content:space-between;color:#13233a;font:inherit;cursor:pointer;text-align:start}.collapsible-heading b{font-size:1rem}.collapsible-heading small{color:#7d8795}.collapsible-body{margin-top:8px}@media(max-width:700px){.search-select-menu{position:fixed;left:10px;right:10px;top:25vh;inset-inline:auto;max-height:60vh}.search-select-options{max-height:45vh}}\n'''
if 'Searchable operational selectors and collapsible report sections' not in css:p.write_text(css+extra)

print('UX patch applied')
