from pathlib import Path


def replace(path, old, new, count=1):
    p=Path(path); s=p.read_text()
    if old not in s:
        raise SystemExit(f'pattern not found in {path}: {old[:140]!r}')
    p.write_text(s.replace(old,new,count))

# Seats: searchable trip selector + explicit direction choice.
replace('src/modules/seats/Seats.jsx',"import {Badge,Button,Card,ErrorBox,Field,Loading,Modal,PageHeader,Select,Table} from '../../components/UI.jsx';","import {Badge,Button,Card,ErrorBox,Field,Loading,Modal,PageHeader,SearchSelect,Select,Table} from '../../components/UI.jsx';")
replace('src/modules/seats/Seats.jsx',"const {data}=useAppData();const [payload,setPayload]=useState(null),[error,setError]=useState(''),[tripId,setTripId]=useState(initialTrip),[tripVehicleId,setTripVehicleId]=useState(''),[segment,setSegment]=useState('outbound'),","const {data}=useAppData();const [payload,setPayload]=useState(null),[error,setError]=useState(''),[tripId,setTripId]=useState(initialTrip),[tripVehicleId,setTripVehicleId]=useState(''),[segment,setSegment]=useState(''),")
replace('src/modules/seats/Seats.jsx'," const tvs=useMemo(()=>payload?.trip_vehicles?.filter(x=>s(x.trip_id)===s(tripId))||[],[payload,tripId]);"," const tripOptions=useMemo(()=>[...(data.trips||[])].sort((a,b)=>String(b.departure_date||'').localeCompare(String(a.departure_date||''))).map(t=>({value:t.id,label:tripDisplay(t),searchText:[t.trip_code,t.code,t.from_city,t.to_city,t.origin,t.destination,t.departure_date,t.return_date].filter(Boolean).join(' ')})),[data.trips]);\n const tvs=useMemo(()=>payload?.trip_vehicles?.filter(x=>s(x.trip_id)===s(tripId))||[],[payload,tripId]);")
replace('src/modules/seats/Seats.jsx','''<Field label="الرحلة"><Select value={tripId} onChange={e=>setTripId(e.target.value)}><option value="">اختر رحلة</option>{data.trips.map(t=><option key={t.id} value={t.id}>{tripDisplay(t)}</option>)}</Select></Field>''','''<Field label="الرحلة"><SearchSelect value={tripId} onChange={e=>setTripId(e.target.value)} options={tripOptions} placeholder="اختر الرحلة"/></Field>''')
replace('src/modules/seats/Seats.jsx','''<Field label="الاتجاه"><Select value={segment} onChange={e=>setSegment(e.target.value)}><option value="outbound">الذهاب</option><option value="return">العودة</option></Select></Field>''','''<Field label="الاتجاه"><Select value={segment} onChange={e=>setSegment(e.target.value)}><option value="">اختر الاتجاه</option><option value="outbound">الذهاب</option><option value="return">العودة</option></Select></Field>''')

# Operations: searchable trip selector, no change to operational logic.
replace('src/modules/operations/Operations.jsx',"import {Badge,Button,Card,PageHeader,Select,Field,Loading,ErrorBox,Table,Input} from '../../components/UI.jsx';","import {Badge,Button,Card,PageHeader,SearchSelect,Select,Field,Loading,ErrorBox,Table,Input} from '../../components/UI.jsx';")
replace('src/modules/operations/Operations.jsx'," const branchMap=useMemo(()=>new Map(data.branches.map(b=>[s(b.id),b.name||b.branch_name||b.id])),[data.branches]);"," const tripOptions=useMemo(()=>[...(data.trips||[])].sort((a,b)=>String(b.departure_date||'').localeCompare(String(a.departure_date||''))).map(t=>({value:t.id,label:tripDisplay(t),searchText:[t.trip_code,t.code,t.from_city,t.to_city,t.origin,t.destination,t.departure_date,t.return_date].filter(Boolean).join(' ')})),[data.trips]);\n const branchMap=useMemo(()=>new Map(data.branches.map(b=>[s(b.id),b.name||b.branch_name||b.id])),[data.branches]);")
replace('src/modules/operations/Operations.jsx','''<Field label="الرحلة"><Select value={tripId} onChange={e=>{setTripId(e.target.value);setX(null);setScanner(null)}}><option value="">اختر رحلة</option>{data.trips.map(t=><option key={t.id} value={t.id}>{tripDisplay(t)}</option>)}</Select></Field>''','''<Field label="الرحلة"><SearchSelect value={tripId} onChange={e=>{setTripId(e.target.value);setX(null);setScanner(null)}} options={tripOptions} placeholder="اختر الرحلة"/></Field>''')

# Returns: remove automatic trip selection + searchable selector.
replace('src/modules/returns/Returns.jsx',"import {Badge,Button,Card,ErrorBox,Field,Input,Loading,Modal,PageHeader,Select,Table,Textarea} from '../../components/UI.jsx';","import {Badge,Button,Card,ErrorBox,Field,Input,Loading,Modal,PageHeader,SearchSelect,Select,Table,Textarea} from '../../components/UI.jsx';")
replace('src/modules/returns/Returns.jsx'," async function load(){setError('');try{const x=await api.module('return_ops');setData(x);if(!tripId){const preferred=(app.trips||[]).find(t=>t.return_date||t.return_trip_id)||(app.trips||[])[0];if(preferred)setTripId(s(preferred.id))}}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);"," async function load(){setError('');try{const x=await api.module('return_ops');setData(x)}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);")
replace('src/modules/returns/Returns.jsx'," const trip=useMemo(()=>(app.trips||[]).find(t=>s(t.id)===tripId),[app.trips,tripId]);"," const tripOptions=useMemo(()=>[...(app.trips||[])].sort((a,b)=>String(b.return_date||b.departure_date||'').localeCompare(String(a.return_date||a.departure_date||''))).map(t=>({value:t.id,label:tripDisplay(t),searchText:[t.trip_code,t.code,t.from_city,t.to_city,t.origin,t.destination,t.departure_date,t.return_date].filter(Boolean).join(' ')})),[app.trips]);\n const trip=useMemo(()=>(app.trips||[]).find(t=>s(t.id)===tripId),[app.trips,tripId]);")
replace('src/modules/returns/Returns.jsx','''<Field label="الرحلة"><Select value={tripId} onChange={e=>setTripId(e.target.value)}><option value="">اختر رحلة</option>{(app.trips||[]).map(t=><option key={t.id} value={t.id}>{tripDisplay(t)}</option>)}</Select></Field>''','''<Field label="الرحلة"><SearchSelect value={tripId} onChange={e=>setTripId(e.target.value)} options={tripOptions} placeholder="اختر الرحلة"/></Field>''')

# Scanner: no automatic scan mode; force explicit choice.
replace('src/modules/scanner/Scanner.jsx'," const [code,setCode]=useState(''),[mode,setMode]=useState('outbound_boarding'),"," const [code,setCode]=useState(''),[mode,setMode]=useState(''),")
replace('src/modules/scanner/Scanner.jsx'," async function scan(v=code){if(!String(v).trim())return;setError('');try{"," async function scan(v=code){if(!mode){setError('اختر وضع المسح أولًا.');return}if(!String(v).trim())return;setError('');try{")
replace('src/modules/scanner/Scanner.jsx','''<Field label="وضع المسح"><Select value={mode} onChange={e=>setMode(e.target.value)}><option value="outbound_boarding">صعود الذهاب</option>''','''<Field label="وضع المسح"><Select value={mode} onChange={e=>setMode(e.target.value)}><option value="">اختر وضع المسح</option><option value="outbound_boarding">صعود الذهاب</option>''')

# Actual room editor: searchable trip selector.
replace('src/modules/housing/Housing.jsx',"import {Button,Card,ErrorBox,Field,Input,Select} from '../../components/UI.jsx';","import {Button,Card,ErrorBox,Field,Input,SearchSelect,Select} from '../../components/UI.jsx';")
replace('src/modules/housing/Housing.jsx'," const tripHotels=useMemo(()=>(payload?.trip_hotels||[]).filter(x=>s(x.trip_id)===s(tripId)),[payload,tripId]);"," const tripOptions=useMemo(()=>[...(data.trips||[])].sort((a,b)=>String(b.departure_date||'').localeCompare(String(a.departure_date||''))).map(t=>({value:t.id,label:tripDisplay(t),searchText:[t.trip_code,t.code,t.from_city,t.to_city,t.origin,t.destination,t.departure_date,t.return_date].filter(Boolean).join(' ')})),[data.trips]);\n const tripHotels=useMemo(()=>(payload?.trip_hotels||[]).filter(x=>s(x.trip_id)===s(tripId)),[payload,tripId]);")
replace('src/modules/housing/Housing.jsx','''<Field label="الرحلة"><Select value={tripId} onChange={e=>setTripId(e.target.value)}><option value="">اختر رحلة</option>{(data.trips||[]).map(t=><option key={t.id} value={t.id}>{tripDisplay(t)}</option>)}</Select></Field>''','''<Field label="الرحلة"><SearchSelect value={tripId} onChange={e=>setTripId(e.target.value)} options={tripOptions} placeholder="اختر الرحلة"/></Field>''')
