import fs from 'node:fs';
const source=fs.readFileSync(new URL('../src/modules/bookings/BookingEditor.jsx',import.meta.url),'utf8');
const start=source.indexOf('function calcPrice('),end=source.indexOf('\nfunction isFemale',start);
if(start<0||end<0)throw new Error('Unable to locate calcPrice in BookingEditor.jsx');
const n=v=>Number(v||0);
const normalizeRoomDays=(count,values,fallback=1)=>Array.from({length:Math.max(1,Number(count||1))},(_,i)=>Math.max(1,Number(values?.[i]||fallback||1)));
const calcPrice=new Function('n','normalizeRoomDays',`${source.slice(start,end)}; return calcPrice;`)(n,normalizeRoomDays);
const trip={price_one_way:100,price_return_only:80,price_round_trip:170,price_shared_daily:25,price_no_accommodation:170,price_shared:260,price_private_room:60};
const returnTrip={price_one_way:90};
const base={travelers:2,rooms:1,days:3,roomDays:[3],separateRoomDays:false,trip,returnTrip};
const price=(mode,type,extra={})=>calcPrice({...base,mode,type,...extra});
const eq=(a,b,label)=>{if(a!==b)throw new Error(`${label}: expected ${b}, got ${a}`)};
eq(price('oneway','none'),200,'oneway transport');
eq(price('returnonly','none'),160,'return-only transport');
eq(price('roundtrip','none'),340,'round-trip transport');
eq(price('oneway','shared'),350,'oneway + shared daily');
eq(price('returnonly','shared'),310,'return-only + shared daily');
eq(price('roundtrip','shared'),490,'round-trip + shared daily');
eq(price('oneway','private'),380,'oneway + private');
eq(price('returnonly','private'),340,'return-only + private');
eq(price('roundtrip','private'),520,'round-trip + private');
eq(price('separate','shared'),700,'separate shared legacy');
eq(price('separate','private'),700,'separate private legacy');
const legacyTrip={...trip,price_shared_daily:null};
eq(calcPrice({...base,mode:'roundtrip',type:'shared',trip:legacyTrip}),520,'legacy shared fallback');
console.log('Pricing invariants: PASS');
