import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import GlobalFeedback from './components/GlobalFeedback.jsx';
import {ThemeProvider} from './core/ThemeContext.jsx';
import {SystemBrandProvider} from './core/SystemBrandContext.jsx';
import {installBookingSaveRuntimeGuard} from './lib/bookingSaveRuntimeGuard.js';
import {installTicketLegalBottom} from './ticket-legal-bottom.js';
import {installBooking360Overview} from './booking-360.js';
import {installBooking360QuickActions} from './booking-360-actions.js';
import './styles.css';
import './mobile-safe-area.css';
import './themes.css';
import './branch-branding.css';
import './developer-footer.css';
import './modal-feedback.css';
import './feedback.css';
import './booking-360.css';
import './booking-360-actions.css';
import './ticket-approved.css';
import './ticket-polish.css';
import './ticket-thermal-table.css';
import './mobile-booking-ticket.css';
import './ticket-a4-no-scale.css';
import './ticket-a4-mobile-print-final.css';
import './ticket-readability-final.css';
import './ticket-a4-one-page-final.css';
import './ticket-branch-license.css';
import './ticket-logo-left.css';

installBookingSaveRuntimeGuard();
installTicketLegalBottom();
installBooking360Overview();
installBooking360QuickActions();

createRoot(document.getElementById('root')).render(<React.StrictMode><ThemeProvider><SystemBrandProvider><App/><GlobalFeedback/></SystemBrandProvider></ThemeProvider></React.StrictMode>);
