import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import GlobalFeedback from './components/GlobalFeedback.jsx';
import {ThemeProvider} from './core/ThemeContext.jsx';
import {SystemBrandProvider} from './core/SystemBrandContext.jsx';
import {installBookingSaveRuntimeGuard} from './lib/bookingSaveRuntimeGuard.js';
import {installTicketLegalBottom} from './ticket-legal-bottom.js';
import {installBooking360Overview} from './booking-360.js';
import {installBooking360QuickActions} from './booking-360-actions.js';
import {installBooking360Cancellation} from './booking-360-cancel.js';
import {installBooking360Readiness} from './booking-360-readiness.js';
import {installBooking360LiveAlerts} from './booking-360-alerts.js';
import {installBooking360Refund} from './booking-360-refund.js';
import {installBooking360History} from './booking-360-history.js';
import {installBooking360PassengerEdit} from './booking-360-passenger-edit.js';
import {installBooking360CustomerEdit} from './booking-360-customer-edit.js';
import {installBooking360Status} from './booking-360-status.js';
import {installBooking360TripChange} from './booking-360-trip-change.js';
import {installBooking360Documents} from './booking-360-documents.js';
import {installBooking360InternalNotes} from './booking-360-internal-notes.js';
import {installBooking360CustomerLink} from './booking-360-customer-link.js';
import {installBooking360Completion} from './booking-360-completion.js';
import {installBooking360SyncGuard} from './booking-360-sync-guard.js';
import {installTrip360LiveOperations} from './trip-360-live-operations.js';
import {installTrip360Lifecycle} from './trip-360-lifecycle.js';
import {installTrip360ReadinessCountBridge} from './trip-360-readiness-count-bridge.js';
import {installTrip360ReadinessGate} from './trip-360-readiness.js';
import {installTrip360Handoff} from './trip-360-handoff.js';
import {installTrip360Incidents} from './trip-360-incidents.js';
import {installTrip360Closure} from './trip-360-closure.js';
import {installTrip360FinalReport} from './trip-360-final-report.js';
import {installFinance360} from './finance-360.js';
import {installFinance360Ledger} from './finance-360-ledger.js';
import './styles.css';
import './mobile-safe-area.css';
import './themes.css';
import './branch-branding.css';
import './developer-footer.css';
import './modal-feedback.css';
import './feedback.css';
import './booking-360.css';
import './booking-360-actions.css';
import './booking-360-cancel.css';
import './booking-360-readiness.css';
import './booking-360-alerts.css';
import './booking-360-refund.css';
import './booking-360-history.css';
import './booking-360-passenger-edit.css';
import './booking-360-customer-edit.css';
import './booking-360-status.css';
import './booking-360-trip-change.css';
import './booking-360-documents.css';
import './booking-360-internal-notes.css';
import './booking-360-customer-link.css';
import './booking-360-completion.css';
import './trip-360-live-operations.css';
import './trip-360-lifecycle.css';
import './trip-360-readiness.css';
import './trip-360-handoff.css';
import './trip-360-incidents.css';
import './trip-360-closure.css';
import './trip-360-final-report.css';
import './finance-360.css';
import './finance-360-ledger.css';
import './ticket-approved.css';
import './ticket-polish.css';
import './ticket-thermal-table.css';
import './mobile-booking-ticket.css';
import './ticket-a4-no-scale.css';
import './ticket-a4-mobile-print-final.css';
import './ticket-readability-final.css';
import './ticket-a4-one-page-final.css';
import './ticket-branch-license.css';
import './ticket-logo-left.css';

installBookingSaveRuntimeGuard();
installBooking360SyncGuard();
installTicketLegalBottom();
installBooking360Overview();
installBooking360QuickActions();
installBooking360Cancellation();
installBooking360Readiness();
installBooking360LiveAlerts();
installBooking360Refund();
installBooking360History();
installBooking360PassengerEdit();
installBooking360CustomerEdit();
installBooking360Status();
installBooking360TripChange();
installBooking360Documents();
installBooking360InternalNotes();
installBooking360CustomerLink();
installBooking360Completion();
installTrip360LiveOperations();
installTrip360Lifecycle();
installTrip360ReadinessCountBridge();
installTrip360ReadinessGate();
installTrip360Handoff();
installTrip360Incidents();
installTrip360Closure();
installTrip360FinalReport();
installFinance360();
installFinance360Ledger();

createRoot(document.getElementById('root')).render(<React.StrictMode><ThemeProvider><SystemBrandProvider><App/><GlobalFeedback/></SystemBrandProvider></ThemeProvider></React.StrictMode>);