import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import GlobalFeedback from './components/GlobalFeedback.jsx';
import {ThemeProvider} from './core/ThemeContext.jsx';
import {SystemBrandProvider} from './core/SystemBrandContext.jsx';
import {installBookingSaveRuntimeGuard} from './lib/bookingSaveRuntimeGuard.js';
import {installTicketLegalBottom} from './ticket-legal-bottom.js';
import {installBooking360Overview} from './booking-360.js';
import {installBooking360QuickActions} from './booking-360-actions.js';
import {installBooking360Cancellation} from './booking-360-cancel.js';
import {installBooking360Readiness} from './booking-360-readiness.js';
import {installBooking360LiveAlerts} from './booking-360-alerts.js';
import {installBooking360Refund} from './booking-360-refund.js';
import {installBooking360History} from './booking-360-history.js';
import {installBooking360PassengerEdit} from './booking-360-passenger-edit.js';
import {installBooking360CustomerEdit} from './booking-360-customer-edit.js';
import {installBooking360Status} from './booking-360-status.js';
import {installBooking360TripChange} from './booking-360-trip-change.js';
import {installBooking360SyncGuard} from './booking-360-sync-guard.js';
import './styles.css';
import './mobile-safe-area.css';
import './themes.css';
import './branch-branding.css';
import './developer-footer.css';
import './modal-feedback.css';
import './feedback.css';
import './booking-360.css';
import './booking-360-actions.css';
import './booking-360-cancel.css';
import './booking-360-readiness.css';
import './booking-360-alerts.css';
import './booking-360-refund.css';
import './booking-360-history.css';
import './booking-360-passenger-edit.css';
import './booking-360-customer-edit.css';
import './booking-360-status.css';
import './booking-360-trip-change.css';
import './ticket-approved.css';
import './ticket-polish.css';
import './ticket-thermal-table.css';
import './mobile-booking-ticket.css';
import './ticket-a4-no-scale.css';
import './ticket-a4-mobile-print-final.css';
import './ticket-readability-final.css';
import './ticket-a4-one-page-final.css';
import './ticket-branch-license.css';
import './ticket-logo-left.css';

installBookingSaveRuntimeGuard();
installBooking360SyncGuard();
installTicketLegalBottom();
installBooking360Overview();
installBooking360QuickActions();
installBooking360Cancellation();
installBooking360Readiness();
installBooking360LiveAlerts();
installBooking360Refund();
installBooking360History();
installBooking360PassengerEdit();
installBooking360CustomerEdit();
installBooking360Status();
installBooking360TripChange();

createRoot(document.getElementById('root')).render(<React.StrictMode><ThemeProvider><SystemBrandProvider><App/><GlobalFeedback/></SystemBrandProvider></ThemeProvider></React.StrictMode>);
