-- ID Studio V3 foundation
-- IMPORTANT: designed for Test first. Do not run on Production before review/approval.

create extension if not exists pgcrypto;

create table if not exists public.id_card_templates (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name_ar text not null,
  name_en text,
  version integer not null default 1 check (version > 0),
  layout_mode text not null default 'both' check (layout_mode in ('full','front_back','both')),
  config jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.id_cards (
  id uuid primary key default gen_random_uuid(),
  card_number text not null unique,
  linked_employee_id text null,
  holder_type text not null default 'employee' check (holder_type in ('employee','seasonal','contractor','driver','supervisor','visitor','other')),
  source_type text not null default 'standalone' check (source_type in ('standalone','linked_employee')),
  owner_branch_id text null,
  name_ar text not null,
  name_en text,
  job_title_ar text,
  job_title_en text,
  department_ar text,
  department_en text,
  phone text,
  photo_path text,
  license_number text,
  season_label text,
  issue_date date not null default current_date,
  expiry_date date,
  status text not null default 'draft' check (status in ('draft','pending_approval','active','suspended','expired','lost','revoked','reissued')),
  print_mode text not null default 'full' check (print_mode in ('full','front_back')),
  template_code text not null default 'makkah_luxury',
  template_version integer not null default 1,
  qr_token uuid not null default gen_random_uuid() unique,
  translation_auto boolean not null default true,
  approved_at timestamptz,
  approved_by text,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint id_cards_link_consistency check (
    (source_type='standalone') or (source_type='linked_employee' and linked_employee_id is not null)
  )
);

create index if not exists id_cards_linked_employee_idx on public.id_cards(linked_employee_id);
create index if not exists id_cards_owner_branch_idx on public.id_cards(owner_branch_id);
create index if not exists id_cards_status_idx on public.id_cards(status);
create index if not exists id_cards_expiry_idx on public.id_cards(expiry_date);
create index if not exists id_cards_name_ar_idx on public.id_cards(name_ar);

create table if not exists public.id_card_versions (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.id_cards(id) on delete cascade,
  version integer not null,
  snapshot jsonb not null,
  reason text,
  created_by text,
  created_at timestamptz not null default now(),
  unique(card_id, version)
);

create table if not exists public.id_card_print_logs (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.id_cards(id) on delete cascade,
  print_side text not null check (print_side in ('full','front','back','both')),
  copies integer not null default 1 check (copies > 0),
  printer_profile_id uuid,
  printed_by text,
  printed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.id_card_audit_logs (
  id bigint generated by default as identity primary key,
  card_id uuid references public.id_cards(id) on delete set null,
  action text not null,
  actor_id text,
  before_data jsonb,
  after_data jsonb,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.id_card_printer_profiles (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_user_id text,
  printer_name text,
  offset_x_mm numeric(7,3) not null default 0,
  offset_y_mm numeric(7,3) not null default 0,
  scale_x numeric(8,5) not null default 1,
  scale_y numeric(8,5) not null default 1,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.id_card_print_logs
  drop constraint if exists id_card_print_logs_printer_profile_id_fkey;
alter table public.id_card_print_logs
  add constraint id_card_print_logs_printer_profile_id_fkey
  foreign key (printer_profile_id) references public.id_card_printer_profiles(id) on delete set null;

-- RLS is intentionally enabled with no permissive end-user policy in this foundation.
-- Current application architecture uses protected Worker APIs/service role for sensitive operations.
alter table public.id_cards enable row level security;
alter table public.id_card_versions enable row level security;
alter table public.id_card_templates enable row level security;
alter table public.id_card_print_logs enable row level security;
alter table public.id_card_audit_logs enable row level security;
alter table public.id_card_printer_profiles enable row level security;

insert into public.id_card_templates(code,name_ar,name_en,version,layout_mode,config)
values
 ('makkah_luxury','مكة الفاخر','Makkah Luxury',1,'both','{"thumbnail":"makkah_luxury"}'::jsonb),
 ('executive_side','التنفيذي الجانبي','Executive Side',1,'both','{"thumbnail":"executive_side"}'::jsonb),
 ('clean_formal','الرسمي النظيف','Clean Formal',1,'both','{"thumbnail":"clean_formal"}'::jsonb),
 ('royal_dark','رويال دارك','Royal Dark',1,'both','{"thumbnail":"royal_dark"}'::jsonb),
 ('minimal_corporate','المؤسسي البسيط','Minimal Corporate',1,'both','{"thumbnail":"minimal_corporate"}'::jsonb)
on conflict (code) do nothing;

comment on table public.id_cards is 'ID Studio cards; linked_employee_id is optional so card creation never requires a system staff account.';
comment on column public.id_cards.qr_token is 'Non-guessable public verification token; never expose employee/system identifiers as verification secrets.';
