create table if not exists public.attendance_incident_sla_policies (
  id uuid primary key default gen_random_uuid(),
  policy_key text not null unique,
  branch_id uuid null,
  category text not null default '*',
  severity text not null default '*',
  active boolean not null default true,
  response_minutes integer not null default 30,
  resolution_minutes integer not null default 240,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists attendance_incident_sla_policies_match_idx
  on public.attendance_incident_sla_policies(active,branch_id,category,severity);

create table if not exists public.attendance_incidents (
  id uuid primary key default gen_random_uuid(),
  incident_number bigint generated by default as identity unique,
  incident_key text not null unique,
  source_notification_id uuid null references public.attendance_notifications(id) on delete set null,
  branch_id uuid null,
  device_id uuid null references public.attendance_devices(id) on delete set null,
  category text not null default 'device_health',
  severity text not null default 'warning',
  title text not null,
  summary text null,
  status text not null default 'open',
  source_active boolean not null default true,
  owner_staff_id text null,
  owner_name text null,
  sla_policy_id uuid null references public.attendance_incident_sla_policies(id) on delete set null,
  started_at timestamptz not null default now(),
  response_due_at timestamptz null,
  resolution_due_at timestamptz null,
  acknowledged_at timestamptz null,
  acknowledged_by text null,
  resolved_at timestamptz null,
  resolved_by text null,
  closed_at timestamptz null,
  closed_by text null,
  response_seconds integer null,
  resolution_seconds integer null,
  response_breached boolean not null default false,
  resolution_breached boolean not null default false,
  reopened_count integer not null default 0,
  resolution_reason text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists attendance_incidents_branch_status_idx
  on public.attendance_incidents(branch_id,status,started_at desc);
create index if not exists attendance_incidents_device_started_idx
  on public.attendance_incidents(device_id,started_at desc);
create index if not exists attendance_incidents_sla_idx
  on public.attendance_incidents(response_breached,resolution_breached,status,started_at desc);

create table if not exists public.attendance_incident_events (
  id uuid primary key default gen_random_uuid(),
  incident_id uuid not null references public.attendance_incidents(id) on delete cascade,
  event_type text not null,
  actor_id text null,
  actor_name text null,
  note text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists attendance_incident_events_incident_idx
  on public.attendance_incident_events(incident_id,created_at desc);

alter table public.attendance_incident_sla_policies enable row level security;
alter table public.attendance_incidents enable row level security;
alter table public.attendance_incident_events enable row level security;
revoke all on table public.attendance_incident_sla_policies from anon, authenticated;
revoke all on table public.attendance_incidents from anon, authenticated;
revoke all on table public.attendance_incident_events from anon, authenticated;

insert into public.attendance_incident_sla_policies
(policy_key,category,severity,response_minutes,resolution_minutes)
values
('default-critical','*','critical',15,120),
('default-warning','*','warning',60,480),
('default-info','*','info',240,1440)
on conflict (policy_key) do nothing;
